---
title: "integration_report_conditions"
author: "Lea Wölbert"
date: '2023-06-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Report on integrated datasets.

#### Load libraries, source code, objects

```{r load,  message = FALSE}
library(SingleCellExperiment, quietly = TRUE) 
library(DropletUtils, quietly = TRUE) 
library(tidyverse, quietly = TRUE) 
library(scater, quietly = TRUE) 
library(scuttle, quietly = TRUE) 
library(scran, quietly = TRUE) 

color_tables <- snakemake@params[["color_tables"]]
source(file = "../../source/sce_functions.R")
source(file = "../../source/plotting.R")
source(file = "../../source/colors.R")

set.seed(37)
```

```{r load_code, message = FALSE}
sce_06_as <- readRDS(file = snakemake@input[["sce_08"]])
sce_06_as
```

# UMAPs

```{r}

make_plots <- function(sce, title){
  
  col_cts_baccin_clst <- col_cts[match(unique(sce$baccin_celltype_scmapclust),
                                       names(col_cts))]
  col_cts_dahlin_clst <- col_cts[match(unique(sce$dahlin_celltype_scmapclust), 
                                       names(col_cts))]
  col_cts_dolgalev_clst <- col_cts[match(unique(sce$dolgalev_celltype_scmapclust),
                                         names(col_cts))]
  
  if(title == "species"){title <- paste(title, sce$Species_ID[1])}
  if(title == "condition"){title <- paste(title, sce$Species_ID[1], sce$Age_ID[1])}
  
  plot_1 <- umap_base(sce, color_by = "baccin_celltype_scmapclust")+ 
    ggtitle(title)+
    scale_color_manual("baccin_celltype_scmapclust",
                       values = col_cts_baccin_clst)
  plot_1l <- umap_legend(sce, color_by = "baccin_celltype_scmapclust")+
    scale_color_manual("baccin_celltype_scmapclust", 
                       values = col_cts_baccin_clst)
  legend_1 <- get_legend(plot_1l)
  
  plot_2 <- umap_base(sce, color_by = "dahlin_celltype_scmapclust")+ 
    ggtitle(title)+
    scale_color_manual("dahlin_celltype_scmapclust", values = col_cts_dahlin_clst)
  plot_2l <- umap_legend(sce, color_by = "dahlin_celltype_scmapclust")+
    scale_color_manual("dahlin_celltype_scmapclust", values = col_cts_dahlin_clst)
  legend_2 <- get_legend(plot_2l)

  plot_3 <- umap_base(sce, color_by = "dolgalev_celltype_scmapclust")+ 
    ggtitle(title)+
    scale_color_manual("dolgalev_celltype_scmapclust", 
                       values = col_cts_dolgalev_clst)
  plot_3l <- umap_legend(sce, color_by = "dolgalev_celltype_scmapclust")+
    scale_color_manual("dolgalev_celltype_scmapclust", 
                       values = col_cts_dolgalev_clst)
  legend_3 <- get_legend(plot_3l)
  
  plot_4 <- umap_base_l(sce, color_by = "Age_ID")+ 
    ggtitle(title)
  plot_5 <- umap_base_l(sce, color_by = "Species_ID")+ 
    ggtitle(title)
  plot_6 <- umap_base_l(sce, color_by = "Fraction_ID")+ 
    ggtitle(title)
  
  PLOT_1 <- ggarrange(plot_1, legend_1)
  PLOT_2 <- ggarrange(plot_2, legend_2)
  PLOT_3 <- ggarrange(plot_3, legend_3)

return(list(PLOT_1, PLOT_2, PLOT_3, plot_4, plot_5, plot_6))
}

```

```{r}
plotlist_species <- make_plots(sce_06_as, title = "condition")
plotlist_species
```

```{r}
sessionInfo()
```