---
title: "integration_summary_report"
author: "Amy Danson, Lea Wölbert"
date: '2022-10-12'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Summary report for data integration.

#### Load libraries, source code 

```{r load,  message = FALSE}

library(DropletUtils, quietly = TRUE) 
library(scater, quietly = TRUE) 
library(scuttle, quietly = TRUE) 
library(scran, quietly = TRUE) 
library(tidyverse, quietly = TRUE) 

```

```{r load_code, message = FALSE}

source(file = "../source/colors.R")
source(file = "../source/sce_functions.R")

sce_07_path <- snakemake@input[["sce_07_path"]] # before renormalization
sce_08_path <- snakemake@input[["sce_08_path"]] # before correction
sce_09mnn_path <- snakemake@input[["sce_09mnn_path"]] # after correction

nr_hvgs <- snakemake@params[["nr_hvgs"]]
species_all <- snakemake@params[["species_all"]]
batches <- snakemake@params[["batches"]]

print(nr_hvgs)
print(species_all)
print(batches)

```

# Before batch correction

```{r}

sce_list_07 <- list()
for(s in species_all){
  sce_list_07[[s]] <- readRDS(file = paste0(sce_07_path, 
                                            "/sce_", s, "-07"))
}
print(sce_list_07)

sce_list_08 <- list()
for(b in batches){
  for(s in species_all){
    sce_list_08[[b]][[s]] <- readRDS(file = paste0(sce_08_path, 
                                                   "/sce_", s, "_", b, "-08"))
  }
}  
print(sce_list_08)

sce_list_09mnn <- list()
for(b in batches){
  for(s in species_all){
    sce_list_09mnn[[b]][[s]] <- readRDS(file = paste0(sce_09mnn_path,
                                                      "/sce_", s, "_", b, 
                                                      "-09"))
  }
}   
print(sce_list_09mnn)

```

```{r}

reduce_dims_all <- function(sce){
  
  hvgs <- modelGeneVar(sce)
  hvgs <- getTopHVGs(hvgs, n=nr_hvgs)
  
  if(!"corrected" %in% reducedDimNames(sce)){ # corrected doesn't need PCs
    sce <- runPCA(sce, ncomponents=25, subset_row = hvgs) 
    sce <- runUMAP(sce, dimred = 'PCA',
                   external_neighbors=TRUE, subset_row = hvgs)
  }else{
    sce <- runUMAP(sce, dimred = 'corrected', 
                   external_neighbors=TRUE, subset_row = hvgs) 
  }
  # PRELIM, use for now but change later
  sce$Identity <- sce$Identity_ref
  sce <- change_cts(sce)

  return(sce)  
}

sce_list_07 <- lapply(sce_list_07, reduce_dims_all)
sce_list_08_1 <- lapply(sce_list_08[[batches[1]]], reduce_dims_all)
sce_list_09mnn_1 <- lapply(sce_list_09mnn[[batches[1]]], reduce_dims_all)

```

```{r}

make_plots <- function(sce){
  
  batch_use <- sce$Batch_type_used[1]
  rescaled <- sce$Rescaled[1]
  correction_method <- sce$Correction_method[1]
  
  # by possible batches
  plot_1a <- ggplot(data.frame(reducedDims(sce)[["UMAP"]]),
                    aes(x = X1, y = X2, color = sce$Batch_exp_day))+
    geom_point(size = 0.01)+
    theme_classic()+
    ylab("UMAP 2")+
    xlab("UMAP 1")+
    theme(axis.text = element_blank())+
    theme(legend.key.size = unit(0.3, "cm"), 
          legend.key.width = unit(0.3, "cm"),
          legend.spacing = unit(0.06, "cm"), 
          legend.text = element_text(size = 7))+ 
    ggtitle(paste0("Corrected by: ", batch_use, 
                  ", Rescaled: ", rescaled, 
                  ", Method used: ", correction_method))
  
   plot_1b <- ggplot(data.frame(reducedDims(sce)[["UMAP"]]),
                    aes(x = X1, y = X2, color = sce$Batch_sequencing))+
    geom_point(size = 0.01)+
    theme_classic()+
    ylab("UMAP 2")+
    xlab("UMAP 1")+
    theme(axis.text = element_blank())+
    theme(legend.key.size = unit(0.3, "cm"), 
          legend.key.width = unit(0.3, "cm"),
          legend.spacing = unit(0.06, "cm"), 
          legend.text = element_text(size = 7))+ 
    ggtitle(paste0("Corrected by: ", batch_use, 
                  ", Rescaled: ", rescaled, 
                  ", Method used: ", correction_method))
 
   plot_1c <- ggplot(data.frame(reducedDims(sce)[["UMAP"]]),
                    aes(x = X1, y = X2, color = sce$Object_ID))+
    geom_point(size = 0.01)+
    theme_classic()+
    ylab("UMAP 2")+
    xlab("UMAP 1")+
    theme(axis.text = element_blank())+
    theme(legend.key.size = unit(0.3, "cm"), 
          legend.key.width = unit(0.3, "cm"),
          legend.spacing = unit(0.06, "cm"), 
          legend.text = element_text(size = 7))+ 
     ggtitle(paste0("Corrected by: ", batch_use, 
                  ", Rescaled: ", rescaled, 
                  ", Method used: ", correction_method))
  
  # check some other QC metrics
  plot_2 <- ggplot(data.frame(reducedDims(sce)[["UMAP"]]),
                    aes(x = X1, y = X2, color = sce$Keep_sample))+
    geom_point(size = 0.01)+
    theme_classic()+
    ylab("UMAP 2")+
    xlab("UMAP 1")+
    theme(axis.text = element_blank())+
    theme(legend.key.size = unit(0.3, "cm"), 
          legend.key.width = unit(0.3, "cm"),
          legend.spacing = unit(0.06, "cm"), 
          legend.text = element_text(size = 7))+ 
    ggtitle(paste0("Corrected by: ", batch_use, 
                  ", Rescaled: ", rescaled, 
                  ", Method used: ", correction_method))
 
  plot_3 <- ggplot(data.frame(reducedDims(sce)[["UMAP"]]),
                    aes(x = X1, y = X2, color = sce$doublet_score))+
    geom_point(size = 0.01)+
    theme_classic()+
    ylab("UMAP 2")+
    xlab("UMAP 1")+
    theme(axis.text = element_blank())+
    theme(legend.key.size = unit(0.3, "cm"), 
          legend.key.width = unit(0.3, "cm"),
          legend.spacing = unit(0.06, "cm"), 
          legend.text = element_text(size = 7))+ 
    ggtitle(paste0("Corrected by: ", batch_use, 
                  ", Rescaled: ", rescaled, 
                  ", Method used: ", correction_method))

  # check everything else
  plot_4 <- ggplot(data.frame(reducedDims(sce)[["UMAP"]]),
                    aes(x = X1, y = X2, color = sce$Species_ID))+
    geom_point(size = 0.01)+
    theme_classic()+
    ylab("UMAP 2")+
    xlab("UMAP 1")+
    theme(axis.text = element_blank())+
    theme(legend.key.size = unit(0.3, "cm"), 
          legend.key.width = unit(0.3, "cm"),
          legend.spacing = unit(0.06, "cm"), 
          legend.text = element_text(size = 7))+ 
    ggtitle(paste0("Corrected by: ", batch_use, 
                  ", Rescaled: ", rescaled, 
                  ", Method used: ", correction_method))
  
  plot_5 <- ggplot(data.frame(reducedDims(sce)[["UMAP"]]),
                    aes(x = X1, y = X2, color = sce$Age))+
    geom_point(size = 0.01)+
    theme_classic()+
    ylab("UMAP 2")+
    xlab("UMAP 1")+
    theme(axis.text = element_blank())+
    theme(legend.key.size = unit(0.3, "cm"), 
          legend.key.width = unit(0.3, "cm"),
          legend.spacing = unit(0.06, "cm"), 
          legend.text = element_text(size = 7))+ 
    ggtitle(paste0("Corrected by: ", batch_use, 
                  ", Rescaled: ", rescaled, 
                  ", Method used: ", correction_method))
 
  plot_6 <- ggplot(data.frame(reducedDims(sce)[["UMAP"]]),
                    aes(x = X1, y = X2, color = sce$Fraction))+
    geom_point(size = 0.01)+
    theme_classic()+
    ylab("UMAP 2")+
    xlab("UMAP 1")+
    theme(axis.text = element_blank())+
    theme(legend.key.size = unit(0.3, "cm"), 
          legend.key.width = unit(0.3, "cm"),
          legend.spacing = unit(0.06, "cm"), 
          legend.text = element_text(size = 7))+ 
    ggtitle(paste0("Corrected by: ", batch_use, 
                  ", Rescaled: ", rescaled, 
                  ", Method used: ", correction_method))
  
  plot_7 <- ggplot(data.frame(reducedDims(sce)[["UMAP"]]),
                    aes(x = X1, y = X2, color = sce$Antibody_combination))+
    geom_point(size = 0.01)+
    theme_classic()+
    ylab("UMAP 2")+
    xlab("UMAP 1")+
    theme(axis.text = element_blank())+
    theme(legend.key.size = unit(0.3, "cm"), 
          legend.key.width = unit(0.3, "cm"),
          legend.spacing = unit(0.06, "cm"), 
          legend.text = element_text(size = 7))+ 
    ggtitle(paste0("Corrected by: ", batch_use, 
                  ", Rescaled: ", rescaled, 
                  ", Method used: ", correction_method))
 
  plot_8 <- ggplot(data.frame(reducedDims(sce)[["UMAP"]]),
                    aes(x = X1, y = X2, color = sce$Date_collected))+
    geom_point(size = 0.01)+
    theme_classic()+
    ylab("UMAP 2")+
    xlab("UMAP 1")+
    theme(axis.text = element_blank())+
    theme(legend.key.size = unit(0.3, "cm"), 
          legend.key.width = unit(0.3, "cm"),
          legend.spacing = unit(0.06, "cm"), 
          legend.text = element_text(size = 7))+ 
    ggtitle(paste0("Corrected by: ", batch_use, 
                  ", Rescaled: ", rescaled, 
                  ", Method used: ", correction_method))
  
  plot_9 <- ggplot(data.frame(reducedDims(sce)[["UMAP"]]),
                    aes(x = X1, y = X2, color = sce$Identity))+
    geom_point(size = 0.01)+
    theme_classic()+
    ylab("UMAP 2")+
    xlab("UMAP 1")+
    theme(axis.text = element_blank())+
    theme(legend.key.size = unit(0.3, "cm"), 
          legend.key.width = unit(0.3, "cm"),
          legend.spacing = unit(0.06, "cm"), 
          legend.text = element_text(size = 7))+ 
    ggtitle(paste0("Corrected by: ", batch_use, 
                  ", Rescaled: ", rescaled, 
                  ", Method used: ", correction_method))+
    scale_color_manual("REF Identity", values = col_cts_all[names(col_cts_all) %in% sce$Identity])

  plot_list <- list(plot_1a, plot_1b, plot_1c, plot_2, plot_3, plot_4,
                    plot_5, plot_6, plot_7, plot_8, plot_9)
  
  return(plot_list)
}

plot_list_07 <-lapply(sce_list_07, make_plots)
plot_list_08_1 <-lapply(sce_list_08_1, make_plots)
plot_list_09mnn_1 <- lapply(sce_list_09mnn_1, make_plots)

```

```{r}
plot_list_07
```

```{r}
plot_list_08_1
```

```{r}
plot_list_09mnn_1
```

```{r}
sessionInfo()
```

