---
title: "ct interactome overlap ages"
author: "Lea Wölbert"
date: '2023-10-23'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Load objects

```{r seed,  message = FALSE}
set.seed(37)
```

```{r load,  message = FALSE}
library(tidyverse)
library(scran)
library(ComplexUpset)
```

```{r colors, meassage = FALSE}
colors_path <- snakemake@params[["colors_path"]]
source(snakemake@params[["colors"]])
```

```{r load_objects}
cci_met_path_list <- snakemake@input[["cci_met_paths"]]

species <- snakemake@params[["species"]]
age <- snakemake@params[["age"]]

cci_met_list <- list()
for(s in species){
  for(a in age){
    cond <- as.character(paste0(s, "_", a))
    cci_met_path <- cci_met_path_list[[which(grepl(cond, cci_met_path_list))]]
    cci_met_list[[cond]] <- readRDS(cci_met_path)
  }
}

print(names(cci_met_list))
```

# Preparation

## NR_DF

```{r}
# now for each species, get the overlap and young and old only interactions
# sort list by species and then age

cci_met_cts_list_ages <- list() 
for(s in species){
  for(a in age){
    cci_met_cts_list_ages[[s]][[a]] <- cci_met_list[[
      which(grepl(s, names(cci_met_list)) & 
              grepl(a, names(cci_met_list)))]]$separate
  }
  
  cts_preserved <- intersect(names(cci_met_cts_list_ages[[s]]$yng),
                             names(cci_met_cts_list_ages[[s]]$old))

  cci_met_cts_list_ages[[s]]$yng <- cci_met_cts_list_ages[[s]]$yng[
    which(names(cci_met_cts_list_ages[[s]]$yng) %in% cts_preserved)]
  cci_met_cts_list_ages[[s]]$old <- cci_met_cts_list_ages[[s]]$old[
    which(names(cci_met_cts_list_ages[[s]]$old) %in% cts_preserved)]
}
```

```{r}
# within species, extract the list of interactions that are preserved,
# young_only, and old_only, as well as handy data frames for each cell type
overlap_lists <- lapply(cci_met_cts_list_ages, function(cci_met_age){
  
  cci_met_yng_list <- cci_met_age[["yng"]]
  cci_met_old_list <- cci_met_age[["old"]]
  
  cts_all <- unique(c(names(cci_met_yng_list), names(cci_met_old_list)))
  cts_all_list <- as.list(cts_all)
  
  overlap <- lapply(cts_all, function(ct){
    
    cci_met_yng <- cci_met_yng_list[[ct]]
    cci_met_old <- cci_met_old_list[[ct]]
    
    preserved <- intersect(unique(cci_met_yng$interaction), 
                           unique(cci_met_old$interaction))

    yng_only <- unique(cci_met_yng$interaction[
      which(!cci_met_yng$interaction %in% preserved)])
    old_only <- unique(cci_met_old$interaction[
      which(!cci_met_old$interaction %in% preserved)])
  
    # make sure the vectors are correct
    stopifnot(!yng_only %in% preserved)
    stopifnot(!old_only %in% preserved)
          
    stopifnot(!yng_only %in% cci_met_old$interaction)
    stopifnot(!old_only %in% cci_met_yng$interaction)
  
    stopifnot(preserved %in% cci_met_yng$interaction)
    stopifnot(preserved %in% cci_met_old$interaction)
    
    # count the length of each cell type entry  
    return_df <- data.frame(
      "mode" = c("preserved", "yng_only", "old_only"),
      "nr" = c(length(preserved), length(yng_only), length(old_only)),
      "cell_type" = rep(ct, 3),
      # within species, so species will be the same in each list item
      "species" = rep(cci_met_old_list[[1]]$species[1], 3)
    )
    
    return(list("preserved" = preserved,
                "yng_only" = yng_only,
                "old_only" = old_only,
                "nr_df" = return_df))
  })
  names(overlap) <- cts_all
  return(overlap)
})
names(overlap_lists) <- names(cci_met_cts_list_ages)

sort(names(overlap_lists$mmus))
names(overlap_lists[[1]][[1]])
```

```{r}
# extract only the nr_dfs for now!
nr_df_all <- data.frame()
for(i in 1:length(overlap_lists)){
  for(j in 1:length(overlap_lists[[i]])){

    nr_df_add <- overlap_lists[[i]][[j]]$nr_df
    nr_df_add$proportion <- nr_df_add$nr/sum(nr_df_add$nr)
    nr_df_add$normalized <- nr_df_add$nr/nr_df_add$nr[
      nr_df_add$mode == "preserved"]
      
    nr_df_all <- rbind(nr_df_all, nr_df_add)
    
  }
}

head(nr_df_all)
```

```{r}
nr_df_all$mode <- factor(nr_df_all$mode,
                         levels = c("old_only" ,"yng_only", "preserved"))
nr_df_all$mode_rev <- factor(nr_df_all$mode, 
                             levels = rev(c( "old_only" ,"yng_only", 
                                             "preserved")))
nr_df_all$cell_type <- factor(nr_df_all$cell_type,
                              levels = c(names(col_cts_hsc), 
                                         names(col_cts_str)))
nr_df_all$cell_type_rev <- factor(nr_df_all$cell_type,
                                  levels = rev(c(names(col_cts_hsc),
                                                 names(col_cts_str))))
nr_df_all$species <- factor(nr_df_all$species, levels = names(col_spc))
nr_df_all$species_rev <- factor(nr_df_all$species, levels = rev(names(col_spc)))

col_mode <- c("old_only" = "grey60", "yng_only" = "black",
              "preserved" = "orange2")
```

## Upset Plots 

```{r}
large_df <- bind_rows(cci_met_cts_list_ages$mmus$yng)
large_df <- rbind(large_df, bind_rows(cci_met_cts_list_ages$mmus$old))
large_df <- rbind(large_df, bind_rows(cci_met_cts_list_ages$mcas$yng))
large_df <- rbind(large_df, bind_rows(cci_met_cts_list_ages$mcas$old))
large_df <- rbind(large_df, bind_rows(cci_met_cts_list_ages$mspr$yng))
large_df <- rbind(large_df, bind_rows(cci_met_cts_list_ages$mspr$old))
large_df <- rbind(large_df, bind_rows(cci_met_cts_list_ages$mcar$yng))
large_df <- rbind(large_df, bind_rows(cci_met_cts_list_ages$mcar$old))

large_df$identifier <- paste0(large_df$interaction, "_",
                              large_df$identity, "_",
                              large_df$species, "_", large_df$age)
large_df$mode <- vector(length = nrow(large_df))

cts <- c(names(col_cts_hsc), names(col_cts_str))

for(s in species){
  for(c in cts){
    
    pos <- which(large_df$species == s & large_df$identity == c)
    
    large_df[pos,]$mode[large_df[
      pos,]$interaction %in% overlap_lists[[s]][[c]]$preserved] <- "preserved"
    large_df[pos,]$mode[large_df[
      pos,]$interaction %in% overlap_lists[[s]][[c]]$yng_only] <- "yng_only"
    large_df[pos,]$mode[large_df[
      pos,]$interaction %in% overlap_lists[[s]][[c]]$old_only] <- "old_only"

  }
}

table(large_df$mode)

large_df_upset <- large_df
large_df_upset_old <- large_df_upset[large_df_upset$mode == "old_only",]
large_df_upset_yng <- large_df_upset[large_df_upset$mode == "yng_only",]
large_df_upset_shr <- large_df_upset[large_df_upset$mode == "preserved",]
```

```{r}
for(s in species){
  
  print(s)
  
  large_df_upset_old$add <- vector(length = nrow(large_df_upset_old))
  large_df_upset_yng$add <- vector(length = nrow(large_df_upset_yng))
  large_df_upset_shr$add <- vector(length = nrow(large_df_upset_shr))

  all_ints_of_species_old <- unique(
    large_df_upset_old$interaction[large_df_upset_old$species == s])
  all_ints_of_species_yng <- unique(
    large_df_upset_yng$interaction[large_df_upset_yng$species == s])
  all_ints_of_species_shr <- unique(
    large_df_upset_shr$interaction[large_df_upset_shr$species == s])
  
  large_df_upset_old$add[
    large_df_upset_old$interaction %in% all_ints_of_species_old] <- TRUE
  large_df_upset_yng$add[
    large_df_upset_yng$interaction %in% all_ints_of_species_yng] <- TRUE
  large_df_upset_shr$add[
    large_df_upset_shr$interaction %in% all_ints_of_species_shr] <- TRUE
  
  colnames(large_df_upset_old)[colnames(large_df_upset_old) == "add"] <- s
  colnames(large_df_upset_yng)[colnames(large_df_upset_yng) == "add"] <- s
  colnames(large_df_upset_shr)[colnames(large_df_upset_shr) == "add"] <- s
  
}

large_df_upset_old_slim <- large_df_upset_old[!duplicated(
  large_df_upset_old$interaction),]
large_df_upset_yng_slim <- large_df_upset_yng[!duplicated(
  large_df_upset_yng$interaction),]
large_df_upset_shr_slim <- large_df_upset_shr[!duplicated(
  large_df_upset_shr$interaction),]
```

# Important Plots

```{r fig.width= 10, fig.height = 5}
ggplot(nr_df_all, aes(y = cell_type_rev, x = nr, fill = mode))+
  geom_col(position = "stack")+
  theme_classic()+
  facet_grid(cols = vars(species))+
  scale_fill_manual("", values = col_mode)+
  xlab("Nr of detected interactions per cell type")+
  theme(axis.text.x = element_text(angle = 90))+
  ylab("Cell type")

ggplot(nr_df_all, aes(y = cell_type_rev, x = nr, fill = mode))+
  geom_col(position = "fill")+
  theme_classic()+
  facet_grid(cols = vars(species))+
  scale_fill_manual("", values = col_mode)+
  xlab("Proportions of detected interactions per cell type")+
  theme(axis.text.x = element_text(angle = 90))+
  ylab("Cell type")
```

```{r, fig.width = 4, fig.height = 4}
ggplot(nr_df_all, aes(x = species, y = proportion, color = mode))+
  geom_boxplot()+
  xlab("Proportion of detected interactions per cell type")+
  theme_classic()+
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank())+
  scale_color_manual(" ", values = col_mode)+
  facet_grid(cols = vars(mode))+
  ylab("Species")

ggplot(nr_df_all, aes(x = mode_rev, y = proportion, color = mode))+
  geom_boxplot()+
  ylab("Proportion of detected interactions per cell type")+
  theme_classic()+
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank())+
  scale_color_manual("", values = col_mode)+
  facet_grid(cols = vars(species))+
  theme(axis.text.x = element_blank())
```

```{r, fig.width = 5, fig.height = 7}

upset(large_df_upset_old_slim, intersect = c("mmus", "mcas", "mspr",  "mcar"),
      base_annotations=list(
        'Intersection size'=intersection_size(mapping=aes(fill='bars_color'))+
          scale_fill_manual(values=c('bars_color'= col_age[["old"]]), 
                            guide='none')))+
  xlab("")

upset(large_df_upset_yng_slim, intersect = c("mmus", "mcas", "mspr",  "mcar"),
      base_annotations=list(
        'Intersection size'=intersection_size(mapping=aes(fill='bars_color'))+
          scale_fill_manual(values=c('bars_color'= col_age[["yng"]]), 
                            guide='none')))+
  xlab("")

upset(large_df_upset_shr_slim, intersect = c("mmus", "mcas", "mspr",  "mcar"),
      base_annotations=list(
        'Intersection size'=intersection_size(mapping=aes(fill='bars_color'))+
          scale_fill_manual(values=c('bars_color'= "orange"), 
                            guide='none')))+
  xlab("")
```

```{r}
large_df_upset_old$species <- factor(large_df_upset_old$species,
                                     levels = names(col_spc))

large_df_upset_old$detection <- vector(length = nrow(large_df_upset_old))
large_df_upset_old$detection[
  which(large_df_upset_old$mmus == "TRUE" &
          large_df_upset_old$mcas == "TRUE" &
          large_df_upset_old$mspr == "TRUE" &
          large_df_upset_old$mcar == "TRUE")] <- TRUE 

large_df_upset_old$detection[
  large_df_upset_old$detection == "FALSE"] <- unfactor(large_df_upset_old$species[
    large_df_upset_old$detection == "FALSE"])

large_df_upset_old$species_pos <- vector(length = nrow(large_df_upset_old))

# all
large_df_upset_old$species_pos[large_df_upset_old$detection == "TRUE"] <- 16

# all but mcar
large_df_upset_old$species_pos[which(large_df_upset_old$mmus == "TRUE" &
                                       large_df_upset_old$mcas == "TRUE" &
                                       large_df_upset_old$mspr == "TRUE" &
                                       large_df_upset_old$mcar == "TRUE")] <- 15

# all but mcar
large_df_upset_old$species_pos[which(large_df_upset_old$mmus == "TRUE" &
                                       large_df_upset_old$mcas == "TRUE" &
                                       large_df_upset_old$mspr == "TRUE" &
                                       large_df_upset_old$mcar == "FALSE")] <- 14

# all but mspr
large_df_upset_old$species_pos[which(large_df_upset_old$mmus == "TRUE" &
                                       large_df_upset_old$mcas == "TRUE" &
                                       large_df_upset_old$mspr == "FALSE" &
                                       large_df_upset_old$mcar == "TRUE")] <- 13

# all but mcas
large_df_upset_old$species_pos[which(large_df_upset_old$mmus == "TRUE" &
                                       large_df_upset_old$mcas == "FALSE" &
                                       large_df_upset_old$mspr == "TRUE" &
                                       large_df_upset_old$mcar == "TRUE")] <- 12

# all but mmus
large_df_upset_old$species_pos[which(large_df_upset_old$mmus == "FALSE" &
                                       large_df_upset_old$mcas == "TRUE" &
                                       large_df_upset_old$mspr == "TRUE" &
                                       large_df_upset_old$mcar == "TRUE")] <- 11

# mmus and mcas
large_df_upset_old$species_pos[which(large_df_upset_old$mmus == "TRUE" &
                                       large_df_upset_old$mcas == "TRUE" &
                                       large_df_upset_old$mspr == "FALSE" &
                                       large_df_upset_old$mcar == "FALSE")] <- 10

# mmus and mspr
large_df_upset_old$species_pos[which(large_df_upset_old$mmus == "TRUE" &
                                       large_df_upset_old$mcas == "FALSE" &
                                       large_df_upset_old$mspr == "TRUE" &
                                       large_df_upset_old$mcar == "FALSE")] <- 9

# mmus and mcar
large_df_upset_old$species_pos[which(large_df_upset_old$mmus == "TRUE" &
                                       large_df_upset_old$mcas == "FALSE" &
                                       large_df_upset_old$mspr == "FALSE" &
                                       large_df_upset_old$mcar == "TRUE")] <- 8

# mcas and mspr
large_df_upset_old$species_pos[which(large_df_upset_old$mmus == "FALSE" &
                                       large_df_upset_old$mcas == "TRUE" &
                                       large_df_upset_old$mspr == "FALSE" &
                                       large_df_upset_old$mcar == "TRUE")] <- 7

# mcas and mcar
large_df_upset_old$species_pos[which(large_df_upset_old$mmus == "FALSE" &
                                       large_df_upset_old$mcas == "TRUE" &
                                       large_df_upset_old$mspr == "TRUE" &
                                       large_df_upset_old$mcar == "FALSE")] <- 6

# mspr and mcar
large_df_upset_old$species_pos[which(large_df_upset_old$mmus == "FALSE" &
                                       large_df_upset_old$mcas == "FALSE" &
                                       large_df_upset_old$mspr == "TRUE" &
                                       large_df_upset_old$mcar == "TRUE")] <- 5

# mmus
large_df_upset_old$species_pos[which(large_df_upset_old$mmus == "TRUE" &
                                       large_df_upset_old$mcas == "FALSE" &
                                       large_df_upset_old$mspr == "FALSE" &
                                       large_df_upset_old$mcar == "FALSE")] <- 4
# mcas
large_df_upset_old$species_pos[which(large_df_upset_old$mmus == "FALSE" &
                                       large_df_upset_old$mcas == "TRUE" &
                                       large_df_upset_old$mspr == "FALSE" &
                                       large_df_upset_old$mcar == "FALSE")] <- 3

# mspr
large_df_upset_old$species_pos[which(large_df_upset_old$mmus == "FALSE" &
                                       large_df_upset_old$mcas == "FALSE" &
                                       large_df_upset_old$mspr == "TRUE" &
                                       large_df_upset_old$mcar == "FALSE")] <- 2

# mcar
large_df_upset_old$species_pos[which(large_df_upset_old$mmus == "FALSE" &
                                       large_df_upset_old$mcas == "FALSE" &
                                       large_df_upset_old$mspr == "FALSE" &
                                       large_df_upset_old$mcar == "TRUE")] <- 1
```

```{r fig.height = 40, fig.width = 6}
ggplot(large_df_upset_old, 
       aes(y = reorder(interaction, species_pos), fill = detection))+
  geom_bar()+
  facet_grid(cols = vars(species))+
  scale_fill_manual(values = c(col_spc, "TRUE" = "orange"))+
  ylab("Old-specific interactions")+
  xlab("Nr of cell types")
```

```{r}

for(s in species){
  
  print(s)
  
  large_df_upset$add <- vector(length = nrow(large_df_upset))

  all_ints_of_species <- unique(
    large_df_upset$interaction[large_df_upset$species == s])

  large_df_upset$add[
    large_df_upset$interaction %in% all_ints_of_species] <- TRUE
 
  colnames(large_df_upset)[colnames(large_df_upset) == "add"] <- s

}

large_df_upset$species <- factor(large_df_upset$species,
                                     levels = names(col_spc))

large_df_upset$detection <- vector(length = nrow(large_df_upset))
large_df_upset$detection[
  which(large_df_upset$mmus == "TRUE" &
          large_df_upset$mcas == "TRUE" &
          large_df_upset$mspr == "TRUE" &
          large_df_upset$mcar == "TRUE")] <- TRUE 

large_df_upset$detection[
  large_df_upset$detection == "FALSE"] <- unfactor(large_df_upset$species[
    large_df_upset$detection == "FALSE"])

large_df_upset$species_pos <- vector(length = nrow(large_df_upset))

# all
large_df_upset$species_pos[large_df_upset$detection == "TRUE"] <- 16

# all but mcar
large_df_upset$species_pos[which(large_df_upset$mmus == "TRUE" &
                                       large_df_upset$mcas == "TRUE" &
                                       large_df_upset$mspr == "TRUE" &
                                       large_df_upset$mcar == "TRUE")] <- 15

# all but mcar
large_df_upset$species_pos[which(large_df_upset$mmus == "TRUE" &
                                       large_df_upset$mcas == "TRUE" &
                                       large_df_upset$mspr == "TRUE" &
                                       large_df_upset$mcar == "FALSE")] <- 14

# all but mspr
large_df_upset$species_pos[which(large_df_upset$mmus == "TRUE" &
                                       large_df_upset$mcas == "TRUE" &
                                       large_df_upset$mspr == "FALSE" &
                                       large_df_upset$mcar == "TRUE")] <- 13

# all but mcas
large_df_upset$species_pos[which(large_df_upset$mmus == "TRUE" &
                                       large_df_upset$mcas == "FALSE" &
                                       large_df_upset$mspr == "TRUE" &
                                       large_df_upset$mcar == "TRUE")] <- 12

# all but mmus
large_df_upset$species_pos[which(large_df_upset$mmus == "FALSE" &
                                       large_df_upset$mcas == "TRUE" &
                                       large_df_upset$mspr == "TRUE" &
                                       large_df_upset$mcar == "TRUE")] <- 11

# mmus and mcas
large_df_upset$species_pos[which(large_df_upset$mmus == "TRUE" &
                                       large_df_upset$mcas == "TRUE" &
                                       large_df_upset$mspr == "FALSE" &
                                       large_df_upset$mcar == "FALSE")] <- 10

# mmus and mspr
large_df_upset$species_pos[which(large_df_upset$mmus == "TRUE" &
                                       large_df_upset$mcas == "FALSE" &
                                       large_df_upset$mspr == "TRUE" &
                                       large_df_upset$mcar == "FALSE")] <- 9

# mmus and mcar
large_df_upset$species_pos[which(large_df_upset$mmus == "TRUE" &
                                       large_df_upset$mcas == "FALSE" &
                                       large_df_upset$mspr == "FALSE" &
                                       large_df_upset$mcar == "TRUE")] <- 8

# mcas and mspr
large_df_upset$species_pos[which(large_df_upset$mmus == "FALSE" &
                                       large_df_upset$mcas == "TRUE" &
                                       large_df_upset$mspr == "FALSE" &
                                       large_df_upset$mcar == "TRUE")] <- 7

# mcas and mcar
large_df_upset$species_pos[which(large_df_upset$mmus == "FALSE" &
                                       large_df_upset$mcas == "TRUE" &
                                       large_df_upset$mspr == "TRUE" &
                                       large_df_upset$mcar == "FALSE")] <- 6

# mspr and mcar
large_df_upset$species_pos[which(large_df_upset$mmus == "FALSE" &
                                       large_df_upset$mcas == "FALSE" &
                                       large_df_upset$mspr == "TRUE" &
                                       large_df_upset$mcar == "TRUE")] <- 5

# mmus
large_df_upset$species_pos[which(large_df_upset$mmus == "TRUE" &
                                       large_df_upset$mcas == "FALSE" &
                                       large_df_upset$mspr == "FALSE" &
                                       large_df_upset$mcar == "FALSE")] <- 4
# mcas
large_df_upset$species_pos[which(large_df_upset$mmus == "FALSE" &
                                       large_df_upset$mcas == "TRUE" &
                                       large_df_upset$mspr == "FALSE" &
                                       large_df_upset$mcar == "FALSE")] <- 3

# mspr
large_df_upset$species_pos[which(large_df_upset$mmus == "FALSE" &
                                       large_df_upset$mcas == "FALSE" &
                                       large_df_upset$mspr == "TRUE" &
                                       large_df_upset$mcar == "FALSE")] <- 2

# mcar
large_df_upset$species_pos[which(large_df_upset$mmus == "FALSE" &
                                       large_df_upset$mcas == "FALSE" &
                                       large_df_upset$mspr == "FALSE" &
                                       large_df_upset$mcar == "TRUE")] <- 1
```

```{r fig.height = 50, fig.width = 6}
ggplot(large_df_upset, 
       aes(y = reorder(interaction, species_pos), fill = mode))+
  geom_bar()+
  facet_grid(cols = vars(species))+
  ylab("Interactions")+
  scale_fill_manual(values = col_mode)+
  xlab("Nr of cell types")
```

```{r fig.height = 50, fig.width = 6}
ggplot(large_df_upset, 
       aes(y = interaction, fill = mode))+
  geom_bar()+
  facet_grid(cols = vars(species))+
  ylab("Interactions")+
  scale_fill_manual(values = col_mode)+
  xlab("Nr of cell types")
```

```{r fig.height = 6, fig.width = 6}
ints_of_interest <- c("Wnt5b_Lrp6",
                      "Vcam1_Itgb7",
                      "Psen1_Notch2",
                      "Psen1_Notch1",
                      "Psen1_Ncstn",
                      "Pdgfd_Pdgfrb",
                      "Pdgfc_Pdgfrb",
                      "Pdgfb_Pdgfrb",
                      "Pdgfa_Pdgfrb",
                      "L1cam_Itgb1",
                      "Il15_Il2rg",
                      "Fn1_Itgb1",
                      "Fn1_Cd44",
                      "Has2_Hmmr",
                      "Has2_Cd44",
                      "Fgf2_Kit",
                      "Fgf2_Cd44",
                      "Col2a1_Itga2b",
                      "Bmp5_Bmpr2",
                      "Bmp4_Bmpr2",
                      "Bmp2_Bmpr2",
                      "Cd14_Itgb1",
                      "Cd14_Itga4",
                      "Cd14_Cd55",
                      "Col4a5_Itgb1",
                      "Cxcl12_Cxcr4",
                      "Vcam1_Itga4",
                      "Vcam1_Itgb1",
                      "Spp1_Itgb1",
                      "Kitl_Kit",
                      "Il7_Il7r",
                      "Il6_Il6ra",
                      "Cxcl14_Cxcr4",
                      "Adam10_Tspan5",
                      "Adam10_Tspan14",
                      "Adam10_Il6ra",
                      "Igf2_Insr",
                      "Igf2_Igf2r")

ggplot(large_df_upset[large_df_upset$interaction %in% ints_of_interest,], 
       aes(y = reorder(interaction, species_pos), fill = mode))+
  geom_bar()+
  facet_grid(cols = vars(species))+
  ylab("Interactions")+
  scale_fill_manual(values = col_mode)+
  xlab("Nr of cell types")
```

```{r fig.height = 6, fig.width = 6}
ints_of_interest2 <- c(
                      "Vcam1_Itga4",
                      "Vcam1_Itgb1",
                         "Fn1_Itgb1",
                      "Fn1_Cd44",
                      "Spp1_Itgb1",
                      "Kitl_Kit",
                      "Cxcl12_Cxcr4",
                      "Cxcl14_Cxcr4",

                        "Vcam1_Itgb7",
                       "Wnt5b_Lrp6",
                      "Psen1_Notch2",
                      "Psen1_Notch1",
                      "Psen1_Ncstn",
                      "Pdgfd_Pdgfrb",
                      "Pdgfc_Pdgfrb",
                      "Pdgfb_Pdgfrb",
                      "Pdgfa_Pdgfrb",
                      "L1cam_Itgb1",
                      "Il15_Il2rg",

                      "Has2_Hmmr",
                      "Has2_Cd44",
                      "Fgf2_Kit",
                      "Fgf2_Cd44",
                      "Col2a1_Itga2b",
                      "Bmp5_Bmpr2",
                      "Bmp4_Bmpr2",
                      "Bmp2_Bmpr2",
                      "Cd14_Itgb1",
                      "Cd14_Itga4",
                      "Cd14_Cd55",
                      "Col4a5_Itgb1",

                      "Il7_Il7r",
                      "Il6_Il6ra",
                      "Adam10_Tspan5",
                      "Adam10_Tspan14",
                      "Adam10_Il6ra",
                      "Igf2_Insr",
                      "Igf2_Igf2r")

ggdf_x <- large_df_upset[large_df_upset$interaction %in% ints_of_interest2,]
ggdf_x$interaction <- factor(ggdf_x$interaction, levels = rev(ints_of_interest2))

ggplot(ggdf_x,
       aes(y = interaction, fill = mode))+
  geom_bar()+
  facet_grid(cols = vars(species))+
  ylab("Interactions")+
  scale_fill_manual(values = col_mode)+
  xlab("Nr of cell types")
```

# QC PLOTS

```{r}
ggplot(nr_df_all, aes(y = cell_type, x = normalized, fill = mode))+
  geom_col(position = "dodge")+
  theme_classic()+
  facet_grid(cols = vars(species))+
  scale_fill_manual("Detection", values = col_mode)+
  xlab("Normalized nr of detected interactions per cell type")+
  theme(axis.text.x = element_text(angle = 90))+
  ylab("Cell type")

ggplot(nr_df_all, aes(y = cell_type, x = proportion, fill = mode))+
  geom_col(position = "dodge")+
  theme_classic()+
  facet_grid(cols = vars(species))+
  scale_fill_manual("Detection", values = col_mode)+
  xlab("Proportions of detected interactions per cell type")+
  theme(axis.text.x = element_text(angle = 90))+
  ylab("Cell type")

ggplot(nr_df_all, aes(y = cell_type, x = nr, fill = mode))+
  geom_col(position = "dodge")+
  theme_classic()+
  facet_grid(cols = vars(species))+
  scale_fill_manual("Detection", values = col_mode)+
  xlab("Nr of detected interactions per cell type")+
  theme(axis.text.x = element_text(angle = 90))+
  ylab("Cell type")
```

```{r}
ggplot(nr_df_all, aes(x = mode, y = proportion, color = mode))+
  geom_boxplot()+
  ylab("Proportion of detected interactions per cell type")+
  theme_classic()+
  scale_color_manual("Detection", values = col_mode)+
  facet_grid(cols = vars(cell_type))+
  theme(axis.text.x = element_blank(),
        strip.text.x = element_text(angle = 90),
        axis.ticks.x = element_blank())+
  xlab("Species")
```

```{r}
ggplot(nr_df_all, aes(y= cell_type, x = nr, color = mode))+
  geom_boxplot()+
  theme_classic()+
  facet_grid(cols = vars(mode))+
  scale_color_manual("Detection", values = col_mode)+
  xlab("Nr of detected interactions per cell type")+
  theme(axis.text.x = element_text(angle = 90))
```

```{r}
sessionInfo()
```