---
title: "ctp interactome overlap ages"
author: "Lea Wölbert"
date: '2023-10-23'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Load objects

```{r seed,  message = FALSE}
set.seed(37)
```

```{r load,  message = FALSE}
library(tidyverse)
library(scran)
library(ComplexUpset)
```

```{r colors, meassage = FALSE}
colors_path <- snakemake@params[["colors_path"]]
source(snakemake@params[["colors"]])
```

```{r load_objects}
cci_met_path_list <- snakemake@input[["cci_met_paths"]]

species <- snakemake@params[["species"]]
age <- snakemake@params[["age"]]

cci_met_list <- list()
for(s in species){
  for(a in age){
    cond <- as.character(paste0(s, "_", a))
    cci_met_path <- cci_met_path_list[[which(grepl(cond, cci_met_path_list))]]
    cci_met_list[[cond]] <- readRDS(cci_met_path)
  }
}

print(names(cci_met_list))
```

# Preparation

## NR_DF

```{r}
# for each condition, summarize all ctp list entries from separate
# into one large data frame
cci_met_dfs_list <- lapply(cci_met_list, function(cci_met){
  
  cci_met_df <- bind_rows(cci_met[[2]])
  return(cci_met_df)

})
names(cci_met_dfs_list) <- names(cci_met_list)
print(head(cci_met_dfs_list[[1]]))
```




```{r}
# now for each species, get the overlap and young and old only interactions
# sort list by species and then age

cci_met_list_ages <- list()
for(s in species){
  for(a in age){
    cci_met_list_ages[[s]][[a]] <- cci_met_list[[
      which(grepl(s, names(cci_met_list)) &
              grepl(a, names(cci_met_list)))]]$separate
  }
  
  ctps_preserved <- intersect(names(cci_met_list_ages[[s]]$yng),
                          names(cci_met_list_ages[[s]]$old))

  cci_met_list_ages[[s]]$yng <- cci_met_list_ages[[s]]$yng[
    which(names(cci_met_list_ages[[s]]$yng) %in% ctps_preserved)]
  cci_met_list_ages[[s]]$old <- cci_met_list_ages[[s]]$old[
    which(names(cci_met_list_ages[[s]]$old) %in% ctps_preserved)]
}
```

```{r}
# within species, extract the list of interactions that are preserved,
# young_only, and old_only, as well as handy data frames for each cell type
overlap_lists <- lapply(cci_met_list_ages, function(cci_met_age){
  
  cci_met_yng_list <- cci_met_age[["yng"]]
  cci_met_old_list <- cci_met_age[["old"]]
  
  ctps_all <- unique(c(names(cci_met_yng_list), names(cci_met_old_list)))
  print(ctps_all[1:4])
  ctps_all_list <- as.list(ctps_all)
  
  overlap <- lapply(ctps_all_list, function(ctp){
    
    cci_met_yng <- cci_met_yng_list[[ctp]]
    cci_met_old <- cci_met_old_list[[ctp]]
    
    preserved <- intersect(unique(cci_met_yng$interaction), 
                        unique(cci_met_old$interaction))

    yng_only <- unique(cci_met_yng$interaction[which(!cci_met_yng$interaction %in% preserved)])
    old_only <- unique(cci_met_old$interaction[which(!cci_met_old$interaction %in% preserved)])
  
    # make sure the vectors are correct
    stopifnot(!yng_only %in% preserved)
    stopifnot(!old_only %in% preserved)
          
    stopifnot(!yng_only %in% cci_met_old$interaction)
    stopifnot(!old_only %in% cci_met_yng$interaction)
  
    stopifnot(preserved %in% cci_met_yng$interaction)
    stopifnot(preserved %in% cci_met_old$interaction)
    
    # count the length of each cell type entry  
    return_df <- data.frame(
      "mode" = c("preserved", "yng_only", "old_only"),
      "nr" = c(length(preserved), length(yng_only), length(old_only)),
      "cell_type_pair" = rep(ctp, 3),
      # within species, so species will be the same in each list item
      "species" = rep(cci_met_old_list[[1]]$species[1], 3)
      
    )
    
    return(list("preserved" = preserved,
                "yng_only" = yng_only,
                "old_only" = old_only,
                "nr_df" = return_df))
  })
  names(overlap) <- ctps_all
  return(overlap)
})
names(overlap_lists) <- names(cci_met_list_ages)

sort(names(overlap_lists$mmus))
names(overlap_lists[[1]][[1]])
```

```{r}
# extract only the nr_dfs for now!
nr_df_all <- data.frame()
for(i in 1:length(overlap_lists)){
  for(j in 1:length(overlap_lists[[i]])){

    nr_df_add <- overlap_lists[[i]][[j]]$nr_df
    nr_df_add$proportion <- nr_df_add$nr/sum(nr_df_add$nr)
    nr_df_add$normalized <- nr_df_add$nr/nr_df_add$nr[nr_df_add$mode == "preserved"]
      
    nr_df_all <- rbind(nr_df_all, nr_df_add)
    
  }
}

head(nr_df_all)
```

```{r}
nr_df_all$mode <- factor(nr_df_all$mode,
                         levels = c("old_only" ,"yng_only", "preserved"))
nr_df_all$mode_rev <- factor(nr_df_all$mode, 
                             levels = rev(c( "old_only" ,"yng_only", "preserved")))

nr_df_all$species <- factor(nr_df_all$species, levels = names(col_spc))
nr_df_all$species_rev <- factor(nr_df_all$species, levels = rev(names(col_spc)))

col_mode <- c("old_only" = "grey60", "yng_only" = "black", "preserved" = "orange2")

nr_df_all <- separate(nr_df_all, col = 3, sep = "&", into = c("Emitter", "Receiver"), remove = FALSE)

nr_df_all$Emitter <- factor(nr_df_all$Emitter,
                              levels = names(col_cts_str))
nr_df_all$Emitter_rev <- factor(nr_df_all$Emitter,
                                  levels = rev(names(col_cts_str)))

nr_df_all$Receiver <- factor(nr_df_all$Receiver,
                              levels = names(col_cts_hsc))
nr_df_all$Receiver_rev <- factor(nr_df_all$Receiver,
                                  levels = rev(names(col_cts_hsc)))
```

## Upset Plots 

```{r}
large_df <- bind_rows(cci_met_list_ages$mmus$yng)
large_df <- rbind(large_df, bind_rows(cci_met_list_ages$mmus$old))
large_df <- rbind(large_df, bind_rows(cci_met_list_ages$mcas$yng))
large_df <- rbind(large_df, bind_rows(cci_met_list_ages$mcas$old))
large_df <- rbind(large_df, bind_rows(cci_met_list_ages$mspr$yng))
large_df <- rbind(large_df, bind_rows(cci_met_list_ages$mspr$old))
large_df <- rbind(large_df, bind_rows(cci_met_list_ages$mcar$yng))
large_df <- rbind(large_df, bind_rows(cci_met_list_ages$mcar$old))

large_df$identifier <- paste0(large_df$interaction, "_", large_df$cell_type_pair, "_", large_df$species, "_", large_df$age)
large_df$mode <- vector(length = nrow(large_df))

ctps <- unique(c(cci_met_list$mmus_yng$overview$ident_pairs,
                 cci_met_list$mmus_old$overview$ident_pairs,
                 cci_met_list$mcas_yng$overview$ident_pairs,
                 cci_met_list$mcas_old$overview$ident_pairs,
                 cci_met_list$mspr_yng$overview$ident_pairs,
                 cci_met_list$mspr_old$overview$ident_pairs,
                 cci_met_list$mcar_yng$overview$ident_pairs,
                 cci_met_list$mcar_old$overview$ident_pairs))


for(s in species){
  for(c in ctps){
    
    pos <- which(large_df$species == s & large_df$ident_pair == c)
    
    large_df[pos,]$mode[large_df[pos,]$interaction %in% overlap_lists[[s]][[c]]$preserved] <- "preserved"
    large_df[pos,]$mode[large_df[pos,]$interaction %in% overlap_lists[[s]][[c]]$yng_only] <- "yng_only"
    large_df[pos,]$mode[large_df[pos,]$interaction %in% overlap_lists[[s]][[c]]$old_only] <- "old_only"

  }
}

table(large_df$mode)

large_df_upset <- large_df
large_df_upset_old <- large_df_upset[large_df_upset$mode == "old_only",]
large_df_upset_yng <- large_df_upset[large_df_upset$mode == "yng_only",]
large_df_upset_shr <- large_df_upset[large_df_upset$mode == "preserved",]
```

```{r}
for(s in species){
  
  print(s)
  
  large_df_upset_old$add <- vector(length = nrow(large_df_upset_old))
  large_df_upset_yng$add <- vector(length = nrow(large_df_upset_yng))
  large_df_upset_shr$add <- vector(length = nrow(large_df_upset_shr))

  all_ints_of_species_old <- unique(large_df_upset_old$interaction[large_df_upset_old$species == s])
  all_ints_of_species_yng <- unique(large_df_upset_yng$interaction[large_df_upset_yng$species == s])
  all_ints_of_species_shr <- unique(large_df_upset_shr$interaction[large_df_upset_shr$species == s])
  
  large_df_upset_old$add[large_df_upset_old$interaction %in% all_ints_of_species_old] <- TRUE
  large_df_upset_yng$add[large_df_upset_yng$interaction %in% all_ints_of_species_yng] <- TRUE
  large_df_upset_shr$add[large_df_upset_shr$interaction %in% all_ints_of_species_shr] <- TRUE
  
  colnames(large_df_upset_old)[colnames(large_df_upset_old) == "add"] <- s
  colnames(large_df_upset_yng)[colnames(large_df_upset_yng) == "add"] <- s
  colnames(large_df_upset_shr)[colnames(large_df_upset_shr) == "add"] <- s
  
}

large_df_upset_old <- large_df_upset_old[!duplicated(large_df_upset_old$interaction),]
large_df_upset_yng <- large_df_upset_yng[!duplicated(large_df_upset_yng$interaction),]
large_df_upset_shr <- large_df_upset_shr[!duplicated(large_df_upset_shr$interaction),]
```

# Important Plots

```{r fig.width= 10, fig.height = 5}
ggplot(nr_df_all, aes(y = Emitter_rev, x = nr, color = mode))+
  geom_boxplot()+
  theme_classic()+
  facet_grid(cols = vars(species))+
  scale_color_manual("", values = col_mode)+
  xlab("Nr of interactions per cell type pair")+
  theme(axis.text.x = element_text(angle = 90))+
  ylab("Emitter")

ggplot(nr_df_all, aes(y = Receiver_rev, x = nr, color = mode))+
  geom_boxplot()+
  theme_classic()+
  facet_grid(cols = vars(species))+
  scale_color_manual("", values = col_mode)+
  xlab("Nr of interactions per cell type pair")+
  theme(axis.text.x = element_text(angle = 90))+
  ylab("Receiver")
```

```{r, fig.width = 4, fig.height = 4}
ggplot(nr_df_all, aes(x = species, y = proportion, color = mode))+
  geom_boxplot()+
  ylab("Proportion of interactions per cell type pair")+
  theme_classic()+
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank())+
  scale_color_manual(" ", values = col_mode)+
  facet_grid(cols = vars(mode))+
  ylab("Species")

ggplot(nr_df_all, aes(x = mode_rev, y = proportion, color = mode))+
  geom_boxplot()+
  ylab("Proportion of interactions per cell type pair")+
  theme_classic()+
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank())+
  scale_color_manual("", values = col_mode)+
  facet_grid(cols = vars(species))+
  theme(axis.text.x = element_blank())
```

```{r, fig.width = 5, fig.height = 7}

upset(large_df_upset_old, intersect = c("mmus", "mcas", "mspr",  "mcar"),
      base_annotations=list(
        'Intersection size'=intersection_size(mapping=aes(fill='bars_color'))+
          scale_fill_manual(values=c('bars_color'= col_age[["old"]]), 
                            guide='none')))+
  xlab("")

upset(large_df_upset_yng, intersect = c("mmus", "mcas", "mspr",  "mcar"),
      base_annotations=list(
        'Intersection size'=intersection_size(mapping=aes(fill='bars_color'))+
          scale_fill_manual(values=c('bars_color'= col_age[["yng"]]), 
                            guide='none')))+
  xlab("")

upset(large_df_upset_shr, intersect = c("mmus", "mcas", "mspr",  "mcar"),
      base_annotations=list(
        'Intersection size'=intersection_size(mapping=aes(fill='bars_color'))+
          scale_fill_manual(values=c('bars_color'= "orange"), 
                            guide='none')))+
  xlab("")
```

```{r}
sessionInfo()
```