---
title: "scores summary"
author: "Lea Wölbert"
date: '2023-08-22'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Load objects

```{r seed,  message = FALSE}
set.seed(37)
```

```{r load,  message = FALSE}
library(tidyverse)
library(ggpubr)
library(scran)
library(ComplexUpset)
```

```{r}
#cci_mlist_mcar_old <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/main_analysis/cci_objects/01_cci_preparation/10_ipis/ipi_mcar_old")
#cci_mlist_mcar_yng <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/main_analysis/cci_objects/01_cci_preparation/10_ipis/ipi_mcar_yng")
#cci_mlist_mmus_old <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/main_analysis/cci_objects/01_cci_preparation/10_ipis/ipi_mmus_old")
#cci_mlist_mmus_yng <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/main_analysis/cci_objects/01_cci_preparation/10_ipis/ipi_mmus_yng")

#cci_met_list <- list(cci_mlist_mcar_old, cci_mlist_mcar_yng, cci_mlist_mmus_old, cci_mlist_mmus_yng)
#names(cci_met_list) <- c("mcar_old", "mcar_yng", "mmus_old", "mmus_yng")
#species <- c("mcar", "mmus")

cci_met_path_list <- snakemake@input[["cci_met_paths"]]
print(cci_met_path_list)

species <- snakemake@params[["species"]]
age <- snakemake@params[["age"]]

cci_met_list <- list()
for(s in species){
  for(a in age){
    cond <- as.character(paste0(s, "_", a))
    print(cond)
    cci_met_path <- cci_met_path_list[[which(grepl(cond, cci_met_path_list))]]
    print(cci_met_path)
    cci_met_list[[cond]] <- readRDS(cci_met_path)
  }
}

print(names(cci_met_list))

```

# Preparation

```{r}
species_list <- as.list(species)
cci_score_delta_list <- lapply(species_list, function(s, cci_met_list){
  
  cci_met <- cci_met_list[grep(s, names(cci_met_list))]
  print(names(cci_met))

  cci_met_yng <- cci_met[[grep("yng", names(cci_met))]]
  cci_met_old <- cci_met[[grep("old", names(cci_met))]]
  print(head(cci_met_yng$overview))
  
  ctps_shared <- intersect(names(cci_met_yng$separate), 
                           names(cci_met_old$separate))
  
  cci_met_yng_s <- cci_met_yng$separate[ctps_shared]
  cci_met_old_s <- cci_met_old$separate[ctps_shared]
  
  overview_yng <- cci_met_yng$overview
  overview_old <- cci_met_old$overview
  
  print(ctps_shared[1:10])
  
  score_delta_df <- lapply(as.list(ctps_shared), function(ctp, cci_met_yng_s, 
                                                          cci_met_old_s,
                                                          overview_yng,
                                                          overview_old){
    
    yng_df <- cci_met_yng_s[[ctp]]
    old_df <- cci_met_old_s[[ctp]]
    
    yng_df$interactome_size_yng <- rep(overview_yng[
      overview_yng$ident_pairs == ctp,]$nr_ints, nrow(yng_df))
    old_df$interactome_size_old <- rep(overview_old[
      overview_old$ident_pairs == ctp,]$nr_ints, nrow(old_df))
    
    ints_shared <- intersect(yng_df$interaction, old_df$interaction)
    yng_df <- yng_df[yng_df$interaction %in% ints_shared,]
    old_df <- old_df[old_df$interaction %in% ints_shared,]
    
    old_df <- old_df[match(yng_df$interaction, old_df$interaction),]
    
    colnames(yng_df)[colnames(yng_df) == "score"] <- "score_yng"
    colnames(yng_df)[
      colnames(yng_df) == "nr_cells_emitter"] <- "nr_cells_emitter_yng"
    colnames(yng_df)[colnames(yng_df) == "ligandrank"] <- "ligandrank_yng"
    colnames(yng_df)[
      colnames(yng_df) == "nr_cells_receiver"] <- "nr_cells_receiver_yng"
    colnames(yng_df)[colnames(yng_df) == "receptorrank"] <- "receptorrank_yng"
    
    stopifnot(identical(yng_df$interaction, old_df$interaction))
    
    return_df <- yng_df[,-which(colnames(yng_df) == "age")]

    return_df$score_old <- old_df$score
    return_df$score_delta <- return_df$score_old - return_df$score_yng
    
    return_df$nr_cells_emitter_old <- old_df$nr_cells_emitter
    return_df$nr_cells_receiver_old <- old_df$nr_cells_receiver

    return_df$ligandrank_old <- old_df$ligandrank
    return_df$receptorrank_old <- old_df$receptorrank
    
    return_df$ligandrank_delta <- return_df$ligandrank_old -
      return_df$ligandrank_yng
    return_df$receptorrank_delta <- return_df$receptorrank_old - 
      return_df$receptorrank_yng
    
    return_df$interactome_size_old <- old_df$interactome_size_old

    return(return_df)
    },
    
  cci_met_yng_s,
  cci_met_old_s,
  overview_yng,
  overview_old
  
  )
  return(score_delta_df)
  },
  cci_met_list
)

```

```{r}
score_delta_df <- bind_rows(cci_score_delta_list)
print(nrow(score_delta_df))
```

```{r}
colors_path <- snakemake@params[["colors_path"]]
source(snakemake@params[["colors"]])
#colors_path <- "/omics/odcf/analysis/OE0538_projects/DO-0008/metadata/colors/colors.txt"
#source("/home/l012t/repositories/Interspecies_BM_phd/code/source/colors.R") 

col_cts_emi <- col_cts_str[names(col_cts_str) %in% unique(score_delta_df$emitter)]
col_cts_rec <- col_cts_hsc[names(col_cts_hsc) %in% unique(score_delta_df$receiver)]

score_delta_df$emitter <- factor(
  score_delta_df$emitter,
  levels = names(col_cts_emi[names(col_cts_emi) %in% score_delta_df$emitter]))

score_delta_df$receiver <- factor(
  score_delta_df$receiver,
  levels = names(col_cts_rec[names(col_cts_rec) %in% score_delta_df$receiver]))

score_delta_df$species <- factor(
  score_delta_df$species,
  levels = names(col_spc))
```

```{r}

ctps <- unique(score_delta_df$ident_pair)

outlier_list <- lapply(as.list(ctps), function(ctp, score_delta_df){
  
  species_list <- lapply(as.list(species), function(species, ctp, 
                                                    score_delta_df){
    
    # subset by cell type to get outliers within cell type
    score_delta_df_ctp <- score_delta_df[score_delta_df$ident_pair == ctp,]
   
    # subset by species as well
    score_delta_df_ctp <- score_delta_df_ctp[
      score_delta_df_ctp$species == species,]
    
    mean <- mean(abs(score_delta_df_ctp$score_delta))
    sd <- sd(abs(score_delta_df_ctp$score_delta))

    outlier <- mean + 3*sd
    
    return_df <- score_delta_df_ctp[
      which(abs(score_delta_df_ctp$score_delta) > outlier),]
    
    return(return_df)
  
  }, ctp, score_delta_df)
  
  # bind rows again to have on df per cell type
  names(species_list) <- species
  species_df <- bind_rows(species_list)
  return(species_df)
  
}, score_delta_df)
names(outlier_list) <- ctps

outlier_df <- bind_rows(outlier_list)
head(outlier_df)
```

```{r}
outlier_df$direction[outlier_df$score_delta < 0] <- "decrease during ageing"
outlier_df$direction[outlier_df$score_delta > 0] <- "increase during ageing"

outlier_df_slim <- outlier_df[,c(1, 2, 4, 7, 10, 22)]

outlier_df_slim_up <- outlier_df_slim[outlier_df_slim$direction == "increase during ageing",]
outlier_df_slim_dw <- outlier_df_slim[outlier_df_slim$direction == "decrease during ageing",]

for(s in species){
  
  outlier_df_slim_up$add <- vector(length = nrow(outlier_df_slim_up))
  outlier_df_slim_dw$add <- vector(length = nrow(outlier_df_slim_dw))
  
  all_ints_of_species_up <- unique(outlier_df_slim_up$interaction[outlier_df_slim_up$species == s])
  all_ints_of_species_dw <- unique(outlier_df_slim_dw$interaction[outlier_df_slim_dw$species == s])
  
  outlier_df_slim_up$add[outlier_df_slim_up$interaction %in% all_ints_of_species_up] <- TRUE
  outlier_df_slim_dw$add[outlier_df_slim_dw$interaction %in% all_ints_of_species_dw] <- TRUE
  
  colnames(outlier_df_slim_up)[colnames(outlier_df_slim_up) == "add"] <- s
  colnames(outlier_df_slim_dw)[colnames(outlier_df_slim_dw) == "add"] <- s
  
}

outlier_df_slim_up_short <- outlier_df_slim_up[!duplicated(outlier_df_slim_up$interaction),]
outlier_df_slim_dw_short <- outlier_df_slim_dw[!duplicated(outlier_df_slim_dw$interaction),]
```


# Important Plots

```{r fig.width = 4, fig.height = 4}
ggplot(outlier_df, aes(x = species, y = score_delta, color = species))+
  geom_jitter()+
  theme_classic()+
  scale_color_manual(values = col_spc)
```

```{r fig.width = 4, fig.height = 4}
score_delta_df$identifier <- paste0(score_delta_df$ident_pair, "_", score_delta_df$interaction, "_", score_delta_df$species)
outlier_df$identifier <- paste0(outlier_df$ident_pair, "_", outlier_df$interaction, "_", outlier_df$species)

score_delta_df$is_outlier <- vector(length = nrow(score_delta_df))

pos <- match(outlier_df$identifier, score_delta_df$identifier)
score_delta_df$is_outlier[pos] <- TRUE

ggplot(score_delta_df, aes(x = species, y = score_delta, color = is_outlier))+
  geom_jitter(alpha = 0.6)+
  theme_classic()+
  scale_color_manual(values = c("FALSE" = "grey80", "TRUE" = "dodgerblue3"))+
  theme(axis.text.x = element_text(angle = 90))+
  xlab("Species")+
  ylab("Delta Score (old - young)")
```

```{r fig.width = 4, fig.height = 4}
ggplot(score_delta_df, 
       aes(x = species, y = abs(score_delta), color = species))+
  geom_boxplot(outlier.size =  0.4)+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90),
        legend.position = "none")+
  xlab("Species")+
  ylab("|Delta Score (old - ynd)|")+
  scale_color_manual("Species", values = col_spc)+
  stat_compare_means(test = 'kruskal.test', p.adjust.method = "BH", label.y = 1.5)+
  stat_compare_means(
    comparisons = list(c("mmus", "mcas"), c("mmus", "mspr"), c("mmus", "mcar"),
                       c("mcas", "mspr"), c("mcas", "mcar"), c("mspr", "mcar")),
    test = 'dunn_test', p.adjust.method = "BH", hide.ns = TRUE, aes(label = after_stat(p.signif)))

ggplot(score_delta_df, 
       aes(x = species, y = abs(score_delta)))+
  geom_violin(fill = "grey80", color = "grey80")+
  geom_boxplot(outlier.size =  0.4, alpha = 0.3, color = "black")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90),
        legend.position = "none")+
  xlab("Species")+
  ylab("|Delta Score (old - yng)|")+
  stat_compare_means(method = 'kruskal.test', p.adjust.method = "BH", label.y = 1.3)+
  stat_compare_means(
    comparisons = list(c("mmus", "mcas"), c("mmus", "mspr"), c("mmus", "mcar"),
                       c("mcas", "mspr"), c("mcas", "mcar"), c("mspr", "mcar")),
    test = 'dunn_test', p.adjust.method = "BH", hide.ns = TRUE, aes(label = after_stat(p.signif)))+
  ylim(c(0, 1.4))

ggplot(score_delta_df, 
       aes(x = species, y = abs(score_delta)))+
  geom_violin(color = "grey80", fill = "grey80")+
  geom_boxplot(outlier.size =  0.4, color = "black", alpha = 0.3)+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90),
        legend.position = "none")+
  xlab("Species")+
  ylab("|Delta Score (old - ynd)|")+
  scale_color_manual("Species", values = col_spc)+
  stat_compare_means(test = 'kruskal.test', p.adjust.method = "BH")
```

```{r fig.width = 4, fig.height = 4}
ggplot(outlier_df, 
       aes(x = species, y = abs(score_delta)))+
  geom_violin(color = "dodgerblue3", fill= "dodgerblue3")+
  geom_boxplot(outlier.size =  0.4, color = "black", alpha = 0.3)+
  theme_classic()+
  stat_compare_means(method = 'kruskal.test', p.adjust.method = "BH", label.y = 1.3)+
  stat_compare_means(
    comparisons = list(c("mmus", "mcas"), c("mmus", "mspr"), c("mmus", "mcar"),
                       c("mcas", "mspr"), c("mcas", "mcar"), c("mspr", "mcar")),
    test = 'dunn_test', p.adjust.method = "BH", hide.ns = TRUE, aes(label = after_stat(p.signif)))+
  theme(axis.text.x = element_text(angle = 90))+
  xlab("Species")+
  ylab("|Delta Scores (old-young)|")+
  ylim(c(0, 1.4))
```

```{r fig.width = 4, fig.height = 4}
nr_df <- as.data.frame(table(outlier_df$ident_pair, outlier_df$species))

ggplot(nr_df, aes(x = Freq, fill = Var2))+
  geom_bar()+
  theme_classic()+
  theme(strip.text.y = element_text(angle = 0))+
  scale_fill_manual("Species", values = col_spc)+
  facet_grid(rows = vars(Var2))+
  xlab("Nr of outlier interactions per cell type pair")+
  ylab("Frequency")

```

```{r}

ggplot(score_delta_df, 
       aes(x = emitter, y = abs(score_delta), fill = emitter))+
  geom_violin(alpha = 0.7, draw_quantiles = c(0.5))+
 # geom_boxplot(alpha = 0)+
  theme_classic()+
  facet_grid(cols = vars(score_delta_df$species))+
  scale_fill_manual("Emitter", values = col_cts_emi)+
  theme(axis.text.x = element_text(angle = 90),
        legend.position = "none")

ggplot(score_delta_df, 
       aes(x = receiver, y = abs(score_delta), fill = receiver))+
  geom_violin(alpha = 0.7, draw_quantiles = c(0.5))+
  theme_classic()+
  facet_grid(cols = vars(score_delta_df$species))+
  scale_fill_manual("Receiver", values = col_cts_rec)+
  theme(axis.text.x = element_text(angle = 90),
        legend.position = "none")
```

```{r fig.width = 4, fig.height = 4}

upset(outlier_df_slim_up_short, intersect = c("mmus", "mcas", "mspr",  "mcar"), # "mcas", "mspr", 
      width_ratio=0.1,
      base_annotations=list(
        'Intersection size'=intersection_size(mapping=aes(fill='bars_color'))+
          scale_fill_manual(values=c('bars_color'= "skyblue1"), 
                            guide='none')))+
  ggtitle("Overlap between interactions that increase during ageing")

upset(outlier_df_slim_dw_short, intersect = c("mmus", "mcas", "mspr",  "mcar"), # "mcas", "mspr", 
      width_ratio=0.1,
      base_annotations=list(
        'Intersection size'= intersection_size(mapping=aes(fill='bars_color'))+
          scale_fill_manual(values=c('bars_color'= "dodgerblue4"), 
                            guide='none')))+
  ggtitle("Overlap between interactions that decrease during ageing")
```

```{r fig.height = 9}
ggdf1 <- outlier_df

ggdf1$species_pos <- vector(length = nrow(ggdf1))
ggdf1$species_pos[ggdf1$species == "mmus"] <- 4
ggdf1$species_pos[ggdf1$species == "mcas"] <- 3
ggdf1$species_pos[ggdf1$species == "mspr"] <- 2
ggdf1$species_pos[ggdf1$species == "mcar"] <- 1

nr <- table(ggdf1$interaction)
only_once <- names(nr[which(nr == 1)])
ggdf1_temp <- ggdf1[!ggdf1$interaction %in% only_once,]

ggplot(ggdf1_temp, aes(y = reorder(interaction, species_pos), fill = direction))+
  geom_bar(position = "stack")+
  facet_grid(cols = vars(species))+
  xlab("Nr of cell type pairs per species")+
  ylab("Outlier Interactions")+
  scale_fill_manual("", values = c("increase during ageing" = "skyblue1",
                                   "decrease during ageing" = "dodgerblue4"))

ggplot(ggdf1, aes(y = reorder(interaction, species_pos), fill = direction))+
  geom_bar(position = "stack")+
  facet_grid(cols = vars(species))+
  xlab("Nr of cell type pairs per species")+
  ylab("Outlier Interactions")+
  scale_fill_manual("", values = c("increase during ageing" = "skyblue1",
                                   "decrease during ageing" = "dodgerblue4"))
```

# QC

## Per cell type

```{r}
ggplot(score_delta_df, 
       aes(x = emitter, y = score_delta, color = emitter))+
  geom_boxplot(alpha = 0)+
  theme_classic()+
  ggtitle("shared interactions only")+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_manual("Emitter", values = col_cts_emi)+
  facet_grid(cols = vars(score_delta_df$species))

ggplot(score_delta_df, 
       aes(x = receiver, y = score_delta, color = receiver))+
  geom_boxplot(alpha = 0)+
  theme_classic()+
  ggtitle("shared interactions only")+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_manual("Receiver", values = col_cts_rec)+
  facet_grid(cols = vars(score_delta_df$species))
```

```{r}
ggplot(score_delta_df, 
       aes(x = species, y = score_delta, color = emitter))+
  geom_boxplot(alpha = 0)+
  theme_classic()+
  ggtitle("shared interactions only")+
  theme(axis.text.x = element_text(angle = 90),
        strip.text.x = element_text(angle = 90),
        legend.position = "none")+
  scale_color_manual("Emitter", values = col_cts_emi)+
  facet_grid(cols = vars(score_delta_df$emitter))

ggplot(score_delta_df, 
       aes(x = species, y = score_delta, color = receiver))+
  geom_boxplot(alpha = 0)+
  theme_classic()+
  ggtitle("shared interactions only")+
  theme(axis.text.x = element_text(angle = 90),
        strip.text.x = element_text(angle = 90),
        legend.position = "none")+
  scale_color_manual("Receiver", values = col_cts_rec)+
  facet_grid(cols = vars(score_delta_df$receiver))
```
```{r}

ggplot(score_delta_df, 
       aes(x = species, y = abs(score_delta)))+
  geom_boxplot()+
  theme_classic()+
  ggtitle("shared interactions only")+
  facet_grid(cols = vars(score_delta_df$emitter))+
  theme(strip.text.x = element_text(angle = 90),
        axis.text.x = element_text(angle = 90))

ggplot(score_delta_df, 
       aes(x = species, y = abs(score_delta)))+
  geom_boxplot()+
  theme_classic()+
  ggtitle("shared interactions only")+
  facet_grid(cols = vars(score_delta_df$receiver))+
  theme(strip.text.x = element_text(angle = 90),
        axis.text.x = element_text(angle = 90))
```

```{r}
ggplot(score_delta_df, 
       aes(x = species, y = abs(score_delta), fill = emitter))+
  geom_violin(alpha = 0.7, draw_quantiles = c(0.5))+
  theme_classic()+
  ggtitle("shared interactions only")+
  scale_fill_manual("Emitter", values = col_cts_emi)+
  facet_grid(cols = vars(score_delta_df$emitter))+
  theme(strip.text.x = element_text(angle = 90),
        axis.text.x = element_text(angle = 90))

ggplot(score_delta_df, 
       aes(x = species, y = abs(score_delta), fill = receiver))+
  geom_violin(alpha = 0.7, draw_quantiles = c(0.5))+
  theme_classic()+
  ggtitle("shared interactions only")+
  scale_fill_manual("Receiver", values = col_cts_rec)+
  facet_grid(cols = vars(score_delta_df$receiver))+
  theme(strip.text.x = element_text(angle = 90),
        axis.text.x = element_text(angle = 90))

ggplot(score_delta_df, 
       aes(x = species, y = abs(score_delta), fill = species))+
  geom_violin(alpha = 0.7, draw_quantiles = c(0.5))+
  theme_classic()+
  ggtitle("shared interactions only")+
  scale_fill_manual("Species", values = col_spc)+
  facet_grid(cols = vars(score_delta_df$emitter))+
  theme(strip.text.x = element_text(angle = 90),
        axis.text.x = element_text(angle = 90))

ggplot(score_delta_df, 
       aes(x = species, y = abs(score_delta), fill = species))+
  geom_violin(alpha = 0.7, draw_quantiles = c(0.5))+
  theme_classic()+
  ggtitle("shared interactions only")+
  scale_fill_manual("Species", values = col_spc)+
  facet_grid(cols = vars(score_delta_df$receiver))+
  theme(strip.text.x = element_text(angle = 90),
        axis.text.x = element_text(angle = 90))
```

```{r}

ggplot(score_delta_df, aes(x = species, y = score_delta, 
                           color = nr_cells_emitter_yng))+
  geom_jitter(alpha = 0.3)+
  theme_classic()

ggplot(score_delta_df, aes(x = species, y = score_delta, 
                           color = nr_cells_emitter_old))+
  geom_jitter(alpha = 0.3)+
  theme_classic()

ggplot(score_delta_df, aes(x = species, y = score_delta, 
                           color = nr_cells_receiver_yng))+
  geom_jitter(alpha = 0.3)+
  theme_classic()

ggplot(score_delta_df, aes(x = species, y = score_delta, 
                           color = nr_cells_receiver_old))+
  geom_jitter(alpha = 0.3)+
  theme_classic()
```

```{r}

ggplot(score_delta_df, aes(x = species, y = score_delta, 
                           color = interactome_size_yng))+
  ggbeeswarm::geom_quasirandom(alpha = 0.5, size = 0.9)+
  theme_classic()+
  scale_color_continuous(limits = c(0, max(
    c(score_delta_df$interactome_size_yng, score_delta_df$interactome_size_old))))

ggplot(score_delta_df, aes(x = species, y = score_delta, 
                           color = interactome_size_old))+
  ggbeeswarm::geom_quasirandom(alpha = 0.5, size = 0.9)+
  theme_classic()+
  scale_color_continuous(limits = c(0, max(
    c(score_delta_df$interactome_size_yng, score_delta_df$interactome_size_old))))
```

```{r}

ggdf2 <- separate(outlier_df, col = "interaction", 
                       sep = "_", remove = FALSE,
                       into = c("Ligand", "Receptor"))

sort(table(ggdf2$Ligand), decreasing = TRUE)

ggdf2$species_pos <- vector(length = nrow(ggdf2))
ggdf2$species_pos[ggdf2$species == "mmus"] <- 4
ggdf2$species_pos[ggdf2$species == "mcas"] <- 3
ggdf2$species_pos[ggdf2$species == "mspr"] <- 2
ggdf2$species_pos[ggdf2$species == "mcar"] <- 1

ggdf2$direction <- vector(length = nrow(ggdf2))
ggdf2$direction[ggdf2$score_delta < 0] <- "decrease during ageing"
ggdf2$direction[ggdf2$score_delta > 0] <- "increase during ageing"

maxn <-40

table(ggdf2$Ligand, ggdf2$direction)

nr <- table(ggdf2$Ligand)
only_once <- names(nr[which(nr == 1)])

ggdf2_temp <- ggdf2[!ggdf2$Ligand %in% only_once,]
      
ggplot(ggdf2_temp, aes(y = reorder(Ligand, species_pos), fill = direction))+
  geom_bar(position = "stack")+
  facet_grid(cols = vars(species))+
  xlim(c(0, maxn))+
  scale_fill_manual("", values = c("increase during ageing" = "skyblue1",
                                   "decrease during ageing" = "dodgerblue4"))

ggplot(ggdf2_temp[ggdf2_temp$species == "mmus",], aes(y = Ligand, fill = direction))+
  geom_bar(position = "stack")+
  facet_grid(cols = vars(ggdf2_temp[ggdf2_temp$species == "mmus",]$emitter))+
  theme(strip.text.x = element_text(angle = 90))+
  ggtitle("mmus")+
  xlim(c(0, maxn))+
  scale_fill_manual("", values = c("increase during ageing" = "skyblue1",
                                   "decrease during ageing" = "dodgerblue4"))

ggplot(ggdf2_temp[ggdf2_temp$species == "mcas",], aes(y = Ligand, fill = direction))+
  geom_bar(position = "stack")+
  facet_grid(cols = vars(ggdf2_temp[ggdf2_temp$species == "mcas",]$emitter))+
  theme(strip.text.x = element_text(angle = 90))+
  ggtitle("mcas")+
  xlim(c(0, maxn))+
  scale_fill_manual("", values = c("increase during ageing" = "skyblue1",
                                   "decrease during ageing" = "dodgerblue4"))

ggplot(ggdf2_temp[ggdf2_temp$species == "mspr",], aes(y = Ligand, fill = direction))+
  geom_bar(position = "stack")+
  facet_grid(cols = vars(ggdf2_temp[ggdf2_temp$species == "mspr",]$emitter))+
  theme(strip.text.x = element_text(angle = 90))+
  ggtitle("mspr")+
  xlim(c(0, maxn))+
  scale_fill_manual("", values = c("increase during ageing" = "skyblue1",
                                   "decrease during ageing" = "dodgerblue4"))

ggplot(ggdf2_temp[ggdf2_temp$species == "mcar",], aes(y = Ligand, fill = direction))+
  geom_bar(position = "stack")+
  facet_grid(cols = vars(ggdf2_temp[ggdf2_temp$species == "mcar",]$emitter))+
  theme(strip.text.x = element_text(angle = 90))+
  ggtitle("mcar")+
  xlim(c(0, maxn))+
  scale_fill_manual("", values = c("increase during ageing" = "skyblue1",
                                   "decrease during ageing" = "dodgerblue4"))

```




```{r}
sort(table(ggdf2$Receptor), decreasing = TRUE)

ggdf2$species_pos <- vector(length = nrow(ggdf2))
ggdf2$species_pos[ggdf2$species == "mmus"] <- 1
ggdf2$species_pos[ggdf2$species == "mcas"] <- 2
ggdf2$species_pos[ggdf2$species == "mspr"] <- 3
ggdf2$species_pos[ggdf2$species == "mcar"] <- 4

ggdf2$direction <- vector(length = nrow(ggdf2))
ggdf2$direction[ggdf2$score_delta < 0] <- "decrease during ageing"
ggdf2$direction[ggdf2$score_delta > 0] <- "increase during ageing"

maxn <- as.numeric(max(table(ggdf2$Receptor)))

table(ggdf2$Receptor, ggdf2$direction)

ggplot(ggdf2, aes(y = reorder(Receptor, species_pos), fill = direction))+
  geom_bar(position = "stack")+
  facet_grid(cols = vars(species))+
  xlim(c(0, maxn))+
  scale_fill_manual("", values = c("increase during ageing" = "skyblue1",
                                   "decrease during ageing" = "dodgerblue4"))


ggplot(ggdf2[ggdf2$species == "mmus",], aes(y = Receptor, fill = direction))+
  geom_bar(position = "stack")+
  facet_grid(cols = vars(ggdf2[ggdf2$species == "mmus",]$receiver))+
  theme(strip.text.x = element_text(angle = 90))+
  ggtitle("mmus")+
  xlim(c(0, maxn))+
  scale_fill_manual("", values = c("increase during ageing" = "skyblue1",
                                   "decrease during ageing" = "dodgerblue4"))


ggplot(ggdf2[ggdf2$species == "mcas",], aes(y = Receptor, fill = direction))+
  geom_bar(position = "stack")+
  facet_grid(cols = vars(ggdf2[ggdf2$species == "mcas",]$receiver))+
  theme(strip.text.x = element_text(angle = 90))+
  ggtitle("mcas")+
  xlim(c(0, maxn))+
  scale_fill_manual("", values = c("increase during ageing" = "skyblue1",
                                   "decrease during ageing" = "dodgerblue4"))


ggplot(ggdf2[ggdf2$species == "mspr",], aes(y = Receptor, fill = direction))+
  geom_bar(position = "stack")+
  facet_grid(cols = vars(ggdf2[ggdf2$species == "mspr",]$receiver))+
  theme(strip.text.x = element_text(angle = 90))+
  ggtitle("mspr")+
  xlim(c(0, maxn))+
  scale_fill_manual("", values = c("increase during ageing" = "skyblue1",
                                   "decrease during ageing" = "dodgerblue4"))


ggplot(ggdf2[ggdf2$species == "mcar",], aes(y = Receptor, fill = direction))+
  geom_bar(position = "stack")+
  facet_grid(cols = vars(ggdf2[ggdf2$species == "mcar",]$receiver))+
  theme(strip.text.x = element_text(angle = 90))+
  ggtitle("mcar")+
  xlim(c(0, maxn))+
  scale_fill_manual("", values = c("increase during ageing" = "skyblue1",
                                   "decrease during ageing" = "dodgerblue4"))
```

```{r}
ggplot(score_delta_df, 
       aes(x = species, y = ligandrank_delta))+
  geom_violin(fill = "grey80", color = "grey80")+
  geom_boxplot(outlier.size =  0.4, alpha = 0.3, color = "black")+
  theme_classic()+
  ggtitle("shared interactions only")

ggplot(score_delta_df, 
       aes(x = species, y = abs(ligandrank_delta)))+
  geom_violin(fill = "grey80", color = "grey80")+
  geom_boxplot(outlier.size =  0.4, alpha = 0.3, color = "black")+
  theme_classic()+
  ggtitle("shared interactions only")+
  stat_compare_means(test = 'kruskal.test', p.adjust.method = "BH", label.y = 0.9)+
  stat_compare_means(
    comparisons = list(c("mmus", "mcas"), c("mmus", "mspr"), c("mmus", "mcar"),
                       c("mcas", "mspr"), c("mcas", "mcar"), c("mspr", "mcar")),
    test = 'dunn_test', p.adjust.method = "BH", hide.ns = TRUE, aes(label = after_stat(p.signif)))

ggplot(score_delta_df, 
       aes(x = species, y = abs(ligandrank_delta)))+
  geom_violin(fill = "grey80", color = "grey80")+
  geom_boxplot(outlier.size =  0.4, alpha = 0.3, color = "black")+
  theme_classic()+
  ggtitle("shared interactions only")
```


```{r}

ggplot(score_delta_df, aes(x = species, y = ligandrank_delta, 
                           color = nr_cells_emitter_yng))+
  geom_jitter(alpha = 0.3)+
  theme_classic()

ggplot(score_delta_df, aes(x = species, y = ligandrank_delta, 
                           color = nr_cells_emitter_old))+
  geom_jitter(alpha = 0.3)+
  theme_classic()

ggplot(score_delta_df, aes(x = species, y = ligandrank_delta, 
                           color = nr_cells_receiver_yng))+
  geom_jitter(alpha = 0.3)+
  theme_classic()

ggplot(score_delta_df, aes(x = species, y = ligandrank_delta, 
                           color = nr_cells_receiver_old))+
  geom_jitter(alpha = 0.3)+
  theme_classic()
```

```{r}

ggplot(score_delta_df, aes(x = species, y = ligandrank_delta, 
                           color = interactome_size_yng))+
  ggbeeswarm::geom_quasirandom(alpha = 0.5, size = 0.9)+
  theme_classic()+
  scale_color_continuous(limits = c(0, max(
    c(score_delta_df$interactome_size_yng, score_delta_df$interactome_size_old))))

ggplot(score_delta_df, aes(x = species, y = ligandrank_delta, 
                           color = interactome_size_old))+
  ggbeeswarm::geom_quasirandom(alpha = 0.5, size = 0.9)+
  theme_classic()+
  scale_color_continuous(limits = c(0, max(
    c(score_delta_df$interactome_size_yng, score_delta_df$interactome_size_old))))
```



```{r}
ggplot(score_delta_df, 
       aes(x = species, y = receptorrank_delta))+
  geom_violin(fill = "grey80", color = "grey80")+
  geom_boxplot(outlier.size =  0.4, alpha = 0.3, color = "black")+
  theme_classic()+
  ggtitle("shared interactions only")

ggplot(score_delta_df, 
       aes(x = species, y = abs(receptorrank_delta)))+
  geom_violin(fill = "grey80", color = "grey80")+
  geom_boxplot(outlier.size =  0.4, alpha = 0.3, color = "black")+
  theme_classic()+
  ggtitle("shared interactions only")+
  stat_compare_means(test = 'kruskal.test', p.adjust.method = "BH", label.y = 0.9)+
  stat_compare_means(
    comparisons = list(c("mmus", "mcas"), c("mmus", "mspr"), c("mmus", "mcar"),
                       c("mcas", "mspr"), c("mcas", "mcar"), c("mspr", "mcar")),
    test = 'dunn_test', p.adjust.method = "BH", hide.ns = TRUE,
    aes(label = after_stat(p.signif)))

ggplot(score_delta_df, 
       aes(x = species, y = abs(receptorrank_delta)))+
  geom_violin(fill = "grey80", color = "grey80")+
  geom_boxplot(outlier.size =  0.4, alpha = 0.3, color = "black")+
 theme_classic()+
  ggtitle("shared interactions only")
```

```{r}

ggplot(score_delta_df, aes(x = species, y = ligandrank_delta, 
                           color = nr_cells_emitter_yng))+
  geom_jitter(alpha = 0.3)+
  theme_classic()

ggplot(score_delta_df, aes(x = species, y = ligandrank_delta, 
                           color = nr_cells_emitter_old))+
  geom_jitter(alpha = 0.3)+
  theme_classic()

ggplot(score_delta_df, aes(x = species, y = ligandrank_delta, 
                           color = nr_cells_receiver_yng))+
  geom_jitter(alpha = 0.3)+
  theme_classic()

ggplot(score_delta_df, aes(x = species, y = ligandrank_delta, 
                           color = nr_cells_receiver_old))+
  geom_jitter(alpha = 0.3)+
  theme_classic()
```

```{r}

ggplot(score_delta_df, aes(x = species, y = ligandrank_delta, 
                           color = interactome_size_yng))+
  ggbeeswarm::geom_quasirandom(alpha = 0.5, size = 0.9)+
  theme_classic()+
  scale_color_continuous(limits = c(0, max(
    c(score_delta_df$interactome_size_yng, score_delta_df$interactome_size_old))))

ggplot(score_delta_df, aes(x = species, y = ligandrank_delta, 
                           color = interactome_size_old))+
  ggbeeswarm::geom_quasirandom(alpha = 0.5, size = 0.9)+
  theme_classic()+
  scale_color_continuous(limits = c(0, max(
    c(score_delta_df$interactome_size_yng, score_delta_df$interactome_size_old))))
```

```{r}
sessionInfo()
```