---
title: "Reference annotation summary report"
author: "Amy Danson, Lea Wölbert"
date: '2022-09-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Summary report on quality for all objects at once.

#### Load libraries, source code, objects

```{r seed, message = FALSE}
set.seed(37)
```

```{r load,  message = FALSE}
library(scuttle, quietly = TRUE) 
```

```{r source, message = FALSE}
source(file = snakemake@params[["plotting"]])
```

```{r load_objects, message = FALSE}
sce_06_pathlist <- snakemake@input[["sce_input_pathlist"]]
samples_to_remove <- snakemake@params[["samples_to_remove"]] # samples to exclude from merging
individuals <- snakemake@params[["individuals"]]
```

# QC

### Preparation

```{r qc_prep}

sce_list_06 <- list()
names(sce_06_pathlist) <- unlist(sce_06_pathlist)

for(i in individuals){
  sce_list_06[[i]] <- readRDS(file = sce_06_pathlist[[
    which(grepl(i, names(sce_06_pathlist)))]])
}

sce_list_06 <- sce_list_06[names(sce_list_06)[!names(sce_list_06) %in% 
                                                samples_to_remove]]
```

## All cells after QC

Check Quality per sample in a large overview.

### Before

```{r qc_before, fig.width = 14}

qcdf_list_06 <- lapply(sce_list_06, function(sce){
  
  qcdf <- scuttle::perCellQCMetrics(sce, assay.type = "counts")
  qcdf$Object_ID <- sce$Object_ID
  qcdf$Species_ID <- sce$Species_ID
  qcdf$Age <- sce$Age
  qcdf$Batch_exp_day <- sce$Batch_exp_day
  qcdf$Batch_sequencing <- sce$Batch_sequencing
  qcdf$Date_collected <- sce$Date_collected
  qcdf$Species <- sce$Species
  qcdf$Fraction <- sce$Fraction
  qcdf$baccin_celltype_scmapclust <- sce$baccin_celltype_scmapclust
  qcdf$dahlin_celltype_scmapclust <- sce$dahlin_celltype_scmapclust
  qcdf$dolgalev_celltype_scmapclust <- sce$dolgalev_celltype_scmapclust

  return(qcdf)
})

qcdf_gg <- DataFrame()

for(i in qcdf_list_06){
  qcdf_gg <- rbind(qcdf_gg, i)
}
qcdf_gg <- data.frame(qcdf_gg)

# by Sample
ggplot(qcdf_gg, aes(x = Object_ID, y = sum))+
  ggbeeswarm::geom_quasirandom(size = 0.1, color = "grey60")+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 120000))+
  scale_y_log10()

ggplot(qcdf_gg, aes(x = Object_ID, y = detected))+
  ggbeeswarm::geom_quasirandom(size = 0.1, color = "grey60")+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 10000))+
  scale_y_log10()

# by Age and Species
ggplot(qcdf_gg, aes(x = Age, y = sum))+
  ggbeeswarm::geom_quasirandom(size = 0.1, color = "grey60")+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 120000))+
  scale_y_log10()+
  facet_grid(cols = vars(qcdf_gg$Species))

ggplot(qcdf_gg, aes(x = Age, y = detected))+
  ggbeeswarm::geom_quasirandom(size = 0.1, color = "grey60")+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 10000))+
  scale_y_log10()+
  facet_grid(cols = vars(qcdf_gg$Species))

# by Fraction and Species
ggplot(qcdf_gg, aes(x = Fraction, y = sum))+
  ggbeeswarm::geom_quasirandom(size = 0.1, color = "grey60")+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 120000))+
  scale_y_log10()+
  facet_grid(cols = vars(qcdf_gg$Species))

ggplot(qcdf_gg, aes(x = Fraction, y = detected))+
  ggbeeswarm::geom_quasirandom(size = 0.1, color = "grey60")+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 10000))+
  scale_y_log10()+
  facet_grid(cols = vars(qcdf_gg$Species))

# by Age and Fraction
ggplot(qcdf_gg, aes(x = Age, y = sum))+
  ggbeeswarm::geom_quasirandom(size = 0.1, color = "grey60")+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 120000))+
  scale_y_log10()+
  facet_grid(cols = vars(qcdf_gg$Fraction))

ggplot(qcdf_gg, aes(x = Age, y = detected))+
  ggbeeswarm::geom_quasirandom(size = 0.1, color = "grey60")+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 10000))+
  scale_y_log10()+
  facet_grid(cols = vars(qcdf_gg$Fraction))

# by Batch experimental day
ggplot(qcdf_gg, aes(x = Batch_exp_day, y = sum))+
  ggbeeswarm::geom_quasirandom(size = 0.1, color = "grey60")+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 120000))+
  scale_y_log10()

ggplot(qcdf_gg, aes(x = Batch_exp_day, y = detected))+
  ggbeeswarm::geom_quasirandom(size = 0.1, color = "grey60")+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 10000))+
  scale_y_log10()

# by Batch sequencing
ggplot(qcdf_gg, aes(x = Batch_sequencing, y = sum))+
  ggbeeswarm::geom_quasirandom(size = 0.1, color = "grey60")+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 120000))+
  scale_y_log10()

ggplot(qcdf_gg, aes(x = Batch_sequencing, y = detected))+
  ggbeeswarm::geom_quasirandom(size = 0.1, color = "grey60")+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 10000))+
  scale_y_log10()

# by Cell type
ggplot(qcdf_gg, aes(x = baccin_celltype_scmapclust, y = sum))+
  ggbeeswarm::geom_quasirandom(size = 0.1, color = "grey60")+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 120000))+
  scale_y_log10()

ggplot(qcdf_gg, aes(x = dahlin_celltype_scmapclust, y = detected))+
  ggbeeswarm::geom_quasirandom(size = 0.1, color = "grey60")+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 10000))+
  scale_y_log10()

ggplot(qcdf_gg, aes(x = dolgalev_celltype_scmapclust, y = detected))+
  ggbeeswarm::geom_quasirandom(size = 0.1, color = "grey60")+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 10000))+
  scale_y_log10()
```

### After

```{r qc_after, fig.width = 14}

qcdf_list_06 <- lapply(sce_list_06, function(sce){
  
  qcdf <- scuttle::perCellQCMetrics(sce, assay.type = "logcounts")
  qcdf$Object_ID <- sce$Object_ID
  qcdf$Species_ID <- sce$Species_ID
  qcdf$Age <- sce$Age
  qcdf$Batch_exp_day <- sce$Batch_exp_day
  qcdf$Batch_sequencing <- sce$Batch_sequencing
  qcdf$Date_collected <- sce$Date_collected
  qcdf$Species <- sce$Species
  qcdf$Fraction <- sce$Fraction
  qcdf$baccin_celltype_scmapclust <- sce$baccin_celltype_scmapclust
  qcdf$dahlin_celltype_scmapclust <- sce$dahlin_celltype_scmapclust
  qcdf$dolgalev_celltype_scmapclust <- sce$dolgalev_celltype_scmapclust

  return(qcdf)
})

qcdf_gg <- DataFrame()

for(i in qcdf_list_06){
  qcdf_gg <- rbind(qcdf_gg, i)
}
qcdf_gg <- data.frame(qcdf_gg)

# by Sample
ggplot(qcdf_gg, aes(x = Object_ID, y = sum))+
  ggbeeswarm::geom_quasirandom(size = 0.1, color = "grey60")+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 120000))+
  scale_y_log10()

ggplot(qcdf_gg, aes(x = Object_ID, y = detected))+
  ggbeeswarm::geom_quasirandom(size = 0.1, color = "grey60")+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 10000))+
  scale_y_log10()

# by Age and Species
ggplot(qcdf_gg, aes(x = Age, y = sum))+
  ggbeeswarm::geom_quasirandom(size = 0.1, color = "grey60")+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 120000))+
  scale_y_log10()+
  facet_grid(cols = vars(qcdf_gg$Species))

ggplot(qcdf_gg, aes(x = Age, y = detected))+
  ggbeeswarm::geom_quasirandom(size = 0.1, color = "grey60")+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 10000))+
  scale_y_log10()+
  facet_grid(cols = vars(qcdf_gg$Species))

# by Fraction and Species
ggplot(qcdf_gg, aes(x = Fraction, y = sum))+
  ggbeeswarm::geom_quasirandom(size = 0.1, color = "grey60")+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 120000))+
  scale_y_log10()+
  facet_grid(cols = vars(qcdf_gg$Species))

ggplot(qcdf_gg, aes(x = Fraction, y = detected))+
  ggbeeswarm::geom_quasirandom(size = 0.1, color = "grey60")+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 10000))+
  scale_y_log10()+
  facet_grid(cols = vars(qcdf_gg$Species))

# by Age and Fraction
ggplot(qcdf_gg, aes(x = Age, y = sum))+
  ggbeeswarm::geom_quasirandom(size = 0.1, color = "grey60")+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 120000))+
  scale_y_log10()+
  facet_grid(cols = vars(qcdf_gg$Fraction))

ggplot(qcdf_gg, aes(x = Age, y = detected))+
  ggbeeswarm::geom_quasirandom(size = 0.1, color = "grey60")+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 10000))+
  scale_y_log10()+
  facet_grid(cols = vars(qcdf_gg$Fraction))

# by Batch experimental day
ggplot(qcdf_gg, aes(x = Batch_exp_day, y = sum))+
  ggbeeswarm::geom_quasirandom(size = 0.1, color = "grey60")+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 120000))+
  scale_y_log10()

ggplot(qcdf_gg, aes(x = Batch_exp_day, y = detected))+
  ggbeeswarm::geom_quasirandom(size = 0.1, color = "grey60")+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 10000))+
  scale_y_log10()

# by Batch sequencing
ggplot(qcdf_gg, aes(x = Batch_sequencing, y = sum))+
  ggbeeswarm::geom_quasirandom(size = 0.1, color = "grey60")+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 120000))+
  scale_y_log10()

ggplot(qcdf_gg, aes(x = Batch_sequencing, y = detected))+
  ggbeeswarm::geom_quasirandom(size = 0.1, color = "grey60")+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 10000))+
  scale_y_log10()

# by Cell type
ggplot(qcdf_gg, aes(x = baccin_celltype_scmapclust, y = sum))+
  ggbeeswarm::geom_quasirandom(size = 0.1, color = "grey60")+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 120000))+
  scale_y_log10()

ggplot(qcdf_gg, aes(x = dahlin_celltype_scmapclust, y = detected))+
  ggbeeswarm::geom_quasirandom(size = 0.1, color = "grey60")+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 10000))+
  scale_y_log10()

ggplot(qcdf_gg, aes(x = dolgalev_celltype_scmapclust, y = detected))+
  ggbeeswarm::geom_quasirandom(size = 0.1, color = "grey60")+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 10000))+
  scale_y_log10()
```

```{r session_info}
sessionInfo()
```