---
title: "Reference annotation reports on sample level"
author: "Lea Wölbert"
date: '2022-11-25'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Report on annotation with three reference datasets, annotated using
scmapcell and scmapcluster at sample level (Object_ID).

#### Load libraries, source code 

```{r seed, message = FALSE}
set.seed(37)
```

```{r load, message = FALSE}
library(pheatmap, quietly = TRUE) 
```

```{r source, message = FALSE}
source(file = snakemake@params[["plotting"]])
source(file = snakemake@params[["functions"]])
```

```{r load_objects, message = FALSE}
print(snakemake@input[[1]])
sce <- base::readRDS(file = snakemake@input[[1]])

name_curr <- colData(sce)$Object_ID[1] 
```

```{r colors, message = FALSE}

colors_ref_path <- snakemake@params[["colors_ref_path"]]
source(file = snakemake@params[["colors"]])

sce <- factor_reference_cts(sce) # own function

col_cts_baccin_cell <- col_cts_ref[base::match(
  levels(sce$baccin_celltype_scmapcell), 
  names(col_cts_ref))]
col_cts_baccin_clst <- col_cts_ref[base::match(
  levels(sce$baccin_celltype_scmapclust),
  names(col_cts_ref))]
col_cts_dahlin_cell <- col_cts_ref[base::match(
  levels(sce$dahlin_celltype_scmapcell), 
  names(col_cts_ref))]
col_cts_dahlin_clst <- col_cts_ref[base::match(
  levels(sce$dahlin_celltype_scmapclust), 
  names(col_cts_ref))]
col_cts_dolgalev_cell <- col_cts_ref[base::match(
  levels(sce$dolgalev_celltype_scmapcell),
  names(col_cts_ref))]
col_cts_dolgalev_clst <- col_cts_ref[base::match(
  levels(sce$dolgalev_celltype_scmapclust),
  names(col_cts_ref))]
```

## Cell types

### All Identities

#### Baccin

```{r baccin_scmap, fig.width=8}

plot_1 <- umap_base(sce, color_by = "baccin_celltype_scmapcell")+ # own function
  ggplot2::ggtitle(name_curr)+
  ggplot2::scale_color_manual("baccin_celltype_scmapcell", 
                              values = col_cts_baccin_cell)
plot_1l <- umap_legend(sce, color_by = "baccin_celltype_scmapcell")+
  ggplot2::scale_color_manual("baccin_celltype_scmapcell", 
                              values = col_cts_baccin_cell)
legend_1 <- ggpubr::get_legend(plot_1l)

plot_2 <- umap_base(sce, color_by = "baccin_celltype_scmapclust")+ 
  ggplot2::ggtitle(name_curr)+
  ggplot2::scale_color_manual("baccin_celltype_scmapclust", 
                              values = col_cts_baccin_clst)
plot_2l <- umap_legend(sce, color_by = "baccin_celltype_scmapclust")+
  ggplot2::scale_color_manual("baccin_celltype_scmapclust", 
                              values = col_cts_baccin_clst)
legend_2 <- ggpubr::get_legend(plot_2l)

PLOT_1 <- ggpubr::ggarrange(plot_1, legend_1)
PLOT_2 <- ggpubr::ggarrange(plot_2, legend_2)

PLOT_1
PLOT_2
```

```{r baccin_qc, fig.width=8}

plot_3 <- umap_base(sce, color_by = "baccin_celltype_scmapcell_sim")+
  ggplot2::ggtitle(name_curr)+
  ggplot2::scale_colour_gradient(low = "black", high = "gold")
plot_3l <- umap_legend(sce, color_by = "baccin_celltype_scmapcell_sim")+
  ggplot2::scale_colour_gradient(low = "black", high = "gold",
                                 name = "baccin_celltype_scmapcell_sim")
legend_3 <- ggpubr::get_legend(plot_3l)  

plot_4 <- umap_base(sce, color_by = "baccin_celltype_scmapclust_sim")+
  ggplot2::ggtitle(name_curr)+
  ggplot2::scale_colour_gradient(low = "black", high = "gold")
plot_4l <- umap_legend(sce, color_by = "baccin_celltype_scmapclust_sim")+
  ggplot2::scale_colour_gradient(low = "black", high = "gold",
                                 name = "baccin_celltype_scmapclust_sim")
legend_4 <- ggpubr::get_legend(plot_4l)  

PLOT_3 <- ggpubr::ggarrange(plot_3, legend_3)
PLOT_4 <- ggpubr::ggarrange(plot_4, legend_4)

PLOT_3
PLOT_4
```

#### Dahlin

```{r dahlin_scmap, fig.width=8}

plot_1 <- umap_base(sce, color_by = "dahlin_celltype_scmapcell")+ 
  ggplot2::ggtitle(name_curr)+
  ggplot2::scale_color_manual("dahlin_celltype_scmapcell",
                              values = col_cts_dahlin_cell)
plot_1l <- umap_legend(sce, color_by = "dahlin_celltype_scmapcell")+
  ggplot2::scale_color_manual("dahlin_celltype_scmapcell", 
                              values = col_cts_dahlin_cell)
legend_1 <- ggpubr::get_legend(plot_1l)

plot_2 <- umap_base(sce, color_by = "dahlin_celltype_scmapclust")+ 
  ggplot2::ggtitle(name_curr)+
  ggplot2::scale_color_manual("dahlin_celltype_scmapclust", 
                              values = col_cts_dahlin_clst)
plot_2l <- umap_legend(sce, color_by = "dahlin_celltype_scmapclust")+
  ggplot2::scale_color_manual("dahlin_celltype_scmapclust",
                              values = col_cts_dahlin_clst)
legend_2 <- ggpubr::get_legend(plot_2l)

PLOT_1 <- ggpubr::ggarrange(plot_1, legend_1)
PLOT_2 <- ggpubr::ggarrange(plot_2, legend_2)

PLOT_1
PLOT_2
```

```{r dahlin_qc, fig.width=8}

plot_3 <- umap_base(sce, color_by = "dahlin_celltype_scmapcell_sim")+
  ggplot2::ggtitle(name_curr)+
  ggplot2::scale_colour_gradient(low = "black", high = "gold")
plot_3l <- umap_legend(sce, color_by = "dahlin_celltype_scmapcell_sim")+
  ggplot2::scale_colour_gradient(low = "black", high = "gold",
                                 name = "dahlin_celltype_scmapcell_sim")
legend_3 <- ggpubr::get_legend(plot_3l)  

plot_4 <- umap_base(sce, color_by = "dahlin_celltype_scmapclust_sim")+
  ggplot2::ggtitle(name_curr)+
  ggplot2::scale_colour_gradient(low = "black", high = "gold")
plot_4l <- umap_legend(sce, color_by = "dahlin_celltype_scmapclust_sim")+
  ggplot2::scale_colour_gradient(low = "black", high = "gold",
                                 name = "dahlin_celltype_scmapclust_sim")
legend_4 <- ggpubr::get_legend(plot_4l)  

PLOT_3 <- ggpubr::ggarrange(plot_3, legend_3)
PLOT_4 <- ggpubr::ggarrange(plot_4, legend_4)

PLOT_3
PLOT_4
```

#### Dolgalev

```{r dolgalev_scmap, fig.width=8}

plot_1 <- umap_base(sce, color_by = "dolgalev_celltype_scmapcell")+ 
  ggplot2::ggtitle(name_curr)+
  ggplot2::scale_color_manual("dolgalev_celltype_scmapcell",
                              values = col_cts_dolgalev_cell)
plot_1l <- umap_legend(sce, color_by = "dolgalev_celltype_scmapcell")+
  ggplot2::scale_color_manual("dolgalev_celltype_scmapcell",
                              values = col_cts_dolgalev_cell)
legend_1 <- ggpubr::get_legend(plot_1l)

plot_2 <- umap_base(sce, color_by = "dolgalev_celltype_scmapclust")+ 
  ggplot2::ggtitle(name_curr)+
  ggplot2::scale_color_manual("dolgalev_celltype_scmapclust", 
                              values = col_cts_dolgalev_clst)
plot_2l <- umap_legend(sce, color_by = "dolgalev_celltype_scmapclust")+
  ggplot2::scale_color_manual("dolgalev_celltype_scmapclust", 
                              values = col_cts_dolgalev_clst)
legend_2 <- ggpubr::get_legend(plot_2l)

PLOT_1 <- ggpubr::ggarrange(plot_1, legend_1)
PLOT_2 <- ggpubr::ggarrange(plot_2, legend_2)

PLOT_1
PLOT_2
```

```{r dolgalev_qc, fig.width=8}

plot_3 <- umap_base(sce, color_by = "dolgalev_celltype_scmapcell_sim")+
  ggplot2::ggtitle(name_curr)+
  ggplot2::scale_colour_gradient(low = "black", high = "gold")
plot_3l <- umap_legend(sce, color_by = "dolgalev_celltype_scmapcell_sim")+
  ggplot2::scale_colour_gradient(low = "black", high = "gold",
                                 name = "dolgalev_celltype_scmapcell_sim")
legend_3 <- ggpubr::get_legend(plot_3l)  

plot_4 <- umap_base(sce, color_by = "dolgalev_celltype_scmapclust_sim")+
  ggplot2::ggtitle(name_curr)+
  ggplot2::scale_colour_gradient(low = "black", high = "gold")
plot_4l <- umap_legend(sce, color_by = "dolgalev_celltype_scmapclust_sim")+
  ggplot2::scale_colour_gradient(low = "black", high = "gold",
                                 name = "dolgalev_celltype_scmapclust_sim")
legend_4 <- ggpubr::get_legend(plot_4l)  

PLOT_3 <- ggpubr::ggarrange(plot_3, legend_3)
PLOT_4 <- ggpubr::ggarrange(plot_4, legend_4)

PLOT_3
PLOT_4
```

```{r session_info}
utils::sessionInfo()
```