---
title: "cellrank_report_sep"
output: html_document
---

Report based on objects separated by lineages.

```{r libraries, warning = FALSE}
library(Seurat)
library(tidyverse)
```

```{r load, warning = FALSE}
markers <- base::readRDS(snakemake@input[["markers"]])

# load and convert all three trajectories
ery_pseudo <- base::readRDS(snakemake@input[["ery_pseudo"]])
ery_pseudo <- CreateSeuratObject(counts = ery_pseudo@assays@data@listData[["logcounts"]],
                                 meta.data = ery_pseudo@colData@listData)

lym_pseudo <- base::readRDS(snakemake@input[["lym_pseudo"]])
lym_pseudo <- CreateSeuratObject(counts = lym_pseudo@assays@data@listData[["logcounts"]],
                                 meta.data = lym_pseudo@colData@listData)

neu_pseudo <- base::readRDS(snakemake@input[["neu_pseudo"]])
neu_pseudo <- CreateSeuratObject(counts = neu_pseudo@assays@data@listData[["logcounts"]],
                                 meta.data = neu_pseudo@colData@listData)
```

Plot

```{r ct_dist, warning = FALSE}
# demonstrates that each species has approximate same distribution of
# cell types across pseudotime (at least within largest, ery, trajectory)
ggplot(ery_pseudo@meta.data,
       aes(
         x = rank(pseudotime),
         fill = celltypes,
         color = celltypes)) +
  facet_wrap(~Species_ID,
             ncol = 1,
             scales = "free_y") +
  geom_density(alpha = 0.4, linewidth = 0.2) +
  theme_classic() +
  labs(y = NULL)
```

```{r plot_data_ery, warning = FALSE}
plot_data <- ery_pseudo@meta.data %>%
  select("pseudotime", "celltypes", "Mouse_ID", 
         "Species_ID", "Age_weeks", "Age_ID")
for(n in 1:length(markers)){
  cell_sp_markers <- markers[[n]][["conserved_signature"]]
  for(g in cell_sp_markers){
    plot_data[,g] <-unlist(FetchData(ery_pseudo, g))
  }
}
plot_data[,7:ncol(plot_data)] <- scale(plot_data[,7:ncol(plot_data)])
```

```{r, warning = FALSE}
for(n in 1:length(markers)){
  cell_sp <- markers[[n]][["conserved_signature"]]
  plot_genes <- plot_data[,c(colnames(plot_data)[1:6],cell_sp)]
  plot_genes <- gather(plot_genes, gene, expression, 
                       -pseudotime, -celltypes, -Mouse_ID, 
                       -Species_ID, -Age_weeks, -Age_ID)
  print(
    ggplot(plot_genes,
    aes(x = rank(pseudotime),
        y = expression,
        color = gene)) +
    geom_smooth(se = F) +
    guides(color = "none") +
    labs(x = "Pseudotime Ery", y = "Scaled Expression",
         title = names(markers)[n]) +
    theme_classic() +
    theme(axis.text = element_blank())
  )
}
```

```{r, warning = FALSE}
plot_data <- neu_pseudo@meta.data %>%
  select("pseudotime", "celltypes", "Mouse_ID", 
         "Species_ID", "Age_weeks", "Age_ID")
for(n in 1:length(markers)){
  cell_sp_markers <- markers[[n]][["conserved_signature"]]
  for(g in cell_sp_markers){
    plot_data[,g] <-unlist(FetchData(neu_pseudo, g))
  }
}
plot_data[,7:ncol(plot_data)] <- scale(plot_data[,7:ncol(plot_data)])
```

```{r, warning = FALSE}
for(n in 1:length(markers)){
  cell_sp <- markers[[n]][["conserved_signature"]]
  plot_genes <- plot_data[,c(colnames(plot_data)[1:6],cell_sp)]
  plot_genes <- gather(plot_genes, gene, expression, 
                       -pseudotime, -celltypes, -Mouse_ID, 
                       -Species_ID, -Age_weeks, -Age_ID)
  print(
    ggplot(plot_genes,
           aes(x = rank(pseudotime),
               y = expression,
               color = gene)) +
      geom_smooth(se = F) +
      guides(color = "none") +
      labs(x = "Pseudotime Neu", y = "Scaled Expression",
           title = names(markers)[n]) +
      theme_classic() +
      theme(axis.text = element_blank())
  )
}
```

```{r, warning = FALSE}
for(g in sort(unique(unlist(lapply(markers, 
                                    function(x){x["conserved_signature"]}))))) {
  plot_data <- ery_pseudo@meta.data %>%
    select("pseudotime", "celltypes", "Mouse_ID", 
           "Species_ID", "Age_weeks", "Age_ID")
  plot_data$gene <-unlist(FetchData(ery_pseudo, g))
  
  print(
    ggplot(plot_data,
           aes(x = rank(pseudotime),
               y = gene,
               color = Species_ID)) +
      geom_smooth() +
      theme_classic() +
      labs(x = "Pseudotime Ery", y = g)  +
      theme(axis.text = element_blank())
  )
}
```

```{r, warning = FALSE}
for(g in sort(unique(unlist(lapply(markers, 
                                   function(x){x["conserved_signature"]}))))) {
  plot_data <- lym_pseudo@meta.data %>%
    select("pseudotime", "celltypes", "Mouse_ID", 
           "Species_ID", "Age_weeks", "Age_ID")
  plot_data$gene <-unlist(FetchData(lym_pseudo, g))
  
  print(
    ggplot(plot_data,
           aes(x = rank(pseudotime),
               y = gene,
               color = Species_ID)) +
      geom_smooth() +
      theme_classic() +
      labs(x = "Pseudotime Lym", y = g)  +
      theme(axis.text = element_blank())
  )
}
```

```{r, warning = FALSE}
for(g in sort(unique(unlist(lapply(markers, 
                                   function(x){x["conserved_signature"]}))))) {
  plot_data <- neu_pseudo@meta.data %>%
    select("pseudotime", "celltypes", "Mouse_ID", 
           "Species_ID", "Age_weeks", "Age_ID")
  plot_data$gene <-unlist(FetchData(neu_pseudo, g))
  
  print(
    ggplot(plot_data,
           aes(x = rank(pseudotime),
               y = gene,
               color = Species_ID)) +
      geom_smooth() +
      theme_classic() +
      labs(x = "Pseudotime Neu", y = g)  +
      theme(axis.text = element_blank())
  )
}
```
