---
title: "check mapping general"
author: "Lea Wölbert"
date: '2023-03-31'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Report QC for all samples separately (Object_ID).
Some operations from the scripts must be repeated to generate relevant plots,
but any new objects cannot be saved from an .Rmd script.

#### Load libraries, source code 

```{r load,  message = FALSE}

library(SingleCellExperiment, quietly = TRUE) 
library(DropletUtils, quietly = TRUE) 
library(tidyverse, quietly = TRUE) 
library(scater, quietly = TRUE) 
library(scuttle, quietly = TRUE) 
library(scran, quietly = TRUE) 
library(pheatmap, quietly = TRUE) 
set.seed(37)
```

```{r load_objects, message = FALSE}

sce_og <- readRDS(file = snakemake@input[["sce_03"]])
sce_fg <- readRDS(file = snakemake@input[["sce_fg"]])

# set name for plots
name_curr <- colData(sce_og)$Object_ID[1] # name to display in plots
nr_hvgs <- snakemake@params[["nr_hvgs"]]

#sce_og <- readRDS(file = "/omics/odcf/analysis/OE0538_projects/DO-0008/data/main_analysis/sce_objects/03_outl/mspr/sce_mspr_old_hsc_2_0-03")
#sce_fg <- readRDS(file = "/omics/odcf/analysis/OE0538_projects/DO-0008/data/fourgenomes/sce_objects/01_cellranger_output/mspr/sce_mspr_old_hsc_2_0-01")

color_tables <- snakemake@params[["color_tables"]]

source(file = "../source/colors.R")
source(file = "../source/plotting.R")
```

```{r}
# subset fg to sce_og
sce_fg <- sce_fg[,which(!is.na(match(colnames(sce_fg), colnames(sce_og))))]
```

```{r}
sce_og
sce_fg

#knitr::knit_exit()

```

```{r}

if(grepl("mspr", name_curr)){knitr::knit_exit()}

head(rowData(sce_og))
head(rowData(sce_fg))

shared_genes <- intersect(rowData(sce_og)$Symbol, rowData(sce_fg)$Symbol)
length(shared_genes)

sce_og_shared <- sce_og[rowData(sce_og)$Symbol %in% shared_genes,]
sce_fg_shared <- sce_fg[rowData(sce_fg)$Symbol %in% shared_genes,]

sce_og_shared <- sce_og_shared[order(rowData(sce_og_shared)$Symbol),]
sce_fg_shared <- sce_fg_shared[order(rowData(sce_fg_shared)$Symbol),]

sce_og_shared <- sce_og_shared[!duplicated(rowData(sce_og_shared)$Symbol),]
sce_fg_shared <- sce_fg_shared[!duplicated(rowData(sce_fg_shared)$Symbol),]

```

```{r}

colnames(sce_og_shared) <- paste0(colnames(sce_og_shared), "_og")
sce_og_shared$Genome <- rep("OneGenome", ncol(sce_og_shared))

colnames(sce_fg_shared) <- paste0(colnames(sce_fg_shared), "_fg")
sce_fg_shared$Genome <- rep("FourGenomes", ncol(sce_fg_shared))

colnames(rowData(sce_og_shared))[colnames(rowData(sce_og_shared)) == "ID"] <- "ID_og"
colnames(rowData(sce_fg_shared))[colnames(rowData(sce_fg_shared)) == "ID"] <- "ID_fg"

rownames(sce_og_shared) <- rowData(sce_og_shared)$Symbol 
rownames(sce_fg_shared) <- rowData(sce_fg_shared)$Symbol 

colData(sce_og_shared) <- colData(sce_og_shared)[,-20]

# combine
sce_tog <- cbind(sce_og_shared, sce_fg_shared)
sce_tog

```

## General quality

```{r}

qcdf_og <- perCellQCMetrics(sce_og_shared)
qcdf_fg <- perCellQCMetrics(sce_fg_shared)

```

```{r}

qcdf_gg <- as.data.frame(qcdf_og)
qcdf_gg <- pivot_longer(qcdf_gg, 
                        names_to = "metric", cols = c(1, 2, 3))

ggplot(qcdf_gg[qcdf_gg$metric == "sum",], aes(y = value, x = metric))+
  theme_classic()+
  ggbeeswarm::geom_quasirandom(size = 0.1)+
  geom_boxplot(alpha = 0)+
  scale_color_manual("Removed", values = c("FALSE" = "grey80", 
                                           "TRUE" = "orange"))+
  ylab("Library size")+
  ggtitle("One genome")+
  theme(axis.title.x = element_blank(), axis.text.x = element_blank())

```

```{r}

qcdf_gg <- as.data.frame(qcdf_fg)
qcdf_gg <- pivot_longer(qcdf_gg, 
                        names_to = "metric", cols = c(1, 2, 3))

ggplot(qcdf_gg[qcdf_gg$metric == "sum",], aes(y = value, x = metric))+
  theme_classic()+
  ggbeeswarm::geom_quasirandom(size = 0.1)+
  geom_boxplot(alpha = 0)+
  scale_color_manual("Removed", values = c("FALSE" = "grey80", 
                                           "TRUE" = "orange"))+
  ylab("Library size")+
  ggtitle("Four genomes")+
  theme(axis.title.x = element_blank(), axis.text.x = element_blank())

```




## PCA


```{r}

quick_clust <- quickCluster(sce_tog) # quick clustering to accelerate calculation

# must be COMPUTE not CALCULATE SumFactors to add directly to SCE
sce_tog <- computeSumFactors(sce_tog, cluster = quick_clust)
sce_tog <- logNormCounts(sce_tog) # log-transformation

# extract hvgs for subsequent dimensionality reduction at sample level
genevar <- modelGeneVar(sce_tog)
hvg <- getTopHVGs(genevar, n=nr_hvgs)

# reduce dimensions
set.seed(37)
sce_tog_temp <- runPCA(sce_tog, subset_row = hvg) 

set.seed(37)
sce_tog_temp <- runUMAP(sce_tog_temp, dimred = 'PCA', external_neighbors=TRUE, 
                   subset_row = hvg)

plot_1 <- umap_base(sce_tog_temp, color_by = "Genome")+ # own function
  ggtitle(name_curr)
plot_1

plot_2 <- pca_base2(sce_tog_temp, color_by = "Genome")+ # own function
  ggtitle(name_curr)
plot_2

plot_3 <- pca_base3(sce_tog_temp, color_by = "Genome")+ # own function
  ggtitle(name_curr)
plot_3


```

```{r}
pca_slot <- reducedDim(sce_tog_temp, "PCA")
rotation <- attr(pca_slot,"rotation")
```

### PC 1

```{r}

genes_pc1 <- rownames(rotation)[order(abs(rotation[,1]), decreasing = TRUE)]

top_genes_pc1 <- genes_pc1[which(abs(rotation[rownames(rotation) %in% genes_pc1,1])>=0.025)]
if(length(top_genes_pc1) > 100){top_genes_pc1 <- top_genes_pc1[1:100]}

print(length(top_genes_pc1))

rotation[order(abs(rotation[,1]), decreasing = TRUE),][1:50,1:3]

sce_tog_temp <- runPCA(sce_tog, subset_row = hvg[which(! hvg %in% top_genes_pc1)]) 
plot_2 <- pca_base2(sce_tog_temp, color_by = "Genome")+ # own function
  ggtitle(name_curr)
plot_2

sce_tog_temp <- runUMAP(sce_tog_temp, dimred = 'PCA', external_neighbors=TRUE, 
                   subset_row = hvg[which(! hvg %in% top_genes_pc1)])

plot_1 <- umap_base(sce_tog_temp, color_by = "Genome")+ # own function
  ggtitle(name_curr)
plot_1

```

### PC 2

```{r}

genes_pc2 <- rownames(rotation)[order(abs(rotation[,2]), decreasing = TRUE)]

top_genes_pc2 <- genes_pc2[which(abs(rotation[rownames(rotation) %in% genes_pc2,2])>=0.025)]
if(length(top_genes_pc2) > 100){top_genes_pc2 <- top_genes_pc2[1:100]}

print(length(top_genes_pc2))

rotation[order(abs(rotation[,2]), decreasing = TRUE),][1:50,1:3]

sce_tog_temp <- runPCA(sce_tog, subset_row = hvg[which(! hvg %in% top_genes_pc2)]) 
plot_2 <- pca_base2(sce_tog_temp, color_by = "Genome")+ # own function
  ggtitle(name_curr)
plot_2

sce_tog_temp <- runUMAP(sce_tog_temp, dimred = 'PCA', external_neighbors=TRUE, 
                   subset_row = hvg[which(! hvg %in% top_genes_pc2)])

plot_1 <- umap_base(sce_tog_temp, color_by = "Genome")+ # own function
  ggtitle(name_curr)
plot_1

```

### PC 3

```{r}

genes_pc3 <- rownames(rotation)[order(abs(rotation[,3]), decreasing = TRUE)]

top_genes_pc3 <- genes_pc3[which(abs(rotation[rownames(rotation) %in% genes_pc3,3])>=0.025)]
if(length(top_genes_pc3) > 100){top_genes_pc3 <- top_genes_pc3[1:100]}

rotation[order(abs(rotation[,3]), decreasing = TRUE),][1:50,1:3]

print(length(top_genes_pc3))

sce_tog_temp <- runPCA(sce_tog, subset_row = hvg[which(! hvg %in% top_genes_pc3)]) 
plot_2 <- pca_base3(sce_tog_temp, color_by = "Genome")+ # own function
  ggtitle(name_curr)
plot_2

sce_tog_temp <- runUMAP(sce_tog_temp, dimred = 'PCA', external_neighbors=TRUE, 
                   subset_row = hvg[which(! hvg %in% top_genes_pc3)])

plot_1 <- umap_base(sce_tog_temp, color_by = "Genome")+ # own function
  ggtitle(name_curr)
plot_1

```

## Heatmap 

```{r}

sce_tog_temp <- sce_tog[-which(rowSums(assays(sce_tog)$counts) == 0),]

mat <- as.matrix(
  assays(sce_tog_temp)$logcounts
)

anno_col <- data.frame(
  features = colnames(sce_tog_temp),
  Genome = colData(sce_tog_temp)$Genome)

anno_col <- column_to_rownames(anno_col, var = "features")

pheatmap(
  mat,
  cluster_cols = FALSE,
  cluster_rows = FALSE,
  annotation_col = anno_col,
  show_rownames = FALSE,
  show_colnames = FALSE
)

```

```{r}

sce_tog_temp <- sce_tog[which(rownames(sce_tog) %in% hvg),]

mat <- as.matrix(
  assays(sce_tog_temp)$logcounts
)

anno_col <- data.frame(
  features = colnames(sce_tog_temp),
  Genome = colData(sce_tog_temp)$Genome)

anno_col <- column_to_rownames(anno_col, var = "features")

pheatmap(
  mat,
  cluster_cols = FALSE,
  cluster_rows = FALSE,
  annotation_col = anno_col,
  show_rownames = FALSE,
  show_colnames = FALSE
)

```

```{r, fig.height=12, fig.width=7}

sce_tog_temp <- sce_tog[which(rownames(sce_tog) %in% top_genes_pc1),]

mat <- as.matrix(
  assays(sce_tog_temp)$logcounts
)

anno_col <- data.frame(
  features = colnames(sce_tog_temp),
  Genome = colData(sce_tog_temp)$Genome)

anno_col <- column_to_rownames(anno_col, var = "features")

pheatmap(
  mat,
  cluster_cols = FALSE,
  annotation_col = anno_col,
  show_colnames = FALSE
)

```

```{r, fig.height=12, fig.width=7}

sce_tog_temp <- sce_tog[which(rownames(sce_tog) %in% top_genes_pc2),]

mat <- as.matrix(
  assays(sce_tog_temp)$logcounts
)

anno_col <- data.frame(
  features = colnames(sce_tog_temp),
  Genome = colData(sce_tog_temp)$Genome)

anno_col <- column_to_rownames(anno_col, var = "features")

pheatmap(
  mat,
  cluster_cols = FALSE,
  annotation_col = anno_col,
  show_colnames = FALSE
)

```

```{r, fig.height=12, fig.width=7}

sce_tog_temp <- sce_tog[which(rownames(sce_tog) %in% top_genes_pc3),]

mat <- as.matrix(
  assays(sce_tog_temp)$logcounts
)

anno_col <- data.frame(
  features = colnames(sce_tog_temp),
  Genome = colData(sce_tog_temp)$Genome)

anno_col <- column_to_rownames(anno_col, var = "features")

pheatmap(
  mat,
  cluster_cols = FALSE,
  annotation_col = anno_col,
  show_colnames = FALSE
)

```