
base: "/omics/odcf/analysis/OE0538_projects/DO-0008"
#data_paths:
  #main: "/data/main_analysis"
  #cellranger_output: "/data/main_analysis/sce_objects/00_cellranger_output" 
  #fourgenomes_output: "/data/fourgenomes/sce_objects/00_cellranger_output" 
scRNAseq_data_paths:
  main: "/data/scRNAseq/main_analysis"
  #main: "/data/test_new_caroli/main_analysis"
  cellranger_output: "/data/scRNAseq/main_analysis/sce_objects/00_cellranger_output" 
  #cellranger_output: "/data/test_new_caroli/main_analysis/sce_objects/00_cellranger_output" 
  fourgenomes_output: "/data/scRNAseq/fourgenomes/sce_objects/00_cellranger_output" 
metadata_paths: 
  table: "/data/metadata/scRNAseq/00_alignment/OE0538_DO-0008_metadata_combined.csv"
  colors: "/data/metadata/colors/colors.txt"
  colors_ref: "/data/metadata/colors/colors_references.txt"
  ensembl_mspr: "/data/metadata/scRNAseq/01_sce_prep/ensembl_mspr/ensembl_list_mspr"
  ref_baccin_sce: "/data/metadata/scRNAseq/01_sce_prep/references_processed/ref_baccin_sce"
  ref_dahlin_sce: "/data/metadata/scRNAseq/01_sce_prep/references_processed/ref_dahlin_sce"
  ref_dolgalev_sce: "/data/metadata/scRNAseq/01_sce_prep/references_processed/ref_dolgalev_sce"
  gene_list_clusters: "/data/metadata/scRNAseq/02_sce_anno/gene_list_clusters.txt"
  gene_list_subclustering: "/data/metadata/scRNAseq/02_sce_anno/gene_list_subclustering.txt"
  gene_list_dotplot: "/data/metadata/scRNAseq/02_sce_anno/gene_list_dotplot.txt"
  annotation_clusters: "/data/metadata/scRNAseq/02_sce_anno/annotation_clusters.txt"
  annotation_subclusters: "/data/metadata/scRNAseq/02_sce_anno/annotation_subclusters.txt"
  annotation_final: "/data/metadata/scRNAseq/02_sce_anno/annotation_final.txt"
  ensembl_hum: "/data/metadata/scRNAseq/03_sce_analysis/reclustering_bm/ensembl_hum"
  ensembl_mus: "/data/metadata/scRNAseq/03_sce_analysis/reclustering_bm/ensembl_mus"
  human_test_datasets: "/data/metadata/scRNAseq/03_sce_analysis/reclustering_bm/pre-processed"
  test_ts_all_stromal: "/data/metadata/scRNAseq/03_sce_analysis/reclustering_bm/pre-processed/ts_all_stromal"
  test_ts_bone_marrow: "/data/metadata/scRNAseq/03_sce_analysis/reclustering_bm/pre-processed/ts_bone_marrow"
  test_ts_hsc_progenitors: "/data/metadata/scRNAseq/03_sce_analysis/reclustering_bm/pre-processed/ts_hscs_progenitors"
  test_li_all_stromal: "/data/metadata/scRNAseq/03_sce_analysis/reclustering_bm/pre-processed/li_all_stromal"
  cell_cycle_genes: "/data/metadata/scRNAseq/03_sce_analysis/cell_cycle_genes/go_term_cellcycleprocess_mouse.csv"
  assignment: "/data/metadata/scRNAseq/05_cci_prep/assignment.txt"
  assignment_reverse: "/data/metadata/scRNAseq/05_cci_prep/assignment_reverse.txt"
  assignment_no_ct_removal: "/data/metadata/scRNAseq/06_cci_alt/assignment_no_ct_removal.txt"
  lrdb_inp: "/data/metadata/scRNAseq/05_cci_prep/lrdb_raw/mouse_lr_pair.rds"
  lrdb_out: "/data/metadata/scRNAseq/05_cci_prep/lrdb_processed/lrdb"

samples_to_remove:
  - mcar_old_str_3_1
  - mcar_old_str_3_2
  - mcas_old_hsc_2_0
  - mcas_old_hsc_4_0
  - mcas_yng_hsc_4_0
  - mcas_old_str_4_0
  - mcas_yng_str_6_0
  - mmus_old_str_1_0
  - mspr_old_hsc_1_0
  - mspr_yng_str_3_1
  
values:
  nr_hvgs: 2000 # nr of top hvgs to use, universal
  01_sce_prep:
    cutoff_umis: 100 # below which droplets are discarded
    cutoff_doublets: 7.5 # above which likely doublets are discarded
    cutoff_mitos: 5 # percentage of mito genes above which cells are discarded
    cutoff_sum: 700 # below which cells are discarded
    cutoff_detected: 500 # below which cells are discarded
    logFC_sample_dmgs: 0.25 # logFC threshold for excluding DMGs per sample
    minPC_sample_dmgs: 0.05 # min percent of cells expressing DMGs per sample
  02_sce_anno:  
    nr_hvgs_batch_correction: 10000 # nr of top hvgs to be used for subsetting  
    batch_use: "Object_ID" # if changed run ENTIRE batch_correction_snakefile
    seeds_umap:
      str: 6 # for nicer plots after batch correction
      hsc: 2 # for nicer plots after batch correction
    seeds_umap_after:
      str: 2 # for nicer plots after subclustering
      hsc: 10 # for nicer plots after subclustering # 10 was ok
    k_louvain: 77 # for louvain clustering resolution
    k_louvain_refs: 50 # for louvain clustering resolution
    ndge_padj_cutoff: 0.05 # below which nDGEs are significant
    ndge_fc_cutoff: 1.5 # above which genes are excluded from nDGEs
  03_sce_dge:
    flayer_integrated_padj_cutoff: 0.05
    flayer_integrated_fc_cutoff: 1.5
  05_cci_prep:
    min_cells: 60 # min number of cells required per cell type to consider for cci
    min_perc: 0.05 # min percentage of cells per cell type a gene must be expressed in to consider for cci
    top_level: 300 # top level of ligand-receptor pairs to ensure even leveling of ranks and scores
    colname_identity: celltypes
    iterations: 250
    min_sp_age_perc: 0.1 # % of iterations that must be successful for stats calc
    nr_cores_age: 20
    nr_cores_cts: 25
    min_sp_cts: 3

# Conditions  
# in caps for use in R, only first letter capitalized for use in Snakefile
run_preprocessing_summary: False
