# TO ADJUST THIS FILE TO YOUR LOCAL CONFIGURATION, CHANGE:
# - table
# - cellranger_output
# - fourgenomes_output
# - base
# TO APPROPRIATE PATHS

#-------------------------------------------------------------------------------

### INPUT ### 

# all base files generated previously/elsewhere
# store where required; add full paths here

# scRNAseq
table: "/omics/odcf/analysis/OE0538_projects/DO-0008/data/metadata/scRNAseq/00_alignment/metadata.csv"
cellranger_output: "/omics/odcf/analysis/OE0538_projects/DO-0008/data/scRNAseq/main_analysis/sce_objects/00_cellranger_output" 
fourgenomes_output: "/omics/odcf/analysis/OE0538_projects/DO-0008/data/scRNAseq/fourgenomes/sce_objects/00_cellranger_output" 

# bulk RNAseq
#TODO: CHANGE FROM TEST
table_bulk: "/omics/odcf/analysis/OE0538_projects/DO-0008/data/bulk_rnaseq/raw_msc_test/metadata_test.csv"
fastq_input: "/omics/odcf/analysis/OE0538_projects/DO-0008/data/bulk_rnaseq/raw_msc_test"

#mm10genome:  "/omics/odcf/analysis/OE0538_projects/DO-0008/data_freeze/02_species_genomes/fourgenomes/mmus"

#-------------------------------------------------------------------------------


### OUTPUT ###

# the general directory that should contain all output data 
# all downstream output paths build on "base"
base: "/omics/odcf/analysis/OE0538_projects/DO-0008"

scRNAseq_data_paths:
  main: "/data/scRNAseq/main_analysis"

bulk_rnaseq_data_paths: 
  "/data/bulk_rnaseq"

# METADATA # 

metadata_paths: 

  metadata: "/data/metadata"

  colors: "/data/metadata/colors/colors.txt"
  colors_ref: "/data/metadata/colors/colors_references.txt"
  
  # previously downloaded for annotation of SPRET_EiJ_v1-aligned datasets
  ensembl_mspr: "/data/metadata/scRNAseq/01_sce_prep/ensembl_mspr/ensembl_list_mspr"

  # references for 01_02 reference annotation, previously downloaded and generated in metadata
  ref_baccin_sce: "/data/metadata/scRNAseq/01_sce_prep/references_processed/ref_baccin_sce"
  ref_dahlin_sce: "/data/metadata/scRNAseq/01_sce_prep/references_processed/ref_dahlin_sce"
  ref_dolgalev_sce: "/data/metadata/scRNAseq/01_sce_prep/references_processed/ref_dolgalev_sce"

  # gene lists for subclustering and visualisation
  gene_list_clusters: "/data/metadata/scRNAseq/02_sce_anno/gene_list_clusters.txt"
  gene_list_subclustering: "/data/metadata/scRNAseq/02_sce_anno/gene_list_subclustering.txt"
  gene_list_dotplot: "/data/metadata/scRNAseq/02_sce_anno/gene_list_dotplot.txt"

  # annotation lists specifying labels for clusters
  annotation_clusters: "/data/metadata/scRNAseq/02_sce_anno/annotation_clusters.txt"
  annotation_subclusters: "/data/metadata/scRNAseq/02_sce_anno/annotation_subclusters.txt"
  annotation_final: "/data/metadata/scRNAseq/02_sce_anno/annotation_final.txt"  

  # hidden sources of variation to remove for DESeq2 analyses
  sources_variation: 
    annotation_species: "/data/metadata/scRNAseq/02_sce_anno/sources_variation.txt"
    analysis_species: "/data/metadata/scRNAseq/03_sce_analysis/sources_variation_species.txt"

  # reclustering analysis
  reclustering: "/data/metadata/scRNAseq/03_sce_analysis/reclustering_bm"
  ensembl_mus: "/data/metadata/scRNAseq/03_sce_analysis/ensembl/ensembl_mus"
  ensembl_hum: "/data/metadata/scRNAseq/03_sce_analysis/ensembl/ensembl_hum"
  ensembl_zeb: "/data/metadata/scRNAseq/03_sce_analysis/ensembl/ensembl_zeb"
  ensembl_nmr: "/data/metadata/scRNAseq/03_sce_analysis/ensembl/ensembl_nmr"
  datasets_other_path: "/data/metadata/scRNAseq/03_sce_analysis/reclustering_bm/prepared"
  resolution_other: "/data/metadata/scRNAseq/03_sce_analysis/reclustering_bm/reclustering_other_resolution.txt"
  frame_other: "/data/metadata/scRNAseq/03_sce_analysis/reclustering_bm/reclustering_other_frame.txt"
  
  # reclustering primate brain dataset
  dataset_brain_path: "/data/metadata/scRNAseq/08_sce_brain/sample.combined_exc_4_species_integration.RDS"

# some samples to remove in addition to what is removed by Keep_sample = FALSE
# in the metadata sheet .csv file
samples_to_remove: 
  - mcar_old_str_3_1
  - mcar_old_str_3_2
  - mcas_old_hsc_2_0
  - mcas_old_hsc_4_0
  - mcas_yng_hsc_4_0
  - mcas_old_str_4_0
  - mcas_yng_str_6_0
  - mmus_old_str_1_0
  - mspr_old_hsc_1_0
  - mspr_yng_str_3_1
  - mcar_yng_str_2_3
  
values:
  nr_hvgs: 2000 # nr of top hvgs to use, universal
  01_sce_prep:
    cutoff_umis: 100 # below which droplets are discarded
    cutoff_doublets: 7.5 # above which likely doublets are discarded
    cutoff_mitos: 5 # percentage of mito genes above which cells are discarded
    cutoff_sum: 700 # below which cells are discarded
    cutoff_detected: 500 # below which cells are discarded
    logFC_sample_dmgs: 0.25 # logFC threshold for excluding DMGs per sample
  02_sce_anno:  
    nr_hvgs_batch_correction: 10000 # nr of top hvgs to be used for batch correction  
    batch_use: "Object_ID" # which variable to use as "batch"
    seeds_umap:
      str: 6 # for nicer plots after batch correction
      hsc: 11 
    seeds_umap_after:
      str: 2 # for nicer plots after subclustering
      hsc: 10 
    k_graph_list:
      hsc: 20 # for louvain clustering SCE
      str: 10 
    resolution_louvain_list:   
      hsc: 0.65 # for louvain clustering SCE
      str: 0.35 
    ndge_padj_cutoff: 0.05 # below which nDGEs are defined as significant
    ndge_fc_cutoff: 1.5 # above which genes are excluded from nDGEs
  03_sce_analysis:
    cell_types_exclude: # due to low numbers
      - "Lymphatic EC"
      - "Chondrocyte"
    reclustering_cutoff_prop: 0.015 # minimum proportion of cells that express a given gene to keep it for permutation
    nr_cores: 20 # nr of cores for parallelization for reclustering and permutation
    iterations: 500 # nr of iterations for permutation

# Conditions  
# are set to true in the relevant snakemake comments per snakefile 
run_preprocessing_summary: False
run_anno_reports: False
run_marker_reports: False

ran_li_ipynb: False

run_sign_rand_own_permutation: False
run_mark_rand_own_permutation: False
run_mmms_rand_own_permutation: False
run_genesets_sign_own_permutation: False

run_sign_rand_other_permutation: False
run_mark_rand_other_permutation: False
run_mmms_rand_other_permutation: False
run_genesets_sign_rand_other_permutation: False

run_pval_correction: False

run_age_comparison: False 

run_custom_reports: False

# snakemake rule configuation
# for bulk RNAseq analysis

# for umi_tools_extract:
umi_tools_extract:
  extra: >-
    --bc-pattern2=NNNNNNNNXXXXXX

# "Trim 8 nt UMIs + 3 nt UMI linker + 3 nt from the SMART UMI Adapter 
# from Read2 prior to mapping" according to protocol
# NNNNNNNN will be added to the sequence name
# XXXXXX will be kept in the read, then I will trim it downstream using cutadapt

# for cutadapt:
cutadapt:
  extra: >-
    -U 6 
    -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA 
    -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT 
    --nextseq-trim 20
    --minimum-length 10

### UMI linker: -U 6
# from the SMART-Seq® Total RNA Library Prep with ZapR Depletion (withUMIs) User Manual
# remove 6 bases from the beginning of Read 2, which are the linker and remaining Smart adapter 

### read length is longer than insert size: trimming the 3' end of reads containing the rest of the adapter sequence
### -a and -A
# https://knowledge.illumina.com/library-preparation/general/library-preparation-general-reference_material-list/000001314
# Truseq adapters: https://dnatech.ucdavis.edu/sites/g/files/dgvnsk15531/files/inline-files/illumina-adapter-sequences_1000000002694-00.pdf
# mentioned also in cutadapt: https://cutadapt.readthedocs.io/en/stable/guide.html#truseq
# cutadapt will also remove the sequence following the adapters

### low quality ends: -q N
# trims low quality below quality N
# because the quality according to fastQC remains high, no quality trimming for now

### low quality ends including the detection of "high-quality Gs" from what was actually dark circles on the machine
### --nextseq-trim N

### poly-A
# no strong indication in fastQC of a lot of TTT or AAA so far, so also no poly-A trimming for now
