paths:
  output_dir: "/omics/odcf/analysis/OE0538_projects/DO-0008/data/sce_objects"
  cellranger_output: "/01_cellranger_output" 
  preprocessing: "/02_preprocessing"
  integration: "/03_integration"
metadata:
  raw: "/omics/odcf/analysis/OE0538_projects/DO-0008/metadata/OE0538_DO-0008_metadata_combined.csv"
  identifiers: 
  # should be the same as in https://github.com/odomlab2/snakemake-cellranger
    - Species_ID
    - Age_ID
    - Fraction_ID
    - Sample_NR
  values:
    cutoff_umis: 100 # below which droplets are discarded
    cutoff_doublets: 7.5 # above which likely doublets are discarded
    cutoff_mitos: 5 # percentage of mito genes above which cells are discarded
    cutoff_sum: 400 # below which cells are discarded
    cutoff_detected: 300 # below which cells are discarded
    nr_hvgs: 2000 # nr of top hvgs 
    nr_hvgs_batch_correction: 5000
  reference_lipka: "/omics/odcf/analysis/OE0538_projects/DO-0008/metadata/PBMC_SCE_short"
  reference_baccin: "/omics/odcf/analysis/OE0538_projects/DO-0008/metadata/Baccin_seurat"
batch_correction:  
  batches: 
  # only add batched for which objects were already created
    - Batch_exp_day
    #- Object_ID
    #- Batch_sequencing
  batch_use: "Batch_exp_day" # if changed, run ENTIRE integration_snakefile
  mnns:
    - ClassicMnnParam()
    - FastMnnParam()
  mnn_use: "FastMnnParam()"
# For conditions use caps if used in R  
run_preprocessing_summary: False
run_integration_summary: False
run_mnncorrect: True
mnn_use_fast: TRUE
run_seurat3: False
run_scmerge: False
hvgs_for_batch_correction: FALSE 
rescale_for_batch_correction: FALSE # Rescaling assumes that the cell composition in all batches is the same 

