paths:
  cellranger_output: "/omics/groups/OE0538/internal/users/l012t/snakemake-cellranger/data/sce_objects/" 
  preprocessing: "/omics/groups/OE0538/internal/users/l012t/Interspecies_BM_phd/data/01_preprocessing"
  integration: "/omics/groups/OE0538/internal/users/l012t/Interspecies_BM_phd/data/02_integration"
metadata:
  raw: "/omics/groups/OE0538/internal/users/l012t/Interspecies_BM_phd/data/metadata_full.csv"
  identifiers: 
    - Species_ID
    - Age_ID
    - Fraction_ID
    - Sample_NR
  values:
    cutoff_umis: 100 # below which droplets are discarded
    cutoff_doublets: 1000 # above which likely doublets are discarded
    cutoff_sum: 400 # below which cells are discarded
    cutoff_detected: 300 # below which cells are discarded
    nr_hvgs: 2000 # nr of top hvgs 
run_preprocessing_summary: False
  

