default: 
# default configs for direct loading into R scripts
  color_tables: "/omics/odcf/analysis/OE0538_projects/DO-0008/metadata/color_tables"
paths:
  output_dir: "/omics/odcf/analysis/OE0538_projects/DO-0008/data"
  cellranger_output: "/sce_objects/01_cellranger_output" 
  preprocessing: "/02_preprocessing"
  integration: "/03_integration"
metadata: 
  raw: "/omics/odcf/analysis/OE0538_projects/DO-0008/metadata/OE0538_DO-0008_metadata_combined.csv"
  color_tables: "/omics/odcf/analysis/OE0538_projects/DO-0008/metadata/color_tables"
  identifiers: 
  # should be the same as in https://github.com/odomlab2/snakemake-cellranger
    - Species_ID
    - Age_ID
    - Fraction_ID
    - Sample_NR
  ref_baccin_sce: "/omics/odcf/analysis/OE0538_projects/DO-0008/metadata/ref_baccin_sce"
  ref_dahlin_sce: "/omics/odcf/analysis/OE0538_projects/DO-0008/metadata/ref_dahlin_sce"
  ref_dolgalev_sce: "/omics/odcf/analysis/OE0538_projects/DO-0008/metadata/ref_dolgalev_sce"
  colors:
    colors_celltypes: "/omics/odcf/analysis/OE0538_projects/DO-0008/metadata/color_tables/colors_celltypes.csv"
    colors_species: "/omics/odcf/analysis/OE0538_projects/DO-0008/metadata/color_tables/colors_species.csv"
    colors_annotations: "/omics/odcf/analysis/OE0538_projects/DO-0008/metadata/color_tables/colors_annotations.csv"
samples_to_remove:
  - mcar_old_str_3_1
  - mcar_old_str_3_2
  - mcas_old_hsc_2_0
  - mcas_old_hsc_4_0
  - mcas_yng_hsc_4_0
  - mcas_old_str_4_0
  - mcas_yng_str_6_0
  - mmus_old_str_1_0
  - mspr_old_hsc_1_0
  - mspr_yng_str_3_1
values:
  preprocessing:
    cutoff_umis: 100 # below which droplets are discarded
    cutoff_doublets: 7.5 # above which likely doublets are discarded
    cutoff_mitos: 5 # percentage of mito genes above which cells are discarded
    cutoff_sum: 400 # below which cells are discarded
    cutoff_detected: 300 # below which cells are discarded
    nr_hvgs: 2000 # nr of top hvgs 
  batch_correction:  
    nr_hvgs_batch_correction: 10000 # nr of top hvgs to be used for bc subsetting  
    batch_use_species: "Batch_exp_day" # if changed run ENTIRE batch_correction_snakefile
    batch_use_fractions: "Object_ID" # if changed run ENTIRE batch_correction_snakefile
    seurat_reduction: "cca" # can be either "rpca" or "cca"
    samples_as_references_seurat:
    # keep for reference even if not used, maybe for later
      - mcar_old_hsc_2_0
      - mcar_yng_str_2_1
      - mcas_yng_hsc_3_0
      - mcas_old_str_3_0
      - mmus_yng_hsc_3_0
      - mmus_yng_str_1_0
      - mspr_old_hsc_2_0
      - mspr_yng_str_1_0
    seeds_umap:
      str: 44
      hsc: 437
  clustering:
    number_k: 
    # adjust according to clustering reports (per species)
      mcar:
        hsc: 11    # 7 ... 11
        str: 13    # just 13
        both: 18   # 18 ... 24
      mcas:
        hsc: 10    # 8 ... 10
        str: 14    # just 14
        both: 20   # 20 ... 21
      mmus:
        hsc: 10    # 9 ... 10
        str: 14    # just 14
        both: 18   # 18 ... 23 ... 25
      mspr:
        hsc: 10    # 9 ... 10
        str: 15    # just 15
        both: 22   # 22 ...25
        #per fraction
      hsc: 6 # 3, 6, 9, 12, 15 
      str: 13 # 9, 13, 14, 26
    resolution: 0.22 # 0.1, 0.15, 0.2, 0.22, 0.25, 0.3, 0.35
    k_louvain: 75 # 80, 75, 70, 50, 45, 40, 30
    use_svm_kernel: "linear" # linear or radial
    size_subs_hscs: 60000 
      
# CONDITIONS  
# in caps for use in R, only first letter capitalized for use in Snakefile
run_preprocessing_summary: False
run_batch_correction_summary: False
run_manual_annotation_summary: False
run_clustering_summary: False
run_annotation_summary_scmap: False
calculate_k: False

merge_all: True
run_mnncorrect: True
run_batch_correct: False
mnn_use_fast: TRUE
run_seurat3: False
hvgs_for_batch_correction: TRUE 
rescale_for_batch_correction: FALSE # Rescaling assumes that the cell composition in all batches is the same 

remove_mature_cells_clustering: FALSE
separate_fractions_clustering: FALSE


