---
title: "clustering_fraction_report_k"
author: "Lea Wölbert"
date: '2022-12-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Report for best ks as part of clustering at fraction level.

#### Load libraries, source code 

```{r load,  message = FALSE}
library(DropletUtils, quietly = TRUE) 
library(dendextend, quietly = TRUE) 
library(factoextra, quietly = TRUE) 
set.seed(37)
```

```{r}
sce_inp <- readRDS(file = snakemake@input[["sce_input"]])
size_subs_hscs <- snakemake@params[["size_subs_hscs"]]

fraction_curr <- sce_inp$Fraction_ID[1]

# sub sample HSC object since it's too big
if(fraction_curr == "hsc"){
  RNGkind("L'Ecuyer-CMRG") # for random number generation
  set.seed(37)
  sample_numbers <- sample(x = 1:ncol(sce_inp), size = size_subs_hscs)
  print(sample_numbers[123])
  sce_inp <- sce_inp[,sample_numbers]
  
}

```

```{r}

# clustering both fractions together
mat <- reducedDim(sce_inp, "PCA") # PCA is batch corrected
mat <- scale(mat)

fviz_nbclust(mat, FUN = hcut, method = "wss", k.max = 28)+
  ggtitle(paste0(fraction_curr, " BOTH"))

fviz_nbclust(mat, FUN = hcut, method = "silhouette", k.max = 28)+
  ggtitle(paste0(fraction_curr, " BOTH"))

rm(mat)
```
