---
title: "cci_conditions_report"
author: "Lea Wölbert"
date: '2023-10-02'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Load libraries, source code 

```{r seed,  message = FALSE}
set.seed(37)
```

```{r load, message = FALSE}
library(tidyverse)
```

```{r sources, message = FALSE}
source(file = "../../source/plotting.R")
```

```{r load_objects}

cci_dist <- readRDS(snakemake@input[["cci_dist_all"]])
#cci_dist <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/main_analysis/cci_objects/02_cci_alt/reverse/07_ed_rev/cci_dist_all")

#load objects
cci_metrics_list_p <- snakemake@input[["metrics_path"]]
#cci_metrics_list_p <- list("/omics/odcf/analysis/OE0538_projects/DO-0008/data/main_analysis/cci_objects/02_cci_alt/reverse/05_mtrc_rev/cci_metrics_mcar_old", "/omics/odcf/analysis/OE0538_projects/DO-0008/data/main_analysis/cci_objects/02_cci_alt/reverse/05_mtrc_rev/cci_metrics_mcar_yng")

cci_metrics_list <- list()

for(i in 1:length(cci_metrics_list_p)){
  cci_metrics_list[[i]] <- readRDS(file = cci_metrics_list_p[[i]])
}

```

```{r colors, message = FALSE}
colors_path <- snakemake@params[["colors_path"]]
source(file = "../../source/colors.R")
```

# METRICS

```{r}

ipi_ov_list <- list()
idi_ov_list <- list()
ilr_ov_list <- list()

for(i in 1:length(cci_metrics_list)){
  ipi_ov_list[[i]] <- cci_metrics_list[[i]]$ipi$overview
  idi_ov_list[[i]] <- cci_metrics_list[[i]]$idi$overview
  ilr_ov_list[[i]] <- cci_metrics_list[[i]]$ilr$overview

  name <- paste0(ipi_ov_list[[i]]$species[1], "_", 
                 ipi_ov_list[[i]]$age[1], "_", 
                 ipi_ov_list[[i]]$condition[1])
  print(name)
  names(ipi_ov_list)[i] <- name
  names(idi_ov_list)[i] <- name
  names(ilr_ov_list)[i] <- name
}

ipi_df <- bind_rows(ipi_ov_list)
idi_df <- bind_rows(idi_ov_list)
ilr_df <- bind_rows(ilr_ov_list)

ipi_df$species <- factor(ipi_df$species, levels = names(col_spc))
idi_df$species <- factor(idi_df$species, levels = names(col_spc))
ilr_df$species <- factor(ilr_df$species, levels = names(col_spc))

ipi_df$age <- factor(ipi_df$age, levels = names(col_age))
idi_df$age <- factor(idi_df$age, levels = names(col_age))
ilr_df$age <- factor(ilr_df$age, levels = names(col_age))

ipi_df$emitter <- factor(ipi_df$emitter, levels = names(col_cts_hsc))
ipi_df$receiver <- factor(ipi_df$receiver, levels = names(col_cts_str))

idi_df$identity <- factor(idi_df$identity, levels = c(names(col_cts_hsc), names(col_cts_str)))
ilr_df$identity <- factor(ilr_df$identity, levels = c(names(col_cts_hsc), names(col_cts_str)))

ipi_df[is.na(ipi_df$nr_ints),]
ipi_df[is.na(ipi_df$nr_cells_emitter),]
ipi_df[is.na(ipi_df$nr_cells_receiver),]

idi_df[is.na(idi_df$nr_ints),]
idi_df[is.na(idi_df$nr_cells),]

ilr_df[is.na(ilr_df$nr_ints),]
ilr_df[is.na(ilr_df$nr_lrs),]
```

```{r}

ggplot(ipi_df, 
       aes(x = species, y = nr_ints, color = species))+
  ggbeeswarm::geom_quasirandom()+
  geom_boxplot(alpha = 0, color = "grey30")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_manual("Species" , values = col_spc)+
  ylab("Nr of interactions per cell type pair")+
  ylim(c(0, max(ipi_df$nr_ints)))+
  ggtitle("reversed assignment")

ggplot(idi_df, 
       aes(x = species, y = nr_ints, color = species))+
  ggbeeswarm::geom_quasirandom()+
  geom_boxplot(alpha = 0, color = "grey30")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_manual("Species" , values = col_spc)+
  ylab("Nr of interactions per identity")+
  ylim(c(0, max(idi_df$nr_ints)))+
  ggtitle("reversed assignment")

ggplot(ilr_df, 
       aes(x = species, y = nr_lrs, color = species))+
  ggbeeswarm::geom_quasirandom()+
  geom_boxplot(alpha = 0, color = "grey30")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_manual("Species" , values = col_spc)+
  ylab("Nr of ligands/receptors per identity")+
  ylim(c(0, max(ilr_df$nr_lrs)))+
  ggtitle("reversed assignment")
```

```{r}
ggplot(ipi_df, 
       aes(x = species, y = nr_ints, color = emitter))+
  ggbeeswarm::geom_quasirandom()+
  geom_boxplot(alpha = 0, color = "grey30")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_manual("Emitters" , values = col_cts_hsc)+
  ylab("Nr of interactions per cell type pair")+
  ylim(c(0, max(ipi_df$nr_ints)))+
  ggtitle("reversed assignment")

ggplot(idi_df[idi_df$identity %in% names(col_cts_hsc),], 
       aes(x = species, y = nr_ints, color = identity))+
  ggbeeswarm::geom_quasirandom()+
  geom_boxplot(alpha = 0, color = "grey30")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_manual("Emitters" , values = col_cts_hsc)+
  ylab("Nr of interactions per identity")+
  ylim(c(0, max(idi_df$nr_ints)))+
  ggtitle("reversed assignment")

ggplot(ilr_df[ilr_df$identity %in% names(col_cts_hsc),], 
       aes(x = species, y = nr_lrs, color = identity))+
  ggbeeswarm::geom_quasirandom()+
  geom_boxplot(alpha = 0, color = "grey30")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_manual("Emitters" , values = col_cts_hsc)+
  ylab("Nr of ligands/receptors per identity")+
  ylim(c(0, max(ilr_df$nr_lrs)))+
  ggtitle("reversed assignment")
```

```{r}
ggplot(ipi_df, 
       aes(x = species, y = nr_ints, color = receiver))+
  ggbeeswarm::geom_quasirandom()+
  geom_boxplot(alpha = 0, color = "grey30")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_manual("Receivers" , values = col_cts_str)+
  ylab("Nr of interactions per cell type pair")+
  ylim(c(0, max(ipi_df$nr_ints)))+
  ggtitle("reversed assignment")

ggplot(idi_df[idi_df$identity %in% names(col_cts_str),], 
       aes(x = species, y = nr_ints, color = identity))+
  ggbeeswarm::geom_quasirandom()+
  geom_boxplot(alpha = 0, color = "grey30")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_manual("Receivers" , values = col_cts_str)+
  ylab("Nr of interactions per identity")+
  ylim(c(0, max(idi_df$nr_ints)))+
  ggtitle("reversed assignment")

ggplot(ilr_df[ilr_df$identity %in% names(col_cts_str),], 
       aes(x = species, y = nr_lrs, color = identity))+
  ggbeeswarm::geom_quasirandom()+
  geom_boxplot(alpha = 0, color = "grey30")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_manual("Receivers" , values = col_cts_str)+
  ylab("Nr of ligands/receptors per identity")+
  ylim(c(0, max(ilr_df$nr_lrs)))+
  ggtitle("reversed assignment")
```

```{r}
ggplot(ipi_df, 
       aes(x = emitter, y = nr_ints, color = emitter))+
  ggbeeswarm::geom_quasirandom()+
  geom_boxplot(alpha = 0, color = "grey30")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_manual("Emitter" , values = col_cts_hsc)+
  ylab("Nr of interactions per cell type pair")+
  ylim(c(0, max(ipi_df$nr_ints)))+
  facet_grid(cols = vars(ipi_df$species))+
  ggtitle("reversed assignment")

ggplot(idi_df[idi_df$identity %in% names(col_cts_hsc),], 
       aes(x = identity, y = nr_ints, color = age))+
  ggbeeswarm::geom_quasirandom()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_manual("Age" , values = col_age)+
  ylab("Nr of interactions per identity")+
  ylim(c(0, max(idi_df$nr_ints)))+
  facet_grid(cols = vars(idi_df[idi_df$identity %in% names(col_cts_hsc),]$species))+
  ggtitle("reversed assignment")

ggplot(ilr_df[ilr_df$identity %in% names(col_cts_hsc),], 
       aes(x = identity, y = nr_lrs, color = age))+
  ggbeeswarm::geom_quasirandom()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_manual("Age" , values = col_age)+
  ylab("Nr of ligands/receptors per identity")+
  ylim(c(0, max(ilr_df$nr_lrs)))+
  facet_grid(cols = vars(ilr_df[ilr_df$identity %in% names(col_cts_hsc),]$species))+
  ggtitle("reversed assignment")
```

```{r}
ggplot(ipi_df, 
       aes(x = receiver, y = nr_ints, color = receiver))+
  ggbeeswarm::geom_quasirandom()+
  geom_boxplot(alpha = 0, color = "grey30")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_manual("Receiver" , values = col_cts_str)+
  ylab("Nr of interactions per cell type pair")+
  ylim(c(0, max(ipi_df$nr_ints)))+
  facet_grid(cols = vars(ipi_df$species))+
  ggtitle("reversed assignment")

ggplot(idi_df[idi_df$identity %in% names(col_cts_str),], 
       aes(x = identity, y = nr_ints, color = age))+
  ggbeeswarm::geom_quasirandom()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_manual("Age" , values = col_age)+
  ylab("Nr of interactions per identity")+
  ylim(c(0, max(idi_df$nr_ints)))+
  facet_grid(cols = vars(idi_df[idi_df$identity %in% names(col_cts_str),]$species))+
  ggtitle("reversed assignment")

ggplot(ilr_df[ilr_df$identity %in% names(col_cts_str),], 
       aes(x = identity, y = nr_lrs, color = age))+
  ggbeeswarm::geom_quasirandom()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_manual("Age" , values = col_age)+
  ylab("Nr of ligands/receptors per identity")+
  ylim(c(0, max(ilr_df$nr_lrs)))+
  facet_grid(cols = vars(ilr_df[ilr_df$identity %in% names(col_cts_str),]$species))+
  ggtitle("reversed assignment")
```

```{r}

ggplot(ipi_df, 
       aes(x = age, y = nr_ints, color = age))+
  ggbeeswarm::geom_quasirandom(alpha = 0.4)+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90),
        strip.text.x = element_text(angle = 90))+
  scale_color_manual("Age", values = col_age)+
  ylim(c(0, max(ipi_df$nr_ints)))+
  xlab("Receiver")+
  ylab("Nr of interactions per cell type pair")+
  facet_grid(cols = vars(ipi_df$species))+
  ggtitle("reversed assignment")

```

```{r}
ggscatter(ipi_df,
          x = "nr_cells_emitter", y = "nr_ints",
          add = "reg.line", conf.int = TRUE, size = 0.4,
          cor.coef = TRUE, cor.method = "pearson", 
          cor.coef.size = 3.5,  cor.coeff.args = list(color = "dodgerblue3"),
          xlab = "nr of cells per emitter", 
          ylab = "nr of interactions per cell type pair")+
  ylim(c(0, (max(ipi_df$nr_ints)+20)))+
  xlim(c(0, (max(ipi_df$nr_cells_emitter)+20)))+
  ggtitle("reversed assignment")

ggscatter(ipi_df,
          x = "nr_cells_receiver", y = "nr_ints",
          add = "reg.line", conf.int = TRUE, size = 0.4,
          cor.coef = TRUE, cor.method = "pearson",
          cor.coef.size = 3.5,  cor.coeff.args = list(color = "dodgerblue3"),
          xlab = "nr of cells per receiver", 
          ylab = "nr of interactions per cell type pair")+
  ylim(c(0, (max(ipi_df$nr_ints)+20)))+
  xlim(c(0, (max(ipi_df$nr_cells_receiver)+20)))+
  ggtitle("reversed assignment")
```

```{r}
ggscatter(ipi_df,
          x = "nr_cells_emitter", y = "nr_ints",
          add = "reg.line", conf.int = TRUE, size = 0.4,
          cor.coef = TRUE, cor.method = "pearson", 
          cor.coef.size = 3.5,  cor.coeff.args = list(color = "dodgerblue3"),
          xlab = "nr of cells per emitter", 
          ylab = "nr of interactions per cell type pair")+
  ylim(c(0, (max(ipi_df$nr_ints)+20)))+
  xlim(c(0, (max(ipi_df$nr_cells_emitter)+20)))+
  facet_grid(rows = vars(ipi_df$species),
             cols = vars(ipi_df$age))+
  ggtitle("reversed assignment")

ggscatter(ipi_df,
          x = "nr_cells_receiver", y = "nr_ints",
          add = "reg.line", conf.int = TRUE, size = 0.4,
          cor.coef = TRUE, cor.method = "pearson",
          cor.coef.size = 3.5,  cor.coeff.args = list(color = "dodgerblue3"),
          xlab = "nr of cells per receiver", 
          ylab = "nr of interactions per cell type pair")+
  ylim(c(0, (max(ipi_df$nr_ints)+20)))+
  xlim(c(0, (max(ipi_df$nr_cells_receiver)+20)))+
  facet_grid(rows = vars(ipi_df$species),
             cols = vars(ipi_df$age))+
  ggtitle("reversed assignment")
```

```{r}
ggscatter(idi_df,
          x = "nr_cells", y = "nr_ints",
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          cor.coef.size = 3.5,  cor.coeff.args = list(color = "dodgerblue3"),
          xlab = "nr of cells per cell type", 
          ylab = "nr of interactions per cell type")+
  ylim(c(0, (max(idi_df$nr_ints)+50)))+
  xlim(c(0, (max(idi_df$nr_cells)+50)))+
  facet_grid(rows = vars(idi_df$species),
             cols = vars(idi_df$age))+
  ggtitle("reversed assignment")
```

# EUCLIDIAN DISTANCES

# Get distances between young and old corresponding CTP 

```{r}
dist_oy <- cci_dist[grep("yng", rownames(cci_dist)), 
                    grep("old", colnames(cci_dist))]

dist_oy <- rownames_to_column(dist_oy, var = "ct_pair_yng")

dist_oy_direct <- dist_oy %>%
  pivot_longer(cols = c(2:ncol(dist_oy)),
               names_to = "ct_pair_old",
               names_ptypes = list("ct_pair_old" = character()),
               values_to = "distance",
               values_ptypes = list("euclidian_distance" = numeric()),
  )

dist_oy_direct <- separate(dist_oy_direct, into = c("remove1", "species_old", "remove2"),
                           col = which(colnames(dist_oy_direct) == "ct_pair_old"),
                           sep = "_", remove = FALSE,)
dist_oy_direct <- separate(dist_oy_direct, into = c("remove3", "species_yng", "remove4"),
                           col = which(colnames(dist_oy_direct) == "ct_pair_yng"),
                           sep = "_", remove = FALSE,)
dist_oy_direct <- dist_oy_direct[,-which(grepl("remove", colnames(dist_oy_direct)))]
```

```{r}
dist_oy_direct$emitter_old <- gsub("[&][[:print:]]+", "", dist_oy_direct$ct_pair_old)
dist_oy_direct$receiver_old <- gsub("[[:print:]]+[&]", "", dist_oy_direct$ct_pair_old)
dist_oy_direct$receiver_old <- gsub("[_][[:print:]]+", "", dist_oy_direct$receiver_old)
dist_oy_direct$ct_pair_old <- gsub("[_][[:print:]]+", "", dist_oy_direct$ct_pair_old)

dist_oy_direct$emitter_yng <- gsub("[&][[:print:]]+", "", dist_oy_direct$ct_pair_yng)
dist_oy_direct$receiver_yng <- gsub("[[:print:]]+[&]", "", dist_oy_direct$ct_pair_yng)
dist_oy_direct$receiver_yng <- gsub("[_][[:print:]]+", "", dist_oy_direct$receiver_yng)
dist_oy_direct$ct_pair_yng <- gsub("[_][[:print:]]+", "", dist_oy_direct$ct_pair_yng)


dist_oy_direct$emitter_old <- factor(dist_oy_direct$emitter_old,
                                levels = names(col_cts_hsc))
dist_oy_direct$emitter_yng <- factor(dist_oy_direct$emitter_yng,
                                levels = names(col_cts_hsc))

dist_oy_direct$receiver_old <- factor(dist_oy_direct$receiver_old,
                                levels = names(col_cts_str))
dist_oy_direct$receiver_yng <- factor(dist_oy_direct$receiver_yng,
                                levels = names(col_cts_str))

dist_oy_direct$species_old <- factor(dist_oy_direct$species_old,
                                levels = names(col_spc))
dist_oy_direct$species_yng <- factor(dist_oy_direct$species_yng,
                                levels = names(col_spc))

dist_oy_direct_direct <- dist_oy_direct[dist_oy_direct$ct_pair_yng == dist_oy_direct$ct_pair_old,]
dist_oy_direct_direct <- dist_oy_direct_direct[dist_oy_direct_direct$species_old == dist_oy_direct_direct$species_yng,]

```

```{r}

ggplot(dist_oy_direct_direct, 
       aes(x = emitter_old, y = distance, color = emitter_old))+
  ggbeeswarm::geom_quasirandom()+
  theme_classic()+
  scale_color_manual("emitter", values = col_cts_hsc)+
  theme(axis.text.x = element_text(angle = 90))+
  geom_boxplot(color = "grey50", alpha = 0)+
  ylab("ED young/old")+
  xlab("Emitters")

ggplot(dist_oy_direct_direct, 
       aes(x = emitter_old, y = distance, color = receiver_old))+
  ggbeeswarm::geom_quasirandom()+
  theme_classic()+
  scale_color_manual("receiver", values = col_cts_str)+
  theme(axis.text.x = element_text(angle = 90))+
  geom_boxplot(color = "grey50", alpha = 0)+
  ylab("ED young/old")+
  xlab("Emitters")

ggplot(dist_oy_direct_direct, 
       aes(x = emitter_old, y = distance, color = species_old))+
  ggbeeswarm::geom_quasirandom()+
  theme_classic()+
  scale_color_manual("age", values = col_spc)+
  theme(axis.text.x = element_text(angle = 90))+
  geom_boxplot(color = "grey50", alpha = 0)+
  ylab("ED young/old")+
  xlab("Emitters")

ggplot(dist_oy_direct_direct, 
       aes(x = receiver_old, y = distance, color = receiver_old))+
  ggbeeswarm::geom_quasirandom()+
  theme_classic()+
  scale_color_manual("receiver", values = col_cts_str)+
  theme(axis.text.x = element_text(angle = 90))+
  geom_boxplot(color = "grey50", alpha = 0)+
  ylab("ED young/old")+
  xlab("Receivers")

ggplot(dist_oy_direct_direct, 
       aes(x = receiver_old, y = distance, color = emitter_old))+
  ggbeeswarm::geom_quasirandom()+
  theme_classic()+
  scale_color_manual("emitter", values = col_cts_hsc)+
  theme(axis.text.x = element_text(angle = 90))+
  geom_boxplot(color = "grey50", alpha = 0)+
  ylab("ED young/old")+
  xlab("Receivers")

ggplot(dist_oy_direct_direct, 
       aes(x = receiver_old, y = distance, color = species_old))+
  ggbeeswarm::geom_quasirandom()+
  theme_classic()+
  scale_color_manual("Species", values = col_spc)+
  theme(axis.text.x = element_text(angle = 90))+
  geom_boxplot(color = "grey50", alpha = 0)+
  ylab("ED young/old")+
  xlab("Receivers")
```

```{r}
ggplot(dist_oy_direct_direct, 
       aes(x = emitter_old, y = distance, color = emitter_old))+
  ggbeeswarm::geom_quasirandom()+
  theme_classic()+
  scale_color_manual("emitter", values = col_cts_hsc)+
  theme(axis.text.x = element_text(angle = 90))+
  geom_boxplot(color = "grey50", alpha = 0)+
  facet_grid(cols = vars(dist_oy_direct_direct$species_old))+
  ylab("ED young/old")+
  xlab("Emitters")

ggplot(dist_oy_direct_direct, 
       aes(x = emitter_old, y = distance, color = receiver_old))+
  ggbeeswarm::geom_quasirandom()+
  theme_classic()+
  scale_color_manual("receiver", values = col_cts_str)+
  theme(axis.text.x = element_text(angle = 90))+
  geom_boxplot(color = "grey50", alpha = 0)+
  facet_grid(cols = vars(dist_oy_direct_direct$species_old))+
  ylab("ED young/old")+
  xlab("Emitters")

ggplot(dist_oy_direct_direct, 
       aes(x = emitter_old, y = distance, color = species_old))+
  ggbeeswarm::geom_quasirandom()+
  theme_classic()+
  scale_color_manual("age", values = col_spc)+
  theme(axis.text.x = element_text(angle = 90))+
  geom_boxplot(color = "grey50", alpha = 0)+
  facet_grid(cols = vars(dist_oy_direct_direct$species_old))+
  ylab("ED young/old")+
  xlab("Emitters")

ggplot(dist_oy_direct_direct, 
       aes(x = receiver_old, y = distance, color = receiver_old))+
  ggbeeswarm::geom_quasirandom()+
  theme_classic()+
  scale_color_manual("receiver", values = col_cts_str)+
  theme(axis.text.x = element_text(angle = 90))+
  geom_boxplot(color = "grey50", alpha = 0)+
  facet_grid(cols = vars(dist_oy_direct_direct$species_old))+
  ylab("ED young/old")+
  xlab("Receivers")

ggplot(dist_oy_direct_direct, 
       aes(x = receiver_old, y = distance, color = emitter_old))+
  ggbeeswarm::geom_quasirandom()+
  theme_classic()+
  scale_color_manual("emitter", values = col_cts_hsc)+
  theme(axis.text.x = element_text(angle = 90))+
  geom_boxplot(color = "grey50", alpha = 0)+
  facet_grid(cols = vars(dist_oy_direct_direct$species_old))+
  ylab("ED young/old")+
  xlab("Receivers")

ggplot(dist_oy_direct_direct, 
       aes(x = receiver_old, y = distance, color = species_yng))+
  ggbeeswarm::geom_quasirandom()+
  theme_classic()+
  scale_color_manual("Species", values = col_spc)+
  theme(axis.text.x = element_text(angle = 90))+
  geom_boxplot(color = "grey50", alpha = 0)+
  facet_grid(cols = vars(dist_oy_direct_direct$species_old))+
  ylab("ED young/old")+
  xlab("Receivers")
```

```{r}
ggplot(dist_oy_direct_direct, 
       aes(x = species_old, y = distance, color = emitter_old))+
  ggbeeswarm::geom_quasirandom()+
  theme_classic()+
  scale_color_manual("emitter", values = col_cts_hsc)+
  theme(axis.text.x = element_text(angle = 90))+
  geom_boxplot(color = "grey50", alpha = 0)+
  facet_grid(cols = vars(dist_oy_direct_direct$emitter_old))+
  theme(strip.text.x = element_text(angle = 90))+
  ylab("ED young/old")+
  xlab("Species")

ggplot(dist_oy_direct_direct, 
       aes(x = species_old, y = distance, color = receiver_old))+
  ggbeeswarm::geom_quasirandom()+
  theme_classic()+
  scale_color_manual("receiver", values = col_cts_str)+
  theme(axis.text.x = element_text(angle = 90))+
  geom_boxplot(color = "grey50", alpha = 0)+
  facet_grid(cols = vars(dist_oy_direct_direct$emitter_old))+
  theme(strip.text.x = element_text(angle = 90))+
  ylab("ED young/old")+
  xlab("Species")

ggplot(dist_oy_direct_direct, 
       aes(x = species_old, y = distance, color = species_old))+
  ggbeeswarm::geom_quasirandom()+
  theme_classic()+
  scale_color_manual("Species", values = col_spc)+
  theme(axis.text.x = element_text(angle = 90))+
  geom_boxplot(color = "grey50", alpha = 0)+
  facet_grid(cols = vars(dist_oy_direct_direct$emitter_old))+
  theme(strip.text.x = element_text(angle = 90))+
  ylab("ED young/old")+
  xlab("Species")

ggplot(dist_oy_direct_direct, 
       aes(x = species_old, y = distance, color = receiver_old))+
  ggbeeswarm::geom_quasirandom()+
  theme_classic()+
  scale_color_manual("receiver", values = col_cts_str)+
  theme(axis.text.x = element_text(angle = 90))+
  geom_boxplot(color = "grey50", alpha = 0)+
  facet_grid(cols = vars(dist_oy_direct_direct$receiver_old))+
  theme(strip.text.x = element_text(angle = 90))+
  ylab("ED young/old")+
  xlab("Species")

ggplot(dist_oy_direct_direct, 
       aes(x = species_old, y = distance, color = emitter_old))+
  ggbeeswarm::geom_quasirandom()+
  theme_classic()+
  scale_color_manual("emitter", values = col_cts_hsc)+
  theme(axis.text.x = element_text(angle = 90))+
  geom_boxplot(color = "grey50", alpha = 0)+
  facet_grid(cols = vars(dist_oy_direct_direct$receiver_old))+
  theme(strip.text.x = element_text(angle = 90))+
  ylab("ED young/old")+
  xlab("Species")

ggplot(dist_oy_direct_direct, 
       aes(x = species_old, y = distance, color = species_yng))+
  ggbeeswarm::geom_quasirandom()+
  theme_classic()+
  scale_color_manual("Species", values = col_spc)+
  theme(axis.text.x = element_text(angle = 90))+
  geom_boxplot(color = "grey50", alpha = 0)+
  facet_grid(cols = vars(dist_oy_direct_direct$receiver_old))+
  theme(strip.text.x = element_text(angle = 90))+
  ylab("ED young/old")+
  xlab("Species")
```

```{r}
ggplot(dist_oy_direct_direct, 
       aes(x = species_old, y = distance, color = emitter_old))+
  ggbeeswarm::geom_quasirandom()+
  theme_classic()+
  scale_color_manual("emitter", values = col_cts_hsc)+
  theme(axis.text.x = element_text(angle = 90))+
  geom_boxplot(color = "grey50", alpha = 0)+
  ylab("ED young/old")+
  xlab("Species")

ggplot(dist_oy_direct_direct, 
       aes(x = species_old, y = distance, color = receiver_old))+
  ggbeeswarm::geom_quasirandom()+
  theme_classic()+
  scale_color_manual("receiver", values = col_cts_str)+
  theme(axis.text.x = element_text(angle = 90))+
  geom_boxplot(color = "grey50", alpha = 0)+
  ylab("ED young/old")+
  xlab("Species")
```

```{r}
ggplot(dist_oy_direct_direct, 
       aes(x = species_old, y = distance))+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  geom_boxplot(color = "black", alpha = 0)+
  ylab("ED young/old")+
  xlab("Species")

#knitr::knit_exit()
```

```{r}
sessionInfo()
```