---
title: "Supplementary Figure 4"
date: '2024-11-28'
output: html_document
---

For Figure 4.
Figure S4 = HSPC reclustering basics mouse

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Load objects

```{r seed, message = FALSE}
RNGkind("L'Ecuyer-CMRG") 
set.seed(37)
```

```{r load, message = FALSE}
library(tidyverse, quietly = TRUE)
library(SingleCellExperiment, quietly = TRUE)
library(ggpubr, quietly = TRUE)
```

```{r base_path}
base_path <- "/omics/odcf/analysis/OE0538_projects/DO-0008/data"
```

```{r load_manual}
# list of score dfs from hscs
score_df_list_hsc <-  base::readRDS(base::paste0(
  base_path, 
  "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/01_reclustering_own/04_rcls/score_df_reso_hsc"))

score_df_list_hsc_new <- list()
for(res in names(score_df_list_hsc)){
  for(cons_level in names(score_df_list_hsc[[res]])){
    score_df_list_hsc_new[[cons_level]][[res]] <- score_df_list_hsc[[res]][[cons_level]]
  }
}
```

```{r load_manual_res}
# data frame containing the correct resolutions for other datasets as visually determined
resolution_df_path <- base::paste0(
  base_path,
  "/metadata/scRNAseq/03_sce_analysis/reclustering_bm/reclustering_other_resolution.txt")

resolution_df <- utils::read.csv(file = resolution_df_path, 
                               header = TRUE, 
                               sep = ";", 
                               check.names=FALSE, 
                               stringsAsFactors=FALSE, 
                               as.is=TRUE, 
                               colClasses = "character")
print(resolution_df)
```

```{r load_manual_other1}
#### OTHER MOUSE DATASET 1 (HSPC)

dataset_o1 <- "mus_tm_bonemarrow"

score_df_list_o1 <-base::readRDS(base::paste0(
  base_path,
  "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/02_reclustering_other/04_rcls/score_df_mus_tm_bonemarrow_list"))

```

```{r load_manual_other2}
#### OTHER MOUSE DATASET 2 (HSPC)

dataset_o2 <- "mus_weinreb_hspc"

score_df_list_o2 <-base::readRDS(base::paste0(
  base_path,
  "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/02_reclustering_other/04_rcls/score_df_mus_weinreb_hspc_list"))

```

```{r corr_pval_df}
# corrected p values (can only load after all p values have been calculated and corrected)
corr_pval_df <-  readRDS(base::paste0(
  base_path,
  "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/02_reclustering_other/09_crpv/all_corrected_pval"))
```

```{r source}
colors_path <- base::paste0(
  base_path, 
  "/metadata/colors/colors.txt")

source("../source/colors.R")
source("../source/plotting.R")
```

```{r pdf_output}
# define output paths for pdf export
output_pdf_a_plot <- base::paste0(
  base_path,
  "/manuscript1_rev/figures4/a_scores_plot.pdf")

output_pdf_a_legend <- base::paste0(
  base_path,
  "/manuscript1_rev/figures4/a_scores_plot_legend.pdf")

output_pdf_b_pval <- base::paste0(
  base_path,
  "/manuscript1_rev/figures4/b_pval_plot.pdf")
```

```{r params}
# global params
source("../figures/determine_params.R")

col_vec1 <- col_score1
col_vec2 <- col_score2

point_plot_size <- 4

color_significance <- c("pval adj. >= 0.05" = "grey70",
                        "pval adj. < 0.05" = "black",
                        "pval adj. = 0" = "blue")
```

Functions

```{r score_vis_function}
vis_clustering_scores <- function(score_df_list, max){
  
  max <- max
  score_df <- dplyr::bind_rows(score_df_list)

  vis_df_1 <- score_df[score_df$type %in% c("mean_prop_cells_cluster",
                                            "mean_cluster_purity",
                                            "adjusted_rand_index",
                                            "variation_information"),]
  
  name1 <- "NULL"
  if(score_df$conservation_level[1] == "conserved_signature"){
    name1 <- "signature genes"
  }else if(score_df$conservation_level[1] == "conserved_markers"){
    name1 <- "conserved markers"
  }else if(score_df$conservation_level[1] == "mmusall_markers"){
    name1 <- "BL6-only markers"
  }else if(score_df$conservation_level[1] == "random_features"){
    name1 <- "random genes"
  }
  
  title <- paste(score_df$nr_genes_used, name1)
  
  vis_df_1$resolution <- as.numeric(vis_df_1$resolution)
  
  plot1 <- ggplot2::ggplot(vis_df_1, 
                           aes(x = resolution, y = value, color = type))+
    ggplot2::geom_hline(yintercept = 0.5,
                        color = "grey85")+
    ggplot2::geom_hline(yintercept = 1,
                        color = "grey85")+
    ggplot2::geom_hline(yintercept = 2,
                        color = "grey85")+
    ggplot2::geom_vline(xintercept = 0.25,
                        color = "grey85")+
    ggplot2::geom_vline(xintercept = 0.5,
                        color = "grey85")+
    ggplot2::geom_vline(xintercept = 0.75,
                        color = "grey85")+
    ggplot2::geom_vline(xintercept = 1,
                        color = "grey85")+
    ggplot2::geom_vline(xintercept = 1.25,
                        color = "grey85")+
    ggplot2::geom_point()+
    theme_all_supp+
    ggplot2::ylim(c(0, max))+
    ggplot2::scale_color_manual("score", values = c(col_vec1, col_vec2))+
    ggplot2::ggtitle(title)

  return(plot1)
  
}

```

# A Dotplot different scores and nr of clusters

```{r hscs, fig.width = 16, fig.height = 3}
max_hsc <- 5

plot_list_hsc <- lapply(score_df_list_hsc_new, vis_clustering_scores, max = max_hsc)

plot_hsc <- ggpubr::ggarrange(
  plot_list_hsc[[1]]+theme(legend.position = "none")+geom_vline(xintercept = 0.65, color = "orangered"),
  plot_list_hsc[[2]]+theme(legend.position = "none", axis.title.y = element_blank())+geom_vline(xintercept = 0.45, color = "orangered"),
  plot_list_hsc[[3]]+theme(legend.position = "none", axis.title.y = element_blank())+geom_vline(xintercept = 0.65, color = "orangered"),
  NULL,
  nrow = 1,
  align = "h",
  widths = c(1, 1, 1, 1)
)

plot_hsc
```

Not sure about these two but let's keep them for now.

```{r other1, fig.width = 16, fig.height = 3}
# run the function, get max
max_o1 <- 3
plot_list_o1 <- lapply(score_df_list_o1, vis_clustering_scores, max = max_o1)
resolution_df[resolution_df$dataset == dataset_o1,]

plot_o1 <- ggpubr::ggarrange(
  plot_list_o1[[1]]+theme(legend.position = "none")+geom_vline(xintercept = 0.65, color = "orangered"),
  plot_list_o1[[2]]+theme(legend.position = "none", axis.title.y = element_blank())+geom_vline(xintercept = 0.5, color = "orangered"),
  plot_list_o1[[3]]+theme(legend.position = "none", axis.title.y = element_blank())+geom_vline(xintercept = 0.4, color = "orangered"),
  plot_list_o1[[4]]+theme(legend.position = "none", axis.title.y = element_blank())+geom_vline(xintercept = 0.65, color = "orangered"),
  nrow = 1,
  align = "h",
  widths = c(1, 1, 1, 1)
)

dataset_o1
plot_o1
```

```{r other2, fig.width = 16, fig.height = 3}
# run the function, get max
max_o2 <- 5
plot_list_o2 <- lapply(score_df_list_o2, vis_clustering_scores, max = max_o2)
resolution_df[resolution_df$dataset == dataset_o2,]

plot_o2 <- ggpubr::ggarrange(
  plot_list_o2[[1]]+theme(legend.position = "none")+geom_vline(xintercept = 0.55, color = "orangered"),
  plot_list_o2[[2]]+theme(legend.position = "none", axis.title.y = element_blank())+geom_vline(xintercept = 0.5, color = "orangered"),
  plot_list_o2[[3]]+theme(legend.position = "none", axis.title.y = element_blank())+geom_vline(xintercept = 0.6, color = "orangered"),
  plot_list_o2[[4]]+theme(legend.position = "none", axis.title.y = element_blank())+geom_vline(xintercept = 0.55, color = "orangered"),
  nrow = 1,
  align = "h",
  widths = c(1, 1, 1, 1)
)

dataset_o2
plot_o2
```

```{r pval_plot_export}
pdf(output_pdf_a_plot, width = 12, height = 3)
plot_hsc
dev.off()
```

#### Legend

```{r, fig.width = 4, fig.height = 2}
legend_plot <- plot_list_o1[[1]]
legend <- ggpubr::get_legend(legend_plot)
legend <- ggpubr::ggarrange(legend)
legend # change in affinity
```

```{r export_legend}
pdf(output_pdf_a_legend, width = 4, height = 2)
legend
dev.off()
```

# B Permutation dotplot

From previous Fig S6.

## Prep

construct a data frame containing p values

```{r pval_df}
# subset to required datasets
corr_pval_df_hsc <- corr_pval_df[corr_pval_df$condition %in% c(
  "hsc",
  "mus_weinreb_hspc",
  "mus_tm_bonemarrow",
  "ts_hscs_progenitors",
  "ts_bone_marrow"
),]

# make it pretty
corr_pval_df_hsc$condition_long <- vector(length = nrow(corr_pval_df_hsc))
corr_pval_df_hsc$condition_long[
  corr_pval_df_hsc$condition == "hsc"] <- "our HSPCs"
corr_pval_df_hsc$condition_long[
  corr_pval_df_hsc$condition == "mus_weinreb_hspc"] <- "Weinreb et al."
corr_pval_df_hsc$condition_long[
  corr_pval_df_hsc$condition == "mus_tm_bonemarrow"] <- "tabula muris"
corr_pval_df_hsc$condition_long[
  corr_pval_df_hsc$condition == "ts_hscs_progenitors"] <- "tabula sapiens fetal"
corr_pval_df_hsc$condition_long[
  corr_pval_df_hsc$condition == "ts_bone_marrow"] <- "tabula sapiens adult"

corr_pval_df_hsc$condition_long <- factor(
  corr_pval_df_hsc$condition_long, levels = rev(c(
    "our HSPCs",
    "tabula muris",
    "Weinreb et al.",
    "tabula sapiens fetal",
    "tabula sapiens adult")))

corr_pval_df_hsc$score_long <- vector(length = nrow(corr_pval_df_hsc))
corr_pval_df_hsc$score_long[
  corr_pval_df_hsc$type == "adjusted_rand_index"] <- "Adjusted\nRand index"
corr_pval_df_hsc$score_long[
  corr_pval_df_hsc$type == "variation_information"] <- "Variation\nof Information"
corr_pval_df_hsc$score_long[
  corr_pval_df_hsc$type == "mean_prop_cells_cluster"] <- "Mean\nProportion"

corr_pval_df_hsc$score_long <- factor(
  corr_pval_df_hsc$score_long, levels = c(
    "Adjusted\nRand index",
    "Variation\nof Information",
    "Mean\nProportion"))

corr_pval_df_hsc$color_id <- vector(length = nrow(corr_pval_df_hsc))
corr_pval_df_hsc$color_id[corr_pval_df_hsc$pval_corrected < 0.05] <- "pval adj. < 0.05"
corr_pval_df_hsc$color_id[corr_pval_df_hsc$pval_corrected == 0] <- "pval adj. = 0"
corr_pval_df_hsc$color_id[corr_pval_df_hsc$pval_corrected >= 0.05] <- "pval adj. >= 0.05"

corr_pval_df_hsc$comparison_long <- vector(length = nrow(corr_pval_df_hsc))
corr_pval_df_hsc$comparison_long[
  corr_pval_df_hsc$comparison == "sign-vs-rand"] <- "signature vs.\nrandom genes"
corr_pval_df_hsc$comparison_long[
  corr_pval_df_hsc$comparison == "mark-vs-rand"] <- "conserved markers vs.\nrandom genes"
corr_pval_df_hsc$comparison_long[
  corr_pval_df_hsc$comparison == "mmms-vs-rand"] <- "BL6-only markers vs.\nrandom genes"
corr_pval_df_hsc$comparison_long[
  corr_pval_df_hsc$comparison == "mark-vs-signrand"] <- "conserved markers vs.\nsignature + random genes"
corr_pval_df_hsc$comparison_long[
  corr_pval_df_hsc$comparison == "mmms-vs-signrand"] <- "BL6-only markers vs.\nsignature + random genes"

corr_pval_df_hsc$comparison_long <- factor(
  corr_pval_df_hsc$comparison_long, levels = c(
    "signature vs.\nrandom genes",
    "conserved markers vs.\nrandom genes",
    "BL6-only markers vs.\nrandom genes",
    "conserved markers vs.\nsignature + random genes",
    "BL6-only markers vs.\nsignature + random genes"))

corr_pval_df_hsc$color_id <- factor(
  corr_pval_df_hsc$color_id, levels = rev(c(
    "pval adj. >= 0.05",
    "pval adj. < 0.05",
    "pval adj. = 0")))

head(corr_pval_df_hsc)
```

```{r b_pval_plot, fig.width = 12, fig.height = 10}
b_pval_plot <- ggplot2::ggplot(
  corr_pval_df_hsc,
  ggplot2::aes(y = condition_long,
               x = score_long,
               fill = color_id,
               size = 10^-pval_corrected))+
  ggplot2::geom_point(alpha = 1, colour="black", pch=21)+
  ggplot2::facet_grid(
    rows = vars(corr_pval_df_hsc$comparison_long), switch = "y")+
  theme_all_supp+
  ggplot2::theme(
    strip.placement = "outside",
    strip.background.y = element_blank(),
    panel.spacing = unit(2, "cm"),
    strip.text.y.left = element_text(
      angle = 0,
      face= "bold",
      color = "black",
      size = 16,
      hjust = 0,
      vjust = 0.5
    ),
    axis.title = element_blank()
  )+
  ggplot2::scale_x_discrete(position = "top")+
  scale_fill_manual("Significance", values = color_significance)
b_pval_plot
```

```{r pval_b_plot_export}
pdf(output_pdf_b_pval, width = 12, height = 10)
b_pval_plot
dev.off()
```



