---
title: "Figure 3"
date: '2026-02-04'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

New Figure 4 for FACS validation

#### Load objects

```{r seed, message = FALSE}
RNGkind("L'Ecuyer-CMRG") 
set.seed(37)
```

```{r load, message = FALSE}
library(tidyverse, quietly = TRUE)
library(SingleCellExperiment, quietly = TRUE)
library(ggpubr, quietly = TRUE)
```

```{r base_path}
base_path <- snakemake@params[["base_path"]]
#base_path <- "/omics/odcf/analysis/OE0538_projects/DO-0008/data"
#setwd("repositories/Interspecies_BM_phd/code/figures_rev")
```

```{r load_sce}
sce_str <- base::readRDS(base::paste0(
  base_path, 
  "/scRNAseq/main_analysis/sce_objects/02_sce_anno/10_anns/sce_str-10"))
```

```{r source}
# color table
colors_path <- base::paste0(
  base_path,
  "/metadata/colors/colors.txt")
print(colors_path)
source("../source/colors.R")
```

```{r prep_sces}

# randomize the barcodes for nicer visualisation
sce_str <- sce_str[,base::sample(
  x = c(1:ncol(sce_str)), 
  size = ncol(sce_str),
  replace = FALSE)]
```

```{r pdf_output}
# define output paths for pdf export

# gene name Il6st, protein name gp130/CD130
output_pdf_umap_cd130 <- base::paste0(
  base_path,
  "/manuscript1_rev/figure3/figure3_umap_cd130.pdf")
output_pdf_umap_cd130_legend <- base::paste0(
  base_path,
  "/manuscript1_rev/figure3/figure3_umap_cd130_legend.pdf")

# gene name Slco2a1 protein name PGT
output_pdf_umap_pgt <- base::paste0(
  base_path,
  "/manuscript1_rev/figure3/figure3_umap_pgt.pdf")
output_pdf_umap_pgt_legend <- base::paste0(
  base_path,
  "/manuscript1_rev/figure3/figure3_umap_pgt_legend.pdf")

# gene name Neo1 protein name Neo1 or neogenin1
output_pdf_umap_neo1 <- base::paste0(
  base_path,
  "/manuscript1_rev/figure3/figure3_umap_neo1.pdf")
output_pdf_umap_neo1_legend <- base::paste0(
  base_path,
  "/manuscript1_rev/figure3/figure3_umap_neo1_legend.pdf")

# gene name Ntrk2, protein name TrkB
output_pdf_umap_trkb <- base::paste0(
  base_path,
  "/manuscript1_rev/figure3/figure3_umap_trkb.pdf")
output_pdf_umap_trkb_legend <- base::paste0(
  base_path,
  "/manuscript1_rev/figure3/figure3_umap_trkb_legend.pdf")
```

```{r params}
# global params
source("../figures/determine_params.R")

umap_point_size <- 0.2
```

## UMAPs 

### Prep

```{r species_prep}
str_umap_df <- base::as.data.frame(
  SingleCellExperiment::reducedDim(
    sce_str, type = "UMAP"))
str_umap_df$cd130_expression <- SingleCellExperiment::logcounts(sce_str)["Il6st",]
str_umap_df$pgt_expression <- SingleCellExperiment::logcounts(sce_str)["Slco2a1",]
str_umap_df$neo1_expression <- SingleCellExperiment::logcounts(sce_str)["Neo1",]
str_umap_df$trkb_expression <- SingleCellExperiment::logcounts(sce_str)["Ntrk2",]

# positive controls
str_umap_df$plvap_expression <- SingleCellExperiment::logcounts(sce_str)["Plvap",]
str_umap_df$sp7_expression <- SingleCellExperiment::logcounts(sce_str)["Sp7",]
str_umap_df$lama2_expression <- SingleCellExperiment::logcounts(sce_str)["Lama2",]
```

### Plots

#### CD130

```{r str_umap_base_cd130}

str_umap_base_cd130 <- ggplot2::ggplot(
  str_umap_df, 
  aes(x = X1,
      y = X2,
      color = cd130_expression))+
  ggplot2::geom_point(
    size = umap_point_size,
    alpha = umap_point_alpha)+
  ggplot2::xlim(c((base::min(str_umap_df$X1)-1), 
                  (base::max(str_umap_df$X1))+1))+
  ggplot2::ylim(c((base::min(str_umap_df$X2)-1),
                  (base::max(str_umap_df$X2))+1))+
  scale_color_gradientn("Il6st expression", colours = mycolors_to_max_light)
```

```{r str_umap_theme_cd130, fig.width = 2, fig.height = 2}
str_umap_theme_cd130 <- str_umap_base_cd130+
  cowplot::theme_nothing()
str_umap_theme_cd130
```

#### PGT

```{r str_umap_base_pgt}

str_umap_base_pgt <- ggplot2::ggplot(
  str_umap_df, 
  aes(x = X1,
      y = X2,
      color = pgt_expression))+
  ggplot2::geom_point(
    size = umap_point_size,
    alpha = umap_point_alpha)+
  ggplot2::xlim(c((base::min(str_umap_df$X1)-1), 
                  (base::max(str_umap_df$X1))+1))+
  ggplot2::ylim(c((base::min(str_umap_df$X2)-1),
                  (base::max(str_umap_df$X2))+1))+
  scale_color_gradientn("Slco2a1 expression", colours = mycolors_to_max_light)
```

```{r str_umap_theme_pgt, fig.width = 2, fig.height = 2}
str_umap_theme_pgt <- str_umap_base_pgt+
  cowplot::theme_nothing()
str_umap_theme_pgt
```

#### Neo1

```{r str_umap_base_neo1}

str_umap_base_neo1 <- ggplot2::ggplot(
  str_umap_df, 
  aes(x = X1,
      y = X2,
      color = neo1_expression))+
  ggplot2::geom_point(
    size = umap_point_size,
    alpha = umap_point_alpha)+
  ggplot2::xlim(c((base::min(str_umap_df$X1)-1), 
                  (base::max(str_umap_df$X1))+1))+
  ggplot2::ylim(c((base::min(str_umap_df$X2)-1),
                  (base::max(str_umap_df$X2))+1))+
  scale_color_gradientn("Neo1 expression", colours = mycolors_to_max_light)
```

```{r str_umap_theme_neo1, fig.width = 2, fig.height = 2}
str_umap_theme_neo1 <- str_umap_base_neo1+
  cowplot::theme_nothing()
str_umap_theme_neo1
```

#### TrkB

```{r str_umap_base_trkb}

str_umap_base_trkb <- ggplot2::ggplot(
  str_umap_df, 
  aes(x = X1,
      y = X2,
      color = trkb_expression))+
  ggplot2::geom_point(
    size = umap_point_size,
    alpha = umap_point_alpha)+
  ggplot2::xlim(c((base::min(str_umap_df$X1)-1), 
                  (base::max(str_umap_df$X1))+1))+
  ggplot2::ylim(c((base::min(str_umap_df$X2)-1),
                  (base::max(str_umap_df$X2))+1))+
  scale_color_gradientn("Ntrk2 expression", colours = mycolors_to_max_light)
```

```{r str_umap_theme_trkb, fig.width = 2, fig.height = 2}
str_umap_theme_trkb <- str_umap_base_trkb+
  cowplot::theme_nothing()
str_umap_theme_trkb
```

#### Legends

```{r cd130_legend, fig.width = 4, fig.height = 1}
cd130_legend_theme_plot <- str_umap_base_cd130+
  theme_all+
  ggplot2::theme(legend.position = "bottom")
cd130_theme_legend <- ggpubr::get_legend(cd130_legend_theme_plot)
cd130_legend <- ggpubr::ggarrange(cd130_theme_legend)

cd130_legend
```

```{r pgt_legend, fig.width = 4, fig.height = 1}
pgt_legend_theme_plot <- str_umap_base_pgt+
  theme_all+
  ggplot2::theme(legend.position = "bottom")
pgt_theme_legend <- ggpubr::get_legend(pgt_legend_theme_plot)
pgt_legend <- ggpubr::ggarrange(pgt_theme_legend)

pgt_legend
```

```{r neo1_legend, fig.width = 4, fig.height = 1}
neo1_legend_theme_plot <- str_umap_base_neo1+
  theme_all+
  ggplot2::theme(legend.position = "bottom")
neo1_theme_legend <- ggpubr::get_legend(neo1_legend_theme_plot)
neo1_legend <- ggpubr::ggarrange(neo1_theme_legend)

neo1_legend
```

```{r trkb_legend, fig.width = 4, fig.height = 1}
trkb_legend_theme_plot <- str_umap_base_trkb+
  theme_all+
  ggplot2::theme(legend.position = "bottom")
trkb_theme_legend <- ggpubr::get_legend(trkb_legend_theme_plot)
trkb_legend <- ggpubr::ggarrange(trkb_theme_legend)

trkb_legend
```

##### Controls

```{r str_umap_base_plvap}

str_umap_base_plvap <- ggplot2::ggplot(
  str_umap_df, 
  aes(x = X1,
      y = X2,
      color = plvap_expression))+
  ggplot2::geom_point(
    size = umap_point_size,
    alpha = umap_point_alpha)+
  ggplot2::xlim(c((base::min(str_umap_df$X1)-1), 
                  (base::max(str_umap_df$X1))+1))+
  ggplot2::ylim(c((base::min(str_umap_df$X2)-1),
                  (base::max(str_umap_df$X2))+1))+
  scale_color_gradientn("Plvap expression", colours = mycolors_to_max_light)
```

```{r str_umap_theme_plvap, fig.width = 2, fig.height = 2}
str_umap_theme_plvap <- str_umap_base_plvap+
  cowplot::theme_nothing()
str_umap_theme_plvap
```

```{r str_umap_base_sp7}

str_umap_base_sp7 <- ggplot2::ggplot(
  str_umap_df, 
  aes(x = X1,
      y = X2,
      color = sp7_expression))+
  ggplot2::geom_point(
    size = umap_point_size,
    alpha = umap_point_alpha)+
  ggplot2::xlim(c((base::min(str_umap_df$X1)-1), 
                  (base::max(str_umap_df$X1))+1))+
  ggplot2::ylim(c((base::min(str_umap_df$X2)-1),
                  (base::max(str_umap_df$X2))+1))+
  scale_color_gradientn("Sp7 expression", colours = mycolors_to_max_light)
```

```{r str_umap_theme_sp7, fig.width = 2, fig.height = 2}
str_umap_theme_sp7 <- str_umap_base_sp7+
  cowplot::theme_nothing()
str_umap_theme_sp7
```

```{r str_umap_base_lama2}

str_umap_base_lama2 <- ggplot2::ggplot(
  str_umap_df, 
  aes(x = X1,
      y = X2,
      color = lama2_expression))+
  ggplot2::geom_point(
    size = umap_point_size,
    alpha = umap_point_alpha)+
  ggplot2::xlim(c((base::min(str_umap_df$X1)-1), 
                  (base::max(str_umap_df$X1))+1))+
  ggplot2::ylim(c((base::min(str_umap_df$X2)-1),
                  (base::max(str_umap_df$X2))+1))+
  scale_color_gradientn("Lama2 expression", colours = mycolors_to_max_light)
```

```{r str_umap_theme_lama2, fig.width = 2, fig.height = 2}
str_umap_theme_lama2 <- str_umap_base_lama2+
  cowplot::theme_nothing()
str_umap_theme_lama2
```

#### EXPORT

```{r export_umap_cd130}
pdf(output_pdf_umap_cd130, width = 2, height = 2)
str_umap_theme_cd130
dev.off()
```

```{r export_umap_cd130_legend}
pdf(output_pdf_umap_cd130_legend, width = 4, height = 1) 
cd130_legend
dev.off()
```

```{r export_umap_pgt}
pdf(output_pdf_umap_pgt, width = 2, height = 2)
str_umap_theme_pgt
dev.off()
```

```{r export_umap_pgt_legend}
pdf(output_pdf_umap_pgt_legend, width = 4, height = 1) 
pgt_legend
dev.off()
```

```{r export_umap_neo1}
pdf(output_pdf_umap_neo1, width = 2, height = 2)
str_umap_theme_neo1
dev.off()
```

```{r export_umap_neo1_legend}
pdf(output_pdf_umap_neo1_legend, width = 4, height = 1) 
neo1_legend
dev.off()
```

```{r export_umap_trkb}
pdf(output_pdf_umap_trkb, width = 2, height = 2)
str_umap_theme_trkb
dev.off()
```

```{r export_umap_trkb_legend}
pdf(output_pdf_umap_trkb_legend, width = 4, height = 1) 
trkb_legend
dev.off()
```

# Violin

```{r violin_ec_prep}

genes_ec <- c( 
  "Il6st",
  "Slco2a1",
  "Plvap")

sce_genes_ec <- sce_str[rownames(sce_str) %in% c(
  genes_ec
),]

# make a df for visualisation
logcounts_df_ec <- logcounts(sce_genes_ec) %>%
  as.matrix() %>%
  as.data.frame() %>% 
  tibble::rownames_to_column(var = "genes") %>%
  tidyr::pivot_longer(
    cols = colnames(sce_genes_ec),
    names_to = "cell",
    values_to = "logcounts")

# add cluster info
logcounts_df_ec$celltypes <- sce_genes_ec$celltypes[
  match(
    logcounts_df_ec$cell,
    rownames(colData(sce_genes_ec)))]

logcounts_df_ec$genes <- factor(logcounts_df_ec$genes, levels = c(
  genes_ec
))
```

```{r vioplot_ec_base, fig.height = 2, fig.width = 5}
vioplot_ec_base <- logcounts_df_ec %>%
  ggplot2::ggplot(
    aes(
      x = celltypes,
      y = logcounts,
      color = celltypes))+
    ggplot2::geom_violin(
      scale = "width",
      draw_quantiles = c(0.25, 0.5, 0.75))
      
vioplot_ec_theme <- vioplot_ec_base+
    ggplot2::scale_y_continuous(
      limits = c(0, 6),
      breaks = c(0, 5)
    )+
    theme_all+
    ggplot2::theme(
      axis.text.x = element_blank(),
      strip.text.y.right = element_text(
        angle = 0, 
        hjust = 0,
        vjust = 0.5,
        color = axis_text_color,
        size = axis_text_size,
        face = axis_text_face
      ),
      strip.background = element_blank(),
      axis.title.x = element_blank(),
      legend.position = "none")+
    ggplot2::facet_grid(rows = vars(genes))+
    ggplot2::scale_color_manual("Cell types", values = col_cts_str)

vioplot_ec_theme
```

```{r violin_mes_prep}

genes_mes <- c( 
  "Neo1",
  "Sp7",
  "Ntrk2",
  "Lama2")

sce_genes_mes <- sce_str[rownames(sce_str) %in% c(
  genes_mes
),]

# make a df for visualisation
logcounts_df_mes <- logcounts(sce_genes_mes) %>%
  as.matrix() %>%
  as.data.frame() %>% 
  tibble::rownames_to_column(var = "genes") %>%
  tidyr::pivot_longer(
    cols = colnames(sce_genes_mes),
    names_to = "cell",
    values_to = "logcounts")

# add cluster info
logcounts_df_mes$celltypes <- sce_genes_mes$celltypes[
  match(
    logcounts_df_mes$cell,
    rownames(colData(sce_genes_mes)))]

logcounts_df_mes$genes <- factor(logcounts_df_mes$genes, levels = c(
  genes_mes
))
```

```{r vioplot_mes_base, fig.height = 4.5, fig.width = 5}
vioplot_mes_base <- logcounts_df_mes %>%
  ggplot2::ggplot(
    aes(
      x = celltypes,
      y = logcounts,
      color = celltypes))+
    ggplot2::geom_violin(
      scale = "width",
      draw_quantiles = c(0.25, 0.5, 0.75))
      
vioplot_mes_theme <- vioplot_mes_base+
    ggplot2::scale_y_continuous(
      limits = c(0, 4),
      breaks = c(0, 3)
    )+
    theme_all+
    ggplot2::theme(
      axis.text.x = element_text(
        angle = 90,
        hjust = 1, 
        vjust = 0.5),
      strip.text.y.right = element_text(
        angle = 0, 
        hjust = 0,
        vjust = 0.5,
        color = axis_text_color,
        size = axis_text_size,
        face = axis_text_face
      ),
      strip.background = element_blank(),
      axis.title.x = element_blank(),
      legend.position = "none")+
    ggplot2::facet_grid(rows = vars(genes))+
    ggplot2::scale_color_manual("Cell types", values = col_cts_str)

vioplot_mes_theme
```

# UTILS

```{r sessioninfo}
utils::sessionInfo()
```
