---
title: "Figure 5"
date: '2024-10-03'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Prior Figure 4. 

The re-annotation part has been moved into 03_analysis.

#### Load objects

```{r seed, message = FALSE}
RNGkind("L'Ecuyer-CMRG") 
set.seed(37)
```

```{r load_packages, message = FALSE}
library(Seurat, quietly = TRUE)
library(SingleCellExperiment, quietly = TRUE)
library(ggpubr, quietly = TRUE)
library(tidyverse, quietly = TRUE)
```

```{r base_path}
base_path <- snakemake@params[["base_path"]]
#base_path <- "/omics/odcf/analysis/OE0538_projects/DO-0008/data"
#setwd("repositories/Interspecies_BM_phd/code/figures_rev")
```

```{r load_other1}
#-------------------------------------------------------------------------------
#### OTHER MOUSE DATASET 1 (HSPC)
#### TABULA SAPIENS BONE MARROW

dataset_o1 <- "ts_bone_marrow"

# load the reclustered and blindly annotated dataset
# this also contains custom clustering but let's ignore that for here
seu_blind_anno_o1 <- readRDS(base::paste0(
  base_path,
  "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/04_blind_annotation/ts_bone_marrow_both.Rds"))
```

```{r load_other2}
#-------------------------------------------------------------------------------
#### OTHER MOUSE DATASET 2 (HSPC)
#### Tabula sapiens HSCs and Progs (fetal)

dataset_o2 <- "ts_hscs_progenitors"

seu_blind_anno_o2 <- readRDS(base::paste0(
  base_path,
  "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/04_blind_annotation/ts_hscs_progenitors.Rds"))
```

```{r source}
colors_path <- base::paste0(
  base_path,
  "/metadata/colors/colors.txt")

source("../source/colors.R")
source("../source/plotting.R")
```

```{r params}
# global params
source("../figures/determine_params.R")
```

```{r export_paths}
output_pdf_heatmap_plot <- base::paste0(
  base_path, "/manuscript1_rev/figure5/figure5_heatmap.pdf")
output_pdf_legend_plot <-  base::paste0(
  base_path, "/manuscript1_rev/figure5/figure5_legend.pdf")
```

# Reclustering and blind annotation heatmaps 

For Figure 5b and Figure 5c.

## Other 1

```{r mat_sign_o1}

mat_sign_o1_anno <- base::table(
  seu_blind_anno_o1$cell_type, 
  seu_blind_anno_o1$annotated_reclustered)

for(i in 1:ncol(mat_sign_o1_anno)){
  mat_sign_o1_anno[,i] <- mat_sign_o1_anno[,i]/base::sum(mat_sign_o1_anno[,i])
}
sign_df_o1_anno <- base::as.data.frame(mat_sign_o1_anno)

sign_df_o1_anno$Var2 <- factor(
  sign_df_o1_anno$Var2,
  levels = rev(levels(seu_blind_anno_o1$annotated_reclustered)))

levels(sign_df_o1_anno$Var1)

# for nicer visualisation/unified cell type naming scheme
sign_df_o1_anno$Var1 <- unfactor(sign_df_o1_anno$Var1)
sign_df_o1_anno$Var1[
  sign_df_o1_anno$Var1 == "hematopoietic stem cell"] <- "HSC"
sign_df_o1_anno$Var1[
  sign_df_o1_anno$Var1 == "common myeloid progenitor"] <- "common myeloid prog"
sign_df_o1_anno$Var1[
  sign_df_o1_anno$Var1 == "erythroid progenitor cell"] <- "erythroid prog"

sign_df_o1_anno$Var1 <- factor(
  sign_df_o1_anno$Var1,
  levels = base::c("HSC", 
                   "common myeloid prog",
                   "erythroid prog",
                   "granulocyte"
                   ))
```

```{r sign_base_plot_o1}
sign_base_plot_o1 <- ggplot2::ggplot(
  sign_df_o1_anno, 
  aes(x = Var1, 
      y = Var2,
      fill = Freq))+
  ggplot2::geom_tile()
```

```{r sign_theme_plot_o1, fig.height = 7, fig.width = 5}
sign_theme_plot_o1 <- sign_base_plot_o1+
  theme_all+
  ggplot2::theme(
    legend.position = "none",
    axis.title = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.y  = element_text(
      vjust = 0.5,
      hjust = 0),
    axis.text.x = element_text(
      angle = 90,
      vjust = 0.5,
      hjust = 1))+
  ggplot2::scale_fill_gradientn(
    colors = mycolors_to1,
    limits = c(0, 1),
    breaks = c(0, 0.5, 1))+
  #ggplot2::ylab("Reclustered + re-annotated")+
  ggplot2::scale_y_discrete(position = "right")
sign_theme_plot_o1
```

### Others 2

Figure 4c.

```{r mat_sign_o2}

mat_sign_o2 <- base::table(
  seu_blind_anno_o2$cell_type, 
  seu_blind_anno_o2$annotated_reclustered)

for(i in 1:ncol(mat_sign_o2)){
  mat_sign_o2[,i] <- mat_sign_o2[,i]/base::sum(mat_sign_o2[,i])
}
sign_df_o2 <- base::as.data.frame(mat_sign_o2)

sign_df_o2$Var2 <- factor(
  sign_df_o2$Var2,
  levels = rev(levels(seu_blind_anno_o2$annotated_reclustered)))

# for nicer visualisation/unified naming scheme
sign_df_o2$Var1 <- unfactor(sign_df_o2$Var1)
sign_df_o2$Var1[
  sign_df_o2$Var1 == "hematopoietic stem cell"] <- "HSC"
sign_df_o2$Var1[
  sign_df_o2$Var1 == "hematopoietic multipotent progenitor cell"] <- "hematopoietic MPP"
sign_df_o2$Var1[
  sign_df_o2$Var1 == "common myeloid progenitor"] <- "common myeloid prog"
sign_df_o2$Var1[
  sign_df_o2$Var1 == "granulocyte monocyte progenitor cell"] <- "granu-mono prog"
sign_df_o2$Var1[
  sign_df_o2$Var1 == "early lymphoid progenitor"] <- "early lymphoid prog"
sign_df_o2$Var1[
  sign_df_o2$Var1 == "megakaryocyte-erythroid progenitor cell"] <- "mk-ery prog"

sign_df_o2$Var1 <- factor(
  sign_df_o2$Var1,
  levels = base::c(
    "HSC",
    "hematopoietic MPP",
    "common myeloid prog",
    "granu-mono prog",
    "promonocyte",
    "promyelocyte",
    "early lymphoid prog",
    "mk-ery prog"
  ))
```

```{r sign_base_plot_o2}
sign_base_plot_o2 <- ggplot2::ggplot(
  sign_df_o2, 
  aes(x = Var1, 
      y = Var2,
      fill = Freq))+
  ggplot2::geom_tile()
```

```{r sign_theme_plot_o2, fig.height = 8, fig.width = 6}
sign_theme_plot_o2 <- sign_base_plot_o2+
  theme_all+
  ggplot2::theme(
    legend.position = "none",
    axis.title = element_blank(),
    axis.text.x = element_text(
      angle = 90,
      hjust = 1, 
      vjust = 0.5),
    axis.text.y = element_text(
      hjust = 0, 
      vjust = 0.5),
    axis.ticks.y = element_blank())+
  ggplot2::scale_fill_gradientn(
    colors = mycolors_to1,
    limits = c(0, 1),
    breaks = c(0, 0.5, 1))+
  #ggplot2::ylab("Reclustered + re-annotated")+
  ggplot2::xlab("Reference cell types")+
  ggplot2::scale_y_discrete(position = "right")
sign_theme_plot_o2
```

```{r legend}
legend_theme_plot <- sign_base_plot_o2+
  theme_all+
  ggplot2::theme(legend.position = "bottom")+
  ggplot2::scale_fill_gradientn(
    "Proportion of cells per cluster",
    colors = mycolors_to1,
    limits = c(0, 1),
    breaks = c(0, 0.5, 1))

heatmap_legend_theme <- ggpubr::get_legend(legend_theme_plot)
heatmap_legend <- ggpubr::ggarrange(heatmap_legend_theme)
```

### Assemble and Export

```{r heatmap_plotparts, fig.width = 11.5, fig.height = 6.5}

sign_plots_heatmap <- ggpubr::ggarrange(
  ncol = 2,
  align = "h",
  sign_theme_plot_o1,
  sign_theme_plot_o2)
sign_plots_heatmap
```

```{r heatmap_plot_export}
pdf(output_pdf_heatmap_plot, width = 12, height = 6.5)
sign_plots_heatmap
dev.off()
```

```{r heatmap_own_legend_export}
pdf(output_pdf_legend_plot, width = 6, height = 1)
heatmap_legend
dev.off()
```

# Utils

```{r sessioninfo}
utils::sessionInfo()
```
