---
title: "Threshold sensitivity of nDEGs and conserved markers — visualization"
date: '2025-12-11'
output: html_document
---

This script generates plots regarding thresholds for Figure S3.

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo       = TRUE,
  message    = FALSE,
  warning    = FALSE,
  fig.align  = "left"
)
```

```{r libraries}
library(tidyverse, quietly = TRUE)
library(ggpubr, quietly = TRUE)
```

```{r paths}
base_path <- snakemake@params[["base_path"]]
#base_path <- "/omics/odcf/analysis/OE0538_projects/DO-0008/data/"
#project_path <- "/omics/groups/OE0433/internal/veronica/github/Interspecies_BM_phd"

# this is the output of threshold analysis, data is loaded from there
out_dir <- file.path(
  base_path,
  "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/05_thresholds"
)
```

```{r source}
colors_path <- base::paste0(
  base_path,
  "/metadata/colors/colors.txt"
)

source("../source/colors.R")
source("../source/plotting.R")
source("../figures/determine_params.R")

#source(file.path(project_path, "code/source/colors.R"))
#source(file.path(project_path, "code/source/plotting.R"))
#source(file.path(project_path, "code/figures/determine_params.R"))
```

# Load precomputed results

```{r load_results}
nDEG_df <- readRDS(file.path(out_dir, "nDEG_df.rds"))
common_marker_stats_df <- readRDS(file.path(out_dir, "common_marker_stats_df.rds"))
```

# Plot: nDEGs vs signature genes over p-value threshold

```{r plot_ndge, fig.width=6, fig.height=5}
plot_nDEG <- ggplot(
  nDEG_df,
  aes(x = -log(padj), color = celltype)
) +
  geom_vline(
    xintercept = -log(0.05),
    color = "grey80"
  ) +
  geom_line(
    aes(y = n_nDEGs),
    linetype = "dashed"
  ) +
  geom_line(
    aes(y = n_signature_genes),
    linetype = "solid"
  ) +
  scale_y_log10(
    name = "Total signature genes (solid),\nTotal nDEGs (dashed)"
  ) +
  scale_color_manual(values = col_cts_hsc,
                    guide = "none") +
  labs(
    x = "-log(padj) nDEG",
    color = NULL
  ) +
  theme_all

plot_nDEG
```

# Plot: common markers vs signature genes over log2FC threshold

```{r plot_markers, fig.width=7, fig.height=5}
plot_markers <- ggplot(
  common_marker_stats_df,
  aes(x = logfc_threshold, color = celltype)
) +
  geom_vline(
    xintercept = 0.25,
    color      = "grey80"
  ) +
  geom_line(
    aes(y = n_common_markers_all_species),
    linetype = "dashed"
  ) +
  geom_line(
    aes(y = n_signature_genes),
    linetype = "solid"
  ) +
  scale_y_log10(
    name = "Total signature genes (solid),\nTotal conserved markers (dashed)"
  ) +
  scale_color_manual(values = col_cts_hsc) +
  labs(
    x     = "marker log2FC",
    color = NULL
  ) +
  theme_all

plot_markers
```

# Output everything together

```{r export_pdf}
thresholds_plot <- ggpubr::ggarrange(
  plot_nDEG,
  plot_markers,
  ncol = 2,
  widths = c(1, 1.6)
)

pdf(
  file = file.path(base_path, "/manuscript1_rev/pdfs/threshold.pdf"),
  height = 5,
  width = 10
)
thresholds_plot
dev.off()
```

```{r session_info}
utils::sessionInfo()
```
