---
title: "Supplementary Figure X Batch correction"
date: '2025-12-29'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Load objects

```{r seed, message = FALSE}
RNGkind("L'Ecuyer-CMRG") 
set.seed(37)
```

```{r load, message = FALSE}
library(tidyverse, quietly = TRUE)
library(SingleCellExperiment, quietly = TRUE)
library(ggpubr, quietly = TRUE)
library(Seurat, quietly = TRUE)
```

```{r base_path}
base_path <- "/omics/odcf/analysis/OE0538_projects/DO-0008/data"
```

```{r source}
colors_path <- base::paste0(
  base_path, 
  "/metadata/colors/colors.txt")
 
source("../source/colors.R")
source("../source/plotting.R")
source("../figures/determine_params.R")
```

## Load and prepare objects

### Original

```{r load_orig}
# original datasets
seu_ts_bone_marrow_orig <- readRDS(base::paste0(
  base_path,
  "/metadata/scRNAseq/03_sce_analysis/reclustering_bm/prepared/ts_bone_marrow"))

seu_ts_hscs_progenitors_orig <- readRDS(base::paste0(
  base_path,
  "/metadata/scRNAseq/03_sce_analysis/reclustering_bm/prepared/ts_hscs_progenitors"))
```


### Blind annotation after signature reclustering

```{r load_blind}
seu_ts_bone_marrow_blind <- readRDS(base::paste0(
  base_path,
  "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/04_blind_annotation/ts_bone_marrow_both.Rds"))

seu_ts_hscs_progenitors_blind <- readRDS(base::paste0(
  base_path,
  "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/04_blind_annotation/ts_hscs_progenitors.Rds"))
```

### After batch correction signature reclustered

```{r load_bc}
seu_ts_bone_marrow_bc <- readRDS(base::paste0(
  base_path,
  "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/06_include_batch_correction/ts_bone_marrow.Rds"))

seu_ts_hscs_progenitors_bc <- readRDS(base::paste0(
  base_path,
  "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/06_include_batch_correction/ts_hscs_progenitors.Rds"))
```

## Prep

```{r add_clusters}
# add all the different cluster labels

seu_ts_bone_marrow <- seu_ts_bone_marrow_orig

# after also adding a blind annotation of these same signature-based clusters
seu_ts_bone_marrow$sign_blind_labels <- vector(length = ncol(seu_ts_bone_marrow))
seu_ts_bone_marrow$sign_blind_labels <- seu_ts_bone_marrow_blind$signature_label[
  match(
    colnames(seu_ts_bone_marrow),
    colnames(seu_ts_bone_marrow_blind))]

# after batch correction for signature clustering AND blind annotation
seu_ts_bone_marrow$sign_bc_labels <- vector(length = ncol(seu_ts_bone_marrow))
seu_ts_bone_marrow$sign_bc_labels <- seu_ts_bone_marrow_bc$batchc_sign_labels[
  match(
    colnames(seu_ts_bone_marrow),
    colnames(seu_ts_bone_marrow_bc))]



seu_ts_hscs_progenitors <- seu_ts_hscs_progenitors_orig

# after also adding a blind annotation of these same signature-based clusters
seu_ts_hscs_progenitors$sign_blind_labels <- vector(length = ncol(seu_ts_hscs_progenitors))
seu_ts_hscs_progenitors$sign_blind_labels <- seu_ts_hscs_progenitors_blind$annotated_reclustered[
  match(
    colnames(seu_ts_hscs_progenitors),
    colnames(seu_ts_hscs_progenitors_blind))]

# after batch correction for signature clustering AND blind annotation
seu_ts_hscs_progenitors$sign_bc_labels <- vector(length = ncol(seu_ts_hscs_progenitors))
seu_ts_hscs_progenitors$sign_bc_labels <- seu_ts_hscs_progenitors_bc$batchc_sign_labels[
  match(
    colnames(seu_ts_hscs_progenitors),
    colnames(seu_ts_hscs_progenitors_bc))]

```

# Heatmaps

Between original cell types and custom clustering.

```{r make_heatmaps_function}

make_heatmaps <- function(colname1, colname2, seu){

  mat <- base::table(
    seu@meta.data[,which(colnames(seu@meta.data) == colname1)], 
    seu@meta.data[,which(colnames(seu@meta.data) == colname2)])

  for(i in 1:ncol(mat)){
    mat[,i] <- mat[,i]/base::sum(mat[,i])
  }

  plot_df <- base::as.data.frame(mat)

  plot_df$Var1 <- factor(
    plot_df$Var1,
    levels = levels(seu@meta.data[,which(colnames(seu@meta.data) == colname1)]))
  
  plot_df$Var2 <- factor(
    plot_df$Var2,
    levels = rev(levels(seu@meta.data[,which(colnames(seu@meta.data) == colname2)])))

  base_heatmap_return <- ggplot2::ggplot(
    plot_df, 
    aes(x = Var1, 
      y = Var2,
      fill = Freq))+
    ggplot2::geom_tile()+
    theme_all+
    ggplot2::theme(
      legend.position = "none",
      axis.text.x = element_text(
        angle = 90
      ),
      axis.ticks.y = element_blank())+
    ggplot2::scale_fill_gradientn(
      colors = mycolors_to1,
      limits = c(0, 1),
      breaks = c(0, 0.5, 1))+
    xlab(colname1)+
    ylab(colname2)
  

  return(base_heatmap_return)
}
```

### Plot ts_bone_marrow

```{r fig.height = 8, fig.width = 5.5}
make_heatmaps("cell_type", "sign_blind_labels", seu_ts_bone_marrow)
```

```{r fig.height = 8, fig.width = 6}
make_heatmaps("cell_type", "sign_bc_labels", seu_ts_bone_marrow)
```

```{r fig.height = 6, fig.width = 8}
make_heatmaps("sign_blind_labels", "sign_bc_labels", seu_ts_bone_marrow)
```

```{r fig.height = 8, fig.width = 8}
make_heatmaps("sign_bc_labels", "sign_blind_labels", seu_ts_bone_marrow)
```

### Plot ts_hscs_progenitors

```{r fig.height = 10, fig.width = 7}
make_heatmaps("cell_type", "sign_blind_labels", seu_ts_hscs_progenitors)
```

```{r fig.height = 9, fig.width = 7}
make_heatmaps("cell_type", "sign_bc_labels", seu_ts_hscs_progenitors)
```

```{r fig.height = 7, fig.width = 8}
make_heatmaps("sign_blind_labels", "sign_bc_labels", seu_ts_hscs_progenitors)
```

```{r fig.height = 8, fig.width = 7}
make_heatmaps("sign_bc_labels", "sign_blind_labels", seu_ts_hscs_progenitors)
```

```{r utils}
utils::sessionInfo()
```