---
title: "Report on other downloaded datasets"
author: "Lea Wölbert"
date: '2024-08-28'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Show all publicly datasets that have been downloaded.

#### Load objects

```{r seed, message = FALSE}
set.seed(37)
```

```{r load, message = FALSE}
library(tidyverse, quietly = TRUE)
library(Seurat, quietly = TRUE)
```

```{r source}
source(snakemake@params[["reclustering_functions"]])
```

```{r manual, eval = FALSE, include = FALSE}
mus_tik_stromal <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/metadata/scRNAseq/03_sce_analysis/reclustering_bm/prepared/mus_tik_stromal")
```

```{r load_objects}
# human stromal fraction
li_all_stromal <- base::readRDS(snakemake@input[["li_all_stromal"]]) 
ts_all_stromal <- base::readRDS(snakemake@input[["ts_all_stromal"]]) 

# human HSPC fraction
ts_bone_marrow <- base::readRDS(snakemake@input[["ts_bone_marrow"]]) 
ts_hscs_progenitors <- base::readRDS(snakemake@input[["ts_hscs_progenitors"]]) 

# mouse HSPC fraction
mus_weinreb_hspc <- base::readRDS(snakemake@input[["mus_weinreb_hspc"]]) 
mus_tm_bonemarrow <- base::readRDS(snakemake@input[["mus_tm_bonemarrow"]]) 

# mouse stromal fraction
mus_tik_stromal <- base::readRDS(snakemake@input[["mus_tik_stromal"]]) 
mus_bar_stromal <- base::readRDS(snakemake@input[["mus_bar_stromal"]]) 

# zebrafish HSPC fraction
zeb_all_hspc <- base::readRDS(snakemake@input[["zeb_all_hspc"]]) 

# naked mole rat HSPC fraction
nmr_sorted_hspc <- base::readRDS(snakemake@input[["nmr_sorted_hspc"]]) 
```

## li_all_stromal

```{r li_all_stromal}
li_all_stromal
ncol(li_all_stromal)
li_all_stromal@assays
li_all_stromal@assays$RNA
li_all_stromal@assays$RNA@counts[90:100,1:10] # RAW COUNTS
li_all_stromal@assays$RNA@data[90:100,1:10] # RAW COUNTSs
li_all_stromal@assays$originalexp@counts[90:100,1:10] # RAW COUNTS
li_all_stromal@assays$originalexp@data[90:100,1:10] # RAW COUNTSs

li_all_stromal@misc

head(li_all_stromal@meta.data)

li_all_stromal@reductions # has original PCA
DimPlot(li_all_stromal, group.by = "cell_type")
```

Try reclustering with standard seurat pipeline.
This is just to try the process so just use the first 300 genes as the
actual clusters don't matter.

```{r li_all_stromal_pca}
li_all_stromal_reclustered <- standard_seu_pipeline(
  seu = li_all_stromal,
  resolution = 0.5,
  features = rownames(li_all_stromal)[1:300],
  data_use = li_all_stromal@misc$data_use
)

print(li_all_stromal@misc$data_use)
li_all_stromal@assays
li_all_stromal_reclustered@assays$RNA@counts[90:100,1:10] # RAW COUNTS
li_all_stromal_reclustered@assays$RNA@data[90:100,1:10] # Normalised counts
li_all_stromal_reclustered@reductions # has original PCA and new PCA
base::table(li_all_stromal_reclustered$seurat_clusters)

rm(li_all_stromal)
rm(li_all_stromal_reclustered)
```

## ts_all_stromal

```{r ts_all_stromal}
ts_all_stromal
ncol(ts_all_stromal)
ts_all_stromal@assays
ts_all_stromal@assays$RNA
ts_all_stromal@assays$RNA@counts[90:100,1:10] # RAW COUNTS
ts_all_stromal@assays$RNA@counts[90:100,1:10] # NORMALISED/LOGCOUNTSs

ts_all_stromal@misc

head(ts_all_stromal@meta.data)

ts_all_stromal@reductions # NO REDUCTIONS
```

```{r ts_all_stromal_pca}
ts_all_stromal_reclustered <- standard_seu_pipeline(
  seu = ts_all_stromal,
  resolution = 0.5,
  features = rownames(ts_all_stromal)[1:300],
  data_use = ts_all_stromal@misc$data_use
)

print(ts_all_stromal@misc$data_use)
ts_all_stromal_reclustered@assays$RNA@counts[90:100,1:10] # RAW COUNTS
ts_all_stromal_reclustered@assays$RNA@data[90:100,1:10] # other normalised data as before
ts_all_stromal_reclustered@reductions # has only new PCA
base::table(ts_all_stromal_reclustered$seurat_clusters)

rm(ts_all_stromal)
rm(ts_all_stromal_reclustered)
```

## ts_bone_marrow

```{r ts_bone_marrow}
ts_bone_marrow
ncol(ts_bone_marrow)
ts_bone_marrow@assays
ts_bone_marrow@assays$RNA
ts_bone_marrow@assays$RNA@counts[90:100,1:10] # RAW COUNTS
ts_bone_marrow@assays$RNA@data[90:100,1:10] # NORMALISED/LOGCOUNTSs

ts_bone_marrow@misc

head(ts_bone_marrow@meta.data)

ts_bone_marrow@reductions # has original PCs
DimPlot(ts_bone_marrow, group.by = "cell_type")
```

```{r ts_bone_marrow_pca}
ts_bone_marrow_reclustered <- standard_seu_pipeline(
  seu = ts_bone_marrow,
  resolution = 0.5,
  features = rownames(ts_bone_marrow)[1:300],
  data_use = ts_bone_marrow@misc$data_use
)

print(ts_bone_marrow@misc$data_use)
ts_bone_marrow_reclustered@assays$RNA@counts[90:100,1:10] # RAW COUNTS
ts_bone_marrow_reclustered@assays$RNA@data[90:100,1:10] # different logcounts than before
ts_bone_marrow_reclustered@reductions # has original PCA
base::table(ts_bone_marrow_reclustered$seurat_clusters)

rm(ts_bone_marrow)
rm(ts_bone_marrow_reclustered)
```

## ts_hscs_progenitors

```{r ts_hscs_progenitors}
ts_hscs_progenitors
ncol(ts_hscs_progenitors)
ts_hscs_progenitors@assays
ts_hscs_progenitors@assays$RNA
ts_hscs_progenitors@assays$RNA@counts[90:100,1:10] # RAW COUNTS
ts_hscs_progenitors@assays$RNA@data[90:100,1:10] # NORMALISED/LOGCOUNTSs

ts_hscs_progenitors@misc

head(ts_hscs_progenitors@meta.data)

ts_hscs_progenitors@reductions # NO REDUCED DIMS
```

```{r ts_hscs_progenitors_pca}
ts_hscs_progenitors_reclustered <- standard_seu_pipeline(
  seu = ts_hscs_progenitors,
  resolution = 0.5,
  features = rownames(ts_hscs_progenitors)[1:300],
  data_use = ts_hscs_progenitors@misc$data_use
)

print(ts_hscs_progenitors@misc$data_use)
ts_hscs_progenitors_reclustered@assays$RNA@counts[90:100,1:10] # RAW COUNTS
ts_hscs_progenitors_reclustered@assays$RNA@data[90:100,1:10] # new normalised data
ts_hscs_progenitors_reclustered@reductions # only new PCA

rm(ts_hscs_progenitors)
rm(ts_hscs_progenitors_reclustered)
```

## mus_weinreb_hspc

```{r mus_weinreb_hspc}
mus_weinreb_hspc
ncol(mus_weinreb_hspc)
mus_weinreb_hspc@assays
mus_weinreb_hspc@assays$RNA
mus_weinreb_hspc@assays$RNA@counts[1:10,1:10] # NORMALISED/LOGCOUNTSs
mus_weinreb_hspc@assays$RNA@data[1:10,1:10] # NORMALISED/LOGCOUNTSs

mus_weinreb_hspc@misc

head(mus_weinreb_hspc@meta.data)

mus_weinreb_hspc@reductions # NO REDUCED DIMS
```

```{r mus_weinreb_hspc_pca}
mus_weinreb_hspc_reclustered <- standard_seu_pipeline(
  seu = mus_weinreb_hspc,
  resolution = 0.5,
  features = rownames(mus_weinreb_hspc)[1:300],
  data_use = mus_weinreb_hspc@misc$data_use
)

print(mus_weinreb_hspc@misc$data_use)
mus_weinreb_hspc_reclustered@assays$RNA@counts[1:10,1:10] 
mus_weinreb_hspc_reclustered@assays$RNA@data[1:10,1:10] # the same
mus_weinreb_hspc_reclustered@assays$RNA@scale.data[1:10,1:10] # scale is new
mus_weinreb_hspc_reclustered@reductions # has new PCA

rm(mus_weinreb_hspc)
rm(mus_weinreb_hspc_reclustered)
```

## mus_tik_stromal

```{r mus_tik_stromal}
mus_tik_stromal
ncol(mus_tik_stromal)
mus_tik_stromal@assays
mus_tik_stromal@assays$RNA
mus_tik_stromal@assays$RNA@counts[1:10,1:10] # NORMALISED/LOGCOUNTSs
mus_tik_stromal@assays$RNA@data[1:10,1:10] # NORMALISED/LOGCOUNTSs

mus_tik_stromal@misc

head(mus_tik_stromal@meta.data)

mus_tik_stromal@reductions # 
```

```{r mus_tik_stromal_pca}
mus_tik_stromal_reclustered <- standard_seu_pipeline(
  seu = mus_tik_stromal,
  resolution = 0.5,
  features = rownames(mus_tik_stromal)[1:300],
  data_use = mus_tik_stromal@misc$data_use
)

print(mus_tik_stromal@misc$data_use)
mus_tik_stromal_reclustered@assays$RNA@counts[1:10,1:10] 
mus_tik_stromal_reclustered@assays$RNA@data[1:10,1:10] # the same
mus_tik_stromal_reclustered@assays$RNA@scale.data[1:10,1:10] # scale is new
mus_tik_stromal_reclustered@reductions # has new PCA

rm(mus_tik_stromal)
rm(mus_tik_stromal_reclustered)
```


## mus_bar_stromal

```{r mus_bar_stromal}
mus_bar_stromal
ncol(mus_bar_stromal)
mus_bar_stromal@assays
mus_bar_stromal@assays$RNA
mus_bar_stromal@assays$RNA@counts[1:10,1:10] # NORMALISED/LOGCOUNTSs
mus_bar_stromal@assays$RNA@data[1:10,1:10] # NORMALISED/LOGCOUNTSs

mus_bar_stromal@misc

head(mus_bar_stromal@meta.data)

mus_bar_stromal@reductions # 
```

```{r mus_bar_stromal_pca}
mus_bar_stromal_reclustered <- standard_seu_pipeline(
  seu = mus_bar_stromal,
  resolution = 0.5,
  features = rownames(mus_bar_stromal)[1:300],
  data_use = mus_bar_stromal@misc$data_use
)

print(mus_bar_stromal@misc$data_use)
mus_bar_stromal_reclustered@assays$RNA@counts[1:10,1:10] 
mus_bar_stromal_reclustered@assays$RNA@data[1:10,1:10] # the same
mus_bar_stromal_reclustered@assays$RNA@scale.data[1:10,1:10] # scale is new
mus_bar_stromal_reclustered@reductions # has new PCA

rm(mus_bar_stromal)
rm(mus_bar_stromal_reclustered)
```

## zeb_all_hspc

```{r zeb_all_hspc}
zeb_all_hspc
ncol(zeb_all_hspc)
zeb_all_hspc@assays
zeb_all_hspc@assays$RNA
zeb_all_hspc@assays$RNA@counts[90:100,1:10] # RAW COUNTS
zeb_all_hspc@assays$RNA@data[90:100,1:10] # RAW COUNTS

zeb_all_hspc@misc

head(zeb_all_hspc@meta.data)

zeb_all_hspc@reductions # NO REDUCED DIMS
```

```{r zeb_all_hspc_pca}
zeb_all_hspc_reclustered <- standard_seu_pipeline(
  seu = zeb_all_hspc,
  resolution = 0.5,
  features = rownames(zeb_all_hspc)[1:300],
  data_use = zeb_all_hspc@misc$data_use
)

print(zeb_all_hspc@misc$data_use)
zeb_all_hspc_reclustered@assays$RNA@counts[90:100,1:10] # RAW COUNTS
zeb_all_hspc_reclustered@assays$RNA@data[90:100,1:10] # normalised
zeb_all_hspc_reclustered@reductions # has new PCA

rm(zeb_all_hspc)
rm(zeb_all_hspc_reclustered)
```

## nmr_sorted_hspc

```{r nmr_sorted_hspc}
nmr_sorted_hspc
ncol(nmr_sorted_hspc)
nmr_sorted_hspc@assays
nmr_sorted_hspc@assays$RNA
nmr_sorted_hspc@assays$RNA@counts[80:90,1:10] # RAW COUNTS
nmr_sorted_hspc@assays$RNA@data[80:90,1:10] # NORMALISED/LOGCOUNTS COUNTS

nmr_sorted_hspc@misc

head(nmr_sorted_hspc@meta.data)

nmr_sorted_hspc@reductions # has orig PCA
DimPlot(nmr_sorted_hspc, group.by = "cell_type")
```

```{r nmr_sorted_hspc_pca}
nmr_sorted_hspc_reclustered <- standard_seu_pipeline(
  seu = nmr_sorted_hspc,
  resolution = 0.5,
  features = rownames(nmr_sorted_hspc)[1:300],
  data_use = nmr_sorted_hspc@misc$data_use
)

print(nmr_sorted_hspc@misc$data_use)
nmr_sorted_hspc_reclustered@assays$RNA@counts[80:90,1:10] # RAW COUNTS
nmr_sorted_hspc_reclustered@assays$RNA@data[80:90,1:10] 
nmr_sorted_hspc_reclustered@reductions # has original PCA
```

```{r sessioninfo}
utils::sessionInfo()
```
