---
title: "Reclustering permutation report"
author: "Lea Wölbert"
date: '2024-05-08'
output: html_document
---

Plotting the reclustered values for overview/quality assurance.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Load objects

```{r seed, message = FALSE}
set.seed(37)
```

```{r load, message = FALSE}
library(tidyverse, quietly = TRUE)
```

```{r manual, include = FALSE, eval = FALSE}

fraction_curr <- "str"

score_df <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/01_reclustering_own/04_rcls/score_df_str")

perm_score_df <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/01_reclustering_own/05_psig/perm_score_df_str")

cons_level_use <- "conserved_signature"
```

```{r manualscriptown, include = FALSE, eval = FALSE}
cut_off_counts <- 0
nr_cores <- 1 
iterations <- 2

sce <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/scRNAseq/main_analysis/sce_objects/02_sce_anno/10_anns/sce_str-10")

source("../../source/sce_functions_reclustering.R")

fraction_curr <- "str"
k_graph <- 10
resolution_louvain <- 0.3

cts_exclude <- c("Lymphatic ECs", "Chondrocytes")

cons_level_use <- "conserved_signature"

geneset_list <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/01_reclustering_own/01_gens/geneset_list_str")


```

```{r load_objects}
fraction_curr <- snakemake@wildcards[["fraction"]]

# permuted scores dataframe, containing all scores per permutation iteration
perm_score_df <- base::readRDS(snakemake@input[["perm_score_df"]])

# score dataframe, containing the calculated scores 
score_df <- base::readRDS(snakemake@input[["score_df"]])

# which conservation level to use
cons_level_use <- snakemake@params[["cons_level_use"]]
```

```{r subset_objects}
score_df <- score_df[score_df$conservation_level == cons_level_use,]

iterations <- nrow(perm_score_df)
```

```{r colors}

# put in colors.txt once color scheme a little more finalized
col_vec_cons <- c(
    "conserved_signature" = "yellowgreen",
    "conserved_markers" = "darkgreen",
    "mmusall_markers" = "blue2",
    "random_features" = "purple2",
    "ndges" = "orangered1")

col_show <- col_vec_cons[names(col_vec_cons) == cons_level_use]
print(col_show)
```

```{r print}
print(head(score_df))
print(head(perm_score_df))
```

# Histogram

```{r perm_plots}

scores <- c(
  "adjusted_rand_index",
  "mean_cluster_purity",
  "mean_prop_cells_cluster")

scores_v <- c(
  "adjusted_rand_index",
  "mean_cluster_purity",
  "mean_prop_cells_cluster",
  "variation_information")

for(score in scores_v){
  
  print(score)
  
  score_df_temp <- score_df[score_df$type == score,]
  perm_scores <- perm_score_df[,which(colnames(perm_score_df) == score)]
  
  if(score != "variation_information"){
    max <- 1
    pval = length(which(perm_scores > score_df_temp$value))/length(perm_scores)
    print(pval)
  
  }else{
    max <- base::max(c(score_df_temp$value, perm_scores))
    # for variation_information score, the smaller, the better
    pval = length(which(perm_scores < score_df_temp$value))/length(perm_scores)
  }
  
  plot1 <- ggplot2::ggplot(as.data.frame(perm_scores), aes(x = perm_scores))+
    ggplot2::geom_histogram(binwidth = 0.02)+
    ggplot2::geom_vline(xintercept = score_df_temp$value, color = col_show)+
    ggplot2::theme_classic()+
    ggplot2::xlim(c(0, max))+
    ggplot2::ggtitle(base::paste(score, 
                                 fraction_curr, 
                                 iterations,
                                 "iterations"))+
    annotate("text", 
             x = 0.8,
             y = 0.8, 
             label = base::paste0("pval = ", as.character(pval)))
  print(plot1)
}
```

# In two plots

All scores between 0 and 1

```{r all1, fig.width = 2, fig.height = 4}

score_df_temp <- score_df[score_df$type %in% scores,]
score_df_temp <- score_df_temp[
  score_df_temp$conservation_level == cons_level_use,]

perm_score_df_temp <- pivot_longer(perm_score_df,
                                   c = 1:ncol(perm_score_df),
                                   values_to = "value",
                                   names_to = "type")
perm_score_df_temp <- perm_score_df_temp[perm_score_df_temp$type %in% scores,]

plot1 <- ggplot2::ggplot(score_df_temp, aes(x = type, y = value))+
  ggplot2::geom_violin(data = perm_score_df_temp,
                       scale = "width",
                       position = position_nudge(x = 0.2, y = 0))+
  ggplot2::geom_point(color = col_show, 
                      size = 2,
                      position = position_nudge(x = -0.2, y = 0))+
  ggplot2::ylim(c(0,1))+
  ggplot2::theme_classic()+
  ggplot2::theme(axis.text.x = element_text(angle = 90))+
  ggplot2::ggtitle(base::paste(fraction_curr, 
                               iterations,
                               "iterations"))
```

```{r all2, fig.width = 5, fig.height = 4}

score_df_temp <- score_df[score_df$type %in% c("variation_information"),]
score_df_temp <- score_df_temp[
  score_df_temp$conservation_level == cons_level_use,]

perm_score_df_temp <- pivot_longer(perm_score_df, 
                                   c = 1:ncol(perm_score_df),
                                   values_to = "value",
                                   names_to = "type")
perm_score_df_temp <- perm_score_df_temp[
  perm_score_df_temp$type %in% c("variation_information"),]

plot2 <- ggplot2::ggplot(score_df_temp, aes(x = type, y = value))+
  ggplot2::geom_violin(data = perm_score_df_temp,
                       scale = "width", 
                       position = position_nudge(x = 0.2, y = 0))+
  ggplot2::geom_point(color = col_show, 
                      size = 2,
                      position = position_nudge(x = -0.2, y = 0))+
  ggplot2::ylim(c(0, base::max(perm_score_df_temp$value)))+
  ggplot2::theme_classic()+
  ggplot2::theme(axis.text.x = element_text(angle = 90))+
  ggplot2::ggtitle(base::paste(fraction_curr,
                               "\n",
                               iterations,
                               "iterations"))
```

```{r numbers_mark_sign}
print("cell types:")
print(score_df$nr_celltypes[1])
print(base::table(perm_score_df$nr_celltypes))

print("clusters:")
print(score_df$nr_clusters[1])
print(base::table(perm_score_df$nr_clusters))
```

```{r plot_2, fig.width = 3, fig.height = 4.5}
plot <- ggpubr::ggarrange(
  plot1 + ggplot2::theme(legend.position = "none"), 
  plot2 + ggplot2::theme(plot.title = element_blank(),
                          axis.title.y = element_blank()),
  align = "h",
  widths = c(1, 0.5))
plot
```

```{r session_info}
sessionInfo()
```
