---
title: "Report on other downloaded datasets"
author: "Lea Wölbert"
date: '2024-08-28'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Show all publicly datasets that have been downloaded.

#### Load objects

```{r seed, message = FALSE}
set.seed(37)
```

```{r load, message = FALSE}
library(tidyverse, quietly = TRUE)
library(Seurat, quietly = TRUE)
```

```{r manual, eval = FALSE, include = FALSE}

mus_weinreb_hspc <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/metadata/scRNAseq/03_sce_analysis/reclustering_bm/prepared/mus_weinreb_hspc")

```


```{r load_objects}

li_all_stromal <- snakemake@input[["li_all_stromal"]] # human stromal
ts_all_stromal <- snakemake@input[["ts_all_stromal"]] # human stromal
ts_bone_marrow <- snakemake@input[["ts_bone_marrow"]] # human HSPC fraction
ts_hscs_progenitors <- snakemake@input[["ts_hscs_progenitors"]] # human HSPC fraction

mus_weinreb_hspc <- snakemake@input[["mus_weinreb_hspc"]] # mouse HSPC fraction
mus_tm_bonemarrow <- snakemake@input[["mus_tm_bonemarrow"]] # mouse HSPC fraction

zeb_all_hspc <- snakemake@input[["zeb_all_hspc"]] # zebrafish HSPC fraction
nmr_sorted_hspc <- snakemake@input[["nmr_sorted_hspc"]] # naked mole rat HSPC fraction

```

## li_all_stromal

```{r li_all_stromal}
li_all_stromal
li_all_stromal@assays
li_all_stromal@assays$RNA
li_all_stromal@assays$RNA$counts[90:100,1:10] # RAW COUNTS
li_all_stromal@assays$RNA$data[90:100,1:10] # RAW COUNTSs

li_all_stromal@misc

head(li_all_stromal@meta.data)

li_all_stromal@reductions # has original PCA
DimPlot(li_all_stromal, group.by = "cell_type")
```

## ts_all_stromal

```{r ts_all_stromal}
ts_all_stromal
ts_all_stromal@assays
ts_all_stromal@assays$RNA
ts_all_stromal@assays$RNA$counts[90:100,1:10] # RAW COUNTS
ts_all_stromal@assays$RNA$data[90:100,1:10] # NORMALISED/LOGCOUNTSs

ts_all_stromal@misc

head(ts_all_stromal@meta.data)

ts_all_stromal@reductions # NO REDUCTIONS
```

## ts_bone_marrow

```{r ts_bone_marrow}
ts_bone_marrow
ts_bone_marrow@assays
ts_bone_marrow@assays$RNA
ts_bone_marrow@assays$RNA$counts[90:100,1:10] # RAW COUNTS
ts_bone_marrow@assays$RNA$data[90:100,1:10] # NORMALISED/LOGCOUNTSs

ts_bone_marrow@misc

head(ts_bone_marrow@meta.data)

ts_bone_marrow@reductions # has original PCs
DimPlot(ts_bone_marrow, group.by = "cell_type")
```

## ts_hscs_progenitors

```{r ts_hscs_progenitors}
ts_hscs_progenitors
ts_hscs_progenitors@assays
ts_hscs_progenitors@assays$RNA
ts_hscs_progenitors@assays$RNA$counts[90:100,1:10] # RAW COUNTS
ts_hscs_progenitors@assays$RNA$data[90:100,1:10] # NORMALISED/LOGCOUNTSs

ts_hscs_progenitors@misc

head(ts_hscs_progenitors@meta.data)

ts_hscs_progenitors@reductions # NO REDUCED DIMS
```

## mus_weinreb_hspc

```{r mus_weinreb_hspc}
mus_weinreb_hspc
mus_weinreb_hspc@assays
mus_weinreb_hspc@assays$RNA
mus_weinreb_hspc@assays$RNA$counts[1:10,1:10] # NORMALISED/LOGCOUNTSs
mus_weinreb_hspc@assays$RNA$data[1:10,1:10] # NORMALISED/LOGCOUNTSs

mus_weinreb_hspc@misc

head(mus_weinreb_hspc@meta.data)

mus_weinreb_hspc@reductions # NO REDUCED DIMS
```

## zeb_all_hspc

```{r zeb_all_hspc}
zeb_all_hspc
zeb_all_hspc@assays
zeb_all_hspc@assays$RNA
zeb_all_hspc@assays$RNA$counts[90:100,1:10] # RAW COUNTS
zeb_all_hspc@assays$RNA$data[90:100,1:10] # RAW COUNTS

zeb_all_hspc@misc

head(zeb_all_hspc@meta.data)

zeb_all_hspc@reductions # NO REDUCED DIMS
```

## nmr_sorted_hspc

```{r nmr_sorted_hspc}
nmr_sorted_hspc
nmr_sorted_hspc@assays
nmr_sorted_hspc@assays$RNA
nmr_sorted_hspc@assays$RNA$counts[80:90,1:10] # RAW COUNTS
nmr_sorted_hspc@assays$RNA$data[80:90,1:10] # NORMALISED/LOGCOUNTS COUNTS

nmr_sorted_hspc@misc

head(nmr_sorted_hspc@meta.data)

nmr_sorted_hspc@reductions # has orig PCA
DimPlot(nmr_sorted_hspc, group.by = "cell_type")
```

```{r sessioninfo}
utils::sessionInfo()
```
