---
title: "cci_pca_report"
author: "Lea Wölbert"
date: '2023-07-30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Load objects

```{r seed,  message = FALSE}
set.seed(37)
```

```{r load,  message = FALSE}
library(tidyverse)
library(scran)
library(SingleCellExperiment)
```

```{r source, message = FALSE}
#source(file =  snakemake@params[["functions"]])
source(file =  snakemake@params[["plotting"]])
```

```{r load_objects}

pca_list <- readRDS(snakemake@input[["pca_input"]])
sce_hsc <- readRDS(snakemake@input[["sce_hsc"]])
sce_str <- readRDS(snakemake@input[["sce_str"]])
ggdf <- pca_list[[2]]
cci <- readRDS(snakemake@input[["cci_input"]])

if(length(which(c("mmus", "mcas", "mspr", "mcar") %in% ggdf$Species)) == 4){
  wc_curr <- "all"
  point_size <- 2
}else{
  wc_curr <- snakemake@wildcards[[1]]
  point_size <- 2.5
}

```

```{r colors, meassage = FALSE}
colors_path <- snakemake@params[["colors_path"]]
source(snakemake@params[["colors"]])

col_cts_emi <- col_cts_str[names(col_cts_str) %in% cci$Identities$emitter]
col_cts_rec <- col_cts_hsc[names(col_cts_hsc) %in% cci$Identities$receiver]

ggdf$Species <- factor(ggdf$Species, 
                       levels = names(col_spc)[names(col_spc) %in% ggdf$Species])
ggdf$Age <- factor(ggdf$Age, 
                   levels = names(col_age)[names(col_age) %in% ggdf$Age])

ggdf$emitter <- factor(ggdf$emitter,
                       levels = names(col_cts_emi[names(col_cts_emi) %in% ggdf$emitter]))

ggdf$receiver <- factor(ggdf$receiver,
                        levels = names(col_cts_rec[names(col_cts_rec) %in% ggdf$receiver]))

```

```{r}
plot_ints <- function(int){
  
  ggdf$lr_int <- t(cci$Score[which(rownames(cci$Score) == int),])
  
  lig <- str_split(int, "_")[[1]][1]
  rec <- str_split(int, "_")[[1]][2]

  ggdf$ligand1 <- t(cci$Ligandrank[which(rownames(cci$Ligandrank) == int),])
  ggdf$receptor1 <- t(cci$Receptorrank[which(rownames(cci$Receptorrank) == int),])
  
  ggdf$ligand1[is.na(ggdf$ligand1)] <- 0
  ggdf$receptor1[is.na(ggdf$receptor1)] <- 0
  
  print(colnames(ggdf$ligand1))
  print(colnames(ggdf$receptor1))
  
  logc_str <- assays(sce_str)[["logcounts"]]
  ggdf_sce_str <- as.data.frame(colData(sce_str))
  ggdf_sce_str$Species_ID <- factor(ggdf_sce_str$Species_ID,
                                    levels = c("mmus", "mcas", "mspr", "mcar"))
  
  logc_hsc <- assays(sce_hsc)[["logcounts"]]
  ggdf_sce_hsc <- as.data.frame(colData(sce_hsc))
  ggdf_sce_hsc$Species_ID <- factor(ggdf_sce_hsc$Species_ID,
                                    levels = c("mmus", "mcas", "mspr", "mcar"))
  
  plot1 <- umap_gene(sce_str, lig)+
    facet_grid(cols = vars(sce_str$Species_ID), 
               rows = vars(sce_str$Age_ID))+
    ggtitle(paste(wc_curr, int))
  plot2 <- umap_gene(sce_hsc, rec)+
    facet_grid(cols = vars(sce_hsc$Species_ID), 
               rows = vars(sce_hsc$Age_ID))+
    ggtitle(paste(wc_curr, int))
  
  plot8 <- ggplot(ggdf_sce_str, aes(x = celltypes,
                                    y = logc_str[rownames(logc_str) == lig,],
                                    color = celltypes))+
    ggbeeswarm::geom_quasirandom(size = 0.2)+
    theme_classic()+
    geom_boxplot(color = "black", alpha = 0)+
    scale_color_manual(values = col_cts_emi)+
    theme(axis.text.x = element_text(angle = 90),
          legend.position = "none")+
    ylab(paste0(lig, " expression"))+
    facet_grid(cols = vars(sce_str$Species_ID), 
               rows = vars(sce_str$Age_ID))
  
  plot9 <- ggplot(ggdf_sce_hsc, aes(x = celltypes,
                                    y = logc_hsc[rownames(logc_hsc) == rec,],
                                    color = celltypes))+
    ggbeeswarm::geom_quasirandom(size = 0.2)+
    theme_classic()+
    geom_boxplot(color = "black", alpha = 0)+
    scale_color_manual(values = col_cts_rec)+
    theme(axis.text.x = element_text(angle = 90),
          legend.position = "none")+
    ylab(paste0(rec, " expression"))+
    facet_grid(cols = vars(sce_hsc$Species_ID), 
               rows = vars(sce_hsc$Age_ID))

  plot3 <- ggplot(ggdf, aes(x = PC1, y = PC2, color = lr_int))+
    geom_point(size = point_size)+
    theme_classic()+
    ggtitle(paste(wc_curr, int))+
    xlab(paste0("PC1 [", PC1_var, "%]"))+
    ylab(paste0("PC2 [", PC2_var, "%]"))+
    theme(axis.text = element_blank(),
          axis.ticks = element_blank())+
    scale_color_continuous(paste(int, "Score"))+
    facet_grid(cols = vars(ggdf$Age))

  plot4 <- ggplot(ggdf, aes(x = PC1, y = PC2, color = ligand1))+
    geom_point(size = point_size)+
    theme_classic()+
    ggtitle(paste(wc_curr, int))+
    xlab(paste0("PC1 [", PC1_var, "%]"))+
    ylab(paste0("PC2 [", PC2_var, "%]"))+
    theme(axis.text = element_blank(),
          axis.ticks = element_blank())+
    scale_color_continuous(paste(lig, "Ligand Rank"))+
    geom_text(label = ggdf$emitter, check_overlap = TRUE, nudge_y = 1.3)
  
  plot5 <- ggplot(ggdf, aes(x = Age, y = ligand1, fill = Age))+
    geom_col(position = "dodge")+
    theme_classic()+
    theme(axis.text.x = element_text(angle = 90))+
    ylab(paste(lig, "Rank"))+
    scale_fill_manual("Age", values = col_age)+
    theme(strip.text.x = element_text(angle = 90))+
    facet_grid(cols = vars(ggdf$emitter))

  plot6 <- ggplot(ggdf, aes(x = PC1, y = PC2, color = receptor1))+
    geom_point(size = point_size)+
    theme_classic()+
    ggtitle(paste(wc_curr, int))+
    xlab(paste0("PC1 [", PC1_var, "%]"))+
    ylab(paste0("PC2 [", PC2_var, "%]"))+
    theme(axis.text = element_blank(),
            axis.ticks = element_blank())+
    scale_color_continuous(paste(rec, "Receptor Rank"))+
    geom_text(label = ggdf$receiver, check_overlap = TRUE, nudge_y = 1.3)
  
  plot7 <- ggplot(ggdf, aes(x = Age, y = receptor1, fill = Age))+
    geom_col(position = "dodge")+
    theme_classic()+
    theme(axis.text.x = element_text(angle = 90))+
    ylab(paste(rec, "Rank"))+
    scale_fill_manual("Age", values = col_age)+
    theme(strip.text.x = element_text(angle = 90))+
    facet_grid(cols = vars(ggdf$receiver))
  
  return(list(int, plot3, plot1, plot8, plot4, plot5, plot2, plot9, plot6, plot7))

}
```

## PCA plots

```{r}
sum_df <- summary(pca_list[[1]])

PC1_var <- sum_df$importance[2,1]*100
PC2_var <- sum_df$importance[2,2]*100
PC3_var <- sum_df$importance[2,3]*100
PC4_var <- sum_df$importance[2,4]*100
PC5_var <- sum_df$importance[2,5]*100
```

### PC1 and 2

```{r}

ggplot(ggdf, aes(x = PC1, y = PC2, color = Age))+
  geom_point(size = point_size)+
  theme_classic()+
  scale_color_manual(values = col_age)+
  ggtitle(wc_curr)+
  xlab(paste0("PC1 [", PC1_var, "%]"))+
  ylab(paste0("PC2 [", PC2_var, "%]"))+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())
  
ggplot(ggdf, aes(x = PC1, y = PC2, color = Species))+
  geom_point(size = point_size)+
  theme_classic()+
  scale_color_manual(values = col_spc)+
  ggtitle(wc_curr)+
  xlab(paste0("PC1 [", PC1_var, "%]"))+
  ylab(paste0("PC2 [", PC2_var, "%]"))+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())

ggplot(ggdf, aes(x = PC1, y = PC2, color = emitter))+
  geom_point(size = point_size)+
  theme_classic()+
  scale_color_manual(values = col_cts_emi)+
  ggtitle(wc_curr)+
  xlab(paste0("PC1 [", PC1_var, "%]"))+
  ylab(paste0("PC2 [", PC2_var, "%]"))+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())

ggplot(ggdf, aes(x = PC1, y = PC2, color = receiver))+
  geom_point(size = point_size)+
  theme_classic()+
  scale_color_manual(values = col_cts_rec)+
  ggtitle(wc_curr)+
  xlab(paste0("PC1 [", PC1_var, "%]"))+
  ylab(paste0("PC2 [", PC2_var, "%]"))+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())
```

### PC1 and 3

```{r}

ggplot(ggdf, aes(x = PC1, y = PC3, color = Age))+
  geom_point(size = point_size)+
  theme_classic()+
  scale_color_manual(values = col_age)+
  ggtitle(wc_curr)+
  xlab(paste0("PC1 [", PC1_var, "%]"))+
  ylab(paste0("PC3 [", PC3_var, "%]"))+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())
  
ggplot(ggdf, aes(x = PC1, y = PC3, color = Species))+
  geom_point(size = point_size)+
  theme_classic()+
  scale_color_manual(values = col_spc)+
  ggtitle(wc_curr)+
  xlab(paste0("PC1 [", PC1_var, "%]"))+
  ylab(paste0("PC3 [", PC3_var, "%]"))+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())

ggplot(ggdf, aes(x = PC1, y = PC3, color = emitter))+
  geom_point(size = point_size)+
  theme_classic()+
  scale_color_manual(values = col_cts_emi)+
  ggtitle(wc_curr)+
  xlab(paste0("PC1 [", PC1_var, "%]"))+
  ylab(paste0("PC3 [", PC3_var, "%]"))+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())

ggplot(ggdf, aes(x = PC1, y = PC3, color = receiver))+
  geom_point(size = point_size)+
  theme_classic()+
  scale_color_manual(values = col_cts_rec)+
  ggtitle(wc_curr)+
  xlab(paste0("PC1 [", PC1_var, "%]"))+
  ylab(paste0("PC3 [", PC3_var, "%]"))+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())
```

### PC2 and 3

```{r}

ggplot(ggdf, aes(x = PC2, y = PC3, color = Age))+
  geom_point(size = point_size)+
  theme_classic()+
  scale_color_manual(values = col_age)+
  ggtitle(wc_curr)+
  xlab(paste0("PC2 [", PC2_var, "%]"))+
  ylab(paste0("PC3 [", PC3_var, "%]"))+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())
  
ggplot(ggdf, aes(x = PC2, y = PC3, color = Species))+
  geom_point(size = point_size)+
  theme_classic()+
  scale_color_manual(values = col_spc)+
  ggtitle(wc_curr)+
  xlab(paste0("PC2 [", PC2_var, "%]"))+
  ylab(paste0("PC3 [", PC3_var, "%]"))+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())

ggplot(ggdf, aes(x = PC2, y = PC3, color = emitter))+
  geom_point(size = point_size)+
  theme_classic()+
  scale_color_manual(values = col_cts_emi)+
  ggtitle(wc_curr)+
  xlab(paste0("PC2 [", PC2_var, "%]"))+
  ylab(paste0("PC3 [", PC3_var, "%]"))+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())

ggplot(ggdf, aes(x = PC2, y = PC3, color = receiver))+
  geom_point(size = point_size)+
  theme_classic()+
  scale_color_manual(values = col_cts_rec)+
  ggtitle(wc_curr)+
  xlab(paste0("PC2 [", PC2_var, "%]"))+
  ylab(paste0("PC3 [", PC3_var, "%]"))+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())
```

### PC1 and 4

```{r}

ggplot(ggdf, aes(x = PC1, y = PC4, color = Age))+
  geom_point(size = point_size)+
  theme_classic()+
  scale_color_manual(values = col_age)+
  ggtitle(wc_curr)+
  xlab(paste0("PC1 [", PC1_var, "%]"))+
  ylab(paste0("PC4 [", PC4_var, "%]"))+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())
  
ggplot(ggdf, aes(x = PC1, y = PC4, color = Species))+
  geom_point(size = point_size)+
  theme_classic()+
  scale_color_manual(values = col_spc)+
  ggtitle(wc_curr)+
  xlab(paste0("PC1 [", PC1_var, "%]"))+
  ylab(paste0("PC4 [", PC4_var, "%]"))+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())

ggplot(ggdf, aes(x = PC1, y = PC4, color = emitter))+
  geom_point(size = point_size)+
  theme_classic()+
  scale_color_manual(values = col_cts_emi)+
  ggtitle(wc_curr)+
  xlab(paste0("PC1 [", PC1_var, "%]"))+
  ylab(paste0("PC4 [", PC4_var, "%]"))+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())

ggplot(ggdf, aes(x = PC1, y = PC4, color = receiver))+
  geom_point(size = point_size)+
  theme_classic()+
  scale_color_manual(values = col_cts_rec)+
  ggtitle(wc_curr)+
  xlab(paste0("PC1 [", PC1_var, "%]"))+
  ylab(paste0("PC4 [", PC4_var, "%]"))+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())
```

### PC1 and 5

```{r}

ggplot(ggdf, aes(x = PC1, y = PC5, color = Age))+
  geom_point(size = point_size)+
  theme_classic()+
  scale_color_manual(values = col_age)+
  ggtitle(wc_curr)+
  xlab(paste0("PC1 [", PC1_var, "%]"))+
  ylab(paste0("PC4 [", PC5_var, "%]"))+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())
  
ggplot(ggdf, aes(x = PC1, y = PC5, color = Species))+
  geom_point(size = point_size)+
  theme_classic()+
  scale_color_manual(values = col_spc)+
  ggtitle(wc_curr)+
  xlab(paste0("PC1 [", PC1_var, "%]"))+
  ylab(paste0("PC4 [", PC5_var, "%]"))+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())

ggplot(ggdf, aes(x = PC1, y = PC5, color = emitter))+
  geom_point(size = point_size)+
  theme_classic()+
  scale_color_manual(values = col_cts_emi)+
  ggtitle(wc_curr)+
  xlab(paste0("PC1 [", PC1_var, "%]"))+
  ylab(paste0("PC4 [", PC5_var, "%]"))+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())

ggplot(ggdf, aes(x = PC1, y = PC5, color = receiver))+
  geom_point(size = point_size)+
  theme_classic()+
  scale_color_manual(values = col_cts_rec)+
  ggtitle(wc_curr)+
  xlab(paste0("PC1 [", PC1_var, "%]"))+
  ylab(paste0("PC4 [", PC5_var, "%]"))+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())
```

```{r}

ggdf_temp <- ggdf
colnames(ggdf_temp)[1] <- paste0(colnames(ggdf_temp)[1] , " [", PC1_var, "%]")
colnames(ggdf_temp)[2] <- paste0(colnames(ggdf_temp)[2] , " [", PC2_var, "%]")
colnames(ggdf_temp)[3] <- paste0(colnames(ggdf_temp)[3] , " [", PC3_var, "%]")
colnames(ggdf_temp)[4] <- paste0(colnames(ggdf_temp)[4] , " [", PC4_var, "%]")
colnames(ggdf_temp)[5] <- paste0(colnames(ggdf_temp)[5] , " [", PC5_var, "%]")

ggdf_temp <- pivot_longer(ggdf_temp, cols = c(1:5), names_to = "PCs")
  
ggplot(ggdf_temp, aes(x = PCs, y = value, color = Age))+
  ggbeeswarm::geom_quasirandom(size = 0.75)+
  theme_classic()+
  scale_color_manual(values = col_age)+
  ggtitle(wc_curr)

ggplot(ggdf_temp, aes(x = PCs, y = value, color = Species))+
  ggbeeswarm::geom_quasirandom(size = 0.75)+
  theme_classic()+
  scale_color_manual(values = col_spc)+
  ggtitle(wc_curr)

ggplot(ggdf_temp, aes(x = PCs, y = value, color = emitter))+
  ggbeeswarm::geom_quasirandom(size = 0.75)+
  theme_classic()+
  scale_color_manual("Emitter", values = col_cts_str)+
  ggtitle(wc_curr)
  
ggplot(ggdf_temp, aes(x = PCs, y = value, color = receiver))+
  ggbeeswarm::geom_quasirandom(size = 0.75)+
  theme_classic()+
  scale_color_manual("Receiver", values = col_cts_hsc)+
  ggtitle(wc_curr)
```

## PCA Rotation

```{r}

PC1_rot <- pca_list[[1]]$rotation[,1]
PC1_rot_df <- data.frame(
  "ident_pair" = names(PC1_rot),
  "rotation" = PC1_rot)
PC1_rot_df[order(abs(PC1_rot_df$rotation), decreasing = TRUE),]

PC2_rot <- pca_list[[1]]$rotation[,2]
PC2_rot_df <- data.frame(
  "ident_pair" = names(PC2_rot),
  "rotation" = PC2_rot)
PC2_rot_df[order(abs(PC2_rot_df$rotation), decreasing = TRUE),]

PC_rot_ggdf <- as.data.frame(pca_list[[1]]$rotation[,1:2])
PC_rot_ggdf$data <- rep("data", nrow(PC_rot_ggdf))

ggplot(PC_rot_ggdf, aes(x = data, y = PC1))+
  geom_violin(fill = "grey80")+
  geom_point(alpha = 0.4)+
  theme_classic()+
  ggtitle(wc_curr)+
  ylab("PC1 contribution")+
  geom_text(label = rownames(PC_rot_ggdf), nudge_x = 0.1, check_overlap = TRUE)

ggplot(PC_rot_ggdf, aes(x = data, y = PC2))+
  geom_violin(fill = "grey80")+
  geom_point(alpha = 0.4)+
  theme_classic()+
  ggtitle(wc_curr)+
  ylab("PC2 contribution")+
  geom_text(label = rownames(PC_rot_ggdf), nudge_x = 0.1, check_overlap = TRUE)
```

```{r}

for(i in 1:nrow(PC_rot_ggdf)){
  PC_rot_ggdf$ligand[i] <- str_split(rownames(PC_rot_ggdf)[i], "_")[[1]][1]
  PC_rot_ggdf$receptor[i] <- str_split(rownames(PC_rot_ggdf)[i], "_")[[1]][2]
}

ggplot(PC_rot_ggdf, aes(x = data, y = PC1))+
  geom_violin(fill = "grey80")+
  geom_point(alpha = 0.4)+
  theme_classic()+
  ggtitle(wc_curr)+
  ylab("PC1 contribution, Ligands")+
  geom_text(label = PC_rot_ggdf$ligand, nudge_x = 0.1, check_overlap = TRUE)

ggplot(PC_rot_ggdf, aes(x = data, y = PC2))+
  geom_violin(fill = "grey80")+
  geom_point(alpha = 0.4)+
  theme_classic()+
  ggtitle(wc_curr)+
  ylab("PC2 contribution, Ligands")+
  geom_text(label = PC_rot_ggdf$ligand, nudge_x = 0.1, check_overlap = TRUE)
```

```{r}

ggplot(PC_rot_ggdf, aes(x = data, y = PC1))+
  geom_violin(fill = "grey80")+
  geom_point(alpha = 0.4)+
  theme_classic()+
  ggtitle(wc_curr)+
  ylab("PC1 contribution, Receptors")+
  geom_text(label = PC_rot_ggdf$receptor, nudge_x = 0.1, check_overlap = TRUE)

ggplot(PC_rot_ggdf, aes(x = data, y = PC2))+
  geom_violin(fill = "grey80")+
  geom_point(alpha = 0.4)+
  theme_classic()+
  ggtitle(wc_curr)+
  ylab("PC2 contribution, Receptors")+
  geom_text(label = PC_rot_ggdf$receptor, nudge_x = 0.1, check_overlap = TRUE)

```


```{r}
PC_rot_ggdf <- PC_rot_ggdf[order(abs(PC_rot_ggdf$PC1), decreasing = TRUE),]
if(nrow(PC_rot_ggdf) >= 10){
  top_ints_PC1 <- rownames(PC_rot_ggdf)[1:10]
}else{
  top_ints_PC1 <- rownames(PC_rot_ggdf)
}

plotlist <- lapply(top_ints_PC1, plot_ints)
print(plotlist)
```

```{r}
PC_rot_ggdf <- PC_rot_ggdf[order(abs(PC_rot_ggdf$PC2), decreasing = TRUE),]
if(nrow(PC_rot_ggdf) >= 10){
  top_ints_PC2 <- rownames(PC_rot_ggdf)[1:10]
}else{
  top_ints_PC2 <- rownames(PC_rot_ggdf)
}

plotlist <- lapply(top_ints_PC2, plot_ints)
print(plotlist)
```

```{r}
sessionInfo()
```