---
title: "cci_conditions_report"
author: "Lea Wölbert"
date: '2023-10-02'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Load libraries, source code 

```{r seed,  message = FALSE}
set.seed(37)
```

```{r load, message = FALSE}
library(tidyverse)
```

```{r sources, message = FALSE}
source(file = "../../source/plotting.R")
```

```{r load_objects}

#load objects
cci_metrics_list_p <- snakemake@input[["metrics_path"]]
#cci_metrics_list_p <- list("/omics/odcf/analysis/OE0538_projects/DO-0008/data/main_analysis/cci_objects/02_cci_alt_conds/02_mtrc/cci_metrics_mcar_old_main", "/omics/odcf/analysis/OE0538_projects/DO-0008/data/main_analysis/cci_objects/02_cci_alt_conds/02_mtrc/cci_metrics_mspr_yng_nctf")

cci_pca_list_p <- snakemake@input[["pca_path"]]
#cci_pca_list_p <- list("/omics/odcf/analysis/OE0538_projects/DO-0008/data/main_analysis/cci_objects/02_cci_alt_conds/03_cpca/cci_pca_mcar_old_main", "/omics/odcf/analysis/OE0538_projects/DO-0008/data/main_analysis/cci_objects/02_cci_alt_conds/03_cpca/cci_pca_mspr_yng_nctf")

cci_metrics_list <- list()
cci_pca_list <- list()

for(i in 1:length(cci_metrics_list_p)){
  cci_metrics_list[[i]] <- readRDS(file = cci_metrics_list_p[[i]])
  cci_pca_list[[i]] <- readRDS(file = cci_pca_list_p[[i]])
}

```

```{r colors, message = FALSE}
colors_path <- snakemake@params[["colors_path"]]
source(file = "../../source/colors.R")
```

```{r}

ipi_ov_list <- list()
idi_ov_list <- list()
ilr_ov_list <- list()

for(i in 1:length(cci_metrics_list)){
  ipi_ov_list[[i]] <- cci_metrics_list[[i]]$ipi$overview
  idi_ov_list[[i]] <- cci_metrics_list[[i]]$idi$overview
  ilr_ov_list[[i]] <- cci_metrics_list[[i]]$ilr$overview

  name <- paste0(ipi_ov_list[[i]]$species[1], "_", 
                 ipi_ov_list[[i]]$age[1], "_", 
                 ipi_ov_list[[i]]$condition[1])
  print(name)
  names(ipi_ov_list)[i] <- name
  names(idi_ov_list)[i] <- name
  names(ilr_ov_list)[i] <- name
}

ipi_df <- bind_rows(ipi_ov_list)
idi_df <- bind_rows(idi_ov_list)
ilr_df <- bind_rows(ilr_ov_list)

levs <- c("all preprocessing steps",
          "no rank level",
          "no downsampling",
          "no cutoff",
          "no pre-processing steps")

ipi_df$condition <- factor(ipi_df$condition, levels = levs)
idi_df$condition <- factor(idi_df$condition, levels = levs)
ilr_df$condition <- factor(ilr_df$condition, levels = levs)

ipi_df$species <- factor(ipi_df$species, levels = names(col_spc))
idi_df$species <- factor(idi_df$species, levels = names(col_spc))
ilr_df$species <- factor(ilr_df$species, levels = names(col_spc))

ipi_df[is.na(ipi_df$nr_ints),]
ipi_df[is.na(ipi_df$nr_cells_emitter),]
ipi_df[is.na(ipi_df$nr_cells_receiver),]

idi_df[is.na(idi_df$nr_ints),]
idi_df[is.na(idi_df$nr_cells),]

ilr_df[is.na(ilr_df$nr_ints),]
ilr_df[is.na(ilr_df$nr_lrs),]
```

```{r}

ggplot(ipi_df, 
       aes(x = condition, y = nr_ints, color = species))+
  ggbeeswarm::geom_quasirandom()+
  geom_boxplot(alpha = 0, color = "grey30")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_manual("Species" , values = col_spc)+
  xlab("Condition")+
  ylab("Nr of interactions per cell type pair")+
  ylim(c(0, max(ipi_df$nr_ints)))

ggplot(idi_df, 
       aes(x = condition, y = nr_ints, color = species))+
  ggbeeswarm::geom_quasirandom()+
  geom_boxplot(alpha = 0, color = "grey30")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_manual("Species" , values = col_spc)+
  xlab("Condition")+
  ylab("Nr of interactions per identity")+
  ylim(c(0, max(idi_df$nr_ints)))

ggplot(ilr_df, 
       aes(x = condition, y = nr_lrs, color = species))+
  ggbeeswarm::geom_quasirandom()+
  geom_boxplot(alpha = 0, color = "grey30")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_manual("Species" , values = col_spc)+
  xlab("Condition")+
  ylab("Nr of ligands/receptors per identity")+
  ylim(c(0, max(ilr_df$nr_lrs)))

ggplot(ipi_df, 
       aes(x = condition, y = nr_ints))+
  geom_boxplot(alpha = 0, color = "grey30")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_manual("Species" , values = col_spc)+
  xlab("Condition")+
  ylab("Nr of interactions per cell type pair")+
  ylim(c(0, max(ipi_df$nr_ints)))

ggplot(ilr_df, 
       aes(x = condition, y = nr_lrs))+
  geom_boxplot(alpha = 0, color = "grey30")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_manual("Species" , values = col_spc)+
  xlab("Condition")+
  ylab("Nr of ligands/receptors per identity")+
  ylim(c(0, max(ilr_df$nr_lrs)))

```

```{r}
ggscatter(ipi_df[ipi_df$condition == "all preprocessing steps",],
          x = "nr_cells_emitter", y = "nr_ints",
          add = "reg.line", conf.int = TRUE, size = 0.4,
          cor.coef = TRUE, cor.method = "pearson", 
          cor.coef.size = 3.5,  cor.coeff.args = list(color = "dodgerblue3"),
          xlab = "nr of cells per emitter", 
          ylab = "nr of interactions per cell type pair")+
  ylim(c(0, (max(ipi_df$nr_ints)+20)))+
  xlim(c(0, (max(ipi_df$nr_cells_emitter)+20)))+
  ggtitle("all preprocessing steps")

ggscatter(ipi_df[ipi_df$condition == "all preprocessing steps",],
          x = "nr_cells_receiver", y = "nr_ints",
          add = "reg.line", conf.int = TRUE, size = 0.4,
          cor.coef = TRUE, cor.method = "pearson",
          cor.coef.size = 3.5,  cor.coeff.args = list(color = "dodgerblue3"),
          xlab = "nr of cells per receiver", 
          ylab = "nr of interactions per cell type pair")+
  ylim(c(0, (max(ipi_df$nr_ints)+20)))+
  xlim(c(0, (max(ipi_df$nr_cells_receiver)+20)))+
  ggtitle("all preprocessing steps")

ggscatter(ipi_df[ipi_df$condition == "no pre-processing steps",],
          x = "nr_cells_emitter", y = "nr_ints",
          add = "reg.line", conf.int = TRUE, size = 0.4,
          cor.coef = TRUE, cor.method = "pearson", 
          cor.coef.size = 3.5,  cor.coeff.args = list(color = "dodgerblue3"),
          xlab = "nr of cells per emitter", 
          ylab = "nr of interactions per cell type pair")+
  ylim(c(0, (max(ipi_df$nr_ints)+20)))+
  xlim(c(0, (max(ipi_df$nr_cells_emitter)+20)))+
  ggtitle("no preprocessing steps")

ggscatter(ipi_df[ipi_df$condition == "no pre-processing steps",],
          x = "nr_cells_receiver", y = "nr_ints",
          add = "reg.line", conf.int = TRUE, size = 0.4,
          cor.coef = TRUE, cor.method = "pearson",
          cor.coef.size = 3.5,  cor.coeff.args = list(color = "dodgerblue3"),
          xlab = "nr of cells per receiver", 
          ylab = "nr of interactions per cell type pair")+
  ylim(c(0, (max(ipi_df$nr_ints)+20)))+
  xlim(c(0, (max(ipi_df$nr_cells_receiver)+20)))+
  ggtitle("no preprocessing steps")
```


```{r}

ggscatter(ipi_df[ipi_df$condition == "all preprocessing steps",],
          x = "nr_cells_emitter", y = "nr_ints",
          add = "reg.line", conf.int = TRUE, size = 0.4,
          cor.coef = TRUE, cor.method = "pearson", 
          cor.coef.size = 3.5,  cor.coeff.args = list(color = "dodgerblue3"),
          xlab = "nr of cells per emitter", 
          ylab = "nr of interactions per cell type pair")+
  ylim(c(0, (max(ipi_df$nr_ints)+20)))+
  xlim(c(0, (max(ipi_df$nr_cells_emitter)+20)))+
  facet_grid(rows = vars(ipi_df[ipi_df$condition == "all preprocessing steps",]$species),
             cols = vars(ipi_df[ipi_df$condition == "all preprocessing steps",]$age))+
  ggtitle("all preprocessing steps")

ggscatter(ipi_df[ipi_df$condition == "all preprocessing steps",],
          x = "nr_cells_receiver", y = "nr_ints",
          add = "reg.line", conf.int = TRUE, size = 0.4,
          cor.coef = TRUE, cor.method = "pearson",
          cor.coef.size = 3.5,  cor.coeff.args = list(color = "dodgerblue3"),
          xlab = "nr of cells per receiver", 
          ylab = "nr of interactions per cell type pair")+
  ylim(c(0, (max(ipi_df$nr_ints)+20)))+
  xlim(c(0, (max(ipi_df$nr_cells_receiver)+20)))+
  facet_grid(rows = vars(ipi_df[ipi_df$condition == "all preprocessing steps",]$species),
             cols = vars(ipi_df[ipi_df$condition == "all preprocessing steps",]$age))+
  ggtitle("all preprocessing steps")



ggscatter(ipi_df[ipi_df$condition == "no rank level",],
          x = "nr_cells_emitter", y = "nr_ints",
          add = "reg.line", conf.int = TRUE, size = 0.4,
          cor.coef = TRUE, cor.method = "pearson",
          cor.coef.size = 3.5,  cor.coeff.args = list(color = "dodgerblue3"),
          xlab = "nr of cells per emitter", 
          ylab = "nr of interactions per cell type pair")+
  ylim(c(0, (max(ipi_df$nr_ints)+20)))+
  xlim(c(0, (max(ipi_df$nr_cells_emitter)+20)))+
  facet_grid(rows = vars(ipi_df[ipi_df$condition == "no rank level",]$species),
             cols = vars(ipi_df[ipi_df$condition == "no rank level",]$age))+
  ggtitle("no rank level")

ggscatter(ipi_df[ipi_df$condition == "no rank level",],
          x = "nr_cells_receiver", y = "nr_ints",
          add = "reg.line", conf.int = TRUE, size = 0.4,
          cor.coef = TRUE, cor.method = "pearson",
          cor.coef.size = 3.5,  cor.coeff.args = list(color = "dodgerblue3"),
          xlab = "nr of cells per receiver", 
          ylab = "nr of interactions per cell type pair")+
  ylim(c(0, (max(ipi_df$nr_ints)+20)))+
  xlim(c(0, (max(ipi_df$nr_cells_receiver)+20)))+
  facet_grid(rows = vars(ipi_df[ipi_df$condition == "no rank level",]$species),
             cols = vars(ipi_df[ipi_df$condition == "no rank level",]$age))+
  ggtitle("no rank level")



ggscatter(ipi_df[ipi_df$condition == "no downsampling",],
          x = "nr_cells_emitter", y = "nr_ints",
          add = "reg.line", conf.int = TRUE, size = 0.4,
          cor.coef = TRUE, cor.method = "pearson",
          cor.coef.size = 3.5,  cor.coeff.args = list(color = "dodgerblue3"),
          xlab = "nr of cells per emitter", 
          ylab = "nr of interactions per cell type pair")+
  ylim(c(0, (max(ipi_df$nr_ints)+20)))+
  xlim(c(0, (max(ipi_df$nr_cells_emitter)+20)))+
  facet_grid(rows = vars(ipi_df[ipi_df$condition == "no downsampling",]$species),
             cols = vars(ipi_df[ipi_df$condition == "no downsampling",]$age))+
  ggtitle("no downsampling")

ggscatter(ipi_df[ipi_df$condition == "no downsampling",],
          x = "nr_cells_receiver", y = "nr_ints",
          add = "reg.line", conf.int = TRUE, size = 0.4,
          cor.coef = TRUE, cor.method = "pearson",
          cor.coef.size = 3.5,  cor.coeff.args = list(color = "dodgerblue3"),
          xlab = "nr of cells per receiver", 
          ylab = "nr of interactions per cell type pair")+
  ylim(c(0, (max(ipi_df$nr_ints)+20)))+
  xlim(c(0, (max(ipi_df$nr_cells_receiver)+20)))+
  facet_grid(rows = vars(ipi_df[ipi_df$condition == "no downsampling",]$species),
             cols = vars(ipi_df[ipi_df$condition == "no downsampling",]$age))+
  ggtitle("no downsampling")



ggscatter(ipi_df[ipi_df$condition == "no cutoff",],
          x = "nr_cells_emitter", y = "nr_ints", size = 0.4,
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson", cor.coef.coord = c(0, 50),
          cor.coef.size = 3.5,  cor.coeff.args = list(color = "dodgerblue3"),
          xlab = "nr of cells per emitter", 
          ylab = "nr of interactions per cell type pair")+
  ylim(c(0, (max(ipi_df$nr_ints)+20)))+
  xlim(c(0, (max(ipi_df$nr_cells_emitter)+20)))+
  facet_grid(rows = vars(ipi_df[ipi_df$condition == "no cutoff",]$species),
             cols = vars(ipi_df[ipi_df$condition == "no cutoff",]$age))+
  ggtitle("no cutoff")

ggscatter(ipi_df[ipi_df$condition == "no cutoff",],
          x = "nr_cells_receiver", y = "nr_ints",
          add = "reg.line", conf.int = TRUE, size = 0.4,
          cor.coef = TRUE, cor.method = "pearson", cor.coef.coord = c(0, 50),
          cor.coef.size = 3.5,  cor.coeff.args = list(color = "dodgerblue3"),
          xlab = "nr of cells per receiver", 
          ylab = "nr of interactions per cell type pair")+
  ylim(c(0, (max(ipi_df$nr_ints)+20)))+
  xlim(c(0, (max(ipi_df$nr_cells_receiver)+20)))+
  facet_grid(rows = vars(ipi_df[ipi_df$condition == "no cutoff",]$species),
             cols = vars(ipi_df[ipi_df$condition == "no cutoff",]$age))+
  ggtitle("no cutoff")



ggscatter(ipi_df[ipi_df$condition == "no pre-processing steps",],
          x = "nr_cells_emitter", y = "nr_ints",
          add = "reg.line", conf.int = TRUE, size = 0.4,
          cor.coef = TRUE, cor.method = "pearson",  cor.coef.coord = c(0, 50),
          cor.coef.size = 3.5,  cor.coeff.args = list(color = "dodgerblue3"),
          xlab = "nr of cells per emitter", 
          ylab = "nr of interactions per cell type pair")+
  ylim(c(0, (max(ipi_df$nr_ints)+20)))+
  xlim(c(0, (max(ipi_df$nr_cells_emitter)+20)))+
  facet_grid(rows = vars(ipi_df[ipi_df$condition == "no pre-processing steps",]$species),
             cols = vars(ipi_df[ipi_df$condition == "no pre-processing steps",]$age))+
  ggtitle("no pre-processing steps")

ggscatter(ipi_df[ipi_df$condition == "no pre-processing steps",],
          x = "nr_cells_receiver", y = "nr_ints",
          add = "reg.line", conf.int = TRUE, size = 0.4,
          cor.coef = TRUE, cor.method = "pearson", cor.coef.coord = c(0, 50),
          cor.coef.size = 3.5,  cor.coeff.args = list(color = "dodgerblue3"),
          xlab = "nr of cells per receiver", 
          ylab = "nr of interactions per cell type pair")+
  ylim(c(0, (max(ipi_df$nr_ints)+20)))+
  xlim(c(0, (max(ipi_df$nr_cells_receiver)+20)))+
  facet_grid(rows = vars(ipi_df[ipi_df$condition == "no pre-processing steps",]$species),
             cols = vars(ipi_df[ipi_df$condition == "no pre-processing steps",]$age))+
  ggtitle("no pre-processing steps")
```

```{r}

ggscatter(idi_df[idi_df$condition == "all preprocessing steps",],
          x = "nr_cells", y = "nr_ints",
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          cor.coef.size = 3.5,  cor.coeff.args = list(color = "dodgerblue3"),
          xlab = "nr of cells per cell type", 
          ylab = "nr of interactions per cell type")+
  ylim(c(0, (max(idi_df$nr_ints)+50)))+
  xlim(c(0, (max(idi_df$nr_cells)+50)))+
  facet_grid(rows = vars(idi_df[idi_df$condition == "all preprocessing steps",]$species),
             cols = vars(idi_df[idi_df$condition == "all preprocessing steps",]$age))+
  ggtitle("all pre-processing steps")

ggscatter(idi_df[idi_df$condition == "no rank level",],
          x = "nr_cells", y = "nr_ints",
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          cor.coef.size = 3.5,  cor.coeff.args = list(color = "dodgerblue3"),
          xlab = "nr of cells per emitter", 
          ylab = "nr of interactions per cell type")+
  ylim(c(0, (max(idi_df$nr_ints)+50)))+
  xlim(c(0, (max(idi_df$nr_cells)+50)))+
  facet_grid(rows = vars(idi_df[idi_df$condition == "no rank level",]$species),
             cols = vars(idi_df[idi_df$condition == "no rank level",]$age))+
  ggtitle("no rank level")

ggscatter(idi_df[idi_df$condition == "no downsampling",],
          x = "nr_cells", y = "nr_ints",
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          cor.coef.size = 3.5,  cor.coeff.args = list(color = "dodgerblue3"),
          xlab = "nr of cells per emitter", 
          ylab = "nr of interactions per cell type")+
  ylim(c(0, (max(idi_df$nr_ints)+50)))+
  xlim(c(0, (max(idi_df$nr_cells)+50)))+
  facet_grid(rows = vars(idi_df[idi_df$condition == "no downsampling",]$species),
             cols = vars(idi_df[idi_df$condition == "no downsampling",]$age))+
  ggtitle("no downsampling")

ggscatter(idi_df[idi_df$condition == "no cutoff",],
          x = "nr_cells", y = "nr_ints",
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson", cor.coef.coord = c(0, 50),
          cor.coef.size = 3.5,  cor.coeff.args = list(color = "dodgerblue3"),
          xlab = "nr of cells per emitter", 
          ylab = "nr of interactions per cell type pair")+
  ylim(c(0, (max(idi_df$nr_ints)+50)))+
  xlim(c(0, (max(idi_df$nr_cells)+50)))+
  facet_grid(rows = vars(idi_df[idi_df$condition == "no cutoff",]$species),
             cols = vars(idi_df[idi_df$condition == "no cutoff",]$age))+
  ggtitle("no cutoff")

ggscatter(idi_df[idi_df$condition == "no pre-processing steps",],
          x = "nr_cells", y = "nr_ints",
          add = "reg.line", conf.int = TRUE,  cor.coef.coord = c(0, 50),
          cor.coef.size = 3.5,  cor.coeff.args = list(color = "dodgerblue3"),
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "nr of cells per emitter", 
          ylab = "nr of interactions per cell type")+
  ylim(c(0, (max(idi_df$nr_ints)+50)))+
  xlim(c(0, (max(idi_df$nr_cells)+50)))+
  facet_grid(rows = vars(idi_df[idi_df$condition == "no pre-processing steps",]$species),
             cols = vars(idi_df[idi_df$condition == "no pre-processing steps",]$age))+
  ggtitle("no pre-processing steps")
```

```{r}

ggdf_list <- list()

for(i in 1:length(cci_pca_list)){
  ggdf_list[[i]] <- cci_pca_list[[i]][[2]]

  name <- paste0(ggdf_list[[i]]$species[1], "_", ggdf_list[[i]]$age[1], "_", ggdf_list[[i]]$condition[1])
  print(name)
  names(ggdf_list)[i] <- name
}

ggdf_df <- bind_rows(ggdf_list)

ggdf_df$condition <- factor(ggdf_df$condition, levels = levs)
ggdf_df$species <- factor(ggdf_df$species, levels = names(col_spc))

```

```{r}

ggplot(ggdf_df[ggdf_df$age == "yng",], aes(x = PC1, y = PC2, color = species))+
  geom_point()+
  theme_classic()+
  scale_color_manual(values = col_spc)+
  #xlab(paste0("PC1 [", ggdf_df$PC1_var, "%]"))+
  #ylab(paste0("PC2 [", ggdf_df$PC2_var, "%]"))+
  #theme(axis.text = element_blank(),
  #      axis.ticks = element_blank())+
  facet_grid(cols = vars(ggdf_df[ggdf_df$age == "yng",]$condition),
             rows = vars(ggdf_df[ggdf_df$age == "yng",]$species))+
  theme(strip.text.x = element_text(angle = 90))

ggplot(ggdf_df[ggdf_df$age == "old",], aes(x = PC1, y = PC2, color = species))+
  geom_point()+
  theme_classic()+
  scale_color_manual(values = col_spc)+
  #xlab(paste0("PC1 [", ggdf_df$PC1_var, "%]"))+
  #ylab(paste0("PC2 [", ggdf_df$PC2_var, "%]"))+
  #theme(axis.text = element_blank(),
  #      axis.ticks = element_blank())+
  facet_grid(cols = vars(ggdf_df[ggdf_df$age == "old",]$condition),
             rows = vars(ggdf_df[ggdf_df$age == "old",]$species))+
  theme(strip.text.x = element_text(angle = 90))

```


