---
title: "preprocessing_summary"
author: "Amy Danson, Lea Wölbert"
date: '2022-09-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

QC summary report for all objects at once.
Some operations from the scripts must be repeated to generate relevant plots,
but any new objects cannot be saved from an .Rmd script.

#### Load libraries, source code 

```{r load,  message = FALSE}
library(SingleCellExperiment, quietly = TRUE) 
library(DropletUtils, quietly = TRUE) 
library(tidyverse, quietly = TRUE) 
library(scater, quietly = TRUE) 
library(scuttle, quietly = TRUE) 
library(scran, quietly = TRUE) 
set.seed(37)
```

```{r load_snakemake, message = FALSE}

sce_01_path <- snakemake@input[["sce_01_path"]]

metadata <- read.csv(file = snakemake@params[["metadata"]], 
                     head = TRUE, 
                     sep = ",", 
                     check.names=FALSE, 
                     stringsAsFactors=FALSE, 
                     as.is=TRUE, 
                     colClasses = "character")

individuals <- snakemake@params[["individuals"]]

nr_hvgs <- snakemake@params[["nr_hvgs"]]
cutoff_sum <- snakemake@params[["cutoff_sum"]]
cutoff_detected <- snakemake@params[["cutoff_detected"]]
cutoff_mitos <- snakemake@params[["cutoff_mitos"]]
color_tables <- snakemake@params[["color_tables"]]

```

```{r}
source(file = "../../source/colors.R")
```

# QC

Check Quality per sample.

```{r fig.width = 14}

sce_list_01 <- list()

species <- c("mmus", "mspr", "mcas", "mcar")

for(s in species){
  for(i in individuals){
    if(grepl(s, i) == TRUE){
      sce_list_01[[i]] <- readRDS(file = paste0(sce_01_path, "/", s,
                                                "/sce_", i, "-01"))
    }
  }
}

qcdf_list_01 <- lapply(sce_list_01, function(sce){
  
  mito_genes <- grep("mt-", rownames(sce))

  qcdf <- perCellQCMetrics(sce, subsets=list(Mito=mito_genes))
  qcdf$Object_ID <- sce$Object_ID
  qcdf$Species_ID <- sce$Species_ID
  qcdf$Age <- sce$Age
  qcdf$Batch_exp_day <- sce$Batch_exp_day
  qcdf$Batch_sequencing <- sce$Batch_sequencing
  qcdf$Date_collected <- sce$Date_collected
  qcdf$Species <- sce$Species
  qcdf$Fraction <- sce$Fraction
  qcdf$Keep_sample <- sce$Keep_sample

  sum_out <- qcdf$sum < cutoff_sum 
  det_out <- qcdf$detected < cutoff_detected 
  mito_out <- qcdf$subsets_Mito_percent > cutoff_mitos
  
  remove_pos <- sum_out | det_out | mito_out
  qcdf$removed <- remove_pos
  
  return(qcdf)
})

qcdf_gg <- DataFrame()

for(i in qcdf_list_01){
  qcdf_gg <- rbind(qcdf_gg, i)
}
qcdf_gg <- as.data.frame(qcdf_gg)

# by Sample
ggplot(qcdf_gg, aes(x = Object_ID, y = sum,
                    color = removed, alpha = Keep_sample))+
  geom_jitter(size = 0.1, alpha = 50)+
  geom_violin(color = "black", alpha = 0, draw_quantiles = 0.5)+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 120000))+
  ggtitle(paste("cutoff sum = ", cutoff_sum))+ 
  scale_y_log10()+
  scale_alpha_discrete("Samples to keep",
                       range = c("FALSE" = 0.02, "TRUE" = 0.7))+
  scale_color_manual("Cells to remove", 
                     values = c("TRUE" = "orange", "FALSE" = "grey80"))
  

ggplot(qcdf_gg, aes(x = Object_ID, y = detected, 
                    color = removed, alpha = Keep_sample))+
  geom_jitter(size = 0.1, alpha = 50)+
  geom_violin(color = "black", alpha = 0, draw_quantiles = 0.5)+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 10000))+
  ggtitle(paste("cutoff detected = ", cutoff_detected))+ 
  scale_y_log10()+
  scale_alpha_discrete("Samples to keep",
                       range = c("FALSE" = 0.02, "TRUE" = 0.7))+
  scale_color_manual("Cells to remove", 
                     values = c("TRUE" = "orange", "FALSE" = "grey80"))

# by Species_ID
ggplot(qcdf_gg[qcdf_gg$Keep_sample == TRUE,],
       aes(x = Species_ID, y = sum, color = removed))+
  geom_jitter(size = 0.1, alpha = 50)+
  geom_violin(color = "black", alpha = 0, draw_quantiles = 0.5)+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 120000))+
  ggtitle(paste("cutoff sum = ", cutoff_sum))+ 
  scale_y_log10() +
  scale_color_manual("Cells to remove", 
                     values = c("TRUE" = "orange", "FALSE" = "grey80"))

ggplot(qcdf_gg[qcdf_gg$Keep_sample == TRUE,], 
       aes(x = Species_ID, y = detected, color = removed))+
  geom_jitter(size = 0.1, alpha = 50)+
  geom_violin(color = "black", alpha = 0, draw_quantiles = 0.5)+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 10000))+
  ggtitle(paste("cutoff detected = ", cutoff_detected))+ 
  scale_y_log10()+
  scale_color_manual("Cells to remove",
                     values = c("TRUE" = "orange", "FALSE" = "grey80"))

# by Age
ggplot(qcdf_gg[qcdf_gg$Keep_sample == TRUE,], 
       aes(x = Age, y = sum, color = removed))+
  geom_jitter(size = 0.1, alpha = 50)+
  geom_violin(color = "black", alpha = 0, draw_quantiles = 0.5)+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 120000))+
  ggtitle(paste("cutoff sum = ", cutoff_sum))+ 
  scale_y_log10()+
  scale_color_manual("Cells to remove", 
                     values = c("TRUE" = "orange", "FALSE" = "grey80")) 

ggplot(qcdf_gg[qcdf_gg$Keep_sample == TRUE,], 
       aes(x = Age, y = detected, color = removed))+
  geom_jitter(size = 0.1, alpha = 50)+
  geom_violin(color = "black", alpha = 0, draw_quantiles = 0.5)+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 10000))+
  ggtitle(paste("cutoff detected = ", cutoff_detected))+ 
  scale_y_log10() +
  scale_color_manual("Cells to remove", 
                     values = c("TRUE" = "orange", "FALSE" = "grey80"))

# by Fraction
ggplot(qcdf_gg[qcdf_gg$Keep_sample == TRUE,], 
       aes(x = Fraction, y = sum, color = removed))+
  geom_jitter(size = 0.1, alpha = 50)+
  geom_violin(color = "black", alpha = 0, draw_quantiles = 0.5)+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 120000))+
  ggtitle(paste("cutoff sum = ", cutoff_sum))+ 
  scale_y_log10() +
  scale_color_manual("Cells to remove",
                     values = c("TRUE" = "orange", "FALSE" = "grey80"))

ggplot(qcdf_gg[qcdf_gg$Keep_sample == TRUE,], 
       aes(x = Fraction, y = detected, color = removed))+
  geom_jitter(size = 0.1, alpha = 50)+
  geom_violin(color = "black", alpha = 0, draw_quantiles = 0.5)+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 10000))+
  ggtitle(paste("cutoff detected = ", cutoff_detected))+ 
  scale_y_log10() +
  scale_color_manual("Cells to remove", 
                     values = c("TRUE" = "orange", "FALSE" = "grey80"))

# by Batch_exp_day
ggplot(qcdf_gg[qcdf_gg$Keep_sample == TRUE,], 
       aes(x = Batch_exp_day, y = sum, color = removed))+
  geom_jitter(size = 0.1, alpha = 50)+
  geom_violin(color = "black", alpha = 0, draw_quantiles = 0.5)+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 120000))+
  ggtitle(paste("cutoff sum = ", cutoff_sum)) + 
  scale_y_log10() +
  scale_color_manual("Cells to remove",
                     values = c("TRUE" = "orange", "FALSE" = "grey80"))

ggplot(qcdf_gg[qcdf_gg$Keep_sample == TRUE,], 
       aes(x = Batch_exp_day, y = detected, color = removed))+
  geom_jitter(size = 0.1, alpha = 50)+
  geom_violin(color = "black", alpha = 0, draw_quantiles = 0.5)+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 10000))+
  ggtitle(paste("cutoff detected = ", cutoff_detected))+ 
  scale_y_log10() +
  scale_color_manual("Cells to remove", 
                     values = c("TRUE" = "orange", "FALSE" = "grey80"))

# by Batch_sequencing
ggplot(qcdf_gg[qcdf_gg$Keep_sample == TRUE,], 
       aes(x = Batch_sequencing, y = sum, color = removed))+
  geom_jitter(size = 0.1, alpha = 50)+
  geom_violin(color = "black", alpha = 0, draw_quantiles = 0.5)+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 120000))+
  ggtitle(paste("cutoff sum = ", cutoff_sum))+ 
  scale_y_log10()+
  scale_color_manual("Cells to remove",
                     values = c("TRUE" = "orange", "FALSE" = "grey80")) 

ggplot(qcdf_gg[qcdf_gg$Keep_sample == TRUE,], aes(x = Batch_sequencing, 
                                                  y = detected, 
                                                  color = removed))+
  geom_jitter(size = 0.1, alpha = 50)+
  geom_violin(color = "black", alpha = 0, draw_quantiles = 0.5)+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 10000))+
  ggtitle(paste("cutoff detected = ", cutoff_detected))+ 
  scale_y_log10() +
  scale_color_manual("Cells to remove",
                     values = c("TRUE" = "orange", "FALSE" = "grey80"))

# by Date_collected
ggplot(qcdf_gg[qcdf_gg$Keep_sample == TRUE,], aes(x = Date_collected, 
                                                  y = sum, color = removed))+
  geom_jitter(size = 0.1, alpha = 50)+
  geom_violin(color = "black", alpha = 0, draw_quantiles = 0.5)+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 120000))+
  ggtitle(paste("cutoff sum = ", cutoff_sum))+ 
  scale_y_log10()+
  scale_color_manual("Cells to remove", 
                     values = c("TRUE" = "orange", "FALSE" = "grey80")) 

ggplot(qcdf_gg[qcdf_gg$Keep_sample == TRUE,], aes(x = Date_collected, 
                                                  y = detected, 
                                                  color = removed))+
  geom_jitter(size = 0.1, alpha = 50)+
  geom_violin(color = "black", alpha = 0, draw_quantiles = 0.5)+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 10000))+
  ggtitle(paste("cutoff detected = ", cutoff_detected))+ 
  scale_y_log10() +
  scale_color_manual("Cells to remove", 
                     values = c("TRUE" = "orange", "FALSE" = "grey80"))
```

```{r}
sessionInfo()
```