---
title: "cci_metrics_qc_summary"
author: "Lea Wölbert"
date: '2023-07-17'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Load libraries, source code 

```{r seed, message = FALSE}
set.seed(37)
```

```{r load, message = FALSE}
library(scran)
library(scater)
library(ggpubr)
library(tidyverse)
```

```{r sources, message = FALSE}
source(file = "../../source/plotting.R")
```

```{r load_objects}

#load SCE objects
ident_info_p <- snakemake@input[["ident_info"]]
sce_p <- snakemake@input[["sce_input"]]

ident_info_list <- list()
sce_list <- list()

for(i in 1:length(ident_info_p)){
  ident_info_list[[i]] <- readRDS(file = ident_info_p[[i]])
  sce_list[[i]] <- readRDS(file = sce_p[[i]])
}

```

```{r colors, message = FALSE}
colors_path <- snakemake@params[["colors_path"]]
source(file = "../../source/colors.R")
col_cts <- c(col_cts_hsc, col_cts_str)
```

Prepare data

```{r}
# o for overview
temp_list <- list()
for(i in 1:length(ident_info_list)){
  temp_list[[i]] <- ident_info_list[[i]]$overview
}
idio_df <- bind_rows(temp_list)
idio_df$name <- paste0(idio_df$species, "_", idio_df$age)
head(idio_df)
```

Calculate Stats

```{r}

qcdf_list <- lapply(sce_list, function(sce){
  
  qcdf_counts <- perCellQCMetrics(sce, assay.type = "counts")
  qcdf_downsm <- perCellQCMetrics(sce, assay.type = "downsampled")
  
  qcdf_counts$Object_ID <- sce$Object_ID
  qcdf_downsm$Object_ID <- sce$Object_ID

  qcdf_counts$Species_ID <- sce$Species_ID
  qcdf_downsm$Species_ID <- sce$Species_ID

  qcdf_counts$Age_ID <- sce$Age_ID
  qcdf_downsm$Age_ID <- sce$Age_ID
  
  qcdf_counts$Identity <- sce$Identity
  qcdf_downsm$Identity <- sce$Identity
  
  qcdf_counts$Status <- "before downsampling"
  qcdf_downsm$Status <- "after downsampling"
  
  qcdf_both <- rbind(qcdf_counts, qcdf_downsm)

  return(qcdf_both)
}) 

qcdf_gg <- DataFrame()
for(i in qcdf_list){
  qcdf_gg <- rbind(qcdf_gg, i)
}
qcdf_gg <- as.data.frame(qcdf_gg)

qcdf_gg$name <- paste0(qcdf_gg$Species_ID, "_", qcdf_gg$Age_ID)
```

Get nr of cells from corresponding SCE objects

```{r}

# since the SCE list is not named by sample name, cbind
# then separate by sample name again, just to make sure 

sce_all <- sce_list[[1]]
for(i in 2:length(sce_list)){
  sce_all <- cbind(sce_all, sce_list[[i]])
}
sce_all$name <- paste0(sce_all$Species_ID, "_", sce_all$Age_ID)

unique(sce_all$Age_ID)
unique(sce_all$Species_ID)
unique(sce_all$name)

names <- unique(sce_all$name)

idio_df$nr_cells <- vector(length = nrow(idio_df))

for(i in names){
  sce_temp <- sce_all[,sce_all$name == i]
  nr_cells <- table(sce_temp$Identity)
  
  print(i)
  print(nr_cells)
  
  for(j in names(nr_cells)){
    idio_df[idio_df$name == i,]$nr_cells[idio_df[
      idio_df$name == i,]$identity == j] <- nr_cells[names(nr_cells) == j]
  }
}
print(head(idio_df))
```

Factor cell types, ages, and species

```{r}

# cell types
idio_df$identity <- factor(idio_df$identity, levels = names(col_cts)[
  names(col_cts) %in% idio_df$identity])
qcdf_gg$Identity <- factor(qcdf_gg$Identity, levels = names(col_cts)[
  names(col_cts) %in% qcdf_gg$Identity])

# age
idio_df$age <- factor(idio_df$age, levels = c("yng", "old"))
qcdf_gg$Age_ID <- factor(qcdf_gg$Age_ID, levels = c("yng", "old"))

# species
species <- c("mmus", "mcas", "mspr", "mcar")
idio_df$species <- factor(idio_df$species, levels = species)
qcdf_gg$Species_ID <- factor(qcdf_gg$Species_ID, species)

# name
conds <- c("mmus_yng", "mmus_old", "mcas_yng", "mcas_old",
           "mspr_yng", "mspr_old", "mcar_yng", "mcar_old")
idio_df$name <- factor(idio_df$name, levels = conds)
```

Prepare downsampled counts

```{r}
qcdf_gg_ds <- qcdf_gg[qcdf_gg$Status == "after downsampling",]

max_qcdf_gg_ds <- 4000 # this removes two cells in mcar

qcdf_gg_ds_emis <- qcdf_gg_ds[qcdf_gg_ds$Identity %in% names(col_cts_str),]
qcdf_gg_ds_recs <- qcdf_gg_ds[qcdf_gg_ds$Identity %in% names(col_cts_hsc),]
```

# Important Plots

```{r, fig.width = 4, fig.height = 4}
idio_df_emi <- idio_df[idio_df$assignment == "emitter",]
idio_df_rec <- idio_df[idio_df$assignment == "receiver",]

ggplot(idio_df, 
       aes(x = name, y = nr_ints, color = age))+
  ggbeeswarm::geom_quasirandom(size = 2.5, alpha = 0.9)+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90))+
  scale_color_manual("Age", values = col_age)+
  ylab("Nr of detected interactions per cell type")+
  stat_compare_means(
    comparisons = list(c("mmus_yng", "mmus_old"),
                       c("mcas_yng", "mcas_old"),
                       c("mspr_yng", "mspr_old"),
                       c("mcar_yng", "mcar_old")),
    test = 'wilcox', p.adjust.method = "BH", hide.ns = TRUE,
    aes(label = after_stat(p.signif)))+
  ylim(c(0, 280))

ggplot(idio_df_emi, 
       aes(x = name, y = nr_ints, color = age))+
  ggbeeswarm::geom_quasirandom(size = 2.5, alpha = 0.9)+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90))+
  scale_color_manual("Age", values = col_age)+
  ylab("Nr of detected interactions per cell type")+
  stat_compare_means(
    comparisons = list(c("mmus_yng", "mmus_old"),
                       c("mcas_yng", "mcas_old"),
                       c("mspr_yng", "mspr_old"),
                       c("mcar_yng", "mcar_old")),
    test = 'wilcox', p.adjust.method = "BH", hide.ns = TRUE,
    aes(label = after_stat(p.signif)))+
  ylim(c(0, 280))+
  ggtitle("Emitters")

ggplot(idio_df_rec, 
       aes(x = name, y = nr_ints, color = age))+
  ggbeeswarm::geom_quasirandom(size = 2.5, alpha = 0.9)+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90))+
  scale_color_manual("Age", values = col_age)+
  ylab("Nr of detected interactions per cell type")+
  stat_compare_means(
    comparisons = list(c("mmus_yng", "mmus_old"),
                       c("mcas_yng", "mcas_old"),
                       c("mspr_yng", "mspr_old"),
                       c("mcar_yng", "mcar_old")),
    test = 'wilcox', p.adjust.method = "BH", hide.ns = TRUE,
    aes(label = after_stat(p.signif)))+
  ylim(c(0, 280))+
  ggtitle("Receivers")
```

```{r, fig.width = 4, fig.height = 5}

conds_temp_yng <- c("mmus_yng", "mcas_yng", "mspr_yng", "mcar_yng")
conds_temp_old <- c("mmus_old", "mcas_old", "mspr_old", "mcar_old")

idio_df_yng <- idio_df[idio_df$age == "yng",]
idio_df_yng$name_temp <- factor(idio_df_yng$name, levels = conds_temp_yng)

idio_df_old <- idio_df[idio_df$age == "old",]
idio_df_old$name_temp <- factor(idio_df_old$name, levels = conds_temp_old)

ggplot(idio_df_yng, 
       aes(x = name_temp, y = nr_ints, color = age))+
  ggbeeswarm::geom_quasirandom(size = 2.5, alpha = 0.9)+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90),
        legend.position = "none")+
  scale_color_manual("Age", values = col_age)+
  ylab("Nr of detected interactions per cell type")+
  stat_compare_means(test = 'kruskal.test', p.adjust.method = "BH",
                     label.y = 0.9)+
  stat_compare_means(
    comparisons = list(c("mmus_yng", "mcas_yng"), c("mmus_yng", "mspr_yng"),
                       c("mmus_yng", "mcar_yng"), c("mcas_yng", "mspr_yng"),
                       c("mcas_yng", "mcar_yng"), c("mspr_yng", "mcar_yng")),
    test = 'dunn_test', p.adjust.method = "BH",
    hide.ns = TRUE, aes(label = after_stat(p.signif)))+
  ylim(c(0, 280))+
  xlab("Species")

ggplot(idio_df_old, 
       aes(x = name_temp, y = nr_ints, color = age))+
  ggbeeswarm::geom_quasirandom(size = 2.5, alpha = 0.9)+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90),
        legend.position = "none")+
  scale_color_manual("Age", values = col_age)+
  ylab("Nr of detected interactions per cell type")+
  stat_compare_means(test = 'kruskal.test', p.adjust.method = "BH", 
                     label.y = 0.9)+
  stat_compare_means(
    comparisons = list(c("mmus_old", "mcas_old"), c("mmus_old", "mspr_old"),
                       c("mmus_old", "mcar_old"), c("mcas_old", "mspr_old"),
                       c("mcas_old", "mcar_old"), c("mspr_old", "mcar_old")),
    test = 'dunn_test', p.adjust.method = "BH",
    hide.ns = TRUE, aes(label = after_stat(p.signif)))+
  ylim(c(0, 280))+
  xlab("Species")
```

# QC Plots

```{r}

ggplot(idio_df, 
       aes(x = identity, y = nr_ints, color = name))+
  ggbeeswarm::geom_quasirandom()+
  geom_boxplot(alpha = 0, color = "grey30")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_discrete("Condition")+
  ylim(c(0, max(idio_df$nr_ints)))+
  xlab("Cell types")+
  ylab("Nr of interactions per cell type")+
  ggtitle("all conditions")

ggplot(idio_df, 
       aes(x = identity, y = nr_ints, color = nr_cells))+
  ggbeeswarm::geom_quasirandom()+
  geom_boxplot(alpha = 0, color = "grey30")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_continuous("nr cells/cell type")+
  ylim(c(0, max(idio_df$nr_ints)))+
  xlab("Cell types")+
  ylab("Nr of interactions per cell type")+
  ggtitle("all conditions")
```

```{r}

ggplot(idio_df, aes(x = nr_cells, y = nr_ints, color = identity))+
  geom_point()+
  theme_classic()+
  ylim(c(0, (max(idio_df$nr_ints)+20)))+
  xlim(c(0, (max(idio_df$nr_cells)+20)))+
  scale_color_manual("Cell types", values = col_cts)+
  ylab("Nr of interactions per cell type pair")+
  theme(legend.position = "none")+
  geom_smooth(method = lm, se = FALSE)

ggplot(idio_df, aes(x = nr_cells, y = nr_ints, color = species))+
  geom_point()+
  theme_classic()+
  ylim(c(0, (max(idio_df$nr_ints)+20)))+
  xlim(c(0, (max(idio_df$nr_cells)+20)))+
  scale_color_manual("Species", values = col_spc)+
  ylab("Nr of interactions per cell type pair")+
  theme(legend.position = "none")+
  geom_smooth(method = lm, se = FALSE)

ggplot(idio_df, aes(x = nr_cells, y = nr_ints, color = age))+
  geom_point()+
  theme_classic()+
  ylim(c(0, (max(idio_df$nr_ints)+20)))+
  xlim(c(0, (max(idio_df$nr_cells)+20)))+
  scale_color_manual("Age", values = col_age)+
  ylab("Nr of interactions per cell type pair")+
  theme(legend.position = "none")+
  geom_smooth(method = lm, se = FALSE)

```

```{r}
ggscatter(idio_df, x = "nr_cells", y = "nr_ints",
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "nr of cells per cell type", 
          ylab = "nr of interactions per cell type")+
  ylim(c(0, (max(idio_df$nr_ints)+20)))+
  xlim(c(0, (max(idio_df$nr_cells)+20)))

ggscatter(idio_df[idio_df$assignment == "emitter",], x = "nr_cells", 
          y = "nr_ints", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "nr of cells per cell type", 
          ylab = "nr of interactions per cell type")+
  ylim(c(0, (max(idio_df$nr_ints)+20)))+
  xlim(c(0, (max(idio_df$nr_cells)+20)))

ggscatter(idio_df[idio_df$assignment == "receiver",], x = "nr_cells", 
          y = "nr_ints", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "nr of cells per cell type", 
          ylab = "nr of interactions per cell type")+
  ylim(c(0, (max(idio_df$nr_ints)+20)))+
  xlim(c(0, (max(idio_df$nr_cells)+20)))

```

```{r}
sessionInfo()
```