---
title: "Report on age integration"
author: "Lea Wölbert"
date: '2023-06-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Report on integrated datasets.

#### Load libraries, source code, objects

```{r seed,  message = FALSE}
set.seed(37)
```

```{r source,  message = FALSE}
source(snakemake@params[["plotting"]])
```

```{r load_objects, message = FALSE}
sce_input <- base::readRDS(file = snakemake@input[["sce_input"]])
sce_input
```

```{r colors, message = FALSE}
colors_ref_path <- snakemake@params[["colors_ref_path"]]
source(snakemake@params[["colors"]])
```

# UMAPs

```{r umap_function}

make_plots <- function(sce, title){
  
  col_cts_baccin_clst <- col_cts_ref[
    base::match(base::unique(sce$baccin_celltype_scmapclust), 
                names(col_cts_ref))]
  
  col_cts_dahlin_clst <- col_cts_ref[
    base::match(base::unique(sce$dahlin_celltype_scmapclust), 
                names(col_cts_ref))]
  
  col_cts_dolgalev_clst <- col_cts_ref[
    base::match(base::unique(sce$dolgalev_celltype_scmapclust), 
                names(col_cts_ref))]
  
  if(title == "species"){title <- base::paste(title, 
                                              sce$Species_ID[1])}
  if(title == "condition"){title <- base::paste(title, 
                                                sce$Species_ID[1], 
                                                sce$Age_ID[1])}
  
  # own function
  plot_1 <- umap_base(sce, color_by = "baccin_celltype_scmapclust")+ 
    ggplot2::ggtitle(title)+
    ggplot2::scale_color_manual("baccin_celltype_scmapclust",
                                values = col_cts_baccin_clst)
  plot_1l <- umap_legend(sce, color_by = "baccin_celltype_scmapclust")+
    ggplot2::scale_color_manual("baccin_celltype_scmapclust", 
                                values = col_cts_baccin_clst)
  legend_1 <- ggpubr::get_legend(plot_1l)
  
  plot_2 <- umap_base(sce, color_by = "dahlin_celltype_scmapclust")+ 
    ggplot2::ggtitle(title)+
    ggplot2::scale_color_manual("dahlin_celltype_scmapclust", 
                                values = col_cts_dahlin_clst)
  plot_2l <- umap_legend(sce, color_by = "dahlin_celltype_scmapclust")+
    ggplot2::scale_color_manual("dahlin_celltype_scmapclust", 
                                values = col_cts_dahlin_clst)
  legend_2 <- ggpubr::get_legend(plot_2l)

  plot_3 <- umap_base(sce, color_by = "dolgalev_celltype_scmapclust")+ 
    ggplot2::ggtitle(title)+
    ggplot2::scale_color_manual("dolgalev_celltype_scmapclust", 
                                values = col_cts_dolgalev_clst)
  plot_3l <- umap_legend(sce, color_by = "dolgalev_celltype_scmapclust")+
    ggplot2::scale_color_manual("dolgalev_celltype_scmapclust", 
                                values = col_cts_dolgalev_clst)
  legend_3 <- ggpubr::get_legend(plot_3l)
  
  plot_4 <- umap_base_l(sce, color_by = "Age_ID")+ 
    ggplot2::ggtitle(title)
  plot_5 <- umap_base_l(sce, color_by = "Species_ID")+ 
    ggplot2::ggtitle(title)
  plot_6 <- umap_base_l(sce, color_by = "Fraction_ID")+ 
    ggplot2::ggtitle(title)
  
  PLOT_1 <- ggpubr::ggarrange(plot_1, legend_1)
  PLOT_2 <- ggpubr::ggarrange(plot_2, legend_2)
  PLOT_3 <- ggpubr::ggarrange(plot_3, legend_3)

return(list(PLOT_1, PLOT_2, PLOT_3, plot_4, plot_5, plot_6))
}
```

```{r make_plots}
plotlist_species <- make_plots(sce_input, title = "condition")
plotlist_species
```

```{r session_info}
utils::sessionInfo()
```