---
title: "permutation_report"
author: "Lea Wölbert"
date: '2023-08-17'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Load objects

```{r seed,  message = FALSE}
set.seed(37)
```

```{r load,  message = FALSE}
library(tidyverse)
library(SingleCellExperiment)
```

```{r load_objects}
res_lists <- readRDS(snakemake@input[["res_lists"]])
#res_lists <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/main_analysis/cci_objects/03_cci_analysis/04_pres_age/res_lists_ages_mcar")
sce_yng <-  readRDS(snakemake@input[["sce_yng_input"]])
sce_old <-  readRDS(snakemake@input[["sce_old_input"]])
#sce_yng <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/main_analysis/cci_objects/01_cci_preparation/04_subs/sce_mcar_yng-04")
#sce_old <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/main_analysis/cci_objects/01_cci_preparation/04_subs/sce_mcar_old-04")
iterations <- snakemake@params[["iterations"]]
species_curr <- snakemake@wildcards[["species"]]
```

```{r}
names(res_lists)
names(res_lists[[1]])

#print(head(res_lists[[1]]$res_df))
#print(head(res_lists[[1]]$vis_df))

ctps_of_int <- list("Adipo/CARs&HSCs", "Fibro/Chondro&HSCs", 
                    "Pericytes/Smooth Muscle&HSCs", "Sinusoidal ECs&HSCs",
                    "Adipo/CARs&Lymphoid progs.", 
                    "Fibro/Chondro&Lymphoid progs.", 
                    "Pericytes/Smooth Muscle&Lymphoid progs.", 
                    "Arteriolar/Capillary ECs&Lymphoid progs.",
                    "Arteriolar/Capillary ECs&HSCs.", 
                    "Arteriolar/Capillary ECs&Lymphoid progs.",
                    "Arteriolar/Mixed ECs&HSCs",
                    "Arteriolar/Mixed ECs&Lymphoid progs.",
                    "Adipo/CARs&Activated MPPs", "Fibro/Chondro&Activated MPPs", 
                    "Pericytes/Smooth Muscle&Activated MPPs", "Sinusoidal ECs&Activated MPPs")

ctps_of_int <- ctps_of_int[ctps_of_int %in% names(res_lists)]
ints_of_interest <- list("Kitl_Kit", "Cxcl12_Cxcr4", "Lamb1_Itgb1",
            "Vcam1_Itga4", "Vcam1_Itgb1", "Angpt1_Tek", "Col1a1_Itgb1")

#knitr::knit_exit()
```

```{r}

# ctp <- ctps_of_int[[2]
# int <- "Kitl_Kit"
plotlist <- lapply(ctps_of_int, function(ctp){
  
  vis_df <- res_lists[[ctp]]$vis_df
  res_df <- res_lists[[ctp]]$res_df
  
  res_df <- res_df[res_df$shared == TRUE,]
  
  ints_of_interest <- unique(c(
    ints_of_interest,
    rownames(res_df[order(res_df$p_adj, decreasing = FALSE),])[1:10],
    rownames(res_df[order(abs(res_df$score_delta), decreasing = TRUE),])[1:10]))
  
  ints_of_interest <- ints_of_interest[ints_of_interest %in% rownames(res_df)]
  
  emi <- str_split(ctp, "&")[[1]][1]
  rec <- str_split(ctp, "&")[[1]][2]
  
  nr_emi_yng <- unname(table(sce_yng$Identity)[emi])
  nr_emi_old <- unname(table(sce_old$Identity)[emi])
  
  nr_rec_yng <- unname(table(sce_yng$Identity)[rec])
  nr_rec_old <- unname(table(sce_old$Identity)[rec])
  
  plots <- lapply(ints_of_interest, function(int){
    
    vis_df_temp <- vis_df
    colnames(vis_df_temp)[which(colnames(vis_df_temp) == int)] <- "int"
    
    score_yng <- res_df$score_yng[which(rownames(res_df) == int)]
    score_old <- res_df$score_old[which(rownames(res_df) == int)]
    score_delta <- res_df$score_delta[which(rownames(res_df) == int)]
    p_adj <- res_df$p_adj[which(rownames(res_df) == int)]
    
    max_score_d <- 1
    plot1 <- ggplot(vis_df_temp, aes(x = int))+
      geom_histogram(binwidth = 0.025, fill = "grey80")+
      geom_vline(xintercept = score_delta, color = "orange", linetype="dashed")+
      theme_classic()+
      xlab(paste(int, "Delta Score"))+
      ylab("Frequency")+
      xlim(c(-max_score_d, max_score_d))+
      ggtitle(paste(species_curr, ctp))+
      ylim(c(0, iterations))+
      annotate(x = -(max_score_d-0.1*max_score_d), y = iterations, "text", 
               hjust = 0,
               label = paste("score_yng = ", round(score_yng, digits = 3)))+
      annotate(x = -(max_score_d-0.1*max_score_d),
               y = iterations-0.1*iterations, "text", 
               hjust = 0,
               label = paste("score_old = ", round(score_old, digits = 3)))+
      annotate(x = -(max_score_d-0.1*max_score_d), y = iterations-0.2*iterations, "text",
               hjust = 0,
               label = paste("score_delta = ", round(score_delta, digits = 3)))+
      annotate(x = -(max_score_d-0.1*max_score_d), y = iterations-0.3*iterations, "text", 
               hjust = 0,
               label = paste("p_val_adjusted = ", round(p_adj, digits = 3)))+
      annotate(x = (max_score_d-0.45*max_score_d), y = iterations, "text", 
               hjust = 0,
               label = paste("nr_emi_yng = ", nr_emi_yng))+
      annotate(x = (max_score_d-0.45*max_score_d),
               y = iterations-0.1*iterations, "text", 
               hjust = 0,
               label = paste("nr_emi_old = ", nr_emi_old))+
      annotate(x = (max_score_d-0.45*max_score_d), y = iterations-0.2*iterations, "text",
               hjust = 0,
               label = paste("nr_rec_yng = ", nr_rec_yng))+
      annotate(x = (max_score_d-0.45*max_score_d), y = iterations-0.3*iterations, "text", 
               hjust = 0,
               label = paste("nr_rec_old = ", nr_rec_old))
      
    return(list(int,
                res_df[rownames(res_df) == int,],
                plot1))
  })
  return(list(head(res_df[order(res_df$p_adj, decreasing = FALSE),]), 
              head(res_df[order(abs(res_df$score_delta), decreasing = TRUE),]),
              plots))
})
 
plotlist 

```

The warnings of removed rows are standard in geom_histogram
https://github.com/tidyverse/ggplot2/issues/4200

```{r}
sessionInfo()
```