#!/bin/python 

"""
Info in batch correction methods from:
Luecken et al. "Benchmarking atlas-level data integration in single-cell genomics", Nat Met 2022
Tran, Ang, Chevrier, Zhang et al. "A benchmark of batch effect correction methods for songle-cell RNA sequencing data", Genome Biologz 2020
"""
#-------------------------------------------------------------------------------

import pandas as pd
import numpy as np
import sys 

# paths from config
METADATA_PATH = config["metadata"]["raw"]
OUTPUT_BASE_PATH = config["paths"]["output_dir"]

# objects from config
IDENTIFIERS = config["metadata"]["identifiers"]
METADATA = pd.read_csv(config["metadata"]["raw"])
VALUES =  config["metadata"]["values"]
BATCH_USE = config["metadata"]["batch_use"] # which SCE col to use as batch

#-------------------------------------------------------------------------------

def get_list(metadata, column):
  values = METADATA[column]
  values = values.drop_duplicates()
  values = values.squeeze()
  values = values.tolist()
  return(values)
  
Species_ID = get_list(metadata = METADATA, column = "Species_ID")

# construct paths for all possible outputs/targets, required for rule all
targets = []
for species in Species_ID:
  targets = targets + [OUTPUT_BASE_PATH + "/06_mrge/sce_" + species + "-06"]

print(targets)

#-------------------------------------------------------------------------------

localrules: all  
#
# define rules
rule all: # must contain all possible output paths from all rules
    input:
        targets
        
"""
Merge all datasets into one big dataset, and four species-specific SCE objects
Input data is located in 02_preprocessing/04_norm/
"""
#rule merge_datasets_all:
#    input:
#        sce_04_path = OUTPUT_BASE_PATH + "/04_norm/", 
#    output:
#        sce_06_path = OUTPUT_BASE_PATH + "/06_mrge/" # rest is specified in script
#    params:
#        targets = targets
#    script:
#        if "all" in input:
#        "scripts/06_merge_datasets.R" 

rule merge_datasets_species:
    input: 
        sce_04 = OUTPUT_BASE_PATH + "/04_norm/{species}/"
    output:
        sce_06 = OUTPUT_BASE_PATH + "/06_mrge/sce_{species}-06"
    wildcard_constraints:
        species = "[a-z]+"
    script:
        "scripts/testing_purposes.R" 
  
        
"""
# quick and basic renormalization, scaling, HVG calculation

Scaling improves batch effect removal but worsens bioconservation
HVG selection improves performance but restricts analysis
"""
# quick and basic renormalization, scaling, HVG calculation
#rule renormalize:
#    input:
#        sce_06 = rules.merge_datasets.output + ["sce_{species}-06"]
#    output:
#        sce_07 = OUTPUT_BASE_PATH + "/07_rnrm/sce_{species}-07",
#        hvgs = OUTPUT_BASE_PATH + "/07_rnrm/hvg_{species}-07"
#    params:
#        batch_use = BATCH_USE
#    script:
#        "scripts/07_renormalize.R"

"""
batch correct using MNNcorrect

MNNcorrect is good at recovering DEGs from batch corrected data and bioconservation,
but slow and does not perform well on batch correction 
Requires shared cell types between batches but no labels
(fastMNN) seems to balance vatch effect removal and bioconservation
"""
#if config["run_mnncorrect"]:
#    rule renormalize:
#        input:
#            sce_07 = rules.renormalize.output 
#        output:
#            sce_08 = OUTPUT_BASE_PATH + "/08_mnncorrect/sce_{species}_correctedby_" + BATCH_USE + "-08"
#        params:
#            hvgs_for_batch_correction = config["hvgs_for_batch_correction"]
#        script:
#            "scripts/08_mnncorrect.R"

"""
batch correct using Seurat3

Seurat3 is good at batch corection and among best for multiple batch integration
but not great at recovering DEGs from batch corrected data
unbalanced towards stronger batch effect removal, but successful at removing species batch effects
Requires shared cell types between batches but no labels, scaling little effect
"""
#if config["run_seurat3"]:
#    rule renormalize:
#        input:
#            sce_07 = rules.renormalize.output 
#        output:
#            sce_08 = OUTPUT_BASE_PATH + "/08_seurat3/sce_{species}_correctedby_" + BATCH_USE + "-08"
#        params:
#            hvgs_for_batch_correction = config["hvgs_for_batch_correction"]
#        script:
#            "scripts/08_seurat3.R"

"""
batch correct using scMerge

scMerge and among best for multiple batch integration,
is ok but not great at batch corection and recovering DEGs
seems balanced but is also slow
"""
#if config["run_scmerge"]:
#    rule renormalize:
#        input:
#            sce_07 = rule.renormalize.output 
#        output:
#            sce_08 = OUTPUT_BASE_PATH + "/08_scmerge/sce_{species}_correctedby_" + BATCH_USE + "-08"
#        params:
#            hvgs_for_batch_correction = config["hvgs_for_batch_correction"]
#        script:
#            "scripts/08_scmerge.R"
