---
title: "integration_report"
author: "Amy Danson, Lea Wölbert"
date: '2022-10-12'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Summary report for data integration.

#### Load libraries, source code 

```{r load,  message = FALSE}

library(DropletUtils, quietly = TRUE) 
library(scater, quietly = TRUE) 
library(scuttle, quietly = TRUE) 
library(scran, quietly = TRUE) 
library(tidyverse, quietly = TRUE) 

```

```{r load_code, message = FALSE}

source(file = "../source/colors.R")

sce_06_path <- snakemake@input[["sce_06_path"]] # before renormalization
sce_07_path <- snakemake@input[["sce_07_path"]] # before correction
sce_08mnn_path <- snakemake@input[["sce_08mnn_path"]] # after correction

nr_hvgs <- snakemake@params[["nr_hvgs"]]
species_all <- snakemake@params[["species_all"]]
batches <- snakemake@params[["batches"]]

print(nr_hvgs)
print(species_all)
print(batches)

```

# Before batch correction

```{r}

sce_list_06 <- list()
for(s in species_all){
  sce_list_06[[s]] <- readRDS(file = paste0(sce_06_path, 
                                            "/sce_", s, "-06"))
}
print(sce_list_06)

sce_list_07 <- list()
for(b in batches){
  for(s in species_all){
    sce_list_07[[b]][[s]] <- readRDS(file = paste0(sce_07_path, 
                                                   "/sce_", s, "_", b, "-07"))
  }
}  
print(sce_list_07)

sce_list_08mnn <- list()
for(b in batches){
  for(s in species_all){
    sce_list_08mnn[[b]][[s]] <- readRDS(file = paste0(sce_08mnn_path,
                                                      "/sce_", s, "_", b, 
                                                      "-08"))
  }
}   
print(sce_list_08mnn)

```

```{r}

reduce_dims_all <- function(sce){
  
  hvgs <- modelGeneVar(sce)
  hvgs <- getTopHVGs(hvgs, n=nr_hvgs)
  
  if(!"corrected" %in% reducedDimNames(sce)){ # corrected doesn't need PCs
    sce <- runPCA(sce, ncomponents=25, subset_row = hvgs) 
    sce <- runUMAP(sce, dimred = 'PCA',
                   external_neighbors=TRUE, subset_row = hvgs)
  }else{
    sce <- runUMAP(sce, dimred = 'corrected', 
                   external_neighbors=TRUE, subset_row = hvgs) 
  }
  return(sce)  
}

sce_list_06 <- lapply(sce_list_06, reduce_dims_all)
sce_list_07_1 <- lapply(sce_list_07[[batches[1]]], reduce_dims_all)
sce_list_08mnn_1 <- lapply(sce_list_08mnn[[batches[1]]], reduce_dims_all)

```

```{r}

make_plots <- function(sce){
  
  batch_use <- sce$Batch_type_used[1]
  rescaled <- sce$Rescaled[1]
  correction_method <- sce$Correction_method[1]
  
  # by possible batches
  plot_1a <- plotUMAP(sce, colour_by = "Batch_exp_day")+ 
    ggtitle(paste("Corrected by:", batch_use, 
                  ", Rescaled:", rescaled, 
                  ", Method used:", correction_method))+
    theme(legend.key.size = unit(0.3, "cm"), 
          legend.key.width = unit(0.3, "cm"))+
    theme(legend.spacing = unit(0.06, "cm"), 
          legend.text = element_text(size = 7))
  
  plot_1b <- plotUMAP(sce, colour_by = "Batch_sequencing")+ 
    ggtitle(paste("Corrected by:", batch_use, 
                  ", Rescaled:", rescaled, 
                  ", Method used:", correction_method))+
    theme(legend.key.size = unit(0.3, "cm"), 
          legend.key.width = unit(0.3, "cm"))+
    theme(legend.spacing = unit(0.06, "cm"), 
          legend.text = element_text(size = 7))
  
  plot_1c <- plotUMAP(sce, colour_by = "Object_ID")+ 
    ggtitle(paste("Corrected by:", batch_use, 
                  ", Rescaled:", rescaled, 
                  ", Method used:", correction_method))+
    theme(legend.key.size = unit(0.3, "cm"), 
          legend.key.width = unit(0.3, "cm"))+
    theme(legend.spacing = unit(0.06, "cm"), 
          legend.text = element_text(size = 7))
  
  # check some other QC metrics
  plot_2 <- plotUMAP(sce, colour_by = "Keep_sample")+ 
    ggtitle(paste("Corrected by:", batch_use, 
                  ", Rescaled:", rescaled, 
                  ", Method used:", correction_method))+
    theme(legend.key.size = unit(0.3, "cm"), 
          legend.key.width = unit(0.3, "cm"))+
    theme(legend.spacing = unit(0.06, "cm"), 
          legend.text = element_text(size = 7))
 
  plot_3 <- plotUMAP(sce, colour_by = "doublet_score")+ 
    ggtitle(paste("Corrected by:", batch_use, 
                  ", Rescaled:", rescaled, 
                  ", Method used:", correction_method))+
    theme(legend.key.size = unit(0.3, "cm"),
          legend.key.width = unit(0.3, "cm"))+
    theme(legend.spacing = unit(0.06, "cm"), 
          legend.text = element_text(size = 7))
  
  # check everything else
  
  plot_4 <- plotUMAP(sce, colour_by = "Species_ID")+ 
    ggtitle(paste("Corrected by:", batch_use, 
                  ", Rescaled:", rescaled, 
                  ", Method used:", correction_method))+
    theme(legend.key.size = unit(0.3, "cm"), 
          legend.key.width = unit(0.3, "cm"))+
    theme(legend.spacing = unit(0.06, "cm"), 
          legend.text = element_text(size = 7))
  
  plot_5 <- plotUMAP(sce, colour_by = "Age")+ 
    ggtitle(paste("Corrected by:", batch_use, 
                  ", Rescaled:", rescaled, 
                  ", Method used:", correction_method))+
    theme(legend.key.size = unit(0.3, "cm"), 
          legend.key.width = unit(0.3, "cm"))+
    theme(legend.spacing = unit(0.06, "cm"), 
          legend.text = element_text(size = 7))
  
  plot_6 <- plotUMAP(sce, colour_by = "Fraction")+ 
    ggtitle(paste("Corrected by:", batch_use, 
                  ", Rescaled:", rescaled, 
                  ", Method used:", correction_method))+
    theme(legend.key.size = unit(0.3, "cm"), 
          legend.key.width = unit(0.3, "cm"))+
    theme(legend.spacing = unit(0.06, "cm"), 
          legend.text = element_text(size = 7))

  plot_7 <- plotUMAP(sce, colour_by = "Antibody_combination")+ 
    ggtitle(paste("Corrected by:", batch_use, 
                  ", Rescaled:", rescaled, 
                  ", Method used:", correction_method))+
    theme(legend.key.size = unit(0.3, "cm"), 
          legend.key.width = unit(0.3, "cm"))+
    theme(legend.spacing = unit(0.06, "cm"), 
          legend.text = element_text(size = 7))

  plot_8 <- plotUMAP(sce, colour_by = "Date_collected")+ 
    ggtitle(paste("Corrected by:", batch_use, 
                  ", Rescaled:", rescaled, 
                  ", Method used:", correction_method))+
    theme(legend.key.size = unit(0.3, "cm"), 
          legend.key.width = unit(0.3, "cm"))+
    theme(legend.spacing = unit(0.06, "cm"), 
          legend.text = element_text(size = 7))
  
  plot_list <- list(plot_1a, plot_1b, plot_1c, plot_2, plot_3, plot_4,
                    plot_5, plot_6, plot_7, plot_8)
  
  return(plot_list)
}

plot_list_06 <-lapply(sce_list_06, make_plots)
plot_list_07_1 <-lapply(sce_list_07_1, make_plots)
plot_list_08mnn_1 <- lapply(sce_list_08mnn_1, make_plots)

```

```{r}
plot_list_06
```

```{r}
plot_list_07_1
```

```{r}
plot_list_08mnn_1
```

```{r}
sessionInfo()
```

