---
title: "Figure 4"
date: '2024-10-03'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Generate Figure 4

Also contains supplementary figure parts because it's easier. FOR NOW

#### Load objects

```{r seed, message = FALSE}
base::RNGkind(kind = "Mersenne-Twister")
set.seed(37)
```

```{r load_packages, message = FALSE}
library(Seurat, quietly = TRUE)
library(SingleCellExperiment, quietly = TRUE)
library(ggpubr, quietly = TRUE)
library(tidyverse, quietly = TRUE)
#library(gghalves, quietly = TRUE) # not in conda env
#library(ggpattern, quietly = TRUE) # not in conda env
```

```{r base_path}
base_path <- "/omics/odcf/analysis/OE0538_projects_temp/DO-0008/data_temp/micromamba_test_rerun/data"
```

```{r load_manual_remaining}
#-------------------------------------------------------------------------------
#### REMAINING

# list of gene sets for HSPCs (conserved signature, conserved markers, etc.)
geneset_list_hsc <-base::readRDS(base::paste0(
  base_path,
  "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/01_reclustering_own/01_gens/geneset_list_hsc"))

# data frame containing the correct resolutions for other datasets as visually determined
resolution_df_path <- base::paste0(
  base_path,
  "/metadata/scRNAseq/03_sce_analysis/reclustering_bm/reclustering_other_resolution.txt")

resolution_df <- utils::read.csv(file = resolution_df_path, 
                               header = TRUE, 
                               sep = ";", 
                               check.names=FALSE, 
                               stringsAsFactors=FALSE, 
                               as.is=TRUE, 
                               colClasses = "character")

# corr_pval_df <-  readRDS(base::paste0(
#   base_path_output_temp,
#   "/04_signatures/02_reclustering_other/09_crpv/all_corrected_pval"))

colors_path <- base::paste0(
  base_path,
  "/metadata/colors/colors.txt")

ensembl_sign <- readRDS(base::paste0(
  base_path,
  "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/01_reclustering_own/02_endf/ensembl_sign_hsc"))

source("../source/colors.R")
source("../source/plotting.R")
#source("../source/sce_functions_reclustering.R")
```

```{r load_manual_other1}
#-------------------------------------------------------------------------------
#### OTHER MOUSE DATASET 1 (HSPC)
#### TABULA SAPIENS BONE MARROW

dataset_o1 <- "ts_bone_marrow"

seu_orig_o1 <-  base::readRDS(base::paste0(
  base_path,
  "/metadata/scRNAseq/03_sce_analysis/reclustering_bm/prepared/ts_bone_marrow"))

# list of seurat objects with reclustering vectors for each gene set and resolution
seu_hsc_recl_list_o1 <- base::readRDS(base::paste0(
  base_path,
  "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/02_reclustering_other/03_recl/reclustered_ts_bone_marrow_list"))

# CALIBRATION list of objects, to make sure that clusterings are identical
seu_hsc_recl_list_o1_CAL <- base::readRDS(base::paste0(
  base_path,
  "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/02_reclustering_other_CALIBRATE/03_recl/reclustered_ts_bone_marrow_list"))
stopifnot(identical(seu_hsc_recl_list_o1_CAL$seu_sign[[1]]$seurat_clusters,
                seu_hsc_recl_list_o1$seu_sign[[1]]$seurat_clusters))

# list of dataframes of re-clustering scores for each gene set and resolution
score_df_hsc_list_o1 <- base::readRDS(base::paste0(
  base_path,
  "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/02_reclustering_other/04_rcls/score_df_ts_bone_marrow_list"))

# # dataframes of re-clustering scores after permutation comparing gene sets
# psdf_hsc_mark_signrand_o1 <- base::readRDS(base::paste0(
#   base_path,
#   "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/02_reclustering_other/07_perg/perm_score_df_mark_ts_bone_marrow"))
# psdf_hsc_mmms_signrand_o1 <- base::readRDS(base::paste0(
#   base_path,
#   "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/02_reclustering_other/07_perg/perm_score_df_mmms_ts_bone_marrow"))
# psdf_hsc_mmms_markrand_o1 <- base::readRDS(base::paste0(
#   base_path,
#   "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/02_reclustering_other/07_perg/perm_score_df_mmms_mark_ts_bone_marrow"))
#
# # perm score DF from background permutation (SIGN)
# psdf_hsc_sign_rand_o1 <- base::readRDS(base::paste0(
#   base_path,
#   "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/02_reclustering_other/05_psig/perm_score_df_ts_bone_marrow"))
```

```{r selected_seu_o1}

resolution_df_o1 <- resolution_df[resolution_df$dataset == dataset_o1,]

selected_seu_list_o1 <- lapply(seu_hsc_recl_list_o1, function(seu_list){

  conslev_curr <- seu_list[[1]]@misc$used_genes

  resdf_temp <- resolution_df_o1[resolution_df_o1$conservation_level == conslev_curr,]
  res_curr <- resdf_temp$resolution

  seu_return <- seu_list[[res_curr]]
  return(seu_return)

})

rm(seu_hsc_recl_list_o1)
rm(seu_hsc_recl_list_o1_CAL)
gc()
```

```{r load_manual_other2}
#-------------------------------------------------------------------------------
#### OTHER MOUSE DATASET 2 (HSPC)
#### Tabula sapiens HSCs and Progs (fetal)

dataset_o2 <- "ts_hscs_progenitors"

# original seurat dataset
seu_orig_o2 <- base::readRDS(base::paste0(
  base_path,
  "/metadata/scRNAseq/03_sce_analysis/reclustering_bm/prepared/ts_hscs_progenitors"))

# list of seurat objects with reclustering vectors for each gene set and resolution
seu_hsc_recl_list_o2 <- base::readRDS(base::paste0(
  base_path,
  "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/02_reclustering_other/03_recl/reclustered_ts_hscs_progenitors_list"))

# CALIBRATION list of objects, to make sure that clusterings are identical
seu_hsc_recl_list_o2_CAL <- base::readRDS(base::paste0(
  base_path,
  "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/02_reclustering_other_CALIBRATE/03_recl/reclustered_ts_hscs_progenitors_list"))
stopifnot(identical(seu_hsc_recl_list_o2_CAL$seu_sign[[1]]$seurat_clusters,
                seu_hsc_recl_list_o2$seu_sign[[1]]$seurat_clusters))


# # list of dataframes of re-clustering scores for each gene set and resolution
# score_df_hsc_list_o2 <- base::readRDS(base::paste0(
#   base_path,
#   "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/02_reclustering_other/04_rcls/score_df_ts_hscs_progenitors_list"))
# 
# # dataframes of re-clustering scores after permutation comparing gene sets
# psdf_hsc_mark_signrand_o2 <- base::readRDS(base::paste0(
#   base_path,
#   "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/02_reclustering_other/07_perg/perm_score_df_mark_ts_hscs_progenitors"))
# psdf_hsc_mmms_signrand_o2 <- base::readRDS(base::paste0(
#   base_path,
#   "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/02_reclustering_other/07_perg/perm_score_df_mmms_ts_hscs_progenitors"))
# psdf_hsc_mmms_markrand_o2 <- base::readRDS(base::paste0(
#   base_path,
#   "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/02_reclustering_other/07_perg/perm_score_df_mmms_mark_ts_hscs_progenitors"))

# perm score DF from background permutation (SIGN)
# psdf_hsc_sign_rand_o2 <- base::readRDS(base::paste0(
#   base_path,
#   "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/02_reclustering_other/05_psig/perm_score_df_ts_hscs_progenitors"))
```

```{r selected_seu_o2}

resolution_df_o2 <- resolution_df[resolution_df$dataset == dataset_o2,]

selected_seu_list_o2 <- lapply(seu_hsc_recl_list_o2, function(seu_list){
  
  conslev_curr <- seu_list[[1]]@misc$used_genes
  
  resdf_temp <- resolution_df_o2[resolution_df_o2$conservation_level == conslev_curr,]
  res_curr <- resdf_temp$resolution
  
  seu_return <- seu_list[[res_curr]]
  return(seu_return)
  
})

rm(seu_hsc_recl_list_o2)
rm(seu_hsc_recl_list_o2_CAL)
gc()
```

```{r params}
# global params
source("determine_params.R")
```

```{r export_paths}
output_pdf_ab_plot <- base::paste0(
  base_path, "/manuscript1/figure4/figure4_ab.pdf")
# output_pdf_c_plot <- base::paste0(
#   base_path, "/manuscript1/figure4/figure4_c.pdf")
# output_pdf_c_legend <- base::paste0(
#   base_path, "/manuscript1/figure4/figure4_c_legend.pdf")
```

## Reclustering heatmaps 

### Re-annotate reclustered populations based on signature genes only

```{r prepare_annotate_o1}

seu_sign_o1 <- selected_seu_list_o1$seu_sign
reclustered_o1 <- base::unique(seu_sign_o1$seurat_clusters)

clust_list_o1 <- as.list(reclustered_o1)

ct_markers_o1 <- lapply(clust_list_o1, function(x){
  markers <- Seurat::FindMarkers(seu_sign_o1,
                                 test.use = "wilcox",
                                 ident.1 = x)
  markers <- markers[base::order(base::abs(markers$avg_log2FC), 
                                 decreasing=TRUE),]
  markers$which_cluster <- base::rep(x, nrow(markers))
  markers <- rownames_to_column(markers, var = "genes")
  
  # need to add only ensembl gene symbols as I will not be using others
  markers$symbol <- markers$genes
  markers$symbol <- ensembl_sign$HSAPIENS_SYMBOL[base::match(markers$genes, ensembl_sign$ENSG_ID)]
  return(markers)
})
names(ct_markers_o1) <- reclustered_o1

ct_markers_df_o1 <- bind_rows(ct_markers_o1)
head(ct_markers_df_o1)
```

```{r prepare_annotate_o2}

seu_sign_o2 <- selected_seu_list_o2$seu_sign
reclustered_o2 <- base::unique(seu_sign_o2$seurat_clusters)

clust_list_o2 <- as.list(reclustered_o2)

ct_markers_o2 <- lapply(clust_list_o2, function(x){
  markers <- Seurat::FindMarkers(seu_sign_o2,
                                 test.use = "wilcox",
                                 ident.1 = x)
  markers <- markers[base::order(base::abs(markers$avg_log2FC), 
                                 decreasing=TRUE),]
  markers$which_cluster <- base::rep(x, nrow(markers))
  markers <- rownames_to_column(markers, var = "genes")
  
  # need to add only ensembl gene symbols as I will not be using others
  markers$symbol <- markers$genes
  markers$symbol <- ensembl_sign$HSAPIENS_SYMBOL[
    base::match(markers$genes, ensembl_sign$ENSG_ID)]
  return(markers)
})
names(ct_markers_o2) <- reclustered_o2

ct_markers_df_o2 <- bind_rows(ct_markers_o2)
head(ct_markers_df_o2)
```

```{r prepare_annotate_o2_hsc_only}

seu_sign_o2_hsc <- seu_sign_o2[,seu_sign_o2$seurat_clusters %in%
                                 c("4", "10", "1")]
reclustered_o2_hsc <- base::unique(seu_sign_o2_hsc$seurat_clusters)

clust_list_o2_hsc <- as.list(unfactor(reclustered_o2_hsc))

ct_markers_o2_hsc <- lapply(clust_list_o2_hsc, function(x){
  markers <- Seurat::FindMarkers(seu_sign_o2_hsc,
                                 test.use = "wilcox",
                                 ident.1 = x)
  markers <- markers[base::order(base::abs(markers$avg_log2FC), 
                                 decreasing=TRUE),]
  markers$which_cluster <- base::rep(x, nrow(markers))
  markers <- rownames_to_column(markers, var = "genes")
  
  # need to add only ensembl gene symbols as I will not be using others
  markers$symbol <- markers$genes
  markers$symbol <- ensembl_sign$HSAPIENS_SYMBOL[
    base::match(markers$genes, ensembl_sign$ENSG_ID)]
  return(markers)
})
names(ct_markers_o2_hsc) <- reclustered_o2_hsc

ct_markers_df_o2_hsc <- bind_rows(ct_markers_o2_hsc)
head(ct_markers_df_o2_hsc)
```

#### Others - 1

```{r umap_others_1}
DimPlot(seu_sign_o1, dims = c(1,2), group.by = "seurat_clusters")
DimPlot(seu_sign_o1, dims = c(1,2), group.by = "assay")
seu_sign_o1$annotated_reclustered <- vector(length = ncol(seu_sign_o1))
# cluster 1 is smart-seq batch
```

6, 4, 2, 8, 1, 3, 7, 0, 5

```{r others1_cluster6}
nr <- "6"
markers <- ct_markers_o1[[nr]]$genes[
  !is.na(ct_markers_o1[[nr]]$symbol) &
    ct_markers_o1[[nr]]$avg_log2FC > 0 &
    ct_markers_o1[[nr]]$p_val_adj < 0.05]

# ITGA2B, TGFB1, ANGPT1, RAMP1, MPL, ZFPM1
ct_markers_o1[[nr]][
  !is.na(ct_markers_o1[[nr]]$symbol) & 
    ct_markers_o1[[nr]]$avg_log2FC > 0 &
    ct_markers_o1[[nr]]$p_val_adj < 0.05,][1:50,]

FeaturePlot(seu_sign_o1, markers[1:6])

seu_sign_o1$annotated_reclustered[seu_sign_o1$seurat_clusters == nr] <- "Mk"
```

```{r others1_cluster4}
nr <- "4"
markers <- ct_markers_o1[[nr]]$genes[
  !is.na(ct_markers_o1[[nr]]$symbol) &
    ct_markers_o1[[nr]]$avg_log2FC > 0 &
    ct_markers_o1[[nr]]$p_val_adj < 0.05]

# ITGA2B, KLF1, GATA1, LMO2, ZFPM1, TXNIP, EPOR, GATA2, 
ct_markers_o1[[nr]][
  !is.na(ct_markers_o1[[nr]]$symbol) & 
    ct_markers_o1[[nr]]$avg_log2FC > 0 &
    ct_markers_o1[[nr]]$p_val_adj < 0.05,][1:50,]

FeaturePlot(seu_sign_o1, markers[1:6])

seu_sign_o1$annotated_reclustered[seu_sign_o1$seurat_clusters == nr] <- "Mk/Ery"
```


```{r others1_cluster2}
nr <- "2"
markers <- ct_markers_o1[[nr]]$genes[
  !is.na(ct_markers_o1[[nr]]$symbol) &
    ct_markers_o1[[nr]]$avg_log2FC > 0 &
    ct_markers_o1[[nr]]$p_val_adj < 0.05]

# AQP1, CDC20, KLF1, BLVRB, GATA1, EPOR, CCNB2, TUBB
ct_markers_o1[[nr]][
  !is.na(ct_markers_o1[[nr]]$symbol) & 
    ct_markers_o1[[nr]]$avg_log2FC > 0 &
    ct_markers_o1[[nr]]$p_val_adj < 0.05,][1:50,]

FeaturePlot(seu_sign_o1, markers[1:6])

seu_sign_o1$annotated_reclustered[
  seu_sign_o1$seurat_clusters == nr] <- "Ery"
```

```{r others1_cluster8}
nr <- "8"
markers <- ct_markers_o1[[nr]]$genes[
  !is.na(ct_markers_o1[[nr]]$symbol) &
    ct_markers_o1[[nr]]$avg_log2FC > 0 &
    ct_markers_o1[[nr]]$p_val_adj < 0.05]

# TSPO2, AQP1, HMBS, EPOR, MKI67, CENPE, CENPF, BLVRB, KLF1
ct_markers_o1[[nr]][
  !is.na(ct_markers_o1[[nr]]$symbol) & 
    ct_markers_o1[[nr]]$avg_log2FC > 0 &
    ct_markers_o1[[nr]]$p_val_adj < 0.05,][1:50,]

FeaturePlot(seu_sign_o1, markers[1:6])

seu_sign_o1$annotated_reclustered[
  seu_sign_o1$seurat_clusters == nr] <- "Late Ery"
```

```{r others1_cluster1}
nr <- "1"
markers <- ct_markers_o1[[nr]]$genes[
  !is.na(ct_markers_o1[[nr]]$symbol) &
    ct_markers_o1[[nr]]$avg_log2FC > 0 &
    ct_markers_o1[[nr]]$p_val_adj < 0.05]

# MPL, MS4A2, ARHGDIB, ANXA3, MPO, CTSG, FUT8, TCF4, CD63, MYB, BLVRB, 
ct_markers_o1[[nr]][
  !is.na(ct_markers_o1[[nr]]$symbol) & 
    ct_markers_o1[[nr]]$avg_log2FC > 0 &
    ct_markers_o1[[nr]]$p_val_adj < 0.05,][1:50,]

FeaturePlot(seu_sign_o1, markers[1:6])

seu_sign_o1$annotated_reclustered[
  seu_sign_o1$seurat_clusters == nr] <- "batch, Smart-Seq2"
```

```{r others1_cluster3}
nr <- "3"
markers <- ct_markers_o1[[nr]]$genes[
  !is.na(ct_markers_o1[[nr]]$symbol) &
    ct_markers_o1[[nr]]$avg_log2FC > 0 &
    ct_markers_o1[[nr]]$p_val_adj < 0.05]

# NKX2-3, HLF, C17orf50, CD34, MECOM, MSI2, ANGPT1, RAMP1, MEIS1, MPL
ct_markers_o1[[nr]][
  !is.na(ct_markers_o1[[nr]]$symbol) & 
    ct_markers_o1[[nr]]$avg_log2FC > 0 &
    ct_markers_o1[[nr]]$p_val_adj < 0.05,][1:50,]

FeaturePlot(seu_sign_o1, markers[1:6])

seu_sign_o1$annotated_reclustered[
  seu_sign_o1$seurat_clusters == nr] <- "HSC"
```

```{r others1_cluster7}
nr <- "7"
markers <- ct_markers_o1[[nr]]$genes[
  !is.na(ct_markers_o1[[nr]]$symbol) &
    ct_markers_o1[[nr]]$avg_log2FC > 0 &
    ct_markers_o1[[nr]]$p_val_adj < 0.05]

# SMIM14, LSP1, LY86, CLEC12A, SPI1, MEF2C, CYBA, ANXA2, TCF4, 
ct_markers_o1[[nr]][
  !is.na(ct_markers_o1[[nr]]$symbol) & 
    ct_markers_o1[[nr]]$avg_log2FC > 0 &
    ct_markers_o1[[nr]]$p_val_adj < 0.05,]

FeaturePlot(seu_sign_o1, markers[1:6])

seu_sign_o1$annotated_reclustered[
  seu_sign_o1$seurat_clusters == nr] <- "Mono"
```

```{r others1_cluster0}
nr <- "0"
markers <- ct_markers_o1[[nr]]$genes[
  !is.na(ct_markers_o1[[nr]]$symbol) &
    ct_markers_o1[[nr]]$avg_log2FC > 0 &
    ct_markers_o1[[nr]]$p_val_adj < 0.05]

# PRTN3, CTSG, MPO, MS4A3, CEBPE, ANXA2, CLEC12A, PLAC8, SPI1, LY86
ct_markers_o1[[nr]][
  !is.na(ct_markers_o1[[nr]]$symbol) & 
    ct_markers_o1[[nr]]$avg_log2FC > 0 &
    ct_markers_o1[[nr]]$p_val_adj < 0.05,][1:50,]

FeaturePlot(seu_sign_o1, markers[1:6])

seu_sign_o1$annotated_reclustered[
  seu_sign_o1$seurat_clusters == nr] <- "Myeloid"
```

```{r others1_cluster5}
nr <- "5"
markers <- ct_markers_o1[[nr]]$genes[
  !is.na(ct_markers_o1[[nr]]$symbol) &
    ct_markers_o1[[nr]]$avg_log2FC > 0 &
    ct_markers_o1[[nr]]$p_val_adj < 0.05]

# CENPA, ANXA2, MKI67, AURKB, CENPE, LY86, CDK1, CLEC12A, SPI1, 
ct_markers_o1[[nr]][
  !is.na(ct_markers_o1[[nr]]$symbol) & 
    ct_markers_o1[[nr]]$avg_log2FC > 0 &
    ct_markers_o1[[nr]]$p_val_adj < 0.05,][1:50,]

FeaturePlot(seu_sign_o1, markers[1:6])

seu_sign_o1$annotated_reclustered[seu_sign_o1$seurat_clusters == nr] <- "Cycling Myeloid"
unique(seu_sign_o1$annotated_reclustered)
```

```{r others1_levels}
seu_sign_o1$annotated_reclustered <- factor(seu_sign_o1$annotated_reclustered,
                                            levels = c("HSC",
                                                       "Mk/Ery",
                                                       "Mk",
                                                       "Ery",
                                                       "Late Ery",
                                                       "Myeloid",
                                                       "Mono",
                                                       "Cycling Myeloid",
                                                       "batch, Smart-Seq2"))

plot_suppl_a1 <- DimPlot(seu_sign_o1, dims = c(1,2), 
                         group.by = "annotated_reclustered")
plot_suppl_a2 <- DimPlot(seu_sign_o1, dims = c(1,2), 
                         group.by = "cell_type")
plot_suppl_a3 <- DimPlot(seu_sign_o1, dims = c(1,2), 
                         group.by = "assay")
```

```{r fig.width = 16, fig.height = 3.5}
suppl_plot_a <- ggpubr::ggarrange(
  plot_suppl_a1,
  plot_suppl_a2,
  plot_suppl_a3,
  nrow = 1,
  align = "hv"
)
seu_sign_o1$annotated_reclustered
```

#### Others - 2

```{r umap_others_2}
DimPlot(seu_sign_o2, dims = c(1,2), group.by = "seurat_clusters")
DimPlot(seu_sign_o2, dims = c(1,2), group.by = "assay")
DimPlot(seu_sign_o2, dims = c(1,2), group.by = "donor_id")
DimPlot(seu_sign_o2, dims = c(1,2), group.by = "sex")
DimPlot(seu_sign_o2, dims = c(1,2), group.by = "development_stage")
DimPlot(seu_sign_o2, dims = c(1,2), group.by = "tissue")

seu_sign_o2$annotated_reclustered <- vector(length = ncol(seu_sign_o2))
# clusters 3, 9 and 5 are batch V1
# clusters 2, 8 and 7 are batch V2
```

order: 0, 1, 6, 10, 4, 3, 5, 2, 9, 8, 7, 11

```{r others2_cluster0}
nr <- "0"
markers <- ct_markers_o2[[nr]]$genes[
  !is.na(ct_markers_o2[[nr]]$symbol) &
    ct_markers_o2[[nr]]$avg_log2FC > 0 &
    ct_markers_o2[[nr]]$p_val_adj < 0.05]

# ANXA2, CTSZ, CLEC12A, H1-10, LY86, BLVRB, CEBPE, MPO
ct_markers_o2[[nr]][
  !is.na(ct_markers_o2[[nr]]$symbol) & 
    ct_markers_o2[[nr]]$avg_log2FC > 0 &
    ct_markers_o2[[nr]]$p_val_adj < 0.05,][1:50,]

FeaturePlot(seu_sign_o2, markers[1:6])
FeaturePlot(seu_sign_o2, markers[7:12])

seu_sign_o2$annotated_reclustered[
  seu_sign_o2$seurat_clusters == nr] <- "Granu/Mono Cycling"
```

```{r others2_cluster1}
nr <- "1"
markers <- ct_markers_o2[[nr]]$gene[
  !is.na(ct_markers_o2[[nr]]$symbol) &
    ct_markers_o2[[nr]]$avg_log2FC > 0 &
    ct_markers_o2[[nr]]$p_val_adj < 0.05]

# PRTN3, TIGAB, MPO, MS4A3, CTSG, CEBPE, MS4A2, MS4A2, CALR, CLEC12A
ct_markers_o2[[nr]][
  !is.na(ct_markers_o2[[nr]]$symbol) & 
    ct_markers_o2[[nr]]$avg_log2FC > 0 &
    ct_markers_o2[[nr]]$p_val_adj < 0.05,]

FeaturePlot(seu_sign_o2, markers[1:6])

seu_sign_o2$annotated_reclustered[
  seu_sign_o2$seurat_clusters == nr] <- "Granu"
```

```{r others2_cluster6}
nr <- "6"
markers <- ct_markers_o2[[nr]]$genes[
  !is.na(ct_markers_o2[[nr]]$symbol) &
    ct_markers_o2[[nr]]$avg_log2FC > 0 &
    ct_markers_o2[[nr]]$p_val_adj < 0.05]

# CTSG, PRTN4, MPO, SRBN, CEPBE, MS4A2, CLEC12A
ct_markers_o2[[nr]][
  !is.na(ct_markers_o2[[nr]]$symbol) & 
    ct_markers_o2[[nr]]$avg_log2FC > 0 &
    ct_markers_o2[[nr]]$p_val_adj < 0.05,]

FeaturePlot(seu_sign_o2, markers[1:6])

seu_sign_o2$annotated_reclustered[seu_sign_o2$seurat_clusters == nr] <- "Myeloid"
```

```{r others2_cluster10}
nr <- "10"
markers <- ct_markers_o2[[nr]]$genes[
  !is.na(ct_markers_o2[[nr]]$symbol) &
    ct_markers_o2[[nr]]$avg_log2FC > 0 &
    ct_markers_o2[[nr]]$p_val_adj < 0.05]

# TMEM176B, TMEM176A, ANXA2, CLEC12A, TSPO, LY86, CTSZ, CEBPE, 
ct_markers_o2[[nr]][
  !is.na(ct_markers_o2[[nr]]$symbol) & 
    ct_markers_o2[[nr]]$avg_log2FC > 0 &
    ct_markers_o2[[nr]]$p_val_adj < 0.05,][1:50,]

FeaturePlot(seu_sign_o2, markers[1:6])
FeaturePlot(seu_sign_o2, markers[7:12])
FeaturePlot(seu_sign_o2, markers[13:18])

seu_sign_o2$annotated_reclustered[
  seu_sign_o2$seurat_clusters == nr] <- "Mono/Dendritic"
```


```{r others2_cluster4}
nr <- "4"
markers <- ct_markers_o2[[nr]]$genes[
  !is.na(ct_markers_o2[[nr]]$symbol) &
    ct_markers_o2[[nr]]$avg_log2FC > 0 &
    ct_markers_o2[[nr]]$p_val_adj < 0.05]

# LTB, TRIB2, TCF4, MEF2C, SMIM14, LY86, RAMP1, LSP1, FUT8, CD34, LMO4, CD37
ct_markers_o2[[nr]][
  !is.na(ct_markers_o2[[nr]]$symbol) & 
    ct_markers_o2[[nr]]$avg_log2FC > 0 &
    ct_markers_o2[[nr]]$p_val_adj < 0.05,][1:50,]

FeaturePlot(seu_sign_o2, markers[1:6])

seu_sign_o2$annotated_reclustered[
  seu_sign_o2$seurat_clusters == nr] <- "Lymphoid"

```

```{r others2_cluster3}
nr <- "3"
markers <- ct_markers_o2[[nr]]$genes[
  !is.na(ct_markers_o2[[nr]]$symbol) &
    ct_markers_o2[[nr]]$avg_log2FC > 0 &
    ct_markers_o2[[nr]]$p_val_adj < 0.05]

# NKX2-3, MPL, HLF, MECOM, CD34, ANGPT1, RAMP1, MEIS1
ct_markers_o2[[nr]][
  !is.na(ct_markers_o2[[nr]]$symbol) & 
    ct_markers_o2[[nr]]$avg_log2FC > 0 &
    ct_markers_o2[[nr]]$p_val_adj < 0.05,][1:50,]

FeaturePlot(seu_sign_o2, markers[1:6])

seu_sign_o2$annotated_reclustered[
  seu_sign_o2$seurat_clusters == nr] <- "HSC1 10xV1"
```

```{r others2_cluster5}
nr <- "5"
markers <- ct_markers_o2[[nr]]$genes[
  !is.na(ct_markers_o2[[nr]]$symbol) &
    ct_markers_o2[[nr]]$avg_log2FC > 0 &
    ct_markers_o2[[nr]]$p_val_adj < 0.05]

# CDCA3, CENPA, CENPE, CDC20, MKI67, AURKB, CDK1, H1-4, MPL, NKX2-3, CD34, 
ct_markers_o2[[nr]][
  !is.na(ct_markers_o2[[nr]]$symbol) & 
    ct_markers_o2[[nr]]$avg_log2FC > 0 &
    ct_markers_o2[[nr]]$p_val_adj < 0.05,][1:50,]

FeaturePlot(seu_sign_o2, markers[1:6])
FeaturePlot(seu_sign_o2, markers[7:12])

seu_sign_o2$annotated_reclustered[
  seu_sign_o2$seurat_clusters == nr] <- "Cycling Early 10xV1"
```

```{r others2_cluster2}
nr <- "2"
markers <- ct_markers_o2[[nr]]$genes[
  !is.na(ct_markers_o2[[nr]]$symbol) &
    ct_markers_o2[[nr]]$avg_log2FC > 0 &
    ct_markers_o2[[nr]]$p_val_adj < 0.05]

# HLF, NFIA, VAMP5, MECOM, ANGPT1, MEIS1, RAMP1, GCNT2, CD34, TXNIP
ct_markers_o2[[nr]][
  !is.na(ct_markers_o2[[nr]]$symbol) & 
    ct_markers_o2[[nr]]$avg_log2FC > 0 &
    ct_markers_o2[[nr]]$p_val_adj < 0.05,][1:50,]

FeaturePlot(seu_sign_o2, markers[1:6])

seu_sign_o2$annotated_reclustered[
  seu_sign_o2$seurat_clusters == nr] <- "HSC2 10xV2"

```

```{r others2_cluster9}
nr <- "9"
markers <- ct_markers_o2[[nr]]$genes[
  !is.na(ct_markers_o2[[nr]]$symbol) &
    ct_markers_o2[[nr]]$avg_log2FC > 0 &
    ct_markers_o2[[nr]]$p_val_adj < 0.05]

# GATA1, ITGA2B, KLF1, GATA2, MPL, CENPV, EPOR, LMO4, ZFPM1, AQP1, MEIS1
ct_markers_o2[[nr]][
  !is.na(ct_markers_o2[[nr]]$symbol) & 
    ct_markers_o2[[nr]]$avg_log2FC > 0 &
    ct_markers_o2[[nr]]$p_val_adj < 0.05,][1:50,]

FeaturePlot(seu_sign_o2, markers[1:6])
FeaturePlot(seu_sign_o2, markers[7:12])

seu_sign_o2$annotated_reclustered[
  seu_sign_o2$seurat_clusters == nr] <- "Mk/Ery1 10xV1"
```

```{r others2_cluster8}
nr <- "8"
markers <- ct_markers_o2[[nr]]$gene[
  !is.na(ct_markers_o2[[nr]]$symbol) &
    ct_markers_o2[[nr]]$avg_log2FC > 0 &
    ct_markers_o2[[nr]]$p_val_adj < 0.05]

# CENPA, AURKB, CDCA3, CDK1, CDC20, CENPE, MKI67
ct_markers_o2[[nr]][
  !is.na(ct_markers_o2[[nr]]$symbol) & 
    ct_markers_o2[[nr]]$avg_log2FC > 0 &
    ct_markers_o2[[nr]]$p_val_adj < 0.05,][1:50,]

FeaturePlot(seu_sign_o2, markers[1:6])

seu_sign_o2$annotated_reclustered[
  seu_sign_o2$seurat_clusters == nr] <- "Cycling 10xV2"
```

```{r others2_cluster7}
nr <- "7"
markers <- ct_markers_o2[[nr]]$gene[
  !is.na(ct_markers_o2[[nr]]$symbol) &
    ct_markers_o2[[nr]]$avg_log2FC > 0 &
    ct_markers_o2[[nr]]$p_val_adj < 0.05]

# KLF1, ITGA2B, GATA1, EPOR, AQP1, GATA2, LMO2, ZFPM1, CDK1, CENPV, AURKB
ct_markers_o2[[nr]][
  !is.na(ct_markers_o2[[nr]]$symbol) & 
    ct_markers_o2[[nr]]$avg_log2FC > 0 &
    ct_markers_o2[[nr]]$p_val_adj < 0.05,][1:50,]

FeaturePlot(seu_sign_o2, markers[1:6])

seu_sign_o2$annotated_reclustered[
  seu_sign_o2$seurat_clusters == nr] <- "Mk/Ery2 10xV2"
```

```{r others2_cluster7}
nr <- "11"
markers <- ct_markers_o2[[nr]]$gene[
  !is.na(ct_markers_o2[[nr]]$symbol) &
    ct_markers_o2[[nr]]$avg_log2FC > 0 &
    ct_markers_o2[[nr]]$p_val_adj < 0.05]

# C17orf50, NKX2-3, RAMP1, HLF, CD34, MPL, ANPGT1, MECOM
ct_markers_o2[[nr]][
  !is.na(ct_markers_o2[[nr]]$symbol) & 
    ct_markers_o2[[nr]]$avg_log2FC > 0 &
    ct_markers_o2[[nr]]$p_val_adj < 0.05,][1:50,]

FeaturePlot(seu_sign_o2, markers[1:6])

seu_sign_o2$annotated_reclustered[
  seu_sign_o2$seurat_clusters == nr] <- "HSC3"
unique(seu_sign_o2$annotated_reclustered)
```


```{r others2_level}
seu_sign_o2$annotated_reclustered <- factor(seu_sign_o2$annotated_reclustered,
                                            levels = c(  
    "HSC1 10xV1",
    "HSC2 10xV2",
    "HSC3",
    "Cycling Early 10xV1",
    "Cycling 10xV2",
    "Granu",
    "Myeloid",
    "Mono/Dendritic",
    "Granu/Mono Cycling",
    "Lymphoid",
    "Mk/Ery1 10xV1",
    "Mk/Ery2 10xV2"))

seu_sign_o2$cell_type <- unfactor(seu_sign_o2$cell_type)
seu_sign_o2$cell_type[
  seu_sign_o2$cell_type == "hematopoietic stem cell"] <- "HSC"
seu_sign_o2$cell_type[
  seu_sign_o2$cell_type == "hematopoietic multipotent progenitor cell"] <- "hematopoietic MPP"
seu_sign_o2$cell_type[
  seu_sign_o2$cell_type == "common myeloid progenitor"] <- "common myeloid prog"
seu_sign_o2$cell_type[
  seu_sign_o2$cell_type == "granulocyte monocyte progenitor cell"] <- "granu-mono prog"
seu_sign_o2$cell_type[
  seu_sign_o2$cell_type == "early lymphoid progenitor"] <- "early lymphoid prog"
seu_sign_o2$cell_type[
  seu_sign_o2$cell_type == "megakaryocyte-erythroid progenitor cell"] <- "mk-ery prog"

seu_sign_o2$cell_type <- factor(
  seu_sign_o2$cell_type,
  levels = base::c(
    "HSC",
    "hematopoietic MPP",
    "common myeloid prog",
    "granu-mono prog",
    "promonocyte",
    "promyelocyte",
    "early lymphoid prog",
    "mk-ery prog"
  ))

plot_suppl_b1 <- DimPlot(seu_sign_o2, dims = c(1,2),
                         group.by = "annotated_reclustered")
plot_suppl_b2 <- DimPlot(seu_sign_o2, dims = c(1,2), 
                         group.by = "cell_type")
plot_suppl_b3 <- DimPlot(seu_sign_o2, dims = c(1,2),
                         group.by = "assay")
```

```{r fig.width = 16, fig.height = 3.5}
suppl_plot_b <- ggpubr::ggarrange(
  plot_suppl_b1,
  plot_suppl_b2,
  plot_suppl_b3,
  nrow = 1,
  align = "hv"
)
suppl_plot_b
```

### Make plots

#### Other 1

```{r mat_sign_o1}
mat_sign_o1_anno <- base::table(seu_sign_o1$cell_type, 
                                seu_sign_o1$annotated_reclustered)

for(i in 1:ncol(mat_sign_o1_anno)){
  mat_sign_o1_anno[,i] <- mat_sign_o1_anno[,i]/base::sum(mat_sign_o1_anno[,i])
}
sign_df_o1_anno <- base::as.data.frame(mat_sign_o1_anno)

sign_df_o1_anno$Var2 <- factor(
  sign_df_o1_anno$Var2,
  levels = base::rev(c("HSC", 
                       "Mk/Ery",
                       "Mk", 
                       "Ery",
                       "Late Ery",
                       "Myeloid", 
                       "Mono",
                       "Cycling Myeloid",
                       "batch, Smart-Seq2" )))

levels(sign_df_o1_anno$Var1)

sign_df_o1_anno$Var1 <- unfactor(sign_df_o1_anno$Var1)
sign_df_o1_anno$Var1[
  sign_df_o1_anno$Var1 == "hematopoietic stem cell"] <- "HSC"
sign_df_o1_anno$Var1[
  sign_df_o1_anno$Var1 == "common myeloid progenitor"] <- "common myeloid prog"
sign_df_o1_anno$Var1[
  sign_df_o1_anno$Var1 == "erythroid progenitor cell"] <- "erythroid prog"

sign_df_o1_anno$Var1 <- factor(
  sign_df_o1_anno$Var1,
  levels = base::c("HSC", 
                   "common myeloid prog",
                   "erythroid prog",
                   "granulocyte"
                   ))
```

```{r sign_base_plot_o1}
sign_base_plot_o1 <- ggplot2::ggplot(
  sign_df_o1_anno, 
  aes(x = Var1, 
      y = Var2,
      fill = Freq))+
  ggplot2::geom_tile()
```

```{r sign_theme_plot_o1}
sign_theme_plot_o1 <- sign_base_plot_o1+
  theme_all+
  ggplot2::theme(
    legend.position = "none",
    axis.title.x = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.y  = element_text(
      vjust = 0.5,
      hjust = 0),
    axis.text.x = element_text(
      angle = 90,
      vjust = 0.5,
      hjust = 1))+
  ggplot2::scale_fill_gradientn(
    colors = mycolors_to1,
    limits = c(0, 1),
    breaks = c(0, 0.5, 1))+
  ggplot2::ylab("Reclustered + re-annotated")+
  ggplot2::scale_y_discrete(position = "right")
sign_theme_plot_o1
```

#### Others 2

```{r mat_sign_o2}
mat_sign_o2 <- base::table(seu_sign_o2$cell_type, 
                            seu_sign_o2$annotated_reclustered)

for(i in 1:ncol(mat_sign_o2)){
  mat_sign_o2[,i] <- mat_sign_o2[,i]/base::sum(mat_sign_o2[,i])
}
sign_df_o2 <- base::as.data.frame(mat_sign_o2)

sign_df_o2$Var2 <- factor(
  sign_df_o2$Var2,
  levels = base::rev(c(
    "HSC1 10xV1",
    "HSC2 10xV2",
    "HSC3",
    "Cycling Early 10xV1",
    "Cycling 10xV2",
    "Myeloid",
    "Granu",
    "Mono/Dendritic",
    "Granu/Mono Cycling",
    "Lymphoid",
    "Mk/Ery1 10xV1",
    "Mk/Ery2 10xV2"
  )))


sign_df_o2$Var1 <- unfactor(sign_df_o2$Var1)
sign_df_o2$Var1[
  sign_df_o2$Var1 == "hematopoietic stem cell"] <- "HSC"
sign_df_o2$Var1[
  sign_df_o2$Var1 == "hematopoietic multipotent progenitor cell"] <- "hematopoietic MPP"
sign_df_o2$Var1[
  sign_df_o2$Var1 == "common myeloid progenitor"] <- "common myeloid prog"
sign_df_o2$Var1[
  sign_df_o2$Var1 == "granulocyte monocyte progenitor cell"] <- "granu-mono prog"
sign_df_o2$Var1[
  sign_df_o2$Var1 == "early lymphoid progenitor"] <- "early lymphoid prog"
sign_df_o2$Var1[
  sign_df_o2$Var1 == "megakaryocyte-erythroid progenitor cell"] <- "mk-ery prog"

sign_df_o2$Var1 <- factor(
  sign_df_o2$Var1,
  levels = base::c(
    "HSC",
    "hematopoietic MPP",
    "common myeloid prog",
    "granu-mono prog",
    "promonocyte",
    "promyelocyte",
    "early lymphoid prog",
    "mk-ery prog"
  ))
```

```{r sign_base_plot_o2}
sign_base_plot_o2 <- ggplot2::ggplot(
  sign_df_o2, 
  aes(x = Var1, 
      y = Var2,
      fill = Freq))+
  ggplot2::geom_tile()
```

```{r sign_theme_plot_o2, fig.height = 6, fig.width = 6}
sign_theme_plot_o2 <- sign_base_plot_o2+
  theme_all+
  ggplot2::theme(
    legend.position = "none",
    #axis.title.x = element_blank(),
    #axis.text.y = element_blank(),
    axis.text.x = element_text(
      angle = 90,
      hjust = 1, 
      vjust = 0.5),
    axis.text.y = element_text(
      hjust = 0, 
      vjust = 0.5),
    axis.ticks.y = element_blank())+
  ggplot2::scale_fill_gradientn(
    colors = mycolors_to1,
    limits = c(0, 1),
    breaks = c(0, 0.5, 1))+
  ggplot2::ylab("Reclustered + re-annotated")+
  ggplot2::xlab("Original cell types")+
  ggplot2::scale_y_discrete(position = "right")
sign_theme_plot_o2
```


### Assemble

```{r ab_plotparts, fig.width = 12, fig.height = 6.5}

sign_plots_ab <- ggpubr::ggarrange(
  ncol = 2,
  align = "h",
  sign_theme_plot_o1,
  sign_theme_plot_o2)
sign_plots_ab
```

```{r ab_plot_export}
pdf(output_pdf_ab_plot, width = 12, height = 6.5)
sign_plots_ab
dev.off()
stop()
```

## D Pval Plot

```{r d_prep1, eval = FALSE, include = FALSE}

# add more columns for nicer visualisation
corr_pval_df$color_id <- vector(length = nrow(corr_pval_df))
corr_pval_df$color_id[corr_pval_df$pval_corrected < 0.05] <- "significant"
corr_pval_df$color_id[corr_pval_df$pval_corrected == 0] <- "is_null"
corr_pval_df$color_id[corr_pval_df$pval_corrected >= 0.05] <- "non_significant"

corr_pval_df$cons_level_long <- vector(length = nrow(corr_pval_df))
corr_pval_df$cons_level_long[
  corr_pval_df$conservation_level == "conserved_signature"] <- "signature"
corr_pval_df$cons_level_long[
  corr_pval_df$conservation_level == "conserved_markers"] <- "conserved markers"
corr_pval_df$cons_level_long[
  corr_pval_df$conservation_level == "mmusall_markers"] <- "all BL6 markers"

corr_pval_df$score_long <- vector(length = nrow(corr_pval_df))
corr_pval_df$score_long[
  corr_pval_df$type == "adjusted_rand_index"] <- "Adjusted Rand Index"
corr_pval_df$score_long[
  corr_pval_df$type == "variation_information"] <- "Variation of Information"
corr_pval_df$score_long[
  corr_pval_df$type == "mean_prop_cells_cluster"] <- "Mean prop."

corr_pval_df$cons_level_long <- factor(
  corr_pval_df$cons_level_long, levels = c(
    "signature",
    "conserved markers",
    "all BL6 markers"))

corr_pval_df$score_long <- factor(
  corr_pval_df$score_long, levels = c(
    "Adjusted Rand Index",
    "Variation of Information",
    "Mean prop."))

corr_pval_df$color_id <- factor(
  corr_pval_df$color_id, levels = rev(c(
    "non_significant",
    "significant",
    "is_null")))

color_significance <- c("non_significant" = "grey90",
                        "significant" = "grey40", 
                        "is_null" = "blue")
```

```{r d_prep2_subset, eval = FALSE, include = FALSE}

corr_pval_df_sub <- corr_pval_df[corr_pval_df$condition %in% c(
  dataset_o1,
  dataset_o2,
  "mus_weinreb_hspc",
  "mus_tm_bonemarrow"),]

corr_pval_df_sub <- corr_pval_df_sub[
  !corr_pval_df_sub$conservation_level %in% c("conserved_markers", "all BL6 markers"),]

corr_pval_df_sub$condition_long <- corr_pval_df_sub$condition
corr_pval_df_sub$condition_long[
  corr_pval_df_sub$condition == dataset_o1] <- "tabula sapiens BM"
corr_pval_df_sub$condition_long[
  corr_pval_df_sub$condition == dataset_o2] <- "tabula sapiens fetal"
corr_pval_df_sub$condition_long[
  corr_pval_df_sub$condition == "mus_tm_bonemarrow"] <- "tabula muris"
corr_pval_df_sub$condition_long[
  corr_pval_df_sub$condition == "mus_weinreb_hspc"] <- "Weinreb et al."

corr_pval_df_sub$condition_long <- factor(
  corr_pval_df_sub$condition_long, levels = rev(c(
    "tabula muris",
    "Weinreb et al.",
    "tabula sapiens BM",
    "tabula sapiens fetal")))

corr_pval_df_sub$comparison <- factor(
  corr_pval_df_sub$comparison, levels = c(
    "sign-vs-rand",
    "mmms-vs-signrand"))

corr_pval_df_sub <- corr_pval_df_sub[
  corr_pval_df_sub$comparison %in% c("mmms-vs-signrand", "sign-vs-rand"),]

corr_pval_df_sub$x_axis <- rep("1", nrow(corr_pval_df_sub))
```

```{r d_base_plot, fig.width = 10, fig.height= 3, eval = FALSE, include = FALSE} 
d_base_plot <- ggplot2::ggplot(
  corr_pval_df_sub,
  aes(y = condition_long, 
      x = x_axis,
      color = color_id, 
      size = 10^-pval_corrected))+
  ggplot2::geom_point(alpha = 1)+
  ggplot2::facet_grid(cols = vars(corr_pval_df_sub$score_long),
                      switch = "y",
                      rows = vars(corr_pval_df_sub$comparison))+
  ggplot2::theme_classic()+
  ggplot2::scale_color_manual(values = color_significance)
```

```{r d_theme_plot, fig.width = 8, fig.height = 3, eval = FALSE, include = FALSE} 
d_theme_plot <- d_base_plot+
  theme_all+
  # ggplot2::scale_x_continuous(
  #   limits = c(0, base::max(corr_pval_df_sub$nr_genes_used)))+
  ggplot2::scale_color_manual(values = color_significance)+
  ggplot2::theme(
    legend.position = "none",
    strip.text.x = element_text(
      size = axis_title_size,
      color = axis_title_color,
      face = axis_title_face,
      hjust = 1,
      angle = 0),
    axis.text.y = element_text(
      hjust = 0),
    axis.text.x = element_blank(),   
    axis.ticks.x = element_blank(),   
    strip.text.y.left = element_text(
      size = axis_text_size,
      color = axis_text_color,
      face = axis_text_face,
      hjust = 0,
      angle = 0),
    strip.background = element_blank(),
    strip.placement = "outside",
    axis.title.y = element_blank(),
    axis.title = element_blank())
d_theme_plot
```

```{r , eval = FALSE, include = FALSE}
d_legend_base_plot <- ggplot2::ggplot(
  corr_pval_df,
  aes(y = condition, 
      x = nr_genes_used,
      color = color_id, 
      size = 10^-pval_corrected))+
  ggplot2::geom_point(alpha = 1)+
  ggplot2::facet_grid(cols = vars(corr_pval_df$score_long),
                      switch = "y",
                      rows = vars(corr_pval_df$cons_level_long))+
  ggplot2::theme_classic()+
  ggplot2::scale_x_continuous(limits = c(0, max(corr_pval_df$nr_genes_used)))+
  ggplot2::scale_color_manual(values = color_significance)
```

```{r d_legend_theme_plot, fig.width = 3, fig.height= 4, eval = FALSE, include = FALSE}
d_legend_theme_plot <- d_legend_base_plot+
   ggplot2::theme_classic()+
  ggplot2::scale_x_continuous(
    limits = c(0, base::max(corr_pval_df_sub$nr_genes_used)))+
  ggplot2::scale_color_manual("", values = color_significance)+
  ggplot2::scale_size_continuous("10 adjusted p val")+
  ggplot2::theme(
    legend.title = element_text(
      size = legend_title_size,
      color = legend_title_color,
      face = legend_title_face),
    legend.text = element_text(
      size = legend_text_size,
      color = legend_text_color,
      face = legend_text_face))

d_legend_theme <- ggpubr::get_legend(d_legend_theme_plot)

d_legend <- ggpubr::ggarrange(d_legend_theme)
d_legend
```

```{r d_plot_export, eval = FALSE, include = FALSE}
pdf(output_pdf_c_plot, width = 7, height = 3)
d_theme_plot
dev.off()
```

```{r d_legend_export, eval = FALSE, include = FALSE}
pdf(output_pdf_c_legend, width = 3, height = 3)
d_legend
dev.off()
```

# Utils

```{r sessioninfo}
utils::sessionInfo()
```
