---
title: "Supplementary Figure 7"
date: '2024-12-04'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Generate Figure S7 (for Figure 5)

#### Load objects

```{r seed, message = FALSE}
RNGkind("L'Ecuyer-CMRG") 
set.seed(37)
```

```{r load_packages, message = FALSE}
library(SingleCellExperiment, quietly = TRUE)
library(ggpubr, quietly = TRUE)
library(tidyverse, quietly = TRUE)
library(Seurat, quietly = TRUE)
```

```{r base}
base_path <- "/omics/odcf/analysis/OE0538_projects/DO-0008/data"
```

```{r load_manual}

# data frame containing the correct resolutions for other datasets as visually determined
resolution_df_path <- base::paste0(
  base_path,
  "/metadata/scRNAseq/03_sce_analysis/reclustering_bm/reclustering_other_resolution.txt")

resolution_df <- utils::read.csv(
  file = resolution_df_path, 
  header = TRUE, 
  sep = ";", 
  check.names=FALSE, 
  stringsAsFactors=FALSE, 
  as.is=TRUE, 
  colClasses = "character")

# dataframe containing corrected pvalues for all tests
corr_pval_df <-  readRDS(base::paste0(
  base_path,
  "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/02_reclustering_other/09_crpv/all_corrected_pval"))

colors_path <- base::paste0(
  base_path,
  "/metadata/colors/colors.txt")

source("../source/colors.R")
source("../source/plotting.R")
source("determine_params.R")

color_significance <- c("pval adj. >= 0.05" = "grey70",
                        "pval adj. < 0.05" = "black",
                        "pval adj. = 0" = "blue")
```

```{r load_mus_o2}

# the other mouse dataset
# Baryawno (Niche)
dataset_o2 <- "mus_bar_stromal"

# list of seurat objects with reclustering vectors for each gene set and resolution
seu_str_recl_list_o2 <- base::readRDS(base::paste0(
  base_path,
  "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/02_reclustering_other/03_recl/reclustered_mus_bar_stromal_list"))

```

```{r selected_seu_o2}

resolution_df_o2 <- resolution_df[resolution_df$dataset == dataset_o2,]

selected_seu_list_o2 <- lapply(seu_str_recl_list_o2, function(seu_list){
  
  conslev_curr <- seu_list[[1]]@misc$used_genes
  
  resdf_temp <- resolution_df_o2[
    resolution_df_o2$conservation_level == conslev_curr,]
  res_curr <- resdf_temp$resolution
  
  seu_return <- seu_list[[res_curr]]
  return(seu_return)
  
})

rm(seu_str_recl_list_o2)
gc()
```

```{r load_human_o3}

# the other human dataset
#### ts_all_stromal NICHE

dataset_o3 <- "ts_all_stromal"

# list of seurat objects with reclustering vectors for each gene set and resolution
seu_str_recl_list_o3 <- base::readRDS(base::paste0(
  base_path,
  "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/02_reclustering_other/03_recl/reclustered_ts_all_stromal_list"))

```

```{r selected_seu_o3}

resolution_df_o3 <- resolution_df[resolution_df$dataset == dataset_o3,]

selected_seu_list_o3 <- lapply(seu_str_recl_list_o3, function(seu_list){
  
  conslev_curr <- seu_list[[1]]@misc$used_genes
  
  resdf_temp <- resolution_df_o3[
    resolution_df_o3$conservation_level == conslev_curr,]
  res_curr <- resdf_temp$resolution
  
  seu_return <- seu_list[[res_curr]]
  return(seu_return)
  
})

rm(seu_str_recl_list_o3)
gc()
```

```{r export_paths}
output_baryawno_heatmap <- base::paste0(
  base_path,
  "/manuscript1/supp_figure7/sfigure7_baryawno.pdf")

output_tsbm_heatmap <- base::paste0(
  base_path,
  "/manuscript1/supp_figure7/sfigure7_tsbonemarrow.pdf")

output_pval_plot <- base::paste0(
  base_path,
  "/manuscript1/supp_figure7/sfigure7_pval.pdf")
```

# Reclustering Heatmaps

## O2 Signature

```{r mat_sign_o2}
mat_sign_o2 <- base::table(selected_seu_list_o2$seu_sign$cell_type, 
                           selected_seu_list_o2$seu_sign$seurat_clusters)

# normalise per column = new clusters and turn into DF
for(i in 1:ncol(mat_sign_o2)){
  mat_sign_o2[,i] <- mat_sign_o2[,i]/base::sum(mat_sign_o2[,i])
}
sign_df_o2 <- base::as.data.frame(mat_sign_o2)

# manually factorise clusters
sign_df_o2$Var2 <- factor(
  sign_df_o2$Var2,
  levels = base::rev(c(2, 11, 7, 6, 4, 3, 8, 0, 9, 5, 1, 10)))
```

```{r sign_base_plot_o2}
sign_base_plot_o2 <- ggplot2::ggplot(
  sign_df_o2, 
  aes(x = Var1, 
      y = Var2,
      fill = Freq))+
  ggplot2::geom_tile()
```

```{r sign_theme_plot, fig.height = 10, fig.width = 6}
sign_theme_plot_o2 <- sign_base_plot_o2+
  theme_all_supp+
  ggplot2::theme(
    legend.position = "none",
    axis.text.x = element_text(
      angle = 90,
      hjust = 1,
      vjust = 0.5),
    axis.title.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank())+
  ggplot2::scale_fill_gradientn(
    colors = mycolors_to1,
    limits = c(0, 1),
    breaks = c(0, 0.5, 1))+
  ggplot2::xlab("Reference cell types")
sign_theme_plot_o2
```

## BL6-only

```{r mat_mmms_o2}
mat_mmms_o2 <- base::table(selected_seu_list_o2$seu_mmms$cell_type, 
                           selected_seu_list_o2$seu_mmms$seurat_clusters)

for(i in 1:ncol(mat_mmms_o2)){
  mat_mmms_o2[,i] <- mat_mmms_o2[,i]/base::sum(mat_mmms_o2[,i])
}
mmms_df_o2 <- base::as.data.frame(mat_mmms_o2)

mmms_df_o2$Var2 <- factor(
  mmms_df_o2$Var2,
  levels = base::rev(
    c(2, 13, 7, 8, 4, 1, 9, 12, 0, 10, 5, 6, 3, 11)))
```

```{r mmms_base_plot_o2}
mmms_base_plot_o2 <- ggplot2::ggplot(
  mmms_df_o2, 
  aes(x = Var1, 
      y = Var2,
      fill = Freq))+
  ggplot2::geom_tile()
```

```{r mmms_theme_plot_o2}
mmms_theme_plot_o2 <- mmms_base_plot_o2+
  theme_all_supp+
  ggplot2::theme(
    legend.position = "none",
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks.y = element_blank())+
  ggplot2::scale_fill_gradientn(
    colors = mycolors_to1,
    limits = c(0, 1),
    breaks = c(0, 0.5, 1))
mmms_theme_plot_o2
```

## Assemble O2

```{r baryawno_assemble, fig.width = 5, fig.height = 9}

baryawno_heatmap_theme_plot <- ggpubr::ggarrange(
  ncol = 1,
  mmms_theme_plot_o2,
  sign_theme_plot_o2,
  align = "v",
  heights = c(1, 2.5)
)

baryawno_heatmap_theme_plot
```

```{r export_heatmap_barywano}
pdf(output_baryawno_heatmap, width = 5, height = 9)
baryawno_heatmap_theme_plot
dev.off()
```

## Signature O3 (Human)

```{r mat_sign_o3}
mat_sign_o3 <- base::table(selected_seu_list_o3$seu_sign$cell_type, 
                           selected_seu_list_o3$seu_sign$seurat_clusters)

# normalise per column = new clusters and turn into DF
for(i in 1:ncol(mat_sign_o3)){
  mat_sign_o3[,i] <- mat_sign_o3[,i]/base::sum(mat_sign_o3[,i])
}
sign_df_o3 <- base::as.data.frame(mat_sign_o3)

sign_df_o3$Var2 <- factor(
  sign_df_o3$Var2,
  levels = base::rev(c(10, 8, 6, 3, 2, 0, 7, 11, 9, 12, 5, 4, 1)))
```

```{r sign_base_plot_o3}
sign_base_plot_o3 <- ggplot2::ggplot(
  sign_df_o3, 
  aes(x = Var1, 
      y = Var2,
      fill = Freq))+
  ggplot2::geom_tile()
```

```{r sign_theme_plot_o3, fig.height = 10, fig.width = 6}
sign_theme_plot_o3 <- sign_base_plot_o3+
  theme_all_supp+
  ggplot2::theme(
    legend.position = "none",
    axis.text.x = element_text(
      angle = 90,
      hjust = 1,
      vjust = 0.5),
    axis.title.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank())+
  ggplot2::scale_fill_gradientn(
    colors = mycolors_to1,
    limits = c(0, 1),
    breaks = c(0, 0.5, 1))+
  ggplot2::xlab("Reference cell types")
sign_theme_plot_o3
```

## BL6-only O3 (Human)

```{r mat_mmms_o3}
mat_mmms_o3 <- base::table(selected_seu_list_o3$seu_mmms$cell_type, 
                           selected_seu_list_o3$seu_mmms$seurat_clusters)

for(i in 1:ncol(mat_mmms_o3)){
  mat_mmms_o3[,i] <- mat_mmms_o3[,i]/base::sum(mat_mmms_o3[,i])
}
mmms_df_o3 <- base::as.data.frame(mat_mmms_o3)

mmms_df_o3$Var2 <- factor(
  mmms_df_o3$Var2,
  levels = base::rev(
    c(0, 2, 3, 4, 7, 8, 9, 10, 12, 11, 13, 6 ,5, 1)))
```

```{r mmms_base_plot_o3}
mmms_base_plot_o3 <- ggplot2::ggplot(
  mmms_df_o3, 
  aes(x = Var1, 
      y = Var2,
      fill = Freq))+
  ggplot2::geom_tile()
```

```{r mmms_theme_plot_o3}
mmms_theme_plot_o3 <- mmms_base_plot_o3+
  theme_all_supp+
  ggplot2::theme(
    legend.position = "none",
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks.y = element_blank())+
  ggplot2::scale_fill_gradientn(
    colors = mycolors_to1,
    limits = c(0, 1),
    breaks = c(0, 0.5, 1))
mmms_theme_plot_o3
```

```{r tsbm_assemble, fig.width = 3, fig.height = 9}

tsbm_heatmap_theme_plot <- ggpubr::ggarrange(
  ncol = 1,
  mmms_theme_plot_o3,
  sign_theme_plot_o3,
  align = "v",
  heights = c(1, 2.6)
)

tsbm_heatmap_theme_plot
```

```{r output_tsbm_heatmap}
pdf(output_tsbm_heatmap, width = 3, height = 9)
tsbm_heatmap_theme_plot
dev.off()
```

# PVal plot

construct a data frame containing p values

```{r pval_df}
# subset to required datasets
corr_pval_df_str <- corr_pval_df[corr_pval_df$condition %in% c(
  "str",
  "mus_tik_stromal",
  "mus_bar_stromal",
  "li_all_stromal",
  "ts_all_stromal"
),]

# make it pretty
corr_pval_df_str$condition_long <- vector(length = nrow(corr_pval_df_str))
corr_pval_df_str$condition_long[
  corr_pval_df_str$condition == "str"] <- "our Niche cells"
corr_pval_df_str$condition_long[
  corr_pval_df_str$condition == "mus_tik_stromal"] <- "Tikhonova et al."
corr_pval_df_str$condition_long[
  corr_pval_df_str$condition == "mus_bar_stromal"] <- "Baryawno et al."
corr_pval_df_str$condition_long[
  corr_pval_df_str$condition == "li_all_stromal"] <- "Li et al."
corr_pval_df_str$condition_long[
  corr_pval_df_str$condition == "ts_all_stromal"] <- "tabula sapiens stromal"

corr_pval_df_str$condition_long <- factor(
  corr_pval_df_str$condition_long, levels = rev(c(
    "our Niche cells",
    "Tikhonova et al.",
    "Baryawno et al.",
    "Li et al.",
    "tabula sapiens stromal")))

corr_pval_df_str$score_long <- vector(length = nrow(corr_pval_df_str))
corr_pval_df_str$score_long[
  corr_pval_df_str$type == "adjusted_rand_index"] <- "Adjusted\nRand index"
corr_pval_df_str$score_long[
  corr_pval_df_str$type == "variation_information"] <- "Variation\nof Information"
corr_pval_df_str$score_long[
  corr_pval_df_str$type == "mean_prop_cells_cluster"] <- "Mean\nProportion"

corr_pval_df_str$score_long <- factor(
  corr_pval_df_str$score_long, levels = c(
    "Adjusted\nRand index",
    "Variation\nof Information",
    "Mean\nProportion"))

corr_pval_df_str$color_id <- vector(length = nrow(corr_pval_df_str))
corr_pval_df_str$color_id[corr_pval_df_str$pval_corrected < 0.05] <- "pval adj. < 0.05"
corr_pval_df_str$color_id[corr_pval_df_str$pval_corrected == 0] <- "pval adj. = 0"
corr_pval_df_str$color_id[corr_pval_df_str$pval_corrected >= 0.05] <- "pval adj. >= 0.05"

corr_pval_df_str$comparison_long <- vector(length = nrow(corr_pval_df_str))
corr_pval_df_str$comparison_long[
  corr_pval_df_str$comparison == "sign-vs-rand"] <- "signature vs.\nrandom genes"
corr_pval_df_str$comparison_long[
  corr_pval_df_str$comparison == "mark-vs-rand"] <- "conserved markers vs.\nrandom genes"
corr_pval_df_str$comparison_long[
  corr_pval_df_str$comparison == "mmms-vs-rand"] <- "BL6-only markers vs.\nrandom genes"
corr_pval_df_str$comparison_long[
  corr_pval_df_str$comparison == "mark-vs-signrand"] <- "conserved markers vs.\nsignature + random genes"
corr_pval_df_str$comparison_long[
  corr_pval_df_str$comparison == "mmms-vs-signrand"] <- "BL6-only markers vs.\nsignature + random genes"

corr_pval_df_str$comparison_long <- factor(
  corr_pval_df_str$comparison_long, levels = c(
    "signature vs.\nrandom genes",
    "conserved markers vs.\nrandom genes",
    "BL6-only markers vs.\nrandom genes",
    "conserved markers vs.\nsignature + random genes",
    "BL6-only markers vs.\nsignature + random genes"))

corr_pval_df_str$color_id <- factor(
  corr_pval_df_str$color_id, levels = rev(c(
    "pval adj. >= 0.05",
    "pval adj. < 0.05",
    "pval adj. = 0")))

head(corr_pval_df_str)
```

```{r pval_plot, fig.width = 12, fig.height = 10}
pval_plot <- ggplot2::ggplot(
  corr_pval_df_str,
  ggplot2::aes(y = condition_long,
               x = score_long,
               fill = color_id,
               size = 10^-pval_corrected))+
  ggplot2::geom_point(alpha = 1, colour="black", pch=21)+
  ggplot2::facet_grid(
    rows = vars(corr_pval_df_str$comparison_long), switch = "y")+
  theme_all_supp+
  ggplot2::theme(
    strip.placement = "outside",
    strip.background.y = element_blank(),
    panel.spacing = unit(2, "cm"),
    strip.text.y.left = element_text(
      angle = 0,
      face= "bold",
      color = "black",
      size = 16,
      hjust = 0,
      vjust = 0.5
    ),
    axis.title = element_blank()
  )+
  ggplot2::scale_x_discrete(position = "top")+
  scale_fill_manual("Significance", values = color_significance)
pval_plot
```

```{r output_pval_plot}
pdf(output_pval_plot, width = 12, height = 10)
pval_plot
dev.off()
```