---
title: "Supplementary Figure 3"
date: '2024-11-27'
output: html_document
---

Figure_S3: nr of genes vs nr of cells, condition plot, pseudotime UMAPs 
Figure_S3_silhouette: silhouette score calculation
Figure_S3_genes_v_pseudotime: genes along pseudotime trajectory 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Load objects

```{r seed, message = FALSE}
RNGkind("L'Ecuyer-CMRG") 
set.seed(37)
```

```{r load, message = FALSE}
library(tidyverse, quietly = TRUE)
library(SingleCellExperiment, quietly = TRUE)
library(ggpubr, quietly = TRUE)
library(Seurat)
library(SeuratObject)
```

```{r base_path}
base_path <- "/omics/odcf/analysis/OE0538_projects/DO-0008/data"
```

```{r load_manual}
# fully annotated SCE object (HSPCs)
sce_hsc <- base::readRDS(base::paste0(
  base_path, 
  "/scRNAseq/main_analysis/sce_objects/02_sce_anno/10_anns/sce_hsc-10"))
sce_str <- base::readRDS(base::paste0(
  base_path, 
  "/scRNAseq/main_analysis/sce_objects/02_sce_anno/10_anns/sce_str-10"))

# list of gene sets for HSPCs (conserved signature, conserved markers, etc.)
geneset_list_hsc <- base::readRDS(base::paste0(
  base_path, 
  "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/01_reclustering_own/01_gens/geneset_list_hsc"))

# list of gene sets for Niche (conserved signature, conserved markers, etc.)
geneset_list_str <- base::readRDS(base::paste0(
  base_path, 
  "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_signatures/01_reclustering_own/01_gens/geneset_list_str"))

```

```{r source}
colors_path <- base::paste0(
  base_path, 
  "/metadata/colors/colors.txt")

source("../source/colors.R")
source("../source/plotting.R")
```

```{r pdf_output}
# define output paths for pdf export
output_pdf_b <- base::paste0(
  base_path,
  "/manuscript1/supp_figure3/sfigure3_b.pdf")

output_pdf_umap_neu <- base::paste0(
  base_path,
  "/manuscript1/supp_figure3/sfigure3_umap_n.pdf")

output_pdf_umap_lym <- base::paste0(
  base_path,
  "/manuscript1/supp_figure3/sfigure3_umap_l.pdf")

output_pdf_umap_legend <- base::paste0(
  base_path,
  "/manuscript1/supp_figure3/sfigure3_umap_legend.pdf")

output_pdf_condplot <- base::paste0(
  base_path,
  "/manuscript1/supp_figure3/sfigure3_cond_plot.pdf")
  
output_pdf_condlegend <- base::paste0(
  base_path,
  "/manuscript1/supp_figure3/sfigure3_cond_legend.pdf")
```

```{r params}
# global params
source("determine_params.R")

colors_z_score <- c("steelblue3", "white", "red3")

celltypes_exclude <- c("Chondrocyte", "Lymphatic EC")
```

# Dotplot Nr of cells

```{r prep_hsc_nrcell}

hsc_nrcells_df <- base::as.data.frame(
  base::table(sce_hsc$celltypes, sce_hsc$Species_ID))
hsc_nrcells_df$nr_signature_genes <- vector(length =nrow(hsc_nrcells_df))

for(i in 1:nrow(hsc_nrcells_df)){
  ct <- hsc_nrcells_df$Var1[i]
  nr_genes <- length(geneset_list_hsc[[
    which(names(geneset_list_hsc) == ct)]]$conserved_signature)
  hsc_nrcells_df$nr_signature_genes[i] <- as.numeric(nr_genes)
}
```

```{r prep_str_nrcell}

# remove unwanted cell types first
sce_str <- sce_str[,!sce_str$celltypes %in% celltypes_exclude]
str_nrcells_df <- base::as.data.frame(
  base::table(unfactor(sce_str$celltypes), sce_str$Species_ID))
str_nrcells_df$nr_signature_genes <- vector(length =nrow(str_nrcells_df))

for(i in 1:nrow(str_nrcells_df)){
  ct <- str_nrcells_df$Var1[i]
  nr_genes <- length(geneset_list_str[[
    which(names(geneset_list_str) == ct)]]$conserved_signature)
  str_nrcells_df$nr_signature_genes[i] <- nr_genes
}
```

```{r fig.width = 8, fig.height = 6}
hsc_nrcells_df$fraction <- "HSPCs"
str_nrcells_df$fraction <- "Niche"

nr_cells_df <- rbind(hsc_nrcells_df ,str_nrcells_df)
nr_cells_df$Var2 <- factor(nr_cells_df$Var2, levels = names(col_spc))
```

```{r b_base_plot}
# using spearman because pearson tests for LINEAR vs spearman testing for MONOTONIC?
# also less influenced by extreme values

b_base_plot <- ggpubr::ggscatter(
  nr_cells_df,
  color = "Var1",
  x = "Freq",
  y = "nr_signature_genes")+
  ggpubr::stat_cor(method = "spearman")+
  ggplot2::facet_grid(rows = vars(nr_cells_df$Var2),
                      cols= vars(nr_cells_df$fraction))+
  ggplot2::scale_color_manual("Cell types", 
                              values = c(col_cts_hsc, col_cts_str))
```

```{r, b_theme_plot, fig.width = 8, fig.height = 7}
b_theme_plot <- b_base_plot+
  ylab("# signature genes per cell type")+
  xlab("# cells per cell type")+
  scale_y_continuous(limits = c(0, 230), breaks = c(0, 100, 200))+
  scale_x_continuous(limits = c(0, 12000), breaks = c(0, 5000, 10000))+
  theme_all_supp+
  theme(
    strip.background = element_blank(),
    strip.text = element_text(
      size = 16,
      face = axis_text_face,
      color = axis_text_color))

b_theme_plot
```

```{r export_b}
pdf(output_pdf_b, width = 8, height = 7)
b_theme_plot
dev.off()
```

# UMAPs of branches

```{r load_large}
# fully annotated SCE object (HSPCs) with diffusion pseudotime
sce_hsc_all_pseudotime <- base::readRDS(base::paste0(
 base_path,
  "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/05_cellrank/04_psce/sce_hsc_pseudotime"))
assays(sce_hsc_all_pseudotime) <- list()

# fully annotated SCE object (HSPCs), lym branch cells only, with 
# pseudotime and lym differentiation probability
lym_pseudo <- base::readRDS(base::paste0(
  base_path, 
  "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/05_cellrank/05_bsce/sce_lym"))
assays(lym_pseudo) <- list()

# fully annotated SCE object (HSPCs), neu branch cells only, with 
# pseudotime and neu differentiation probability
neu_pseudo <- base::readRDS(base::paste0(
  base_path, 
  "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/05_cellrank/05_bsce/sce_neu"))
assays(neu_pseudo) <- list()

# fully annotated SCE object (HSPCs), lymphoid branch cells only, with 
# pseudotime and lymphoid differentiation probability
ery_pseudo <- base::readRDS(base::paste0(
  base_path, 
  "/scRNAseq/main_analysis/sce_objects/03_sce_analysis/05_cellrank/05_bsce/sce_ery"))
assays(ery_pseudo) <- list()
```

```{r pt_umaps1}
# transfer pseudotime info, then remove pseudotime SCE object
sce_hsc$pseudotime <- sce_hsc_all_pseudotime$dpt_pseudotime
rm(sce_hsc_all_pseudotime)
gc()

# add lym and neu info
sce_hsc$lymph <- vector(length = ncol(sce_hsc))
sce_hsc$lymph[base::match(colnames(lym_pseudo),
                          colnames(sce_hsc))] <- lym_pseudo$Lymphoid

sce_hsc$neu <- vector(length = ncol(sce_hsc))
sce_hsc$neu[base::match(colnames(neu_pseudo),
                          colnames(sce_hsc))] <- neu_pseudo$Neutrophil

# add ery info
# ery object is still needed later
sce_hsc$ery <- vector(length = ncol(sce_hsc))
sce_hsc$ery[base::match(colnames(ery_pseudo),
                        colnames(sce_hsc))] <- ery_pseudo$Erythroid

```

#### Branch and PT

But I think it doesn't look good

```{r cutoff}
# make it so that pseudotime values are only kept for cells that are in the
# lymph and neutro branch

lymph_cut_off <- min(lym_pseudo$Lymphoid)
neu_cut_off <- min(neu_pseudo$Neutrophil)

sce_hsc$pt_lym <- sce_hsc$pseudotime
sce_hsc$pt_lym[sce_hsc$lymph < lymph_cut_off] <- NA

sce_hsc$pt_neu <- sce_hsc$pseudotime
sce_hsc$pt_neu[sce_hsc$neu < neu_cut_off] <- NA
```


```{r pt_umaps3}
hsc_umap_comb_lym <- base::as.data.frame(
  SingleCellExperiment::reducedDim(
    sce_hsc, type = "UMAP"))
hsc_umap_comb_lym$color_by <- sce_hsc$pt_lym 
hsc_umap_comb_lym <- hsc_umap_comb_lym[base::sample(
  1:nrow(hsc_umap_comb_lym),
  nrow(hsc_umap_comb_lym),
  replace = FALSE),]

hsc_umap_comb_neu <- base::as.data.frame(
  SingleCellExperiment::reducedDim(
    sce_hsc, type = "UMAP"))
hsc_umap_comb_neu$color_by <- sce_hsc$pt_neu
hsc_umap_comb_neu <- hsc_umap_comb_neu[base::sample(
  1:nrow(hsc_umap_comb_neu),
  nrow(hsc_umap_comb_neu),
  replace = FALSE),]

```

```{r pt_umaps_base_plot_lym}
pt_umaps_base_plot_lym <- ggplot2::ggplot(
  hsc_umap_comb_lym, 
  aes(x = X1,
      y = X2,
      color = color_by))+
  ggplot2::geom_point(
    size = umap_point_size,
    alpha = umap_point_alpha)+
  ggplot2::xlim(c(base::min(hsc_umap_comb_lym$X1)-1,
                  base::max(hsc_umap_comb_lym$X1))+1)+
  ggplot2::ylim(c(base::min(hsc_umap_comb_lym$X2)-1, 
                  base::max(hsc_umap_comb_lym$X2))+1)+
  ggplot2::scale_color_gradientn(
    limits = c(0, 1),
    breaks = c(0, 0.5, 1),
    na.value = "grey90",
    "Pseudotime within\nLymhpoid branch",
    colours = c("#061F42", "#8FBEFF"))

```

```{r pt_umaps_base_plot_neu}
pt_umaps_base_plot_neu <- ggplot2::ggplot(
  hsc_umap_comb_neu,
  aes(x = X1,
      y = X2,
      color = color_by))+
  ggplot2::geom_point(
    size = umap_point_size,
    alpha = umap_point_alpha)+
  ggplot2::xlim(c(base::min(hsc_umap_comb_neu$X1)-1,
                  base::max(hsc_umap_comb_neu$X1))+1)+
  ggplot2::ylim(c(base::min(hsc_umap_comb_neu$X2)-1, 
                  base::max(hsc_umap_comb_neu$X2))+1)+
  ggplot2::scale_color_gradientn(
    limits = c(0, 1),
    breaks = c(0, 0.5, 1),
    na.value = "grey90",
    "Pseudotime within\nNeutrophil branch",
    colours = c("#061F42", "#8FBEFF"))


```

```{r pt_umaps_theme_plot_lym, fig.width = 3, fig.height = 3}
pt_umaps_theme_plot_lym <- pt_umaps_base_plot_lym+
  cowplot::theme_nothing()
pt_umaps_theme_plot_lym
```

```{r pt_umaps_theme_plot_neu, fig.width = 3, fig.height = 3}
pt_umaps_theme_plot_neu <- pt_umaps_base_plot_neu+
  cowplot::theme_nothing()
pt_umaps_theme_plot_neu
```

#### PT for legend

```{r}
hsc_umap_pt <- base::as.data.frame(
  SingleCellExperiment::reducedDim(
    sce_hsc, type = "UMAP"))
hsc_umap_pt$color_by <- sce_hsc$pseudotime 
hsc_umap_pt <- hsc_umap_pt[base::sample(
  1:nrow(hsc_umap_pt),
  nrow(hsc_umap_pt),
  replace = FALSE),]
```

```{r pt_umaps_base_plot_1}
pt_umaps_base_plot_1 <- ggplot2::ggplot(
  hsc_umap_pt, 
  aes(x = X1,
      y = X2,
      color = color_by))+
  ggplot2::geom_point(
    size = umap_point_size,
    alpha = umap_point_alpha)+
  ggplot2::xlim(c(base::min(hsc_umap_pt$X1)-1, base::max(hsc_umap_pt$X1))+1)+
  ggplot2::ylim(c(base::min(hsc_umap_pt$X2)-1, base::max(hsc_umap_pt$X2))+1)+
  ggplot2::scale_color_gradientn(
    "Diffusion pseudotime",
    colours = c("#061F42", "#8FBEFF"))

legend <- ggpubr::get_legend(pt_umaps_base_plot_1 + theme_all_supp)
legend <- ggpubr::ggarrange(legend)
legend
```

```{r export_umap_neu}
pdf(output_pdf_umap_neu, width = 3, height = 3)
pt_umaps_theme_plot_neu
dev.off()
```

```{r export_plot_lym}
pdf(output_pdf_umap_lym, width = 3, height = 3)
pt_umaps_theme_plot_lym
dev.off()
```

```{r export_legend}
pdf(output_pdf_umap_legend, width = 3, height = 3)
legend
dev.off()
```

#### Age- and Species-separated expression of Ly6a, Cited2 and Pbx1

```{r heatmap_conds, eval = FALSE, include = FALSE}
# converting to Seurat doesn't really work for some reason, but it's also
# not really required in this case
metadata <- sce_hsc@colData@listData

sce_hsc_seurat <- SeuratObject::CreateSeuratObject(
  counts = sce_hsc@assays@data@listData[["logcounts"]],
  meta.data = metadata)
```

```{r heatmap_conds1}
g <- c(
  "Ly6a",
  "Procr",
  "Pbx1",
  "Cited2"
)

metadata <- sce_hsc@colData@listData

expression <- as.data.frame(t(as.matrix(logcounts(sce_hsc)[
  rownames(logcounts(sce_hsc)) %in% g,])))
metadata$expression <- expression

metadata$celltypes <- as.character(metadata$celltypes)
gene_expression <- metadata$expression %>%
  cbind(do.call(cbind, metadata[c("Species_ID", "Age_ID", "celltypes")]))

```

```{r heatmap_conds2}
plot_1 <- gene_expression[,c(g[1], "Species_ID", "Age_ID", "celltypes")] 
colnames(plot_1)[1] <- "gene"
plot_1 <- plot_1 %>%
  group_by(Species_ID, Age_ID, celltypes) %>%
  summarize(mean = mean(gene))
plot_1$signature <- lapply(plot_1$celltypes, function(x){
  g[1] %in% geneset_list_hsc[[x]][["conserved_signature"]]
}) %>% unlist()


plot_2 <- gene_expression[,c(g[2], "Species_ID", "Age_ID", "celltypes")] 
colnames(plot_2)[1] <- "gene"
plot_2 <- plot_2 %>%
  group_by(Species_ID, Age_ID, celltypes) %>%
  summarize(mean = mean(gene))
plot_2$signature <- lapply(plot_2$celltypes, function(x){
  g[2] %in% geneset_list_hsc[[x]][["conserved_signature"]]
}) %>% unlist()


plot_3 <- gene_expression[,c(g[3], "Species_ID", "Age_ID", "celltypes")] 
colnames(plot_3)[1] <- "gene"
plot_3 <- plot_3 %>%
  group_by(Species_ID, Age_ID, celltypes) %>%
  summarize(mean = mean(gene))
plot_3$signature <- lapply(plot_3$celltypes, function(x){
  g[3] %in% geneset_list_hsc[[x]][["conserved_signature"]]
}) %>% unlist()

plot_4 <- gene_expression[,c(g[4], "Species_ID", "Age_ID", "celltypes")] 
colnames(plot_4)[1] <- "gene"
plot_4 <- plot_4 %>%
  group_by(Species_ID, Age_ID, celltypes) %>%
  summarize(mean = mean(gene))
plot_4$signature <- lapply(plot_4$celltypes, function(x){
  g[4] %in% geneset_list_hsc[[x]][["conserved_signature"]]
}) %>% unlist()
```

```{r heatmap_conds3}
order_condition <- c(
 "mmus yng",
 "mmus old",
 "mcas yng",
 "mcas old",
 "mspr yng",
 "mspr old",
 "mcar yng",
 "mcar old"
)
plot_1$condition <- base::paste(plot_1$Species_ID, plot_1$Age_ID)
plot_1$condition_rev <- plot_1$condition
plot_1$condition <- factor(plot_1$condition, levels = order_condition)
plot_1$conditionrev <- factor(plot_1$condition, levels = rev(order_condition))

plot_2$condition <- base::paste(plot_2$Species_ID, plot_2$Age_ID)
plot_2$condition_rev <- plot_2$condition
plot_2$condition <- factor(plot_2$condition, levels = order_condition)
plot_2$conditionrev <- factor(plot_2$condition, levels = rev(order_condition))

plot_3$condition <- base::paste(plot_3$Species_ID, plot_3$Age_ID)
plot_3$condition_rev <- plot_3$condition
plot_3$condition <- factor(plot_3$condition, levels = order_condition)
plot_3$conditionrev <- factor(plot_3$condition, levels = rev(order_condition))

plot_4$condition <- base::paste(plot_4$Species_ID, plot_4$Age_ID)
plot_4$condition_rev <- plot_4$condition
plot_4$condition <- factor(plot_4$condition, levels = order_condition)
plot_4$conditionrev <- factor(plot_4$condition, levels = rev(order_condition))
```

```{r heatmap_conds3_5}
# scale the expression levels now for better comparability/only one legend

plot_1$z_score <- (plot_1$mean - base::mean(plot_1$mean))/
    stats::sd(plot_1$mean)

plot_2$z_score <- (plot_2$mean - base::mean(plot_2$mean))/
    stats::sd(plot_2$mean)

plot_3$z_score <- (plot_3$mean - base::mean(plot_3$mean))/
    stats::sd(plot_3$mean)

plot_4$z_score <- (plot_4$mean - base::mean(plot_4$mean))/
    stats::sd(plot_4$mean)

max_zs <- base::max(plot_1$z_score,
                    plot_2$z_score,
                    plot_3$z_score,
                    plot_4$z_score)
min_zs <- base::min(plot_1$z_score,
                    plot_2$z_score, 
                    plot_3$z_score,
                    plot_4$z_score)
midpoint <- (max_zs+min_zs)/2
```

```{r heatmap_conds4}
marker_1_wide <- ggplot(plot_1,
       aes(x = factor(celltypes, levels = names(geneset_list_hsc)),
           y = conditionrev,
           fill = z_score,
           color = signature,
           size = signature)) +
  geom_tile(width = 0.95, 
            height = 0.95) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, h = 1)) +
  scale_color_manual(guide = "none", values = c(alpha("black", 0), "grey50")) +
  scale_size_manual(guide = "none", values = c(0, 0.4)) +
  labs(x = NULL, y = NULL, title = g[1]) +
  ggplot2::scale_fill_gradientn(
    "z-score per gene", 
    colours = colors_z_score,
    breaks = c(-8, -4, 0, 4, 8),
    limits = c(-8,8)
    # breaks = c(-6, -3, 0, 3, 6),
    # limits = c(-6,6)
    )+
  theme(legend.position = "none")
```

```{r heatmap_conds5}
marker_2_wide <- ggplot(plot_2,
       aes(x = factor(celltypes, levels = names(geneset_list_hsc)),
           y = conditionrev,
           fill = z_score,
           color = signature,
           size = signature)) +
  geom_tile(width = 0.95, 
            height = 0.95) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, h = 1)) +
  scale_color_manual(guide = "none", values = c(alpha("black", 0), "grey50")) +
  scale_size_manual(guide = "none", values = c(0, 0.4)) +
  labs(x = NULL, y = NULL, title = g[2]) +
  ggplot2::scale_fill_gradientn(
    "z-score per gene", 
    colours = colors_z_score,
    breaks = c(-8, -4, 0, 4, 8),
    limits = c(-8,8)
    )+
  theme(legend.position = "none")
```

```{r heatmap_conds6}
marker_3_wide <- ggplot(plot_3,
       aes(x = factor(celltypes, levels = names(geneset_list_hsc)),
           y = conditionrev,
           fill = z_score,
           color = signature,
           size = signature)) +
  geom_tile(width = 0.95, 
            height = 0.95) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, h = 1)) +
  scale_color_manual(guide = "none", values = c(alpha("black", 0), "grey50")) +
  scale_size_manual(guide = "none", values = c(0, 0.4)) +
  labs(x = NULL, y = NULL, title = g[3]) +
  ggplot2::scale_fill_gradientn(
    "z-score per gene", 
    colours = colors_z_score,
    breaks = c(-8, -4, 0, 4, 8),
    limits = c(-8,8)
    # breaks = c(-5, -2.5, 0, 2.5, 5), 
    # limits = c(-5.5,5.5)
    )+
  theme(legend.position = "none")

# still need to get colors, legend, etc all correct
```

```{r heatmap_conds7}
marker_4_wide <- ggplot(plot_4,
       aes(x = factor(celltypes, levels = names(geneset_list_hsc)),
           y = conditionrev,
           fill = z_score,
           color = signature,
           size = signature)) +
  geom_tile(width = 0.95, 
            height = 0.95) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, h = 1)) +
  scale_color_manual(guide = "none", values = c(alpha("black", 0), "grey50")) +
  scale_size_manual(guide = "none", values = c(0, 0.4)) +
  labs(x = NULL, y = NULL, title = g[4]) +
  ggplot2::scale_fill_gradientn(
    "z-score per gene", 
    colours = colors_z_score,
    breaks = c(-8, -4, 0, 4, 8),
    limits = c(-8,8)
    # breaks = c(-3, -1.5, 0, 1.5, 3),
    # limits = c(-3,3)
    )+
  theme(legend.position = "none")

# still need to get colors, legend, etc all correct
```

```{r marker_1_theme}
marker_1_theme_stacked <- marker_1_wide+
  theme_all_supp+
  ggplot2::theme(
    axis.title.y = element_blank(),
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_text(
      vjust = 0.5,
      hjust = 0),
    plot.title = element_text(
      face = "italic",
      hjust = 0.5),
    legend.title = element_blank(),
    legend.position = "none")+
  ggplot2::scale_y_discrete(expand = c(0, 0))+
  ggplot2::scale_x_discrete(expand = c(0, 0))
```

```{r marker_2_theme}
marker_2_theme_stacked <- marker_2_wide+
  theme_all_supp+
  ggplot2::theme(
    axis.title.y = element_blank(),
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_text(
      vjust = 0.5,
      hjust = 0),
    plot.title = element_text(
      face = "italic",
      hjust = 0.5),
    legend.title = element_blank(),
    legend.position = "none")+
  ggplot2::scale_y_discrete(expand = c(0, 0))+
  ggplot2::scale_x_discrete(expand = c(0, 0))
```

```{r marker_3_theme}
marker_3_theme_stacked <- marker_3_wide+
  theme_all_supp+
  ggplot2::theme(
    axis.title.y = element_blank(),
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_text(
      vjust = 0.5,
      hjust = 0),
    plot.title = element_text(
      face = "italic",
      hjust = 0.5),
    legend.title = element_blank(),
    legend.position = "none")+
  ggplot2::scale_y_discrete(expand = c(0, 0))+
  ggplot2::scale_x_discrete(expand = c(0, 0))
```

```{r marker_4_theme}
marker_4_theme_stacked <- marker_4_wide+
  theme_all_supp+
  ggplot2::theme(
    axis.title.y = element_blank(),
    axis.title.x = element_blank(),
    axis.text.x = element_text(
      hjust = 1,
      vjust = 0.5,
      angle = 90),
    axis.text.y = element_text(
      vjust = 0.5,
      hjust = 0),
    plot.title = element_text(
      face = "italic",
      hjust = 0.5),
    legend.title = element_blank(),
    legend.position = "none")+
  ggplot2::scale_y_discrete(expand = c(0, 0))+
  ggplot2::scale_x_discrete(expand = c(0, 0))
```

```{r heatmap_conds_assemble_stacked, fig.width = 5, fig.height = 11}
heatmap_conds_stacked_plot <- ggpubr::ggarrange(
    marker_1_theme_stacked,
    marker_2_theme_stacked,
    marker_3_theme_stacked,
    marker_4_theme_stacked,
    ncol = 1,
    heights = c(1, 1, 1, 1.8)
  )
heatmap_conds_stacked_plot
```

```{r legend, fig.width = 4, fig.height = 1}
legend_plot <- marker_4_wide+
  theme_all_supp+
  theme(legend.position = "bottom")

legend <- ggpubr::get_legend(legend_plot)
legend <- ggpubr::ggarrange(legend)
legend
```

```{r output_pdf_condplot}
pdf(output_pdf_condplot, width = 5, height = 11)
heatmap_conds_stacked_plot
dev.off()
```

```{r output_pdf_condlegend}
pdf(output_pdf_condlegend, width = 4, height = 1)
legend
dev.off()
```

