---
title: "1st layer shared genes report"
author: "Lea Wölbert"
date: '2023-03-14'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Load libraries, source code 

```{r load,  message = FALSE}
library(DropletUtils, quietly = TRUE) 
library(scater, quietly = TRUE) 
library(scuttle, quietly = TRUE) 
library(scran, quietly = TRUE) 
library(tidyverse, quietly = TRUE) 
library(DESeq2, quietly = TRUE) 
library(EnhancedVolcano)
set.seed(37)
```

```{r}

# load sources
color_tables <- "/omics/odcf/analysis/OE0538_projects/DO-0008/metadata/color_tables"
source(file = "../source/colors.R")
source(file = "../source/plotting.R")
source(file = "../source/sce_functions.R")

#load SCE objects
sce_cluster <- readRDS(file = snakemake@input[["sce_sep"]])
sce <- readRDS(file = snakemake@input[["sce_11"]])
cluster_curr <- snakemake@wildcards[["cluster"]]
fraction_curr <- sce_cluster$Fraction_ID[1]
prelim_curr <- sce$prelimanno_broad[sce$cluster_louvain == cluster_curr][1]

tdsq_list <- readRDS(file = snakemake@input[["tdsq"]])
tdsq <- tdsq_list[[as.numeric(cluster_curr)]]

res_list <- readRDS(file = snakemake@input[["cluster_res_df"]])
names(res_list) <- c(1:length(unique(sce$cluster_louvain)))
res_df <- res_list[[as.character(cluster_curr)]]

fc_cutoff <- snakemake@params[["fc_cutoff"]]
padj_cutoff <- snakemake@params[["padj_cutoff"]]
shared_cutoff_species <- snakemake@params[["shared_cutoff_species"]]
shared_cutoff_all <- snakemake@params[["shared_cutoff_all"]]

print(fc_cutoff)
print(padj_cutoff)
print(shared_cutoff_species)
print(shared_cutoff_all)

gene_list <- read.csv(snakemake@input[["gene_list"]], 
  header = TRUE, 
  sep = ";", 
  check.names=FALSE, 
  stringsAsFactors=FALSE, 
  as.is=TRUE, 
  colClasses = "character")

title <- paste0("Cluster ", cluster_curr, " (", prelim_curr, ") ",
                "FC ", fc_cutoff, ", PADJ ", padj_cutoff)


print(title)

#knitr::knit_exit()

```

# PVal visualisation

```{r}
see_pvals <- function(res_df){
  plot1 <- EnhancedVolcano(res_df, lab = "",
                           x = 'log2FoldChange',  y = 'pvalue', 
                           col = c("grey70", "grey70", "dodgerblue3", "grey70"),
                           subtitle = "", colAlpha = 0.9, pointSize = 0.5,
                           pCutoff = padj_cutoff, FCcutoff = fc_cutoff)+
    theme_classic()+
    ggtitle(paste(title, res_df$comparison[1]))+
    theme(legend.position="none", plot.subtitle = element_blank())

  print(plot1)

}

```

## MMUS MCAS

```{r}
res_df_comb_mmus_mcas <- res_df[res_df$comparison == "mmus-mcas",]
see_pvals(res_df = res_df_comb_mmus_mcas)
```

## MMUS MSPR

```{r}
res_df_comb_mmus_mspr <- res_df[res_df$comparison == "mmus-mspr",]
see_pvals(res_df = res_df_comb_mmus_mspr)
```

## MMUS MCAR

```{r}
res_df_comb_mmus_mcar <- res_df[res_df$comparison == "mmus-mcar",]
see_pvals(res_df = res_df_comb_mmus_mcar)
```

## MCAS MSPR

```{r}
res_df_comb_mcas_mspr <- res_df[res_df$comparison == "mcas-mspr",]
see_pvals(res_df = res_df_comb_mcas_mspr)
```

## MCAS MCAR

```{r}
res_df_comb_mcas_mcar <- res_df[res_df$comparison == "mcas-mcar",]
see_pvals(res_df = res_df_comb_mcas_mcar)
```

## MSPR MCAR

```{r}
res_df_comb_mspr_mcar <- res_df[res_df$comparison == "mspr-mcar",]
see_pvals(res_df = res_df_comb_mspr_mcar)
```

# Shared by all

## By classification

```{r}
# Shared by all 
print(paste0(
  length(unique(res_df$gene[which(res_df$shared_all == TRUE)])),
  " genes are shared by all species with pval ", 
  padj_cutoff, " and FC cutoff ", fc_cutoff))

# shared between mmus and others
res_df_mmus <- res_df[res_df$species == "mmus",]
print(paste0(
  length(unique(res_df_mmus$gene[which(res_df_mmus$shared_species == TRUE)])),
  " genes are shared between mmus and other species with pval ", 
  padj_cutoff, " and FC cutoff ", fc_cutoff))
  
res_df_mcas <- res_df[res_df$species == "mcas",]
print(paste0(
  length(unique(res_df_mcas$gene[which(res_df_mcas$shared_species == TRUE)])),
  " genes are shared between mcas and other species with pval ", 
  padj_cutoff, " and FC cutoff ", fc_cutoff))

res_df_mspr <- res_df[res_df$species == "mspr",]
print(paste0(
  length(unique(res_df_mspr$gene[which(res_df_mspr$shared_species == TRUE)])),
  " genes are shared between mspr and other species with pval ", 
  padj_cutoff, " and FC cutoff ", fc_cutoff))

res_df_mcar <- res_df[res_df$species == "mcar",]
print(paste0(
  length(unique(res_df_mcar$gene[which(res_df_mcar$shared_species == TRUE)])),
  " genes are shared between mcar and other species with pval ", 
  padj_cutoff, " and FC cutoff ", fc_cutoff))

```

```{r}
print(sort(unique(res_df$gene[res_df$shared_all == TRUE])))
```


## By intersect

### Shared by all

```{r}

mmus_mcas_shared <- unique(res_df_comb_mmus_mcas$gene[res_df_comb_mmus_mcas$category == "FC + pval"])
mmus_mcar_shared <- unique(res_df_comb_mmus_mspr$gene[res_df_comb_mmus_mspr$category == "FC + pval"])
mmus_mspr_shared <- unique(res_df_comb_mmus_mcar$gene[res_df_comb_mmus_mcar$category == "FC + pval"])
mcas_mspr_shared <- unique(res_df_comb_mcas_mspr$gene[res_df_comb_mcas_mspr$category == "FC + pval"])
mcas_mcar_shared <- unique(res_df_comb_mcas_mcar$gene[res_df_comb_mcas_mcar$category == "FC + pval"])
mspr_mcar_shared <- unique(res_df_comb_mspr_mcar$gene[res_df_comb_mspr_mcar$category == "FC + pval"])

int <- Reduce(intersect, list(mmus_mcas_shared,
                              mmus_mspr_shared,
                              mmus_mcar_shared,
                              mcas_mspr_shared,
                              mcas_mcar_shared,
                              mspr_mcar_shared
                         ))

identical(unique(res_df$gene[res_df$shared_all == TRUE]), int)

```

### Shared by three out of four

```{r}

mmus_mcas_mspr <- Reduce(intersect, 
                         list(mmus_mcas_shared,
                              mmus_mspr_shared,
                              mcas_mspr_shared))
 
mmus_mcas_mcar <- Reduce(intersect, 
                         list(mmus_mcas_shared,
                              mmus_mcar_shared,
                              mcas_mcar_shared)) 
  
mmus_mspr_mcar <- Reduce(intersect, 
                         list(mmus_mspr_shared,
                              mmus_mcar_shared,
                              mspr_mcar_shared))  

mcas_mspr_mcar <- Reduce(intersect, 
                         list(mcas_mspr_shared,
                              mcas_mcar_shared,
                              mspr_mcar_shared))  

print(length(unique(mmus_mcas_mspr)))
print(sort(unique(mmus_mcas_mspr)))
print(length(unique(mmus_mcas_mcar)))
print(sort(unique(mmus_mcas_mcar)))
print(length(unique(mmus_mspr_mcar)))
print(sort(unique(mmus_mspr_mcar)))
print(length(unique(mcas_mspr_mcar)))
print(sort(unique(mcas_mspr_mcar)))

```

```{r}

at_least_three <- sort(unique(c(
  mmus_mcas_mspr,
  mmus_mcas_mcar,
  mmus_mspr_mcar,
  mcas_mspr_mcar 
)))

print(length(int))
print(length(at_least_three))
print(sort(unique(at_least_three)))

```

```{r}

at_least_three <- sort(unique(c(
  mmus_mcas_mspr,
  mmus_mcas_mcar,
  mmus_mspr_mcar,
  mcas_mspr_mcar 
)))

print(length(int))
print(length(at_least_three))
print(sort(unique(at_least_three)))

```

```{r}

cluster_curr_char <- paste0("cluster_", cluster_curr)
gene_list_temp <- gene_list[gene_list$cluster == cluster_curr_char,]
gene_markers_hsc <- unique(gene_list_temp[,1])

print(gene_markers_hsc[which(gene_markers_hsc %in% res_df$gene[res_df$shared_all == TRUE])])
print(gene_markers_hsc[which(gene_markers_hsc %in% at_least_three)])

```

# Shared genes

```{r}
knitr::knit_exit()
res_shared <- res_df[which(res_df$shared_all == TRUE),]

```

```{r}

if(nrow(res_shared) > 0){
  for(i in sort(unique(res_shared$gene))){
    
    print(i)
    print(res_shared[res_shared$gene == i,])

    dat <- plotCounts(tdsq, gene=i, intgroup="condition", 
                                 returnData=TRUE)
    dat$condition <- factor(dat$condition, 
                            levels = c("mmus", "mcas", "mspr", "mcar"))
    
    plot1 <- ggplot(dat, aes(x=condition, y=count))+ 
      geom_point(position=position_jitter(w=0.1,h=0))+
      ggtitle(paste0(title, " shared gene ", i, " pseudobulk"))+
      theme_classic()+
      ylab(paste0(i, " expression, normalized"))
    print(plot1)
  
    colData(sce)$Species_ID <- factor(colData(sce)$Species_ID, 
                              levels = c("mmus", "mcas", "mspr", "mcar"))
  
    plot_2 <- umap_gene(sce, i)+
      facet_grid(cols = vars(sce$Species_ID))+
      ggtitle(paste0(title, " shared gene ", i))
    plot_3 <- umap_gene(sce_cluster, i)+
      facet_grid(cols = vars(sce_cluster$Species_ID))+
      ggtitle(paste0(title, " shared gene ", i))
  
    ggdf <- as.data.frame(colData(sce_cluster))
    logc <- assays(sce_cluster)[["logcounts"]]
    ggdf$Species_ID <- factor(ggdf$Species_ID, 
                              levels = c("mmus", "mcas", "mspr", "mcar"))
    colData(sce_cluster)$Species_ID <- factor(colData(sce_cluster)$Species_ID, 
                              levels = c("mmus", "mcas", "mspr", "mcar"))
    
    plot_4 <- ggplot(ggdf, aes(x = cluster_louvain,
                               y = logc[rownames(logc) == i,]))+
      ggbeeswarm::geom_quasirandom(size = 0.2, color = "grey60")+
      theme_classic()+
      geom_boxplot(color = "black", alpha = 0)+
      ylab(paste0(i, " expression (log-norm)"))+
      facet_grid(cols = vars(sce_cluster$Species_ID))+
      ggtitle(paste0(title, " shared gene ", i, " SCE"))
    
    print(plot_2)
    print(plot_3)
    print(plot_4)
  }
}else{
  print("no specific genes")
}

```

```{r}
sessionInfo()
```

