---
title: "cci_metrics_qc_report"
author: "Lea Wölbert"
date: '2023-07-17'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Load libraries, source code 

```{r load,  message = FALSE}
set.seed(37)
```

```{r}

#knitr::knit_exit()

# load sources
color_tables <- snakemake@params[["color_tables"]]
source(file = "../../source/colors.R")
source(file = "../../source/plotting.R")
source(file = "../../source/sce_functions.R")

#load SCE objects
ident_pair_info <- readRDS(file = snakemake@input[["ident_pair_info"]])
ident_info <- readRDS(file = snakemake@input[["ident_info"]])
ident_nrlrs_info <- readRDS(file = snakemake@input[["ident_nrlrs_info"]])
sce <- readRDS(file = snakemake@input[["sce_input"]])

species_curr <- snakemake@wildcards[["species"]]
age_curr <- snakemake@wildcards[["age"]]
name <- paste0(species_curr, "_", age_curr)
print(name)
```

Preliminary colors

```{r}

col_recs <- c("HSCs" = "black",
              "Early MPPs" = "grey35",
              "Late MPPs" = "grey60",
              "Myeloid progs." = "red",
               "Eo/Baso/Mast" = "gold",
              "Mk/Ery progs." = "orchid1",
              "Mk progs." = "darkred",
              "Lymphoid" = "wheat2")

col_emis <- c("Mesenchymal progs." = "darkgreen",
              "CARs" = "seagreen2",
              "Fibroblasts" = "chartreuse4",
              "Pericytes/Smooth Muscle" = "cyan",
              "Arteriolar/Capillary ECs" = "skyblue2",
              "Arteriolar/Mixed ECs" = "royalblue3",
              "Sinusoidal ECs" = "midnightblue")

```

```{r}

nr_cells <- as.data.frame(table(sce$Identity))
colnames(nr_cells) <- c("Identity", "nr_cells")
nr_cells[order(nr_cells$nr_cells, decreasing = TRUE),]

```


# Cell type pairs - Cell type pair interactome

```{r}

unique(ident_pair_info$overview$emitter)

```




```{r}

ident_pair_info$overview$receiver <- factor(
  ident_pair_info$overview$receiver,
  levels = names(col_recs)[names(col_recs) %in% ident_pair_info$overview$receiver])

ident_pair_info$overview$emitter <- factor(
  ident_pair_info$overview$emitter,
  levels = names(col_emis)[names(col_emis) %in% ident_pair_info$overview$emitter])

ggdf <- ident_pair_info$overview
ggdf$nr_cells_emitter <- nr_cells$nr_cells[match(ggdf$emitter, nr_cells$Identity)]
ggdf$nr_cells_receiver <- nr_cells$nr_cells[match(ggdf$receiver, nr_cells$Identity)]

ggplot(ggdf, 
       aes(x = emitter, y = nr_ints, color = receiver))+
  ggbeeswarm::geom_quasirandom()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_manual("Receivers", values = col_recs)+
  ylim(c(0, max(ggdf$nr_ints)))+
  ggtitle(name)+
  xlab("Emitters")+
  ylab("Nr of interactions per cell type pair")
  
ggplot(ggdf, 
       aes(x = receiver, y = nr_ints, color = emitter))+
  ggbeeswarm::geom_quasirandom()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_manual("Emitters", values = col_emis)+
  ylim(c(0, max(ggdf$nr_ints)))+
  ggtitle(name)+
  xlab("Receivers")+
  ylab("Nr of interactions per cell type pair")
```

```{r, fig.height = 7}

ggplot(ggdf, 
       aes(x = reorder(ident_pairs, -nr_ints), y = nr_ints, fill = receiver))+
  geom_col()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_fill_manual("Receivers", values = col_recs)+
  ylim(c(0, max(ggdf$nr_ints)))+
  ggtitle(name)+
  xlab("Cell type pairs")+
  ylab("Nr of interactions per cell type pair")

ggplot(ggdf, 
       aes(x = reorder(ident_pairs, -nr_ints), y = nr_ints, fill = emitter))+
  geom_col()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_fill_manual("Emitters", values = col_emis)+
  ylim(c(0, max(ggdf$nr_ints)))+
  ggtitle(name)+
  xlab("Cell type pairs")+
  ylab("Nr of interactions per cell type pair")
```

```{r}

ggplot(ggdf, aes(x = emitter, y = nr_ints, color = nr_cells_emitter))+
  ggbeeswarm::geom_quasirandom()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  ylim(c(0, max(ident_pair_info$overview$nr_ints)))+
  scale_color_continuous("Nr of cells/emitter")+
  ggtitle(name)+
  xlab("Emitters")+
  ylab("Nr of interactions per cell type pair")

ggplot(ggdf, aes(x = emitter, y = nr_ints, color = nr_cells_receiver))+
  ggbeeswarm::geom_quasirandom()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  ylim(c(0, max(ident_pair_info$overview$nr_ints)))+
  scale_color_continuous("Nr of cells/receiver")+
  ggtitle(name)+
  xlab("Emitters")+
  ylab("Nr of interactions per cell type pair")
```

```{r}

ggplot(ident_pair_info$overview, 
       aes(x = receiver, y = nr_ints, 
           color = nr_cells$nr_cells[
             match(ident_pair_info$overview$emitter, nr_cells$Identity)]))+
  ggbeeswarm::geom_quasirandom()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  ylim(c(0, max(ident_pair_info$overview$nr_ints)))+
  scale_color_continuous("Nr of cells/emitter")+
  ggtitle(name)+
  xlab("Receiver")+
  ylab("Nr of interactions per cell type pair")

ggplot(ident_pair_info$overview, 
       aes(x = receiver, y = nr_ints, 
           color = nr_cells$nr_cells[
             match(ident_pair_info$overview$receiver, nr_cells$Identity)]))+
  ggbeeswarm::geom_quasirandom()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  ylim(c(0, max(ident_pair_info$overview$nr_ints)))+
  scale_color_continuous("Nr of cells/receiver")+
  ggtitle(name)+
  xlab("Receiver")+
  ylab("Nr of interactions per cell type pair")
```

```{r}

ggplot(ggdf, aes(x = nr_cells_emitter, y = nr_ints, color = emitter))+
  geom_point()+
  theme_classic()+
  ylim(c(0, (max(ggdf$nr_ints)+20)))+
  xlim(c(0, (max(ggdf$nr_cells_emitter)+20)))+
  scale_color_manual("Emitters", values = col_emis)+
  ylab("Nr of interactions per cell type pair")+
  theme(legend.position = "none")

ggplot(ggdf, aes(x = nr_cells_emitter, y = nr_ints))+
  geom_point()+
  theme_classic()+
  ylim(c(0, (max(ggdf$nr_ints)+20)))+
  xlim(c(0, (max(ggdf$nr_cells_emitter)+20)))+
  ylab("Nr of interactions per cell type pair")+
  geom_smooth(method = lm)

ggplot(ggdf, aes(x = nr_cells_receiver, y = nr_ints, color = receiver))+
  geom_point()+
  theme_classic()+
  ylim(c(0, (max(ggdf$nr_ints)+20)))+
  xlim(c(0, (max(ggdf$nr_cells_receiver)+100)))+
  scale_color_manual("Receivers", values = col_recs)+
  ylab("Nr of interactions per cell type pair")+
  theme(legend.position = "none")

ggplot(ggdf, aes(x = nr_cells_receiver, y = nr_ints))+
  geom_point()+
  theme_classic()+
  ylim(c(0, (max(ggdf$nr_ints)+20)))+
  xlim(c(0, (max(ggdf$nr_cells_receiver)+100)))+
  ylab("Nr of interactions per cell type pair")+
  geom_smooth(method = lm)
```

```{r,  fig.height = 7}

ggplot(ggdf, 
       aes(x = reorder(ident_pairs, -nr_ints), y = nr_ints, 
           fill = nr_cells_emitter))+
  geom_col()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_fill_gradient2("nr cells/emitter", 
                       low= "midnightblue", mid = "dodgerblue4", 
                       high="skyblue2", 
                       limits = c(0, max(ggdf$nr_cells_emitter)))+  
  ylim(c(0, max(ggdf$nr_ints)))+
  ggtitle(name)+
  xlab("Cell type pairs")+
  ylab("Nr of interactions per cell type pair")

ggplot(ggdf, 
       aes(x = reorder(ident_pairs, -nr_ints), y = nr_ints, 
           fill = nr_cells_receiver))+
  geom_col()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_fill_gradient2("nr cells/receiver", 
                       low= "midnightblue", mid = "dodgerblue4",
                       high="skyblue2", 
                       limits = c(0, max(ggdf$nr_cells_receiver)))+
  ylim(c(0, max(ggdf$nr_ints)))+
  ggtitle(name)+
  xlab("Cell type pairs")+
  ylab("Nr of interactions per cell type pair")
```

# Cell types - Cell type interactome

```{r}

ggdf2 <- ident_info$overview
ggdf2$nr_cells <- nr_cells$nr_cells[match(ggdf2$identity, nr_cells$Identity)]

all_cts <- c(col_recs, col_emis)

ggdf2$identity <- factor(
  ggdf2$identity, levels = names(all_cts)[names(all_cts) %in% ggdf2$identity])

```

```{r}

ggplot(ggdf2, aes(x = identity, y = nr_ints, fill = identity))+
  geom_col()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_fill_manual("Cell types", values = all_cts)+
  ylim(c(0, max(ggdf2$nr_ints)))+
  ggtitle(name)+
  xlab("Cell types")+
  ylab("Nr of interactions per cell type")+
  ggtitle(name)

ggplot(ggdf2, 
       aes(x = reorder(identity, -nr_ints), y = nr_ints, fill = identity))+
  geom_col()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_fill_manual("Cell types", values = all_cts)+
  ylim(c(0, max(ggdf2$nr_ints)))+
  ggtitle(name)+
  xlab("Cell types")+
  ylab("Nr of interactions per cell type")+
  ggtitle(name)

ggplot(ggdf2, 
       aes(x = reorder(identity, -nr_ints), y = nr_ints, fill = nr_cells))+
  geom_col()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_fill_continuous("nr cells/cell type")+
  ylim(c(0, max(ggdf2$nr_ints)))+
  ggtitle(name)+
  xlab("Cell types")+
  ylab("Nr of interactions per cell type")+
  ggtitle(name)

ggplot(ggdf2, aes(x = nr_cells, y = nr_ints, color = identity))+
  geom_point()+
  theme_classic()+
  ylim(c(0, (max(ggdf2$nr_ints)+20)))+
  xlim(c(0, (max(ggdf2$nr_cells)+20)))+
  scale_color_manual("Cell types", values = all_cts)+
  ylab("Nr of interactions per cell type")+
  ggtitle(name)

ggplot(ggdf2, aes(x = nr_cells, y = nr_ints))+
  geom_point()+
  theme_classic()+
  ylim(c(0, (max(ggdf2$nr_ints)+20)))+
  xlim(c(0, (max(ggdf2$nr_cells)+20)))+
  scale_color_manual("Cell types", values = all_cts)+
  ylab("Nr of interactions per cell type")+
  geom_smooth(method = lm)+
  ggtitle(name)

ggplot(ggdf2[ggdf2$assignment == "emitter",], aes(x = nr_cells, y = nr_ints))+
  geom_point()+
  theme_classic()+
  ylim(c(0, (max(ggdf2[ggdf2$assignment == "emitter",]$nr_ints)+20)))+
  xlim(c(0, (max(ggdf2[ggdf2$assignment == "emitter",]$nr_cells)+20)))+
  scale_color_manual("Emitters", values = col_emis)+
  ylab("Nr of interactions per emitter")+
  geom_smooth(method = lm)+
  ggtitle(name)

ggplot(ggdf2[ggdf2$assignment == "receiver",], aes(x = nr_cells, y = nr_ints))+
  geom_point()+
  theme_classic()+
  ylim(c(0, (max(ggdf2[ggdf2$assignment == "receiver",]$nr_ints)+20)))+
  xlim(c(0, (max(ggdf2[ggdf2$assignment == "receiver",]$nr_cells)+20)))+
  scale_color_manual("Receivers", values = col_recs)+
  ylab("Nr of interactions per receiver")+
  geom_smooth(method = lm)+
  ggtitle(name)
```

# Cell type - ligand/receptor repertoires

```{r}

ggdf3 <- ident_nrlrs_info

ggdf3$nr_cells <- nr_cells$nr_cells[match(ggdf3$identity, nr_cells$Identity)]

ggdf3$identity <- factor(
  ggdf3$identity, levels = names(all_cts)[names(all_cts) %in% ggdf3$identity])

```

```{r}

ggplot(ggdf3, aes(x = identity, y = nr_lrs, fill = identity))+
  geom_col()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_fill_manual("Cell types", values = all_cts)+
  ylim(c(0, max(ggdf3$nr_lrs)))+
  ggtitle(name)+
  xlab("Cell types")+
  ylab("Nr of Ligs/Recs per cell type")+
  ggtitle(name)

ggplot(ggdf3, 
       aes(x = reorder(identity, -nr_lrs), y = nr_lrs, fill = identity))+
  geom_col()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_fill_manual("Cell types", values = all_cts)+
  ylim(c(0, max(ggdf3$nr_lrs)))+
  ggtitle(name)+
  xlab("Cell types")+
  ylab("Nr of Ligs/Recs per cell type")+
  ggtitle(name)

ggplot(ggdf3, 
       aes(x = reorder(identity, -nr_lrs), y = nr_lrs, fill = nr_cells))+
  geom_col()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_fill_continuous("nr cells/cell type")+
  ylim(c(0, max(ggdf3$nr_lrs)))+
  ggtitle(name)+
  xlab("Cell types")+
  ylab("Nr of Ligs/Recs per cell type")+
  ggtitle(name)

ggplot(ggdf3, aes(x = nr_cells, y = nr_lrs, color = identity))+
  geom_point()+
  theme_classic()+
  ylim(c(0, (max(ggdf3$nr_lrs)+20)))+
  xlim(c(0, (max(ggdf3$nr_cells)+20)))+
  scale_color_manual("Cell types", values = all_cts)+
  ggtitle(name)+
  ylab("Nr of Ligs/Recs per cell type")
```

```{r}

ggdf3_emis <- ggdf3[ggdf3$assignment == "emitter",]
ggdf3_emis$identity <- factor(
  ggdf3_emis$identity, levels = names(all_cts)[names(all_cts) %in% ggdf3_emis$identity])

ggplot(ggdf3_emis, aes(x = identity, y = nr_lrs, fill = identity))+
  geom_col()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_fill_manual("Cell types", values = all_cts)+
  ylim(c(0, max(ggdf3_emis$nr_lrs)))+
  ggtitle(name)+
  xlab("Cell types")+
  ylab("Nr of Ligs per cell type")+
  ggtitle(name)

ggplot(ggdf3_emis, 
       aes(x = reorder(identity, -nr_lrs), y = nr_lrs, fill = identity))+
  geom_col()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_fill_manual("Cell types", values = all_cts)+
  ylim(c(0, max(ggdf3_emis$nr_lrs)))+
  ggtitle(name)+
  xlab("Cell types")+
  ylab("Nr of Ligs per cell type")+
  ggtitle(name)

ggplot(ggdf3_emis, 
       aes(x = reorder(identity, -nr_lrs), y = nr_lrs, fill = nr_cells))+
  geom_col()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_fill_continuous("nr cells/cell type")+
  ylim(c(0, max(ggdf3_emis$nr_lrs)))+
  ggtitle(name)+
  xlab("Cell types")+
  ylab("Nr of Ligs per cell type")+
  ggtitle(name)

ggplot(ggdf3_emis, aes(x = nr_cells, y = nr_lrs, color = identity))+
  geom_point()+
  theme_classic()+
  ylim(c(0, (max(ggdf3_emis$nr_lrs)+20)))+
  xlim(c(0, (max(ggdf3_emis$nr_cells)+20)))+
  scale_color_manual("Cell types", values = all_cts)+
  ylab("Nr of Ligs per cell type")+
  ggtitle(name)

ggplot(ggdf3_emis, aes(x = nr_cells, y = nr_lrs))+
  geom_point()+
  theme_classic()+
  ylim(c(0, (max(ggdf3_emis$nr_lrs)+20)))+
  xlim(c(0, (max(ggdf3_emis$nr_cells)+20)))+
  ylab("Nr of Ligs per cell type")+
  geom_smooth(method = lm)+
  ggtitle(name)
```

```{r}

ggdf3_recs <- ggdf3[ggdf3$assignment == "receiver",]
ggdf3_recs$identity <- factor(
  ggdf3_recs$identity, levels = names(all_cts)[names(all_cts) %in% ggdf3_recs$identity])

ggplot(ggdf3_recs, aes(x = identity, y = nr_lrs, fill = identity))+
  geom_col()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_fill_manual("Cell types", values = all_cts)+
  ylim(c(0, max(ggdf3_recs$nr_lrs)))+
  ggtitle(name)+
  xlab("Cell types")+
  ylab("Nr of Recs per cell type")+
  ggtitle(name)

ggplot(ggdf3_recs, 
       aes(x = reorder(identity, -nr_lrs), y = nr_lrs, fill = identity))+
  geom_col()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_fill_manual("Cell types", values = all_cts)+
  ylim(c(0, max(ggdf3_recs$nr_lrs)))+
  ggtitle(name)+
  xlab("Cell types")+
  ylab("Nr of Recs per cell type")+
  ggtitle(name)

ggplot(ggdf3_recs, 
       aes(x = reorder(identity, -nr_lrs), y = nr_lrs, fill = nr_cells))+
  geom_col()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_fill_continuous("nr cells/cell type")+
  ylim(c(0, max(ggdf3_recs$nr_lrs)))+
  ggtitle(name)+
  xlab("Cell types")+
  ylab("Nr of Recs per cell type")+
  ggtitle(name)

ggplot(ggdf3_recs, aes(x = nr_cells, y = nr_lrs, color = identity))+
  geom_point()+
  theme_classic()+
  ylim(c(0, (max(ggdf3_recs$nr_lrs)+20)))+
  xlim(c(0, (max(ggdf3_recs$nr_cells)+20)))+
  scale_color_manual("Cell types", values = all_cts)+
  ylab("Nr of Recs per cell type")+
  ggtitle(name)

ggplot(ggdf3_recs, aes(x = nr_cells, y = nr_lrs))+
  geom_point()+
  theme_classic()+
  ylim(c(0, (max(ggdf3_recs$nr_lrs)+20)))+
  xlim(c(0, (max(ggdf3_recs$nr_cells)+20)))+
  ylab("Nr of Recs per cell type")+
  geom_smooth(method = lm)+
  ggtitle(name)
```

# Connection between nr_lrs, nr_ints/ct and nr_ints/ctp

```{r}

int_comp_df <- data.frame()
for(i in names(all_cts[names(all_cts) %in% ident_nrlrs_info$identity])){
  
  print(i)
  
  nr_ints_ctp <- ident_pair_info$overview$nr_ints[grep(i, ident_pair_info$overview$ident_pairs)]
  
  temp_df <- data.frame(
    "mode" = c(rep("nr_ints_ctp", length(nr_ints_ctp)), "nr_ints_ct", "nr_lrs"),
    "nr" = c(nr_ints_ctp, vector(length = 2))
  )
  
  temp_df$nr[temp_df$mode == "nr_ints_ct"] <- ident_info$overview$nr_ints[
    ident_info$overview$identity == i]
  temp_df$nr[temp_df$mode == "nr_lrs"] <- ident_nrlrs_info$nr_lrs[
    ident_nrlrs_info$identity == i]

  temp_df$identity <- i
  
  int_comp_df <- rbind(int_comp_df, temp_df)
}

head(int_comp_df)

int_comp_df$mode[int_comp_df$mode == "nr_ints_ctp"] <- "CTP interactome"
int_comp_df$mode[int_comp_df$mode == "nr_ints_ct"] <- "CT interactome"
int_comp_df$mode[int_comp_df$mode == "nr_lrs"] <- "CT lig/rec repertoire"

  
int_comp_df$mode <- factor(int_comp_df$mode, 
                           levels = c("CT lig/rec repertoire",
                                      "CTP interactome",
                                      "CT interactome"))

int_comp_df$identity <- factor(
  int_comp_df$identity, levels = names(all_cts[names(all_cts) %in% int_comp_df$identity]))

max_all <- 350 

```

```{r fig.height = 6, fig.width = 8}

ggplot(int_comp_df, aes(x = mode, y = nr, color = identity))+
  geom_boxplot(outlier.size = 0.5)+
  theme_classic()+
  ylim(c(0, (max_all + 20)))+
  facet_grid(cols = vars(int_comp_df$identity))+
  scale_color_manual("Cell type", values = all_cts[
    names(all_cts) %in% int_comp_df$identity])+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90),
        strip.text.x = element_text(angle = 90),
        legend.position = "none")+
  ylab("nr of interactions/ligands/receptors")+
  ggtitle(name)

ggplot(int_comp_df, aes(x = identity, y = nr, color = identity))+
  geom_boxplot(outlier.size = 0.5)+
  theme_classic()+
  ylim(c(0, (max_all + 20)))+
  facet_grid(cols = vars(int_comp_df$mode))+
  scale_color_manual("Cell type", values = all_cts[
    names(all_cts) %in% int_comp_df$identity])+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90),
        strip.text.x = element_text(angle = 90))+
  ylab("nr of interactions/ligands/receptors")+
  ggtitle(name)
```

```{r}
sessionInfo()
```