---
title: "cci_metrics_qc_summary"
author: "Lea Wölbert"
date: '2023-07-17'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Load libraries, source code 

```{r seed, message = FALSE}
set.seed(37)
```

```{r load, message = FALSE}
library(scran)
library(scater)
library(ggpubr)
library(tidyverse)
```

```{r sources, message = FALSE}
source(file = "../../source/plotting.R")
```

```{r load_objects}

#load objects
ident_nrlrs_info_p <- snakemake@input[["ident_nrlrs_info"]]
sce_p <- snakemake@input[["sce_input"]]

ident_nrlrs_info_list <- list()
sce_list <- list()

for(i in 1:length(ident_nrlrs_info_p)){
  ident_nrlrs_info_list[[i]] <- readRDS(file = ident_nrlrs_info_p[[i]])
  sce_list[[i]] <- readRDS(file = sce_p[[i]])
}

```

```{r colors, message = FALSE}
colors_path <- snakemake@params[["colors_path"]]
source(file = "../../source/colors.R")
col_cts <- c(col_cts_hsc, col_cts_str)
```

Prepare data

```{r}
# o for overview
nrlrso_df <- bind_rows(ident_nrlrs_info_list)
nrlrso_df$name <- paste0(nrlrso_df$species, "_", nrlrso_df$age)
head(nrlrso_df)
```

Calculate Stats

```{r}

qcdf_list <- lapply(sce_list, function(sce){
  
  qcdf_counts <- perCellQCMetrics(sce, assay.type = "counts")
  qcdf_downsm <- perCellQCMetrics(sce, assay.type = "downsampled")
  
  qcdf_counts$Object_ID <- sce$Object_ID
  qcdf_downsm$Object_ID <- sce$Object_ID

  qcdf_counts$Species_ID <- sce$Species_ID
  qcdf_downsm$Species_ID <- sce$Species_ID

  qcdf_counts$Age_ID <- sce$Age_ID
  qcdf_downsm$Age_ID <- sce$Age_ID
  
  qcdf_counts$Identity <- sce$Identity
  qcdf_downsm$Identity <- sce$Identity
  
  qcdf_counts$Status <- "before downsampling"
  qcdf_downsm$Status <- "after downsampling"
  
  qcdf_both <- rbind(qcdf_counts, qcdf_downsm)

  return(qcdf_both)
}) 

qcdf_gg <- DataFrame()
for(i in qcdf_list){
  qcdf_gg <- rbind(qcdf_gg, i)
}
qcdf_gg <- as.data.frame(qcdf_gg)

qcdf_gg$name <- paste0(qcdf_gg$Species_ID, "_", qcdf_gg$Age_ID)
head(qcdf_gg)
```

Get nr of cells from corresponding SCE objects

```{r}

# since the SCE list is not named by sample name, cbind
# then separate by sample name again, just to make sure 

sce_all <- sce_list[[1]]
for(i in 2:length(sce_list)){
  sce_all <- cbind(sce_all, sce_list[[i]])
}
sce_all$name <- paste0(sce_all$Species_ID, "_", sce_all$Age_ID)

unique(sce_all$Age_ID)
unique(sce_all$Species_ID)
unique(sce_all$name)

names <- unique(sce_all$name)

nrlrso_df$nr_cells <- vector(length = nrow(nrlrso_df))

for(i in names){
  sce_temp <- sce_all[,sce_all$name == i]
  nr_cells <- table(sce_temp$Identity)
  
  print(i)
  print(nr_cells)
  
  for(j in names(nr_cells)){
    nrlrso_df[nrlrso_df$name == i,]$nr_cells[nrlrso_df[nrlrso_df$name == i,]$identity == j] <- nr_cells[names(nr_cells) == j]
  }
}

print(head(nrlrso_df))
```

Factor cell types, ages, and species

```{r}

# cell types
nrlrso_df$identity <- factor(nrlrso_df$identity, levels = names(col_cts)[
  names(col_cts) %in% nrlrso_df$identity])
qcdf_gg$Identity <- factor(qcdf_gg$Identity, levels = names(col_cts)[
  names(col_cts) %in% qcdf_gg$Identity])

# age
nrlrso_df$age <- factor(nrlrso_df$age, levels = c("yng", "old"))
qcdf_gg$Age_ID <- factor(qcdf_gg$Age_ID, levels = c("yng", "old"))

# species
species <- c("mmus", "mcas", "mspr", "mcar")
nrlrso_df$species <- factor(nrlrso_df$species, levels = species)
qcdf_gg$Species_ID <- factor(qcdf_gg$Species_ID, species)

# name
conds <- c("mmus_yng", "mmus_old", "mcas_yng", "mcas_old",
           "mspr_yng", "mspr_old", "mcar_yng", "mcar_old")
nrlrso_df$name <- factor(nrlrso_df$name, levels = conds)
```

Prepare downsampled counts

```{r}
qcdf_gg_ds <- qcdf_gg[qcdf_gg$Status == "after downsampling",]

max_qcdf_gg_ds <- 4000 # this removes two cells in mcar

qcdf_gg_ds_emis <- qcdf_gg_ds[qcdf_gg_ds$Identity %in% names(col_cts_str),]
qcdf_gg_ds_recs <- qcdf_gg_ds[qcdf_gg_ds$Identity %in% names(col_cts_hsc),]
```

# Important Plots

```{r, fig.width = 4, fig.height = 6}
nrlrso_df_emi <- nrlrso_df[nrlrso_df$assignment == "emitter",]
nrlrso_df_rec <- nrlrso_df[nrlrso_df$assignment == "receiver",]

ggplot(nrlrso_df_emi, 
       aes(x = name, y = nr_lrs, color = age))+
  ggbeeswarm::geom_quasirandom(size = 2.5, alpha = 0.9)+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90))+
  scale_color_manual("Age", values = col_age)+
  ylab("Nr of detected Ligands per cell type")+
  stat_compare_means(
    comparisons = list(c("mmus_yng", "mmus_old"),
                       c("mcas_yng", "mcas_old"),
                       c("mspr_yng", "mspr_old"),
                       c("mcar_yng", "mcar_old")),
    test = 'wilcox', p.adjust.method = "BH", hide.ns = TRUE,
    aes(label = after_stat(p.signif)))+
  ylim(c(0, 130))+
  ggtitle("Emitters")

ggplot(nrlrso_df_rec, 
       aes(x = name, y = nr_lrs, color = age))+
  ggbeeswarm::geom_quasirandom(size = 2.5, alpha = 0.9)+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90))+
  scale_color_manual("Age", values = col_age)+
  ylab("Nr of detected Receptors per cell type")+
  stat_compare_means(
    comparisons = list(c("mmus_yng", "mmus_old"),
                       c("mcas_yng", "mcas_old"),
                       c("mspr_yng", "mspr_old"),
                       c("mcar_yng", "mcar_old")),
    test = 'wilcox', p.adjust.method = "BH", hide.ns = TRUE,
    aes(label = after_stat(p.signif)))+
  ylim(c(0, 130))+
  ggtitle("Receivers")

```

```{r, fig.width = 4, fig.height = 6}

conds_temp_yng <- c("mmus_yng", "mcas_yng", "mspr_yng", "mcar_yng")
conds_temp_old <- c("mmus_old", "mcas_old", "mspr_old", "mcar_old")

nrlrso_df_emi_yng <- nrlrso_df_emi[nrlrso_df_emi$age == "yng",]
nrlrso_df_emi_yng$name_temp <- factor(nrlrso_df_emi_yng$name, 
                                      levels = conds_temp_yng)

nrlrso_df_emi_old <- nrlrso_df_emi[nrlrso_df_emi$age == "old",]
nrlrso_df_emi_old$name_temp <- factor(nrlrso_df_emi_old$name,
                                      levels = conds_temp_old)

nrlrso_df_rec_yng <- nrlrso_df_rec[nrlrso_df_rec$age == "yng",]
nrlrso_df_rec_yng$name_temp <- factor(nrlrso_df_rec_yng$name,
                                      levels = conds_temp_yng)

nrlrso_df_rec_old <- nrlrso_df_rec[nrlrso_df_rec$age == "old",]
nrlrso_df_rec_old$name_temp <- factor(nrlrso_df_rec_old$name,
                                      levels = conds_temp_old)

ggplot(nrlrso_df_emi_yng, 
       aes(x = name_temp, y = nr_lrs, color = age))+
  ggbeeswarm::geom_quasirandom(size = 2.5, alpha = 0.9)+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_manual("Age", values = col_age)+
  ylab("Nr of detected Ligands per cell type")+
  stat_compare_means(test = 'kruskal.test', p.adjust.method = "BH",
                     label.y = 0.9)+
  stat_compare_means(
    comparisons = list(c("mmus_yng", "mcas_yng"), c("mmus_yng", "mspr_yng"),
                       c("mmus_yng", "mcar_yng"), c("mcas_yng", "mspr_yng"),
                       c("mcas_yng", "mcar_yng"), c("mspr_yng", "mcar_yng")),
    test = 'dunn_test', p.adjust.method = "BH",
    hide.ns = TRUE, aes(label = after_stat(p.signif)))+
  ylim(c(0, 130))+
  ggtitle("Emitters")+
  xlab("Species")

ggplot(nrlrso_df_emi_old, 
       aes(x = name_temp, y = nr_lrs, color = age))+
  ggbeeswarm::geom_quasirandom(size = 2.5, alpha = 0.9)+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_manual("Age", values = col_age)+
  ylab("Nr of detected Ligands per cell type")+
  stat_compare_means(test = 'kruskal.test', p.adjust.method = "BH", 
                     label.y = 0.9)+
  stat_compare_means(
    comparisons = list(c("mmus_old", "mcas_old"), c("mmus_old", "mspr_old"),
                       c("mmus_old", "mcar_old"), c("mcas_old", "mspr_old"),
                       c("mcas_old", "mcar_old"), c("mspr_old", "mcar_old")),
    test = 'dunn_test', p.adjust.method = "BH",
    hide.ns = TRUE, aes(label = after_stat(p.signif)))+
  ylim(c(0, 130))+
  ggtitle("Emitters")+
  xlab("Species")

ggplot(nrlrso_df_rec_yng, 
       aes(x = name_temp, y = nr_lrs, color = age))+
  ggbeeswarm::geom_quasirandom(size = 2.5, alpha = 0.9)+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_manual("Age", values = col_age)+
  ylab("Nr of detected Receotirs per cell type")+
  stat_compare_means(test = 'kruskal.test', p.adjust.method = "BH", label.y = 0.9)+
  stat_compare_means(
    comparisons = list(c("mmus_yng", "mcas_yng"), c("mmus_yng", "mspr_yng"),
                       c("mmus_yng", "mcar_yng"), c("mcas_yng", "mspr_yng"),
                       c("mcas_yng", "mcar_yng"), c("mspr_yng", "mcar_yng")),
    test = 'dunn_test', p.adjust.method = "BH",
    hide.ns = TRUE, aes(label = after_stat(p.signif)))+
  ylim(c(0, 130))+
  ggtitle("Receivers")+
  xlab("Species")

ggplot(nrlrso_df_rec_old, 
       aes(x = name_temp, y = nr_lrs, color = age))+
  ggbeeswarm::geom_quasirandom(size = 2.5, alpha = 0.9)+
  geom_boxplot(alpha = 0, color = "black")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_manual("Age", values = col_age)+
  ylab("Nr of detected Receptors per cell type")+
  stat_compare_means(test = 'kruskal.test', p.adjust.method = "BH", label.y = 0.9)+
  stat_compare_means(
    comparisons = list(c("mmus_old", "mcas_old"), c("mmus_old", "mspr_old"),
                       c("mmus_old", "mcar_old"), c("mcas_old", "mspr_old"),
                       c("mcas_old", "mcar_old"), c("mspr_old", "mcar_old")),
    test = 'dunn_test', p.adjust.method = "BH",
    hide.ns = TRUE, aes(label = after_stat(p.signif)))+
  ylim(c(0, 130))+
  ggtitle("Receivers")+
  xlab("Species")
```

# QC Plots

```{r}

nrlrso_df_emi <- nrlrso_df[nrlrso_df$assignment == "emitter",]
ggplot(nrlrso_df_emi, 
       aes(x = identity, y = nr_lrs, color = name))+
  ggbeeswarm::geom_quasirandom()+
  geom_boxplot(alpha = 0, color = "grey30")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_discrete("Condition")+
  ylim(c(0, max(nrlrso_df_emi$nr_lrs)))+
  xlab("Emitters")+
  ylab("Nr of ligands per cell type")+
  ggtitle("all conditions")

ggplot(nrlrso_df_emi, 
       aes(x = identity, y = nr_lrs, color = nr_cells))+
  ggbeeswarm::geom_quasirandom()+
  geom_boxplot(alpha = 0, color = "grey30")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_continuous("nr cells/emitter")+
  ylim(c(0, max(nrlrso_df_emi$nr_lrs)))+
  xlab("Emitters")+
  ylab("Nr of ligands per cell type")+
  ggtitle("all conditions")
```

```{r}

nrlrso_df_rec <- nrlrso_df[nrlrso_df$assignment == "receiver",]
ggplot(nrlrso_df_rec, 
       aes(x = identity, y = nr_lrs, color = name))+
  ggbeeswarm::geom_quasirandom()+
  geom_boxplot(alpha = 0, color = "grey30")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_discrete("Condition")+
  ylim(c(0, max(nrlrso_df_rec$nr_lrs)))+
  xlab("Receivers")+
  ylab("Nr of receptors per cell type")+
  ggtitle("all conditions")

ggplot(nrlrso_df_rec, 
       aes(x = identity, y = nr_lrs, color = nr_cells))+
  ggbeeswarm::geom_quasirandom()+
  geom_boxplot(alpha = 0, color = "grey30")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_continuous("nr cells/receiver")+
  ylim(c(0, max(nrlrso_df_rec$nr_lrs)))+
  xlab("Receivers")+
  ylab("Nr of receptors per cell type")+
  ggtitle("all conditions")
```

```{r}
ggscatter(nrlrso_df, x = "nr_cells", y = "nr_lrs",
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "nr of cells per cell type", 
          ylab = "nr of Ligands/Receptors per cell type")+
  ylim(c(0, (max(nrlrso_df$nr_lrs)+20)))+
  xlim(c(0, (max(nrlrso_df$nr_cells)+20)))

ggscatter(nrlrso_df_emi, x = "nr_cells", 
          y = "nr_lrs", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "nr of cells per cell type", 
          ylab = "nr of Ligands per cell type")+
  ylim(c(0, (max(nrlrso_df$nr_lrs)+20)))+
  xlim(c(0, (max(nrlrso_df$nr_cells)+20)))+
  ggtitle("Emitters")

ggscatter(nrlrso_df_rec, x = "nr_cells", 
          y = "nr_lrs", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "nr of cells per cell type", 
          ylab = "nr of Receptors per cell type")+
  ylim(c(0, (max(nrlrso_df$nr_lrs)+20)))+
  xlim(c(0, (max(nrlrso_df$nr_cells)+20)))+
  ggtitle("Receivers")
```

```{r}
sessionInfo()
```