---
title: "preprocessing_report"
author: "Amy Danson, Lea Wölbert"
date: '2022-09-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Summary report QC for all objects at once.
Some operations from the scripts must be repeated to generate relevant plots,
but any new objects cannot be saved from an .Rmd script.

#### Load libraries, source code 

```{r load,  message = FALSE}

library(SingleCellExperiment, quietly = TRUE) 
library(DropletUtils, quietly = TRUE) 
library(tidyverse, quietly = TRUE) 
library(scater, quietly = TRUE) 
library(scuttle, quietly = TRUE) 
library(scran, quietly = TRUE) 
set.seed(37)

```



```{r load_snakemake, message = FALSE}

sce_02_path <- snakemake@input[["sce_02_path"]]
#sce_03_path <- snakemake@input[["sce_03_path"]]
#sce_04_path <- snakemake@input[["sce_04_path"]]
#sce_05_path <- snakemake@input[["sce_05_path"]]

metadata <- read.csv(file = snakemake@params[["metadata"]], 
                     head = TRUE, 
                     sep = ",", 
                     check.names=FALSE, 
                     stringsAsFactors=FALSE, 
                     as.is=TRUE, 
                     colClasses = "character")

individuals <- snakemake@params[["individuals"]]

nr_hvgs <- snakemake@params[["nr_hvgs"]]
cutoff_sum <- snakemake@params[["cutoff_sum"]]
cutoff_detected <- snakemake@params[["cutoff_detected"]]
cutoff_mitos <- snakemake@params[["cutoff_mitos"]]
color_tables <- snakemake@params[["color_tables"]]

```

```{r}
source(file = "../source/colors.R")
```

# QC

Check Quality per sample.

```{r fig.width = 14}

sce_list_02 <- list()
#print(paste0(sce_02_path, "/sce_", targets[1]))

species <- c("mmus", "mspr", "mcas", "mcar")


  #print(paste0(sce_02_path, "/sce_", i, "-02"))
for(s in species){
  for(i in individuals){
    if(grepl(s, i) == TRUE){
      sce_list_02[[i]] <- readRDS(file = paste0(sce_02_path, "/", s, "/sce_", i, "-02"))
    }
  }
}

qcdf_list_02 <- lapply(sce_list_02, function(sce){
  
  mito_genes <- grep("mt-", rownames(sce))

  qcdf <- perCellQCMetrics(sce, subsets=list(Mito=mito_genes))
  qcdf$Object_ID <- sce$Object_ID
  qcdf$Species_ID <- sce$Species_ID
  qcdf$Age <- sce$Age
  qcdf$Batch_exp_day <- sce$Batch_exp_day
  qcdf$Batch_sequencing <- sce$Batch_sequencing
  qcdf$Date_collected <- sce$Date_collected
  qcdf$Species <- sce$Species
  qcdf$Fraction <- sce$Fraction
  qcdf$Keep_sample <- sce$Keep_sample

  sum_out <- qcdf$sum < cutoff_sum 
  det_out <- qcdf$detected < cutoff_detected 
  mito_out <- qcdf$subsets_Mito_percent > cutoff_mitos
  
  remove_pos <- sum_out | det_out | mito_out
  qcdf$removed <- remove_pos
  
  return(qcdf)
})

qcdf_gg <- DataFrame()

for(i in qcdf_list_02){
  qcdf_gg <- rbind(qcdf_gg, i)
}
qcdf_gg <- data.frame(qcdf_gg)

# by Sample
ggplot(qcdf_gg, aes(x = Object_ID, y = sum, color = removed, alpha = Keep_sample))+
  ggbeeswarm::geom_quasirandom(size = 0.1)+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 120000))+
  ggtitle(paste("cutoff sum = ", cutoff_sum))+ 
  scale_y_log10()+
  scale_alpha_discrete("Samples to keep", range = c("FALSE" = 0.02, "TRUE" = 0.7))+
  scale_color_manual("Cells to remove", values = c("TRUE" = "black", "FALSE" = "grey80"))
  

ggplot(qcdf_gg, aes(x = Object_ID, y = detected, color = removed, alpha = Keep_sample))+
  ggbeeswarm::geom_quasirandom(size = 0.1)+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 10000))+
  ggtitle(paste("cutoff detected = ", cutoff_detected))+ 
  scale_y_log10()+
  scale_alpha_discrete("Samples to keep", range = c("FALSE" = 0.02, "TRUE" = 0.7))+
  scale_color_manual("Cells to remove", values = c("TRUE" = "black", "FALSE" = "grey80"))

# by Species_ID
ggplot(qcdf_gg[qcdf_gg$Keep_sample == TRUE,], aes(x = Species_ID, y = sum, color = removed))+
  ggbeeswarm::geom_quasirandom(alpha = 0.5, size = 0.1)+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 120000))+
  ggtitle(paste("cutoff sum = ", cutoff_sum))+ 
  scale_y_log10() +
  scale_color_manual("Cells to remove", values = c("TRUE" = "black", "FALSE" = "grey80"))

ggplot(qcdf_gg[qcdf_gg$Keep_sample == TRUE,], aes(x = Species_ID, y = detected, color = removed))+
  ggbeeswarm::geom_quasirandom(alpha = 0.5, size = 0.1)+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 10000))+
  ggtitle(paste("cutoff detected = ", cutoff_detected))+ 
  scale_y_log10()+
  scale_color_manual("Cells to remove", values = c("TRUE" = "black", "FALSE" = "grey80"))

# by Age
ggplot(qcdf_gg[qcdf_gg$Keep_sample == TRUE,], aes(x = Age, y = sum, color = removed))+
  ggbeeswarm::geom_quasirandom(alpha = 0.5, size = 0.1)+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 120000))+
  ggtitle(paste("cutoff sum = ", cutoff_sum))+ 
  scale_y_log10()+
  scale_color_manual("Cells to remove", values = c("TRUE" = "black", "FALSE" = "grey80")) 

ggplot(qcdf_gg[qcdf_gg$Keep_sample == TRUE,], aes(x = Age, y = detected, color = removed))+
  ggbeeswarm::geom_quasirandom(alpha = 0.5, size = 0.1)+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 10000))+
  ggtitle(paste("cutoff detected = ", cutoff_detected))+ 
  scale_y_log10() +
  scale_color_manual("Cells to remove", values = c("TRUE" = "black", "FALSE" = "grey80"))

# by Fraction
ggplot(qcdf_gg[qcdf_gg$Keep_sample == TRUE,], aes(x = Fraction, y = sum, color = removed))+
  ggbeeswarm::geom_quasirandom(alpha = 0.5, size = 0.1)+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 120000))+
  ggtitle(paste("cutoff sum = ", cutoff_sum))+ 
  scale_y_log10() +
  scale_color_manual("Cells to remove", values = c("TRUE" = "black", "FALSE" = "grey80"))

ggplot(qcdf_gg[qcdf_gg$Keep_sample == TRUE,], aes(x = Fraction, y = detected, color = removed))+
  ggbeeswarm::geom_quasirandom(alpha = 0.5, size = 0.1)+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 10000))+
  ggtitle(paste("cutoff detected = ", cutoff_detected))+ 
  scale_y_log10() +
  scale_color_manual("Cells to remove", values = c("TRUE" = "black", "FALSE" = "grey80"))

# by Batch_exp_day
ggplot(qcdf_gg[qcdf_gg$Keep_sample == TRUE,], aes(x = Batch_exp_day, y = sum, color = removed))+
  ggbeeswarm::geom_quasirandom(alpha = 0.5, size = 0.1)+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 120000))+
  ggtitle(paste("cutoff sum = ", cutoff_sum)) + 
  scale_y_log10() +
  scale_color_manual("Cells to remove", values = c("TRUE" = "black", "FALSE" = "grey80"))

ggplot(qcdf_gg[qcdf_gg$Keep_sample == TRUE,], aes(x = Batch_exp_day, y = detected, color = removed))+
  ggbeeswarm::geom_quasirandom(alpha = 0.5, size = 0.1)+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 10000))+
  ggtitle(paste("cutoff detected = ", cutoff_detected))+ 
  scale_y_log10() +
  scale_color_manual("Cells to remove", values = c("TRUE" = "black", "FALSE" = "grey80"))

# by Batch_sequencing
ggplot(qcdf_gg[qcdf_gg$Keep_sample == TRUE,], aes(x = Batch_sequencing, y = sum, color = removed))+
  ggbeeswarm::geom_quasirandom(alpha = 0.5, size = 0.1)+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 120000))+
  ggtitle(paste("cutoff sum = ", cutoff_sum))+ 
  scale_y_log10()+
  scale_color_manual("Cells to remove", values = c("TRUE" = "black", "FALSE" = "grey80")) 

ggplot(qcdf_gg[qcdf_gg$Keep_sample == TRUE,], aes(x = Batch_sequencing, y = detected, color = removed))+
  ggbeeswarm::geom_quasirandom(alpha = 0.5, size = 0.1)+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 10000))+
  ggtitle(paste("cutoff detected = ", cutoff_detected))+ 
  scale_y_log10() +
  scale_color_manual("Cells to remove", values = c("TRUE" = "black", "FALSE" = "grey80"))

# by Date_collected
ggplot(qcdf_gg[qcdf_gg$Keep_sample == TRUE,], aes(x = Date_collected, y = sum, color = removed))+
  ggbeeswarm::geom_quasirandom(alpha = 0.5, size = 0.1)+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 120000))+
  ggtitle(paste("cutoff sum = ", cutoff_sum))+ 
  scale_y_log10()+
  scale_color_manual("Cells to remove", values = c("TRUE" = "black", "FALSE" = "grey80")) 

ggplot(qcdf_gg[qcdf_gg$Keep_sample == TRUE,], aes(x = Date_collected, y = detected, color = removed))+
  ggbeeswarm::geom_quasirandom(alpha = 0.5, size = 0.1)+
  theme_classic()+
  theme(axis.text = element_text(angle = 90))+
  ylim(limits = c(0, 10000))+
  ggtitle(paste("cutoff detected = ", cutoff_detected))+ 
  scale_y_log10() +
  scale_color_manual("Cells to remove", values = c("TRUE" = "black", "FALSE" = "grey80"))

```

```{r}
sessionInfo()
```
