---
title: "DGE age bulk quality report"
author: "Lea Wölbert"
date: '2023-01-04'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Load objects

```{r seed,  message = FALSE}
set.seed(37)
```

```{r load,  message = FALSE}
library(pcaExplorer)
library(pheatmap)
library(RColorBrewer)
library(SingleCellExperiment)
```

```{r source, message = FALSE}
source(file =  snakemake@params[["plotting"]])
```

```{r load_objects}
rlog_list = base::readRDS(snakemake@input[["rlog"]])

fraction_curr <- snakemake@wildcards[["fraction"]]
species_curr <- snakemake@wildcards[["species"]]

print(names(rlog_list))
print(head(rlog_list[[1]]))
```

```{r colors, meassage = FALSE}
colors_path <- snakemake@params[["colors_path"]]
source(snakemake@params[["colors"]])
```

# QC

```{r plot_function, echo=FALSE, message=FALSE, results='hide'}

plotlist <- list()

for(ct in names(rlog_list)){

  rld_pca <- stats::prcomp(t(SummarizedExperiment::assay(rlog_list[[ct]])))

  ggdf <- base::as.data.frame(rld_pca$x)
  ggdf$Antibody_combination <- colData(rlog_list[[ct]])$Antibody_combination
  ggdf$age <- colData(rlog_list[[ct]])$age
  ggdf$batch <- colData(rlog_list[[ct]])$batch
  ggdf$Batch_sequencing <- colData(rlog_list[[ct]])$Batch_sequencing
  ggdf$sample <- colData(rlog_list[[ct]])$sample
  ggdf$ncells <- colData(rlog_list[[ct]])$ncells


  plot1 <- ggplot2::ggplot(ggdf, aes(x = PC1, y = PC2, color = age))+
    ggplot2::geom_point(size = 3)+
    ggplot2::theme_classic()+
    ggplot2::theme(axis.text = element_blank(),
                   axis.ticks = element_blank())+
    ggplot2::scale_color_manual("age", values = col_age)+
    ggplot2::ggtitle(full_title)

  plot2 <- ggplot2::ggplot(ggdf, aes(x = PC1, y = PC2, color = batch))+
    ggplot2::geom_point(size = 3)+
    ggplot2::theme_classic()+
    ggplot2::theme(axis.text = element_blank(),
                   axis.ticks = element_blank())+
    ggplot2::ggtitle(full_title)

  plot3 <- ggplot2::ggplot(ggdf, 
                           aes(x = PC1, y = PC2, color = Antibody_combination))+
    ggplot2::geom_point(size = 3)+
    ggplot2::theme_classic()+
    ggplot2::theme(axis.text = element_blank(),
                   axis.ticks = element_blank())+
    ggplot2::ggtitle(full_title)

  plot4 <- ggplot2::ggplot(ggdf, aes(x = PC1, y = PC2, color = ncells))+
    ggplot2::geom_point(size = 3)+
    ggplot2::theme_classic()+
    ggplot2::theme(axis.text = element_blank(),
                   axis.ticks = element_blank())+
    ggplot2::ggtitle(full_title)


  
  plotlist[[ct]] <- list(
    plot1,
    plot2,
    plot3,
    plot4
  )
}
```

```{r print, fig.width = 5, fig.height = 4}
plotlist
```

```{r}

for(ct in names(rlog_list)){

  rld_pca <- stats::prcomp(t(SummarizedExperiment::assay(rlog_list[[ct]])))
  rld_cor <- pcaExplorer::correlatePCs(rld_pca, colData(rlog_list[[ct]]))

  full_title <- base::paste(ct, species_curr, fraction_curr)
  
  # plots
  print(ct)
  pcaExplorer::distro_expr(rlog_list[[ct]], plot_type = "boxplot")+
    ggplot2::theme_classic()+
    ggplot2::theme(axis.text.x = element_text(angle = 90))+
    ggplot2::theme(legend.position = "none")+
    ggplot2::ggtitle(full_title)
  
  pcaExplorer::plotPCcorrs(rld_cor)
  
  pcaExplorer::pcascree(rld_pca, type="pev", title = full_title)

  pcaExplorer::hi_loadings(rld_pca, 
                           topN = 20,
                           whichpc = 1,
                           title = full_title)

  pcaExplorer::hi_loadings(rld_pca, 
                           topN = 20, 
                           whichpc = 2,
                           title = full_title)
  
  # distance heatmap
  sampleDists <- stats::dist(t(SummarizedExperiment::assay(rlog_list[[ct]])))
  
  sampleDistMatrix <- base::as.matrix(sampleDists)
  rownames(sampleDistMatrix) <- rlog_list[[ct]]$condition
  colnames(sampleDistMatrix) <- NULL
  
  colors <- grDevices::colorRampPalette(
    base::rev(RColorBrewer::brewer.pal(9, "Blues")) )(255)
  
  pheatmap::pheatmap(sampleDistMatrix,
                     clustering_distance_rows=sampleDists,
                     clustering_distance_cols=sampleDists,
                     col=colors)
  
  
}
  
```


```{r session_info}
utils::sessionInfo()
```