---
title: "DGE report on hidden sources of variation"
author: "Lea Wölbert"
date: '2024-07-12'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

For each species and cell type, show the estimated hidden sources of variation
from each sample.

#### Load objects

```{r seed,  message = FALSE}
set.seed(37)
```

```{r load,  message = FALSE}
library(DESeq2, quietly = TRUE)
```

```{r source, message = FALSE}
#source(file =  snakemake@params[["plotting"]])
```

```{r manual, eval = FALSE, include = FALSE}

dsq_list <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/scRNAseq/main_analysis/sce_objects/03_sce_analysis/01_DESeq2_crossage/01_desq/deseq_mmus_str")

sva_list <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/scRNAseq/main_analysis/sce_objects/03_sce_analysis/01_DESeq2_crossage/02_dsqc/sva_mmus_str")

rlog_list <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/scRNAseq/main_analysis/sce_objects/03_sce_analysis/01_DESeq2_crossage/02_dsqc/rlog_mmus_str")

sv_path <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/metadata/scRNAseq/03_sce_analysis/sources_variation.txt")


```

```{r load_objects, message = FALSE}

species_curr <- snakemake@wildcards[["species"]]

dsq_list <- base::readRDS(snakemake@input[["dsq_list"]])
sva_list <- base::readRDS(snakemake@input[["sva_list"]])

print(names(dsq_list))
print(names(sva_list))
```

```{r subset_sva_list}
return_list <- list()

for(ct in names(sva_list)){
  if(!is.null(ncol(sva_list[[ct]][[2]]$sv[1]))){
    print(sva_list[[ct]][[2]]$n.sv)
    return_list[[ct]][["sva"]] <- sva_list[[ct]][[2]]$sv
    
    colData(dsq_list[[ct]])$cell_types <- base::rep(ct, ncol(dsq_list[[ct]]))
    return_list[[ct]][["dsq"]] <- dsq_list[[ct]]
  }
}
names(return_list)
if(length(return_list) == 0){
  knitr::knit_exit()
}
for(i in 1:length(return_list)){
  print(return_list[[i]]$sva)
}
```

```{r plot_function}

# function for making plots 
make_plots <- function(return){

  dsq <- return$dsq
  sva <- return$sva
  
  # prepare data
  colnames(sva) <- base::paste0("sva_", c(1:ncol(sva)))
  sv_list <- as.list(colnames(sva))
  
  ct <- colData(dsq)$cell_types[1]
  
  # in case there is more than one SV
  plotlist <- lapply(sv_list, function(sv){
    
    ggdf <- base::as.data.frame(colData(dsq))
    ggdf$SV <- sva[,sv]
    
    title_full <- base::paste(species_curr, sv, ct)
    
    plot1 <- ggplot2::ggplot(ggdf, aes(y = SV, x = sample))+
      ggplot2::geom_point()+
      ggplot2::theme_classic()+
      ggplot2::theme(axis.text.x = element_text(angle = 90))+
      ggplot2::ggtitle(title_full)+
      ggplot2::geom_hline(yintercept = 0, color = "dodgerblue3")
  
    plot2 <- ggplot2::ggplot(ggdf, aes(y = SV, x = batch))+
      ggplot2::geom_point()+
      ggplot2::theme_classic()+
      ggplot2::theme(axis.text.x = element_text(angle = 90))+
      ggplot2::ggtitle(title_full)+
      ggplot2::geom_hline(yintercept = 0, color = "dodgerblue3")
  
    plot3 <- ggplot2::ggplot(ggdf, aes(y = SV, x = condition))+
      ggplot2::geom_point()+
      ggplot2::theme_classic()+
      ggplot2::theme(axis.text.x = element_text(angle = 90))+
      ggplot2::ggtitle(title_full)+
      ggplot2::geom_hline(yintercept = 0, color = "dodgerblue3")
  
    plot4 <- ggplot2::ggplot(ggdf, aes(y = SV, x = ncells))+
      ggplot2::geom_point()+
      ggplot2::theme_classic()+
      ggplot2::theme(axis.text.x = element_text(angle = 90))+
      ggplot2::ggtitle(title_full)+
      ggplot2::geom_hline(yintercept = 0, color = "dodgerblue3")
  
    plot5 <- ggplot2::ggplot(ggdf, aes(y = SV, x = Antibody_combination))+
      ggplot2::geom_point()+
      ggplot2::theme_classic()+
      ggplot2::theme(axis.text.x = element_text(angle = 90))+
      ggplot2::ggtitle(title_full)+
      ggplot2::geom_hline(yintercept = 0, color = "dodgerblue3")
  
    plot6 <- ggplot2::ggplot(ggdf, aes(y = SV, x = Batch_sequencing))+
      ggplot2::geom_point()+
      ggplot2::theme_classic()+
      ggplot2::theme(axis.text.x = element_text(angle = 90))+
      ggplot2::ggtitle(title_full)+
      ggplot2::geom_hline(yintercept = 0, color = "dodgerblue3")
  
    return(list(plot1, plot2, plot3, plot4, plot5, plot6))
  })
  return(plotlist)
}

plots <- make_plots(return_list)

```

```{r print_plots}
print(plots)
```

```{r session_info}
utils::sessionInfo()
```