---
title: "Custom clustering comparison"
author: "Lea Wölbert"
date: '2025-11-10'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This report is to compare the custom clusterings to the original merged
clustering.

#### Load libraries, source code 

```{r seed, message = FALSE}
set.seed(37)
```

```{r source, message = FALSE}
source(file = snakemake@params[["plotting"]])
source(file = snakemake@params[["custom_utils"]])
```

```{r colors, message = FALSE}
colors_path <- snakemake@params[["colors_path"]]
source(snakemake@params[["colors"]])

col_cts_str <- c(col_cts_str, "removed" = "grey70")
col_cts_str_orig <- col_cts_str
names(col_cts_str_orig) <- paste0("orig ", names(col_cts_str_orig))
col_cts_str_orig
```

```{r libraries, message = FALSE}
library(SingleCellExperiment, quietly = TRUE)
library(tidyverse, quietly = TRUE)
library(ggalluvial, quietly = TRUE)
```

```{r load_objects}
sce_mmus_str <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/scRNAseq/main_analysis/sce_objects/02_sce_anno/02_clst/custom/sce_mmus_str_custom.rds")
sce_mcas_str <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/scRNAseq/main_analysis/sce_objects/02_sce_anno/02_clst/custom/sce_mcas_str_custom.rds")
sce_mspr_str <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/scRNAseq/main_analysis/sce_objects/02_sce_anno/02_clst/custom/sce_mspr_str_custom.rds")
sce_mcar_str <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/scRNAseq/main_analysis/sce_objects/02_sce_anno/02_clst/custom/sce_mcar_str_custom.rds")
```

```{r load_merged}
sce_str_all_cells <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/scRNAseq/main_analysis/sce_objects/02_sce_anno/02_clst/sce_str-02")

# remove unnecessary assays because the objects become too large to load
assays(sce_str_all_cells) <- list(
  counts = assays(sce_str_all_cells)$counts,
  logcounts = assays(sce_str_all_cells)$logcounts
)
reducedDims(sce_str_all_cells) <- list(
  UMAP = reducedDims(sce_str_all_cells)$UMAP
)
gc()
```

```{r cluster_labels}
# add all labels to the object that contains all cells

sce_str_all_cells$custom_label <- vector(length = ncol(sce_str_all_cells))

sce_mmus_str$custom_label <- unfactor(sce_mmus_str$custom_label)
sce_mcas_str$custom_label <- unfactor(sce_mcas_str$custom_label)
sce_mspr_str$custom_label <- unfactor(sce_mspr_str$custom_label)
sce_mcar_str$custom_label <- unfactor(sce_mcar_str$custom_label)

sce_str_all_cells$custom_label[match(
  colnames(sce_mmus_str), colnames(sce_str_all_cells))] <- sce_mmus_str$custom_label
sce_str_all_cells$custom_label[match(
  colnames(sce_mcas_str), colnames(sce_str_all_cells))] <- sce_mcas_str$custom_label
sce_str_all_cells$custom_label[match(
  colnames(sce_mspr_str), colnames(sce_str_all_cells))] <- sce_mspr_str$custom_label
sce_str_all_cells$custom_label[match(
  colnames(sce_mcar_str), colnames(sce_str_all_cells))] <- sce_mcar_str$custom_label

rm(
  sce_mmus_str,
  sce_mcas_str,
  sce_mspr_str,
  sce_mcar_str)
gc()
```

```{r load_anno}
sce_str_anno <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data_freeze/05_annotated_objects/sce_str.rds")

sce_str_all_cells$celltypes <- vector(length = ncol(sce_str_all_cells))
sce_str_all_cells$celltypes <- sce_str_anno$celltypes[
  match(colnames(sce_str_all_cells), colnames(sce_str_anno))]

rm(sce_str_anno)
gc()

# i have removed some cells from the finally annotated object, so those
# that are missing from that object are not called "removed"
levels(sce_str_all_cells$celltypes) <- c(
  levels(sce_str_all_cells$celltypes), 
  "removed")
sce_str_all_cells$celltypes[is.na(sce_str_all_cells$celltypes)] <- "removed"

# randomize the barcodes for nicer visualisation
sce_str_all_cells <- sce_str_all_cells[,base::sample(
  x = c(1:ncol(sce_str_all_cells)), 
  size = ncol(sce_str_all_cells),
  replace = FALSE)]

print(sort(unique(sce_str_all_cells$custom_label)))
```

## Basics

```{r factor_and_colors}

# for nicer handling factor the custom labels, too
# from the soruced custom_utils
sce_str_all_cells$custom_label <- factor(
  sce_str_all_cells$custom_label, 
  levels = factors_custom_str)

col_custom <- col_custom_str

stopifnot(!is.na(sce_str_all_cells$custom_label))
```

```{r tables}
table(
  sce_str_all_cells$celltypes,
  sce_str_all_cells$custom_label)

table(
  sce_str_all_cells$celltypes[sce_str_all_cells$Species_ID == "mmus"],
  sce_str_all_cells$custom_label[sce_str_all_cells$Species_ID == "mmus"])

table(
  sce_str_all_cells$celltypes[sce_str_all_cells$Species_ID == "mcas"],
  sce_str_all_cells$custom_label[sce_str_all_cells$Species_ID == "mcas"])

table(
  sce_str_all_cells$celltypes[sce_str_all_cells$Species_ID == "mspr"],
  sce_str_all_cells$custom_label[sce_str_all_cells$Species_ID == "mspr"])

table(
  sce_str_all_cells$celltypes[sce_str_all_cells$Species_ID == "mcar"],
  sce_str_all_cells$custom_label[sce_str_all_cells$Species_ID == "mcar"])
```

## Comparison

### UMAPs

```{r umap_all_custom, fig.height = 4, fig.width = 4}
umap_base(sce_str_all_cells, "custom_label")+
  ggplot2::scale_color_manual(values = col_custom)
```

```{r umap_all_orig, fig.height = 4, fig.width = 4}
umap_base(sce_str_all_cells, "celltypes")+
  ggplot2::scale_color_manual(values = col_cts_str)
```

```{r umap_spec_custom, fig.height = 8, fig.width = 8}
umap_base(sce_str_all_cells, "custom_label")+
  ggplot2::scale_color_manual(values = col_custom)+
  ggplot2::facet_wrap(facets = vars(sce_str_all_cells$Species_ID))
```

```{r umap_spec_orig, fig.height = 8, fig.width = 8}
umap_base(sce_str_all_cells, "celltypes")+
  ggplot2::scale_color_manual(values = col_cts_str)+
  ggplot2::facet_wrap(facets = vars(sce_str_all_cells$Species_ID))
```

### Tiles

```{r mmus_tiles}
mat_mmus <- table(
  sce_str_all_cells$celltypes[sce_str_all_cells$Species_ID == "mmus"],
  sce_str_all_cells$custom_label[sce_str_all_cells$Species_ID == "mmus"])

for(i in 1:ncol(mat_mmus)){
  mat_mmus[,i] <- mat_mmus[,i]/base::sum(mat_mmus[,i])
}
mmus_df <- mat_mmus %>%
  base::as.data.frame() %>%
  dplyr::filter(!is.nan(Freq))

mmus_df$Var2 <- factor(
  mmus_df$Var2, 
  levels = rev(levels(sce_str_all_cells$custom_label)[
    levels(sce_str_all_cells$custom_label) %in% unique(unfactor(mmus_df$Var2))]))

ggplot2::ggplot(
  mmus_df, 
  aes(x = Var1, 
      y = Var2,
      fill = Freq))+
  ggplot2::geom_tile()+
  ggplot2::theme_classic()+
  ggplot2::theme(
    axis.text.x = element_text(
      angle = 90,
      vjust = 0.5, 
      hjust = 1
    )
  )
```

```{r mcas_tiles}
mat_mcas <- table(
  sce_str_all_cells$celltypes[sce_str_all_cells$Species_ID == "mcas"],
  sce_str_all_cells$custom_label[sce_str_all_cells$Species_ID == "mcas"])

for(i in 1:ncol(mat_mcas)){
  mat_mcas[,i] <- mat_mcas[,i]/base::sum(mat_mcas[,i])
}
mcas_df <- mat_mcas %>%
  base::as.data.frame() %>%
  dplyr::filter(!is.nan(Freq))

mcas_df$Var2 <- factor(
  mcas_df$Var2, 
  levels = rev(levels(sce_str_all_cells$custom_label)[
    levels(sce_str_all_cells$custom_label) %in% unique(unfactor(mcas_df$Var2))]))

ggplot2::ggplot(
  mcas_df, 
  aes(x = Var1, 
      y = Var2,
      fill = Freq))+
  ggplot2::geom_tile()+
  ggplot2::theme_classic()+
  ggplot2::theme(
    axis.text.x = element_text(
      angle = 90,
      vjust = 0.5, 
      hjust = 1
    )
  )
```

```{r mspr_tiles}
mat_mspr <- table(
  sce_str_all_cells$celltypes[sce_str_all_cells$Species_ID == "mspr"],
  sce_str_all_cells$custom_label[sce_str_all_cells$Species_ID == "mspr"])

for(i in 1:ncol(mat_mspr)){
  mat_mspr[,i] <- mat_mspr[,i]/base::sum(mat_mspr[,i])
}
mspr_df <- mat_mspr %>%
  base::as.data.frame() %>%
  dplyr::filter(!is.nan(Freq))

mspr_df$Var2 <- factor(
  mspr_df$Var2, 
  levels = rev(levels(sce_str_all_cells$custom_label)[
    levels(sce_str_all_cells$custom_label) %in% unique(unfactor(mspr_df$Var2))]))

ggplot2::ggplot(
  mspr_df, 
  aes(x = Var1, 
      y = Var2,
      fill = Freq))+
  ggplot2::geom_tile()+
  ggplot2::theme_classic()+
  ggplot2::theme(
    axis.text.x = element_text(
      angle = 90,
      vjust = 0.5, 
      hjust = 1
    )
  )
```

```{r mcar_tiles}
mat_mcar <- table(
  sce_str_all_cells$celltypes[sce_str_all_cells$Species_ID == "mcar"],
  sce_str_all_cells$custom_label[sce_str_all_cells$Species_ID == "mcar"])

for(i in 1:ncol(mat_mcar)){
  mat_mcar[,i] <- mat_mcar[,i]/base::sum(mat_mcar[,i])
}
mcar_df <- mat_mcar %>%
  base::as.data.frame() %>%
  dplyr::filter(!is.nan(Freq))

mcar_df$Var2 <- factor(
  mcar_df$Var2, 
  levels = rev(levels(sce_str_all_cells$custom_label)[
    levels(sce_str_all_cells$custom_label) %in% unique(unfactor(mcar_df$Var2))]))

ggplot2::ggplot(
  mcar_df, 
  aes(x = Var1, 
      y = Var2,
      fill = Freq))+
  ggplot2::geom_tile()+
  ggplot2::theme_classic()+
  ggplot2::theme(
    axis.text.x = element_text(
      angle = 90,
      vjust = 0.5, 
      hjust = 1
    )
  )
```

### Alluvial plots

```{r mmus_alluv, fig.height = 9, fig.width = 8}
mat_mmus <- table(
  sce_str_all_cells$celltypes[sce_str_all_cells$Species_ID == "mmus"],
  sce_str_all_cells$custom_label[sce_str_all_cells$Species_ID == "mmus"])

mmus_df <- mat_mmus %>%
  base::as.data.frame() %>%
  dplyr::filter(!is.nan(Freq))

mmus_df$Var2_rev <- mmus_df$Var2
mmus_df$Var2_rev <- factor(
  mmus_df$Var2_rev, 
  levels = rev(levels(mmus_df$Var2)))

mmus_df2 <- mmus_df %>%
  dplyr::mutate(
    Var1_u = fct_inorder(paste0("orig ", Var1)),
    Var2_u = fct_inorder(paste0("custom ", Var2_rev))
  )

ggplot2::ggplot(data = mmus_df2,
                aes(axis1 = Var1_u,
                    axis2 = Var2_u, 
                    y = Freq))+
  ggalluvial::geom_alluvium(aes(fill = Var1_u))+
  ggalluvial::geom_stratum()+
  ggplot2::geom_text(stat = "stratum",
                     aes(label = after_stat(stratum)))+
  ggplot2::scale_x_discrete(expand = c(0.15, 0.05))+
  theme_void()+
  ggplot2::theme(legend.position = "none")+
  ggplot2::scale_fill_manual(values = col_cts_str_orig)
```

```{r mcas_alluv, fig.height = 9, fig.width = 8}
mat_mcas <- table(
  sce_str_all_cells$celltypes[sce_str_all_cells$Species_ID == "mcas"],
  sce_str_all_cells$custom_label[sce_str_all_cells$Species_ID == "mcas"])

mcas_df <- mat_mcas %>%
  base::as.data.frame() %>%
  dplyr::filter(!is.nan(Freq))

mcas_df$Var2_rev <- mcas_df$Var2
mcas_df$Var2_rev <- factor(
  mcas_df$Var2_rev, 
  levels = rev(levels(mcas_df$Var2)))

mcas_df2 <- mcas_df %>%
  dplyr::mutate(
    Var1_u = fct_inorder(paste0("orig ", Var1)),
    Var2_u = fct_inorder(paste0("custom ", Var2_rev))
  )

ggplot2::ggplot(data = mcas_df2,
                aes(axis1 = Var1_u,
                    axis2 = Var2_u, 
                    y = Freq))+
  ggalluvial::geom_alluvium(aes(fill = Var1_u))+
  ggalluvial::geom_stratum()+
  ggplot2::geom_text(stat = "stratum",
                     aes(label = after_stat(stratum)))+
  ggplot2::scale_x_discrete(expand = c(0.15, 0.05))+
  theme_void()+
  ggplot2::theme(legend.position = "none")+
  ggplot2::scale_fill_manual(values = col_cts_str_orig)
```

```{r mspr_alluv, fig.height = 9, fig.width = 8}
mat_mspr <- table(
  sce_str_all_cells$celltypes[sce_str_all_cells$Species_ID == "mspr"],
  sce_str_all_cells$custom_label[sce_str_all_cells$Species_ID == "mspr"])

mspr_df <- mat_mspr %>%
  base::as.data.frame() %>%
  dplyr::filter(!is.nan(Freq))

mspr_df$Var2_rev <- mspr_df$Var2
mspr_df$Var2_rev <- factor(
  mspr_df$Var2_rev, 
  levels = rev(levels(mspr_df$Var2)))

mspr_df2 <- mspr_df %>%
  dplyr::mutate(
    Var1_u = fct_inorder(paste0("orig ", Var1)),
    Var2_u = fct_inorder(paste0("custom ", Var2_rev))
  )
  
ggplot2::ggplot(data = mspr_df2,
                aes(axis1 = Var1_u,
                    axis2 = Var2_u, 
                    y = Freq))+
  ggalluvial::geom_alluvium(aes(fill = Var1_u))+
  ggalluvial::geom_stratum()+
  ggplot2::geom_text(stat = "stratum",
                     aes(label = after_stat(stratum)))+
  ggplot2::scale_x_discrete(expand = c(0.15, 0.05))+
  theme_void()+
  ggplot2::theme(legend.position = "none")+
  ggplot2::scale_fill_manual(values = col_cts_str_orig)
```

```{r mcar_alluv, fig.height = 9, fig.width = 8}
mat_mcar <- table(
  sce_str_all_cells$celltypes[sce_str_all_cells$Species_ID == "mcar"],
  sce_str_all_cells$custom_label[sce_str_all_cells$Species_ID == "mcar"])

mcar_df <- mat_mcar %>%
  base::as.data.frame() %>%
  dplyr::filter(!is.nan(Freq))

mcar_df$Var2_rev <- mcar_df$Var2
mcar_df$Var2_rev <- factor(
  mcar_df$Var2_rev, 
  levels = rev(levels(mcar_df$Var2)))

mcar_df2 <- mcar_df %>%
  dplyr::mutate(
    Var1_u = fct_inorder(paste0("orig ", Var1)),
    Var2_u = fct_inorder(paste0("custom ", Var2_rev))
  )

ggplot2::ggplot(data = mcar_df2,
                aes(axis1 = Var1_u,
                    axis2 = Var2_u, 
                    y = Freq))+
  ggalluvial::geom_alluvium(aes(fill = Var1_u))+
  ggalluvial::geom_stratum()+
  ggplot2::geom_text(stat = "stratum",
                     aes(label = after_stat(stratum)))+
  ggplot2::scale_x_discrete(expand = c(0.15, 0.05))+
  theme_void()+
  ggplot2::theme(legend.position = "none")+
  ggplot2::scale_fill_manual(values = col_cts_str_orig)
```

```{r all_alluv, fig.height = 18, fig.width = 8}
mat_all <- table(
  sce_str_all_cells$celltypes,
  sce_str_all_cells$custom_label)

all_df <- mat_all %>%
  base::as.data.frame() %>%
  dplyr::filter(!is.nan(Freq))

all_df$Var2_rev <- all_df$Var2
all_df$Var2_rev <- factor(
  all_df$Var2_rev, 
  levels = rev(levels(all_df$Var2)))

all_df2 <- all_df %>%
  dplyr::mutate(
    Var1_u = fct_inorder(paste0("orig ", Var1)),
    Var2_u = fct_inorder(paste0("custom ", Var2_rev))
  )

ggplot2::ggplot(data = all_df2,
                aes(axis1 = Var1_u,
                    axis2 = Var2_u, 
                    y = Freq))+
  ggalluvial::geom_alluvium(aes(fill = Var1_u))+
  ggalluvial::geom_stratum()+
  ggplot2::geom_text(stat = "stratum",
                     aes(label = after_stat(stratum)))+
  ggplot2::scale_x_discrete(expand = c(0.15, 0.05))+
  theme_void()+
  ggplot2::theme(legend.position = "none")+
  ggplot2::scale_fill_manual(values = col_cts_str_orig)
```

