---
title: "Custom clustering comparison"
author: "Lea Wölbert"
date: '2025-11-10'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This report is to compare the custom clusterings to the original merged
clustering.

#### Load libraries, source code 

```{r seed, message = FALSE}
set.seed(37)
```

```{r source, message = FALSE}
source(file =  snakemake@params[["plotting"]])
```

```{r colors, message = FALSE}
colors_path <- snakemake@params[["colors_path"]]
source(snakemake@params[["colors"]])

col_cts_hsc <- c(col_cts_str, "removed" = "grey70")
col_cts_hsc_orig <- col_cts_hsc
names(col_cts_hsc_orig) <- paste0("orig ", names(col_cts_hsc_orig))
col_cts_hsc_orig
```

```{r libraries, message = FALSE}
library(SingleCellExperiment, quietly = TRUE)
library(tidyverse, quietly = TRUE)
library(ggalluvial, quietly = TRUE)
```

```{r load_objects}
sce_mmus_hsc <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/scRNAseq/main_analysis/sce_objects/02_sce_anno/02_clst/custom/sce_mmus_hsc_custom.rds")
sce_mcas_hsc <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/scRNAseq/main_analysis/sce_objects/02_sce_anno/02_clst/custom/sce_mcas_hsc_custom.rds")
sce_mspr_hsc <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/scRNAseq/main_analysis/sce_objects/02_sce_anno/02_clst/custom/sce_mspr_hsc_custom.rds")
sce_mcar_hsc <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/scRNAseq/main_analysis/sce_objects/02_sce_anno/02_clst/custom/sce_mcar_hsc_custom.rds")
```

```{r load_merged}
sce_hsc_all_cells <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/scRNAseq/main_analysis/sce_objects/02_sce_anno/02_clst/sce_hsc-02")

# remove unnecessary assays because the objects become too large to load
assays(sce_hsc_all_cells) <- list(
  counts = assays(sce_hsc_all_cells)$counts,
  logcounts = assays(sce_hsc_all_cells)$logcounts
)
reducedDims(sce_hsc_all_cells) <- list(
  UMAP = reducedDims(sce_hsc_all_cells)$UMAP
)
gc()
```

```{r cluster_labels}
# add all labels to the object that contains all cells

sce_hsc_all_cells$custom_label <- vector(length = ncol(sce_hsc_all_cells))

sce_mmus_hsc$custom_label <- unfactor(sce_mmus_hsc$custom_label)
sce_mcas_hsc$custom_label <- unfactor(sce_mcas_hsc$custom_label)
sce_mspr_hsc$custom_label <- unfactor(sce_mspr_hsc$custom_label)
sce_mcar_hsc$custom_label <- unfactor(sce_mcar_hsc$custom_label)

sce_hsc_all_cells$custom_label[match(
  colnames(sce_mmus_hsc), colnames(sce_hsc_all_cells))] <- sce_mmus_hsc$custom_label
sce_hsc_all_cells$custom_label[match(
  colnames(sce_mcas_hsc), colnames(sce_hsc_all_cells))] <- sce_mcas_hsc$custom_label
sce_hsc_all_cells$custom_label[match(
  colnames(sce_mspr_hsc), colnames(sce_hsc_all_cells))] <- sce_mspr_hsc$custom_label
sce_hsc_all_cells$custom_label[match(
  colnames(sce_mcar_hsc), colnames(sce_hsc_all_cells))] <- sce_mcar_hsc$custom_label

rm(
  sce_mmus_hsc,
  sce_mcas_hsc,
  sce_mspr_hsc,
  sce_mcar_hsc)
gc()
```

```{r load_anno}
sce_hsc_anno <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data_freeze/05_annotated_objects/sce_hsc.rds")

sce_hsc_all_cells$celltypes <- vector(length = ncol(sce_hsc_all_cells))
sce_hsc_all_cells$celltypes <- sce_hsc_anno$celltypes[
  match(colnames(sce_hsc_all_cells), colnames(sce_hsc_anno))]

rm(sce_hsc_anno)
gc()

# i have removed some cells from the finally annotated object, so those
# that are missing from that object are not called "removed"
levels(sce_hsc_all_cells$celltypes) <- c(
  levels(sce_hsc_all_cells$celltypes), 
  "removed")
sce_hsc_all_cells$celltypes[is.na(sce_hsc_all_cells$celltypes)] <- "removed"

# randomize the barcodes for nicer visualisation
sce_hsc_all_cells <- sce_hsc_all_cells[,base::sample(
  x = c(1:ncol(sce_hsc_all_cells)), 
  size = ncol(sce_hsc_all_cells),
  replace = FALSE)]
```

## Basics

```{r factor_and_colors}

# for nicer handling factor the custom labels, too
sce_hsc_all_cells$custom_label <- factor(
  sce_hsc_all_cells$custom_label, 
  levels = c(
    "HSC",
    "HSC/Early Mk",
    "Early MPP cells 1",
    "Early MPP cells 2",
    "MPP cells 1",
    "MPP cells 2",
    "Activated MPP",
    "Activated MPP cells 1",
    "Activated MPP cells 2",
    "Late MPP",
    "Early myeloid",

    "Early granu/mono",
    "Granu/mono progenitor",
    "Neutro progenitor",
    "Later granu/neutro",

    "Early lymphoid",
    "Lymphoid",
    "Late lymphoid",
    "Late/Cycling lymphoid",

    "Baso/Mast progenitor",
    "Mk/E/BM (more Mk and BM)",
    "Mk/E/BM (more Ery)",
    "Early Mk progenitor",
    "Mk/Ery (more Mk)",
    "Mk/Ery",
    "Early ery/baso/mast 1",
    "Early ery/baso/mast 2",
    "Early ery",
    "Early erythroid progenitor",
    "Ery progenitor",
    "Erythroid 1",
    "Erythroid 2",
    "Erythroid 3",
    "Late erythroid progenitor",
    "Latest erythroid progenitor",
    "Cycling",
    "Cycling (more M-phase)",
    "Cycling (more S-phase)",
    "Cycling MPP",
    "Cycling, mostly myeloid",
    "Cycling granu/mono",
    "Cycling ery",
    # separate cells that would be removed
    "Antigen-presenting",
    "Mono/antigen-presenting",
    "Late neutro",
    "Late immune, mixed",
    "Late neutro/ery, mixed",
    "Low quality",
    "Low quality, early",
    "Low quality, neutro",
    "Low quality, ery"
))

col_custom <- c(
  "HSC" = "#4a0805ff", # mmus, mspr, mcar
  "HSC/Early Mk" = "#49006bff", # mcas
  "Early MPP cells 1" = "#6f120fff", # mmus, mcas
  "Early MPP cells 2" = "#b51611ff", # mmus, mcas
  "MPP cells 1" = "#fa221bff", # mspr
  "MPP cells 2" = "#ee8581ff", # mspr
  "Activated MPP" = "#c8605aff", # mmus, mcar 
  "Activated MPP cells 1" = "#f49792ff", # mcasr
  "Activated MPP cells 2" = "#e95e57ff", # mcas
  "Late MPP" = "#e5530fff", # mcas
  "Early myeloid" = "#9d5c1fff", # mspr
  "Early granu/mono" = "#c87121ff", # mcas
  "Granu/mono progenitor" = "#e28c02ff", # mmus, mcar
  "Neutro progenitor" = "#f1ac3dff", # mspr, mcar
  "Later granu/neutro" = "#fc8c23ff", # mcas
  "Early lymphoid" = "#ffd000ff", # mmus, mspr
  "Lymphoid" = "#ffe28aff", # mcas
  "Late lymphoid" = "#faf24fff", # mcar
  "Late/Cycling lymphoid" = "#ffff75ff", # mspr
  "Baso/Mast progenitor" = "#ab00fbff", # mmus, mcas, mspr, mcar
  "Mk/E/BM (more Mk and BM)" = "#6e468bff", # mcar
  "Mk/E/BM (more Ery)" = "#9d81fbff", # mcar
  "Early Mk progenitor" = "#8d0153ff", # mspr
  "Mk/Ery (more Mk)" = "#8e3268ff", # mmus 
  "Mk/Ery" = "#d857a2ff", # mcas
  "Early ery/baso/mast 1" = "#993a8eff", # mspr
  "Early ery/baso/mast 2" = "#d857c9ff", # mspr
  "Early ery" = "#c519bdff", # mmus 
  "Early erythroid progenitor" = "#f4538eff", # mcar
  "Ery progenitor" = "#f989b2ff", # mmus, mcas, mspr
  "Erythroid 1" = "#b32e5fff", # mcar
  "Erythroid 2" = "#ff9bc0ff", # mcar
  "Erythroid 3" = "#f4bde6ff", # mcar
  "Late erythroid progenitor" = "#c26cacff", # mcar
  "Latest erythroid progenitor" = "#6e468bff", # mcar
  "Cycling" = "#b5b5b5ff", # mcas
  "Cycling (more M-phase)" = "#a68482ff", # mmus 
  "Cycling (more S-phase)" = "#cbb9b9ff", # mmus 
  "Cycling MPP" = "#c2ac89ff", # mcar
  "Cycling, mostly myeloid" = "#98877dff", # mspr
  "Cycling granu/mono" = "#dfdcd6ff", # mcar
  "Cycling ery" = "#c3a4b0ff", # mspr
  # separate cells that would be removed
  "Antigen-presenting" = "#4c64fbff", # mcar
  "Mono/antigen-presenting" = "#93a0f7ff", # mspr
  "Late neutro" = "#6cfff5ff", # mmus 
  "Late immune, mixed" = "#37ded3ff", # mmus, mcas, mspr
  "Late neutro/ery, mixed" = "#03b0a5ff", # mcas
  "Low quality" = "#4adf6dff", # mcar
  "Low quality, early" = "#208c39ff", # mspr
  "Low quality, neutro" = "#75811bff", # mspr
  "Low quality, ery" = "#99b835ff" # mspr
)

stopifnot(!is.na(sce_hsc_all_cells$custom_label))

print(col_custom)
```

```{r tables}
table(
  sce_hsc_all_cells$celltypes,
  sce_hsc_all_cells$custom_label)

table(
  sce_hsc_all_cells$celltypes[sce_hsc_all_cells$Species_ID == "mmus"],
  sce_hsc_all_cells$custom_label[sce_hsc_all_cells$Species_ID == "mmus"])

table(
  sce_hsc_all_cells$celltypes[sce_hsc_all_cells$Species_ID == "mcas"],
  sce_hsc_all_cells$custom_label[sce_hsc_all_cells$Species_ID == "mcas"])

table(
  sce_hsc_all_cells$celltypes[sce_hsc_all_cells$Species_ID == "mspr"],
  sce_hsc_all_cells$custom_label[sce_hsc_all_cells$Species_ID == "mspr"])

table(
  sce_hsc_all_cells$celltypes[sce_hsc_all_cells$Species_ID == "mcar"],
  sce_hsc_all_cells$custom_label[sce_hsc_all_cells$Species_ID == "mcar"])
```

## Comparison

### UMAPs

```{r umap_all_custom, fig.height = 4, fig.width = 4}
umap_base(sce_hsc_all_cells, "custom_label")+
  ggplot2::scale_color_manual(values = col_custom)
```

```{r umap_all_orig, fig.height = 4, fig.width = 4}
umap_base(sce_hsc_all_cells, "celltypes")+
  ggplot2::scale_color_manual(values = col_cts_hsc)
```

```{r umap_spec_custom, fig.height = 8, fig.width = 8}
umap_base(sce_hsc_all_cells, "custom_label")+
  ggplot2::scale_color_manual(values = col_custom)+
  ggplot2::facet_wrap(facets = vars(sce_hsc_all_cells$Species_ID))
```

```{r umap_spec_orig, fig.height = 8, fig.width = 8}
umap_base(sce_hsc_all_cells, "celltypes")+
  ggplot2::scale_color_manual(values = col_cts_hsc)+
  ggplot2::facet_wrap(facets = vars(sce_hsc_all_cells$Species_ID))
```

### Tiles

```{r mmus_tiles}
mat_mmus <- table(
  sce_hsc_all_cells$celltypes[sce_hsc_all_cells$Species_ID == "mmus"],
  sce_hsc_all_cells$custom_label[sce_hsc_all_cells$Species_ID == "mmus"])

for(i in 1:ncol(mat_mmus)){
  mat_mmus[,i] <- mat_mmus[,i]/base::sum(mat_mmus[,i])
}
mmus_df <- mat_mmus %>%
  base::as.data.frame() %>%
  dplyr::filter(!is.nan(Freq))

mmus_df$Var2 <- factor(
  mmus_df$Var2, 
  levels = rev(levels(sce_hsc_all_cells$custom_label)[
    levels(sce_hsc_all_cells$custom_label) %in% unique(unfactor(mmus_df$Var2))]))

ggplot2::ggplot(
  mmus_df, 
  aes(x = Var1, 
      y = Var2,
      fill = Freq))+
  ggplot2::geom_tile()+
  ggplot2::theme_classic()+
  ggplot2::theme(
    axis.text.x = element_text(
      angle = 90,
      vjust = 0.5, 
      hjust = 1
    )
  )
```

```{r mcas_tiles}
mat_mcas <- table(
  sce_hsc_all_cells$celltypes[sce_hsc_all_cells$Species_ID == "mcas"],
  sce_hsc_all_cells$custom_label[sce_hsc_all_cells$Species_ID == "mcas"])

for(i in 1:ncol(mat_mcas)){
  mat_mcas[,i] <- mat_mcas[,i]/base::sum(mat_mcas[,i])
}
mcas_df <- mat_mcas %>%
  base::as.data.frame() %>%
  dplyr::filter(!is.nan(Freq))

mcas_df$Var2 <- factor(
  mcas_df$Var2, 
  levels = rev(levels(sce_hsc_all_cells$custom_label)[
    levels(sce_hsc_all_cells$custom_label) %in% unique(unfactor(mcas_df$Var2))]))

ggplot2::ggplot(
  mcas_df, 
  aes(x = Var1, 
      y = Var2,
      fill = Freq))+
  ggplot2::geom_tile()+
  ggplot2::theme_classic()+
  ggplot2::theme(
    axis.text.x = element_text(
      angle = 90,
      vjust = 0.5, 
      hjust = 1
    )
  )
```

```{r mspr_tiles}
mat_mspr <- table(
  sce_hsc_all_cells$celltypes[sce_hsc_all_cells$Species_ID == "mspr"],
  sce_hsc_all_cells$custom_label[sce_hsc_all_cells$Species_ID == "mspr"])

for(i in 1:ncol(mat_mspr)){
  mat_mspr[,i] <- mat_mspr[,i]/base::sum(mat_mspr[,i])
}
mspr_df <- mat_mspr %>%
  base::as.data.frame() %>%
  dplyr::filter(!is.nan(Freq))

mspr_df$Var2 <- factor(
  mspr_df$Var2, 
  levels = rev(levels(sce_hsc_all_cells$custom_label)[
    levels(sce_hsc_all_cells$custom_label) %in% unique(unfactor(mspr_df$Var2))]))

ggplot2::ggplot(
  mspr_df, 
  aes(x = Var1, 
      y = Var2,
      fill = Freq))+
  ggplot2::geom_tile()+
  ggplot2::theme_classic()+
  ggplot2::theme(
    axis.text.x = element_text(
      angle = 90,
      vjust = 0.5, 
      hjust = 1
    )
  )
```

```{r mcar_tiles}
mat_mcar <- table(
  sce_hsc_all_cells$celltypes[sce_hsc_all_cells$Species_ID == "mcar"],
  sce_hsc_all_cells$custom_label[sce_hsc_all_cells$Species_ID == "mcar"])

for(i in 1:ncol(mat_mcar)){
  mat_mcar[,i] <- mat_mcar[,i]/base::sum(mat_mcar[,i])
}
mcar_df <- mat_mcar %>%
  base::as.data.frame() %>%
  dplyr::filter(!is.nan(Freq))

mcar_df$Var2 <- factor(
  mcar_df$Var2, 
  levels = rev(levels(sce_hsc_all_cells$custom_label)[
    levels(sce_hsc_all_cells$custom_label) %in% unique(unfactor(mcar_df$Var2))]))

ggplot2::ggplot(
  mcar_df, 
  aes(x = Var1, 
      y = Var2,
      fill = Freq))+
  ggplot2::geom_tile()+
  ggplot2::theme_classic()+
  ggplot2::theme(
    axis.text.x = element_text(
      angle = 90,
      vjust = 0.5, 
      hjust = 1
    )
  )
```

### Alluvial

```{r mmus_alluv, fig.height = 9, fig.width = 8}
mat_mmus <- table(
  sce_hsc_all_cells$celltypes[sce_hsc_all_cells$Species_ID == "mmus"],
  sce_hsc_all_cells$custom_label[sce_hsc_all_cells$Species_ID == "mmus"])

mmus_df <- mat_mmus %>%
  base::as.data.frame() %>%
  dplyr::filter(!is.nan(Freq))

mmus_df$Var2_rev <- mmus_df$Var2
mmus_df$Var2_rev <- factor(
  mmus_df$Var2_rev, 
  levels = rev(levels(mmus_df$Var2)))

mmus_df2 <- mmus_df %>%
  dplyr::mutate(
    Var1_u = fct_inorder(paste0("orig ", Var1)),
    Var2_u = fct_inorder(paste0("custom ", Var2_rev))
  )

ggplot2::ggplot(data = mmus_df2,
                aes(axis1 = Var1_u,
                    axis2 = Var2_u, 
                    y = Freq))+
  ggalluvial::geom_alluvium(aes(fill = Var1_u))+
  ggalluvial::geom_stratum()+
  ggplot2::geom_text(stat = "stratum",
                     aes(label = after_stat(stratum)))+
  ggplot2::scale_x_discrete(expand = c(0.15, 0.05))+
  theme_void()+
  ggplot2::theme(legend.position = "none")+
  ggplot2::scale_color_manual(values = col_cts_hsc_orig)
```

```{r mcas_alluv, fig.height = 9, fig.width = 8}
mat_mcas <- table(
  sce_hsc_all_cells$celltypes[sce_hsc_all_cells$Species_ID == "mcas"],
  sce_hsc_all_cells$custom_label[sce_hsc_all_cells$Species_ID == "mcas"])

mcas_df <- mat_mcas %>%
  base::as.data.frame() %>%
  dplyr::filter(!is.nan(Freq))

mcas_df$Var2_rev <- mcas_df$Var2
mcas_df$Var2_rev <- factor(
  mcas_df$Var2_rev, 
  levels = rev(levels(mcas_df$Var2)))

mcas_df2 <- mcas_df %>%
  dplyr::mutate(
    Var1_u = fct_inorder(paste0("orig ", Var1)),
    Var2_u = fct_inorder(paste0("custom ", Var2_rev))
  )

ggplot2::ggplot(data = mcas_df2,
                aes(axis1 = Var1_u,
                    axis2 = Var2_u, 
                    y = Freq))+
  ggalluvial::geom_alluvium(aes(fill = Var1_u))+
  ggalluvial::geom_stratum()+
  ggplot2::geom_text(stat = "stratum",
                     aes(label = after_stat(stratum)))+
  ggplot2::scale_x_discrete(expand = c(0.15, 0.05))+
  theme_void()+
  ggplot2::theme(legend.position = "none")+
  ggplot2::scale_color_manual(values = col_cts_hsc_orig)
```

```{r mspr_alluv, fig.height = 9, fig.width = 8}
mat_mspr <- table(
  sce_hsc_all_cells$celltypes[sce_hsc_all_cells$Species_ID == "mspr"],
  sce_hsc_all_cells$custom_label[sce_hsc_all_cells$Species_ID == "mspr"])

mspr_df <- mat_mspr %>%
  base::as.data.frame() %>%
  dplyr::filter(!is.nan(Freq))

mspr_df$Var2_rev <- mspr_df$Var2
mspr_df$Var2_rev <- factor(
  mspr_df$Var2_rev, 
  levels = rev(levels(mspr_df$Var2)))

mspr_df2 <- mspr_df %>%
  dplyr::mutate(
    Var1_u = fct_inorder(paste0("orig ", Var1)),
    Var2_u = fct_inorder(paste0("custom ", Var2_rev))
  )

ggplot2::ggplot(data = mspr_df2,
                aes(axis1 = Var1_u,
                    axis2 = Var2_u, 
                    y = Freq))+
  ggalluvial::geom_alluvium(aes(fill = Var1_u))+
  ggalluvial::geom_stratum()+
  ggplot2::geom_text(stat = "stratum",
                     aes(label = after_stat(stratum)))+
  ggplot2::scale_x_discrete(expand = c(0.15, 0.05))+
  theme_void()+
  ggplot2::theme(legend.position = "none")+
  ggplot2::scale_color_manual(values = col_cts_hsc_orig)
```

```{r mcar_alluv, fig.height = 9, fig.width = 8}
mat_mcar <- table(
  sce_hsc_all_cells$celltypes[sce_hsc_all_cells$Species_ID == "mcar"],
  sce_hsc_all_cells$custom_label[sce_hsc_all_cells$Species_ID == "mcar"])

mcar_df <- mat_mcar %>%
  base::as.data.frame() %>%
  dplyr::filter(!is.nan(Freq))

mcar_df$Var2_rev <- mcar_df$Var2
mcar_df$Var2_rev <- factor(
  mcar_df$Var2_rev, 
  levels = rev(levels(mcar_df$Var2)))

mcar_df2 <- mcar_df %>%
  dplyr::mutate(
    Var1_u = fct_inorder(paste0("orig ", Var1)),
    Var2_u = fct_inorder(paste0("custom ", Var2_rev))
  )

ggplot2::ggplot(data = mcar_df2,
                aes(axis1 = Var1_u,
                    axis2 = Var2_u, 
                    y = Freq))+
  ggalluvial::geom_alluvium(aes(fill = Var1_u))+
  ggalluvial::geom_stratum()+
  ggplot2::geom_text(stat = "stratum",
                     aes(label = after_stat(stratum)))+
  ggplot2::scale_x_discrete(expand = c(0.15, 0.05))+
  theme_void()+
  ggplot2::theme(legend.position = "none")+
  ggplot2::scale_color_manual(values = col_cts_hsc_orig)
```

```{r all_alluv, fig.height = 18, fig.width = 8}
mat_all <- table(
  sce_hsc_all_cells$celltypes,
  sce_hsc_all_cells$custom_label)

all_df <- mat_all %>%
  base::as.data.frame() %>%
  dplyr::filter(!is.nan(Freq))

all_df$Var2_rev <- all_df$Var2
all_df$Var2_rev <- factor(
  all_df$Var2_rev, 
  levels = rev(levels(all_df$Var2)))

all_df2 <- all_df %>%
  dplyr::mutate(
    Var1_u = fct_inorder(paste0("orig ", Var1)),
    Var2_u = fct_inorder(paste0("custom ", Var2_rev))
  )

ggplot2::ggplot(data = all_df2,
                aes(axis1 = Var1_u,
                    axis2 = Var2_u, 
                    y = Freq))+
  ggalluvial::geom_alluvium(aes(fill = Var1_u))+
  ggalluvial::geom_stratum()+
  ggplot2::geom_text(stat = "stratum",
                     aes(label = after_stat(stratum)))+
  ggplot2::scale_x_discrete(expand = c(0.15, 0.05))+
  theme_void()+
  ggplot2::theme(legend.position = "none")+
  ggplot2::scale_color_manual(values = col_cts_hsc_orig)
knitr::knit_exit()
```

