---
title: "bulk_quality_genes_report"
author: "Lea Wölbert"
date: '2023-07-14'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Load objects

```{r load,  message = FALSE}
set.seed(37)
library(pcaExplorer)
library(pheatmap)
library(RColorBrewer)

color_tables <- "/omics/odcf/analysis/OE0538_projects/DO-0008/metadata/color_tables"
source(file = "../../source/plotting.R")
source(file = "../../source/colors.R")
source(file = "../../source/sce_functions.R")
```

```{r}
cluster_curr <- snakemake@wildcards[["cluster"]]

sce <- readRDS(snakemake@input[["sce_input"]])
sce_sep <- readRDS(snakemake@input[["sce_sep"]])

rlog_list = readRDS(snakemake@input[["rlog"]])

sce_clust <- sce[,sce$cluster_louvain == as.numeric(cluster_curr)]
ct_curr <- unfactor(sce_clust$annotation_cluster[1])

rld <- rlog_list[[ct_curr]]

print(rld)
print(ct_curr)
print(sce_clust)
print(cluster_curr)

if(!cluster_curr %in% sce$cluster_louvain){
  print("cluster irrelevant")
  knitr::knit_exit()
}

```

Prepare color schemes

```{r}
sce_clust <- factor_reference_cts(sce_clust)

col_cts_baccin <- col_cts[match(levels(sce_clust$baccin_celltype_scmapclust), 
                                names(col_cts))]
col_cts_dahlin <- col_cts[match(levels(sce_clust$dahlin_celltype_scmapclust), 
                                names(col_cts))]
col_cts_dolgalev <- col_cts[match(levels(sce_clust$dolgalev_celltype_scmapclust),
                                  names(col_cts))]

col_batch_exp_day <- col_alp[names(col_alp) %in% sce_clust$Batch_exp_day]
col_batch_seq <- col_num[names(col_num) %in% sce_clust$Batch_sequencing]
col_ann_age <- col_ann[names(col_ann) %in% sce_clust$Age_ID]
col_species <- col_spc[names(col_spc) %in% sce_clust$Species_ID]

col_clust_l <- col_num[names(col_num) %in% sce_clust$cluster_louvain]
```

# QC

```{r}
plot1 <- distro_expr(rld, plot_type = "boxplot")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))+
  theme(legend.position = "none")

plot1
```

```{r}
rld_pca <- prcomp(t(assay(rld)))

ggdf <- as.data.frame(rld_pca$x)
ggdf$Antibody_combination <- colData(rld)$Antibody_combination
ggdf$age <- colData(rld)$age
ggdf$condition <- colData(rld)$condition
ggdf$batch <- colData(rld)$batch
ggdf$Batch_sequencing <- colData(rld)$Batch_sequencing
ggdf$sample <- colData(rld)$sample
ggdf$ncells <- colData(rld)$ncells

rld_cor <- correlatePCs(rld_pca, colData(rld))

plotPCcorrs(rld_cor)
```

# PCAs

```{r}
plot1 <- ggplot(ggdf, aes(x = PC1, y = PC2, color = condition))+
  geom_point()+
  theme_classic()+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())+
  scale_color_manual("Species", values = col_species)

plot2 <- ggplot(ggdf, aes(x = PC1, y = PC2, color = age))+
  geom_point()+
  theme_classic()+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())+
  scale_color_manual("Age", values = col_ann_age)

plot3 <- ggplot(ggdf, aes(x = PC1, y = PC2, color = batch))+
  geom_point()+
  theme_classic()+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())+
  scale_color_manual("Batch_exp_day", values = col_batch_exp_day)

plot4 <- ggplot(ggdf, aes(x = PC1, y = PC2, color = Antibody_combination))+
  geom_point()+
  theme_classic()+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())

plot5 <- ggplot(ggdf, aes(x = PC1, y = PC2, color = ncells))+
  geom_point()+
  theme_classic()+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())

plot1
plot2
plot3
plot4
plot5
```

```{r}
rld_pca <- prcomp(t(assay(rld)))
plot3 <- pcascree(rld_pca, type="pev")
print(plot3)
```

```{r}
hi_loadings(rld_pca, topN = 20, whichpc = 1)
```

```{r}
hi_loadings(rld_pca, topN = 20, whichpc = 2)
```

```{r}
sampleDists <- dist(t(assay(rld)))
sampleDistMatrix <- as.matrix(sampleDists)
rownames(sampleDistMatrix) <- rld$condition
colnames(sampleDistMatrix) <- NULL
colors <- colorRampPalette(rev(brewer.pal(9, "Blues")) )(255)
pheatmap(sampleDistMatrix,
         clustering_distance_rows=sampleDists,
         clustering_distance_cols=sampleDists,
         col=colors)
```

```{r}
sessionInfo()
```