---
title: "nDGE quality control report"
author: "Lea Wölbert"
date: '2023-07-14'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Report on the quality of each bulk of cell types to be subclustered using
nDGEs.

#### Load objects

```{r seed,  message = FALSE}
set.seed(37)
```

```{r load,  message = FALSE}
library(pcaExplorer, quietly = TRUE)
library(pheatmap, quietly = TRUE)
library(RColorBrewer, quietly = TRUE)
```

```{r source, message = FALSE}
source(file =  snakemake@params[["plotting"]])
```

```{r load_manual, include = FALSE, eval = FALSE}

sce <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/scRNAseq/main_analysis/sce_objects/02_sce_anno/04_annc/03_sce/sce_str-04")

rlog_list <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/scRNAseq/main_analysis/sce_objects/02_sce_anno/06_dsqc/rlog_str")

sce_clust <- sce[,sce$cluster_louvain == 6]
table(sce_clust$annotation_cluster)
rld <- rlog_list[["Mesenchymal cells"]]
```

```{r load_objects, message = FALSE}
cluster_curr <- snakemake@wildcards[["cluster"]]

sce <- base::readRDS(snakemake@input[["sce_input"]])
sep <- base::readRDS(snakemake@input[["sep"]])

rlog_list <- base::readRDS(snakemake@input[["rlog"]])

sce_clust <- sce[,sce$cluster_louvain == as.numeric(cluster_curr)]
ct_curr <- sce_clust$annotation_cluster[1]

rld <- rlog_list[[ct_curr]]
# remove annotation cluster = cell type from rld so that it won't cause problems
rld <- rld[,-which(colnames(rld) == "annotation_cluster")]
```

```{r print_objects, message = FALSE}
print(rld)
print(ct_curr)
print(sce_clust)
print(cluster_curr)
print(snakemake@input[["rlog"]])

if(!cluster_curr %in% sce$cluster_louvain){
  print("cluster irrelevant")
  knitr::knit_exit()
}
```

```{r colors, meassage = FALSE}
colors_path <- snakemake@params[["colors_path"]]
source(snakemake@params[["colors"]])
col_batch_exp_day <- col_alp[names(col_alp) %in% sce_clust$Batch_exp_day]
```

# QC

Distribution of the expression values, should be mostly uniform

```{r plot_pca}
plot1 <- pcaExplorer::distro_expr(rld, plot_type = "boxplot")+
  ggplot2::theme_classic()+
  ggplot2::theme(axis.text.x = element_text(angle = 90),
                 legend.position = "none")
plot1

rld_pca <- stats::prcomp(t(SummarizedExperiment::assay(rld)))
rld_cor <- pcaExplorer::correlatePCs(rld_pca, colData(rld))

pcaExplorer::plotPCcorrs(rld_cor)
```

```{r make_ggdf}

ggdf <- base::as.data.frame(rld_pca$x)
ggdf$Antibody_combination <- colData(rld)$Antibody_combination
ggdf$age <- colData(rld)$age
ggdf$condition <- colData(rld)$condition
ggdf$batch <- colData(rld)$batch
ggdf$Batch_sequencing <- colData(rld)$Batch_sequencing
ggdf$sample <- colData(rld)$sample
ggdf$ncells <- colData(rld)$ncells

head(ggdf)
```

# PCAs

```{r plot}
plot1 <- ggplot2::ggplot(ggdf, aes(x = PC1, y = PC2, color = condition))+
  ggplot2::geom_point()+
  ggplot2::theme_classic()+
  ggplot2::theme(axis.text = element_blank(),
                 axis.ticks = element_blank())+
  ggplot2::scale_color_manual("Species", values = col_spc)

plot2 <- ggplot2::ggplot(ggdf, aes(x = PC1, y = PC2, color = age))+
  ggplot2::geom_point()+
  ggplot2::theme_classic()+
  ggplot2::theme(axis.text = element_blank(),
                 axis.ticks = element_blank())+
  ggplot2::scale_color_manual("Age", values = col_age)

plot3 <- ggplot2::ggplot(ggdf, aes(x = PC1, y = PC2, color = batch))+
  ggplot2::geom_point()+
  ggplot2::theme_classic()+
  ggplot2::theme(axis.text = element_blank(),
                 axis.ticks = element_blank())+
  ggplot2::scale_color_manual("Batch_exp_day", values = col_batch_exp_day)

plot4 <- ggplot2::ggplot(ggdf, 
                         aes(x = PC1, y = PC2, color = Antibody_combination))+
  ggplot2::geom_point()+
  ggplot2::theme_classic()+
  ggplot2::theme(axis.text = element_blank(),
                 axis.ticks = element_blank())

plot5 <- ggplot2::ggplot(ggdf, aes(x = PC1, y = PC2, color = ncells))+
  ggplot2::geom_point()+
  ggplot2::theme_classic()+
  ggplot2::theme(axis.text = element_blank(),
                 axis.ticks = element_blank())

plot1
plot2
plot3
plot4
plot5
```

```{r pca3}
rld_pca <- stats::prcomp(t(SummarizedExperiment::assay(rld)))
plot3 <- pcaExplorer::pcascree(rld_pca, type="pev")
print(plot3)
```

```{r pca4}
pcaExplorer::hi_loadings(rld_pca, topN = 20, whichpc = 1)
```

```{r pca5}
pcaExplorer::hi_loadings(rld_pca, topN = 20, whichpc = 2)
```

```{r pca6}
sampleDists <- stats::dist(t(SummarizedExperiment::assay(rld)))
sampleDistMatrix <- base::as.matrix(sampleDists)
rownames(sampleDistMatrix) <- rld$condition
colnames(sampleDistMatrix) <- NULL

colors <- grDevices::colorRampPalette(base::rev(
  RColorBrewer::brewer.pal(9, "Blues")))(255)

pheatmap::pheatmap(sampleDistMatrix,
                   clustering_distance_rows=sampleDists,
                   clustering_distance_cols=sampleDists,
                   col=colors)

rownames(sampleDistMatrix) <- rld$sample
pheatmap::pheatmap(sampleDistMatrix,
                   clustering_distance_rows=sampleDists,
                   clustering_distance_cols=sampleDists,
                   col=colors)
```

```{r session_info}
utils::sessionInfo()
```