---
title: "ctp interactome overlap ages"
author: "Lea Wölbert"
date: '2023-10-23'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Load objects

```{r seed,  message = FALSE}
set.seed(37)
```

```{r load,  message = FALSE}
library(tidyverse)
library(scran)
```

```{r colors, meassage = FALSE}
colors_path <- snakemake@params[["colors_path"]]
source(snakemake@params[["colors"]])
```

```{r load_objects}
cci_met_path_list <- snakemake@input[["cci_met_paths"]]
print(cci_met_path_list)

species <- snakemake@params[["species"]]
age <- snakemake@params[["age"]]

cci_met_list <- list()
for(s in species){
  for(a in age){
    cond <- as.character(paste0(s, "_", a))
    print(cond)
    cci_met_path <- cci_met_path_list[[which(grepl(cond, cci_met_path_list))]]
    print(cci_met_path)
    cci_met_list[[cond]] <- readRDS(cci_met_path)
  }
}

print(names(cci_met_list))
```

```{r}
# for each condition, summarize all ctp list entries into one large data frame
cci_met_dfs_list <- lapply(cci_met_list, function(cci_met){
  
  cci_met_df <- bind_rows(cci_met[[2]])
  return(cci_met_df)

})
names(cci_met_dfs_list) <- names(cci_met_list)
print(head(cci_met_dfs_list[[1]]))
```

```{r}
# separate the data frame again, now by cell type instead of cell type pair
cci_met_cts_list <- lapply(cci_met_dfs_list, function(cci_met_dfs){
  
  cts <- unique(c(cci_met_dfs$emitter, cci_met_dfs$receiver))
  cts_list <- as.list(cts)
  
  cci_met_cts <- lapply(cts_list, function(ct){
    
    if(ct %in% cci_met_dfs$emitter){
      cci_met_df_ct <- cci_met_dfs[cci_met_dfs$emitter == ct,]
    }else if(ct %in% cci_met_dfs$receiver){
      cci_met_df_ct <- cci_met_dfs[cci_met_dfs$receiver == ct,]
    }
  
    return(cci_met_df_ct)
  })         
  names(cci_met_cts) <- cts

  return(cci_met_cts)
})
names(cci_met_cts_list) <- names(cci_met_dfs_list)

names(cci_met_cts_list)
names(cci_met_cts_list[[2]])
```

```{r}
# now for each species, get the overlap and young and old only interactions
# sort list by species and then age

cci_met_cts_list_ages <- list()
for(s in species){
  for(a in age){
    cci_met_cts_list_ages[[s]][[a]] <- cci_met_cts_list[[which(grepl(s, names(cci_met_cts_list)) & grepl(a, names(cci_met_cts_list)))]]
  }
}

```

```{r}
# within species, extract the list of interactions that are shared,
# young_only, and old_only, as well as handy data frames for each cell type
overlap_lists <- lapply(cci_met_cts_list_ages, function(cci_met_age){
  
  cci_met_yng_list <- cci_met_age[["yng"]]
  cci_met_old_list <- cci_met_age[["old"]]
  
  cts_all <- unique(c(names(cci_met_yng_list), names(cci_met_old_list)))
  cts_all_list <- as.list(cts_all)
  
  overlap <- lapply(cts_all, function(ct){
    
    if(ct %in% names(cci_met_yng_list) & ct %in% names(cci_met_old_list)){
      cci_met_yng <- cci_met_yng_list[[ct]]
      cci_met_old <- cci_met_old_list[[ct]]
    
      shared <- intersect(unique(cci_met_yng$interaction), unique(cci_met_old$interaction))

      yng_only <- unique(cci_met_yng$interaction[which(!cci_met_yng$interaction %in% shared)])
      old_only <- unique(cci_met_old$interaction[which(!cci_met_old$interaction %in% shared)])
  
      # make sure the vectors are correct
      stopifnot(!yng_only %in% shared)
      stopifnot(!old_only %in% shared)
          
      stopifnot(!yng_only %in% cci_met_old$interaction)
      stopifnot(!old_only %in% cci_met_yng$interaction)
  
      stopifnot(shared %in% cci_met_yng$interaction)
      stopifnot(shared %in% cci_met_old$interaction)
      
    }else if(!ct %in% names(cci_met_yng_list)){
      shared <- NULL
      yng_only <- NULL    
      
      cci_met_old <- cci_met_old_list[[ct]]
      old_only <- unique(cci_met_old$interaction)
      
    }else if(!ct %in% names(cci_met_old_list)){
       shared <- NULL
       old_only <- NULL
      
      cci_met_yng <- cci_met_yng_list[[ct]]
      yng_only <- unique(cci_met_yng$interaction)
    }
    
    # count the length of each cell type entry  
    return_df <- data.frame(
      "mode" = c("shared", "yng_only", "old_only"),
      "nr" = c(length(shared), length(yng_only), length(old_only)),
      "cell_type" = rep(ct, 3),
      # within species, so species will be the same in each list item
      "species" = rep(cci_met_old_list[[1]]$species[1], 3)
      
    )
    
    return(list("shared" = shared,
                "yng_only" = yng_only,
                "old_only" = old_only,
                "nr_df" = return_df))
  })
  names(overlap) <- cts_all
  return(overlap)
})
names(overlap_lists) <- names(cci_met_cts_list_ages)

names(overlap_lists[[1]])
names(overlap_lists[[1]][[1]])
```

```{r}
# extract only the nr_dfs for now!
nr_df_all <- data.frame()
for(i in 1:length(overlap_lists)){
  for(j in 1:length(overlap_lists[[i]])){
    
    nr_df_add <- overlap_lists[[i]][[j]]$nr_df
    if(length(grep(0, nr_df_add$nr)) <= 1){
      nr_df_add$proportion <- nr_df_add$nr/sum(nr_df_add$nr)
      nr_df_add$normalized <- nr_df_add$nr/nr_df_add$nr[nr_df_add$mode == "shared"]
      
      nr_df_all <- rbind(nr_df_all, nr_df_add)
    }
  }
}

head(nr_df_all)
```

```{r}
nr_df_all$mode <- factor(nr_df_all$mode,
                         levels = c("old_only" ,"yng_only", "shared"))
nr_df_all$mode_rev <- factor(nr_df_all$mode, 
                             levels = rev(c( "old_only" ,"yng_only", "shared")))
nr_df_all$cell_type <- factor(nr_df_all$cell_type,
                              levels = c(names(col_cts_hsc), 
                                         names(col_cts_str)))
nr_df_all$cell_type_rev <- factor(nr_df_all$cell_type,
                                  levels = rev(c(names(col_cts_hsc),
                                                 names(col_cts_str))))
nr_df_all$species <- factor(nr_df_all$species, levels = names(col_spc))
nr_df_all$species_rev <- factor(nr_df_all$species, levels = rev(names(col_spc)))

col_mode <- c("old_only" = "grey60", "yng_only" = "black", "shared" = "orange2")
```


```{r}
ggplot(nr_df_all, aes(y = cell_type_rev, x = nr, fill = mode))+
  geom_col(position = "stack")+
  theme_classic()+
  facet_grid(cols = vars(species))+
  scale_fill_manual("Detection", values = col_mode)+
  xlab("Nr of detected interactions per cell type")+
  theme(axis.text.x = element_text(angle = 90))+
  ylab("Cell type")

ggplot(nr_df_all, aes(y = cell_type, x = nr, fill = mode))+
  geom_col(position = "fill")+
  theme_classic()+
  facet_grid(cols = vars(species))+
  scale_fill_manual("Detection", values = col_mode)+
  xlab("Proportions of detected interactions per cell type")+
  theme(axis.text.x = element_text(angle = 90))+
  ylab("Cell type")
```

```{r}
ggplot(nr_df_all, aes(y = cell_type, x = normalized, fill = mode))+
  geom_col(position = "dodge")+
  theme_classic()+
  facet_grid(cols = vars(species))+
  scale_fill_manual("Detection", values = col_mode)+
  xlab("Normalized nr of detected interactions per cell type")+
  theme(axis.text.x = element_text(angle = 90))+
  ylab("Cell type")

ggplot(nr_df_all, aes(y = cell_type, x = proportion, fill = mode))+
  geom_col(position = "dodge")+
  theme_classic()+
  facet_grid(cols = vars(species))+
  scale_fill_manual("Detection", values = col_mode)+
  xlab("Proportions of detected interactions per cell type")+
  theme(axis.text.x = element_text(angle = 90))+
  ylab("Cell type")

ggplot(nr_df_all, aes(y = cell_type, x = nr, fill = mode))+
  geom_col(position = "dodge")+
  theme_classic()+
  facet_grid(cols = vars(species))+
  scale_fill_manual("Detection", values = col_mode)+
  xlab("Nr of detected interactions per cell type")+
  theme(axis.text.x = element_text(angle = 90))+
  ylab("Cell type")
```

```{r}
ggplot(nr_df_all, aes(y = species, x = proportion, color = mode))+
  geom_boxplot()+
  xlab("Proportion of detected interactions per cell type")+
  theme_classic()+
  scale_color_manual("Detection", values = col_mode)+
  ylab("Species")

ggplot(nr_df_all, aes(y = species, x = normalized, color = mode))+
  geom_boxplot()+
  xlab("Normalized nr of detected interactions per cell type")+
  theme_classic()+
  scale_color_manual("Detection", values = col_mode)+
  ylab("Species")

ggplot(nr_df_all, aes(x = species, y = proportion, color = mode))+
  geom_boxplot()+
  xlab("Proportion of detected interactions per cell type")+
  theme_classic()+
  scale_color_manual("Detection", values = col_mode)+
  facet_grid(cols = vars(mode))+
  ylab("Species")

ggplot(nr_df_all, aes(x = mode_rev, y = proportion, color = mode))+
  geom_boxplot()+
  ylab("Proportion of detected interactions per cell type")+
  theme_classic()+
  scale_color_manual("Detection", values = col_mode)+
  facet_grid(cols = vars(species))+
  xlab("Detection")+
  theme(axis.text.x = element_blank())
```

```{r}
ggplot(nr_df_all, aes(x = mode, y = proportion, color = mode))+
  geom_boxplot()+
  ylab("Proportion of detected interactions per cell type")+
  theme_classic()+
  scale_color_manual("Detection", values = col_mode)+
  facet_grid(cols = vars(cell_type))+
  theme(axis.text.x = element_blank(),
        strip.text.x = element_text(angle = 90))+
  xlab("Species")
```


```{r}
ggplot(nr_df_all, aes(y= cell_type, x = nr, color = mode))+
  geom_boxplot()+
  theme_classic()+
  facet_grid(cols = vars(mode))+
  scale_color_manual("Detection", values = col_mode)+
  xlab("Nr of detected interactions per cell type")+
  theme(axis.text.x = element_text(angle = 90))

ggplot(nr_df_all, aes(y= cell_type, x = nr, fill = species))+
  geom_col(position = "dodge")+
  theme_classic()+
  facet_grid(cols = vars(mode))+
  scale_fill_manual("species", values = col_spc)+
  xlab("Nr of detected interactions per cell type")+
  theme(axis.text.x = element_text(angle = 90))

knitr::knit_exit()
```

```{r}

sce_mcar_old 

test <- data.frame(
  interactions = unique(c(overlap_lists$mcar$Fibroblasts$shared, overlap_lists$mcar$Fibroblasts$yng_only, overlap_lists$mcar$Fibroblasts$old_only))
)

test$mode <- vector(length = nrow(test))
test$mode[test$interactions %in% overlap_lists$mcar$Fibroblasts$shared] <- "shared"
test$mode[test$interactions %in% overlap_lists$mcar$Fibroblasts$yng_only] <- "yng_only"
test$mode[test$interactions %in% overlap_lists$mcar$Fibroblasts$old_only] <- "old_only"

test2 <- separate(test, col = 1, into = c("ligand", "receptor"), sep = "_", remove = FALSE)

test3 <- pivot_longer(test2, cols = c(2, 3), names_to = "gene_type", values_to = "gene")

test3$average_expression <- vector(length = nrow(test3))

sce_mcar_old_fibros <- sce_mcar_old[,sce_mcar_old$Identity == "Fibroblasts"]

downsampled <- assays(sce_mcar_old)$downsampled
downsampled <- downsampled[match(test3$gene, rownames(downsampled)),]

logcounts <- assays(sce_mcar_old)$logcounts
logcounts <- logcounts[match(test3$gene, rownames(logcounts)),]


test3$average_expression_down <- rowMeans(downsampled) 
test3$average_expression_logc <- rowMeans(logcounts) 

ggplot(test3, aes(y = log(average_expression_down), x = mode))+
  geom_boxplot()

ggplot(test3, aes(y = average_expression_logc, x = mode))+
  geom_boxplot()



```



```{r}

gene_df_fibros <- data.frame(
  interactions = unique(c(overlap_lists$mcar$Fibroblasts$shared,
                          overlap_lists$mcar$Fibroblasts$yng_only, 
                          overlap_lists$mcar$Fibroblasts$old_only))
)

gene_df_fibros$mode <- vector(length = nrow(gene_df_fibros))
gene_df_fibros$mode[gene_df_fibros$interactions %in% overlap_lists$mcar$Fibroblasts$shared] <- "shared"
gene_df_fibros$mode[gene_df_fibros$interactions %in% overlap_lists$mcar$Fibroblasts$yng_only] <- "yng_only"
gene_df_fibros$mode[gene_df_fibros$interactions %in% overlap_lists$mcar$Fibroblasts$old_only] <- "old_only"

gene_df_fibros <- separate(test, col = 1, into = c("ligand", "receptor"), sep = "_", remove = FALSE)

gene_df_fibros <- pivot_longer(gene_df_fibros, cols = c(2, 3), names_to = "gene_type", values_to = "gene")

```


```{r}
sce_mcar_old <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/main_analysis/cci_objects/01_cci_preparation/05_down/sce_mcar_old-05")
sce_mcar_yng <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/main_analysis/cci_objects/01_cci_preparation/05_down/sce_mcar_yng-05")

sce_mcar_old_fibros <- sce_mcar_old[,sce_mcar_old$Identity == "Fibroblasts"]
sce_mcar_yng_fibros <- sce_mcar_old[,sce_mcar_yng$Identity == "Fibroblasts"]

ds_mcar_old_fibros <- assays(sce_mcar_old_fibros)$downsampled
ds_mcar_old_fibros <- ds_mcar_old_fibros[match(gene_df_fibros$gene, rownames(ds_mcar_old_fibros)),]
ds_mcar_old_fibros <- as.data.frame(as.matrix(ds_mcar_old_fibros))

ds_mcar_yng_fibros <- assays(sce_mcar_yng_fibros)$downsampled
ds_mcar_yng_fibros <- ds_mcar_yng_fibros[match(gene_df_fibros$gene, rownames(ds_mcar_yng_fibros)),]
ds_mcar_yng_fibros <- as.data.frame(as.matrix(ds_mcar_yng_fibros))
```

```{r}
gene_df_fibros$average_downsampled_old <- rowMeans(ds_mcar_old_fibros)
gene_df_fibros$average_downsampled_yng <- rowMeans(ds_mcar_yng_fibros)

fibros_old_long <- cbind(gene_df_fibros, ds_mcar_old_fibros)
fibros_old_long <- pivot_longer(fibros_old_long, cols = c(5:ncol(fibros_old_long)), names_to = "ds_mcar_old", values_to = "downsampled_counts")

fibros_yng <- cbind(gene_df_fibros, ds_mcar_yng_fibros)
fibros_yng <- pivot_longer(fibros_yng, cols = c(5:ncol(fibros_yng)), names_to = "ds_mcar_yng", values_to = "downsampled_counts")

# in fibros we only care about ligands
ggdf <- gene_df_fibros[gene_df_fibros$gene_type == "ligand",]
fibros_old_long <- fibros_old_long[fibros_old_long$gene_type == "ligand",]
```


```{r}

ggplot(ggdf, aes(y = average_downsampled_old, x = mode))+
  geom_jitter(color = "grey78", alpha = 30)+
  geom_boxplot(alpha = 0)+
  theme_classic()+
  stat_compare_means(test = 'kruskal.test', p.adjust.method = "BH")+
  stat_compare_means(
    comparisons = list(c("old_only", "shared"), c("old_only", "yng_only"),
                       c("shared", "yng_only")),
    test = 'dunn_test', p.adjust.method = "BH", hide.ns = TRUE, aes(label = after_stat(p.signif)))

ggplot(ggdf, aes(y = average_downsampled_yng, x = mode))+
  geom_jitter(color = "grey78", alpha = 30)+
  geom_boxplot(alpha = 0)+
  theme_classic()+
  stat_compare_means(test = 'kruskal.test', p.adjust.method = "BH")+
  stat_compare_means(
    comparisons = list(c("old_only", "shared"), c("old_only", "yng_only"),
                       c("shared", "yng_only")),
    test = 'dunn_test', p.adjust.method = "BH", hide.ns = TRUE, aes(label = after_stat(p.signif)))

ggplot(ggdf[ggdf$mode != "yng_only",], aes(y = average_downsampled_old, x = mode))+
  geom_jitter(color = "grey78", alpha = 30)+
  geom_boxplot(alpha = 0)+
  theme_classic()+
  stat_compare_means()

ggplot(ggdf[ggdf$mode != "old_only",], aes(y = average_downsampled_yng, x = mode))+
  geom_jitter(color = "grey78", alpha = 30)+
  geom_boxplot(alpha = 0)+
  theme_classic()+
  stat_compare_means()


ggplot(fibros_old_long[fibros_old_long$mode != "yng_only",], aes(y = downsampled_counts, x = mode))+
  geom_jitter(color = "grey78", alpha = 30)+
  geom_boxplot(alpha = 0)+
  theme_classic()+
  stat_compare_means()

ggplot(fibros_yng[fibros_yng$mode != "old_only",], aes(y = downsampled_counts, x = mode))+
  geom_jitter(color = "grey78", alpha = 30)+
  geom_boxplot(alpha = 0)+
  theme_classic()+
  stat_compare_means()

ggplot(fibros_yng[fibros_yng$gene == "Col3a1",], aes(y = downsampled_counts, x = mode))+
  geom_jitter(color = "grey78", alpha = 30)+
  geom_boxplot(alpha = 0)+
  theme_classic()



print(table(fibros_frankenstein$mode))

# TODO HERE!!! Try out the effect of perc_expression on detection

perc_exp_mcar_old <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/main_analysis/cci_objects/01_cci_preparation/06_perc/perc_df_mcar_old")

perc_exp_mcar_old$mode <- perc_exp_mcar_old[perc_exp_mcar_old$gene_symbol %in% ggdf$gene[ggdf$mode == "old_only"],]


```