---
title: "Plot age comparison"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Report on the quality of the cell type pseudo-bulks (annotated)

#### Load objects

```{r seed,  message = FALSE}
set.seed(37)
```

```{r library,  message = FALSE}
library(tidyverse)
```

```{r load}
# load the markers obtaine from pooled analysis
load(snakemake@input[["markers_cons_hsc"]])
markers_cons_hsc <- markers_conservation_hsc
names(markers_cons_hsc)

load(snakemake@input[["markers_cons_str"]])
markers_cons_str <- markers_conservation_str
names(markers_cons_str)


# load the markers obtained from different ages
load(snakemake@input[["markers_conservation_hsc"]])
markers_conservation_hsc <- markers_conservation_hsc
names(markers_conservation_hsc)

load(snakemake@input[["markers_conservation_str"]])
markers_conservation_str <- markers_conservation_str
names(markers_conservation_str)
```


```{r}
conserved_genes <- data.frame(celltype = rep(names(markers_cons_hsc)),
                              young = 0,
                              both = 0,
                              old = 0,
                              n_markers = 0,
                              young_in_markers = 0,
                              both_in_markers = 0,
                              old_in_markers = 0)

for(ct in names(markers_cons_hsc)){
  young <- markers_conservation_hsc[[grep(paste(ct, "young", sep = "_"),
                                      names(markers_conservation_hsc),
                                      value = T)]] %>% as.data.frame()
  young$gene <- rownames(young)
  young <- young[complete.cases(young),]

  old <- markers_conservation_hsc[[grep(paste(ct, "old", sep = "_"),
                                    names(markers_conservation_hsc),
                                    value = T)]] %>% as.data.frame()
  old$gene <- rownames(old)
  old <- old[complete.cases(old),]

  both <- young$gene[young$gene %in% old$gene]

  mark <- markers_cons_hsc[[grep(ct,
                                 names(markers_cons_hsc),
                                 value = T)]]
  mark <- mark[complete.cases(mark),]

  conserved_genes[which(conserved_genes$celltype == ct),1] <- ct

  conserved_genes[which(conserved_genes$celltype == ct),2:8] <-
    c(nrow(young),
      length(both),
      nrow(old),
      nrow(mark),
      sum(young$gene %in% rownames(mark)),
      sum(both %in% rownames(mark)),
      sum(old$gene %in% rownames(mark))) %>% as.numeric()
}


 plot_hsc <- data.frame(celltype = conserved_genes$celltype,
                        both_in_mark = conserved_genes$both_in_markers,
                        old_in_mark = (conserved_genes$both_in_markers/2) + (conserved_genes$old_in_markers - conserved_genes$both_in_markers),   
                        young_in_mark = -(conserved_genes$both_in_markers/2) - (conserved_genes$young_in_markers - conserved_genes$both_in_markers)) %>%
  mutate(only_yng = young_in_mark - (conserved_genes$young - conserved_genes$young_in_markers),
          only_old = old_in_mark + (conserved_genes$old - conserved_genes$old_in_markers),
          both_in_mark_high = both_in_mark/2,
          both_in_mark_low = -both_in_mark_high) %>%
   select(-both_in_mark)

 plot_hsc <- data.frame(celltype = plot_hsc$celltype,
                        xmin = c(plot_hsc$only_yng, plot_hsc$young_in_mark,
                                 plot_hsc$both_in_mark_low, plot_hsc$both_in_mark_high,
                                 plot_hsc$old_in_mark),
                        xmax = c(plot_hsc$young_in_mark,
                                 plot_hsc$both_in_mark_low, plot_hsc$both_in_mark_high,
                                 plot_hsc$old_in_mark, plot_hsc$only_old),
                        fill = rep(c("red", "black", "gold", "black", "red"),
                                   each = length(unique(plot_hsc$celltype))))

ggplot(plot_hsc,
       aes(xmin = xmin,
           xmax = xmax,
           fill = fill)) +
  facet_wrap(~celltype,
             ncol = 1,
             strip.position="left") +
  geom_rect(aes(ymin = 0,
                ymax = 1)) +
  theme_classic() +
  theme(legend.position = "none",
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        strip.background = element_blank()) +
  scale_fill_manual(values = c("gold3", "gold", "grey40"))


plot_hsc <- data.frame(celltype = conserved_genes$celltype,
                       both_in_mark = conserved_genes$both_in_markers,
                       old_and_mark = conserved_genes$old_in_markers - conserved_genes$both_in_markers,
                       young_and_mark = conserved_genes$young_in_markers - conserved_genes$both_in_markers,
                       only_yng = conserved_genes$young - conserved_genes$young_in_markers,
                       only_old = conserved_genes$old - conserved_genes$old_in_markers) %>%
  gather("category", "count", -celltype)

ggplot(plot_hsc,
       aes(x = celltype,
           y = count,
           fill = factor(category,
                         levels = c("only_yng",
                                    "young_and_mark",
                                    "both_in_mark",
                                    "old_and_mark",
                                    "only_old")))) +
  geom_col(position = "fill") +
  theme_classic() +
  labs(x = NULL, y = "% marker genes identified", fill = NULL) +
  theme(axis.text.x = element_text(angle = 90, h = 1))


plot_hsc2 <- gather(conserved_genes[,c("celltype", "n_markers", "young_in_markers", "old_in_markers")],
                    "group", "count", -celltype)
ggplot(plot_hsc2,
       aes(x = celltype,
           y = count,
           fill = group)) +
  geom_col(position = "dodge") +
  theme_classic() +
  labs(x = NULL, y = "# marker genes identified", fill = NULL) +
  theme(axis.text.x = element_text(angle = 90, h = 1))
```

```{r}
conserved_genes <- data.frame(celltype = rep(names(markers_cons_str)),
                              young = 0,
                              both = 0,
                              old = 0,
                              n_markers = 0,
                              young_in_markers = 0,
                              both_in_markers = 0,
                              old_in_markers = 0)
for(ct in names(markers_cons_str)){
  young <- markers_conservation_str[[grep(paste(ct, "young", sep = "_"),
                                      names(markers_conservation_str),
                                      value = T)]] %>% as.data.frame()
  young$gene <- rownames(young)
  young <- young[complete.cases(young),]

  old <- markers_conservation_str[[grep(paste(ct, "old", sep = "_"),
                                    names(markers_conservation_str),
                                    value = T)]] %>% as.data.frame()
  old$gene <- rownames(old)
  old <- old[complete.cases(old),]

  both <- young$gene[young$gene %in% old$gene]

  mark <- markers_cons_str[[grep(ct,
                             names(markers_cons_str),
                             value = T)]]
  mark <- mark[complete.cases(mark),]

  conserved_genes[which(conserved_genes$celltype == ct),1] <- ct

  conserved_genes[which(conserved_genes$celltype == ct),2:8] <-
    c(nrow(young),
      length(both),
      nrow(old),
      nrow(mark),
      sum(young$gene %in% rownames(mark)),
      sum(both %in% rownames(mark)),
      sum(old$gene %in% rownames(mark))) %>% as.numeric()
}


plot_str <- data.frame(celltype = conserved_genes$celltype,
                       both_in_mark = conserved_genes$both_in_markers,
                       old_in_mark = (conserved_genes$both_in_markers/2) + (conserved_genes$old_in_markers - conserved_genes$both_in_markers),
                       young_in_mark = -(conserved_genes$both_in_markers/2) - (conserved_genes$young_in_markers - conserved_genes$both_in_markers)) %>%
  mutate(only_yng = young_in_mark - (conserved_genes$young - conserved_genes$young_in_markers),
         only_old = old_in_mark + (conserved_genes$old - conserved_genes$old_in_markers),
         both_in_mark_high = both_in_mark/2,
         both_in_mark_low = -both_in_mark_high) %>%
  select(-both_in_mark)
plot_str <- data.frame(celltype = plot_str$celltype,
                       xmin = c(plot_str$only_yng, plot_str$young_in_mark,
                                plot_str$both_in_mark_low, plot_str$both_in_mark_high,
                                plot_str$old_in_mark),
                       xmax = c(plot_str$young_in_mark,
                                plot_str$both_in_mark_low, plot_str$both_in_mark_high,
                                plot_str$old_in_mark, plot_str$only_old),
                       fill = rep(c("red", "black", "gold", "black", "red"),
                                  each = length(unique(plot_str$celltype))))
ggplot(plot_str,
       aes(xmin = xmin,
           xmax = xmax,
           fill = fill)) +
  facet_wrap(~celltype,
             ncol = 1,
             strip.position="left") +
  geom_rect(aes(ymin = 0,
                ymax = 1)) +
  theme_classic() +
  theme(legend.position = "none",
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        strip.background = element_blank()) +
  scale_fill_manual(values = c("gold3", "gold", "grey40"))

plot_str <- data.frame(celltype = conserved_genes$celltype,
                       both_in_mark = conserved_genes$both_in_markers,
                       old_and_mark = conserved_genes$old_in_markers - conserved_genes$both_in_markers,
                       young_and_mark = conserved_genes$young_in_markers - conserved_genes$both_in_markers,
                       only_yng = conserved_genes$young - conserved_genes$young_in_markers,
                       only_old = conserved_genes$old - conserved_genes$old_in_markers) %>%
  gather("category", "count", -celltype)

ggplot(plot_str,
       aes(x = celltype,
           y = count,
           fill = factor(category,
                         levels = c("only_yng",
                                    "young_and_mark",
                                    "both_in_mark",
                                    "old_and_mark",
                                    "only_old")))) +
  geom_col(position = "fill") +
  theme_classic() +
  labs(x = NULL, y = "% marker genes identified", fill = NULL) +
  theme(axis.text.x = element_text(angle = 90, h = 1))

plot_str2 <- gather(conserved_genes[,c("celltype", "n_markers", "young_in_markers", "old_in_markers")],
                    "group", "count", -celltype)
ggplot(plot_str2,
       aes(x = celltype,
           y = count,
           fill = group)) +
  geom_col(position = "dodge") +
  theme_classic() +
  labs(x = NULL, y = "# marker genes identified", fill = NULL) +
  theme(axis.text.x = element_text(angle = 90, h = 1))
```
