---
title: ""
author: "Lea Wölbert"
date: '2023-07-24'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Load libraries, source code 

```{r seed, message = FALSE}
set.seed(37)
```

```{r load, message = FALSE}
library(scater)
library(scran)
library(monocle3)
library(tidyverse)
```

```{r sources, message = FALSE}
source(file = snakemake@params[["plotting"]])
#source(file = snakemake@params[["functions"]])
```

```{r}
cds <- readRDS(snakemake@input[["cds_input"]])
#cds <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/main_analysis/sce_objects/03_sce_analysis/13_pstm/cds_hsc")
sce <- readRDS(snakemake@input[["sce_input"]])
#sce <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/main_analysis/sce_objects/02_sce_anno/10_anns/sce_hsc-10")
```


```{r}
colors_path <- snakemake@params[["colors_path"]]
source(snakemake@params[["colors"]])
```

```{r}
plot_cells(cds)
plot_cells(cds, color_cells_by = "celltypes")
plot_cells(cds, color_cells_by = "Species_ID")
plot_cells(cds, color_cells_by = "partition",
           label_groups_by_cluster=FALSE,
           group_label_size = 10,
           label_leaves=FALSE,
           label_branch_points=FALSE, 
           show_trajectory_graph=FALSE)
plot_cells(cds, color_cells_by = "pseudotime",
           label_leaves=FALSE,
           label_branch_points=FALSE)
plot_cells(cds, color_cells_by = "cluster",
           label_groups_by_cluster=FALSE,
           group_label_size = 10,
           label_leaves=FALSE,
           label_branch_points=FALSE, 
           show_trajectory_graph=FALSE)

plot_cells(cds, color_cells_by = "partition")

plot_cells(cds,
           color_cells_by = "celltypes",
           label_groups_by_cluster=FALSE,
           label_leaves=FALSE,
           label_branch_points=FALSE, 
           show_trajectory_graph=FALSE)
```


```{r}
plot_cells(cds,
           genes = c("Mecom", "Mllt3", "Hlf", "Meis1"),
           label_groups_by_cluster=FALSE,
           label_cell_groups = FALSE,
           label_leaves=FALSE,
           label_branch_points=FALSE, 
           show_trajectory_graph=FALSE)

plot_cells(cds,
           genes = c("Adgrl4", "Mcm6",  "Cd34", "Mki67"),
           label_groups_by_cluster=FALSE,
           label_cell_groups = FALSE,
           label_leaves=FALSE,
           label_branch_points=FALSE, 
           show_trajectory_graph=FALSE)

plot_cells(cds,
           genes = c("Satb1", "Il7r", "Cd79a", "Dntt"),
           label_groups_by_cluster=FALSE,
           label_leaves=FALSE,
           label_cell_groups = FALSE,
           label_branch_points=FALSE, 
           show_trajectory_graph=FALSE)

plot_cells(cds,
           genes = c("Irf8", "Elane", "Ctsg", "S100a9"),
           label_groups_by_cluster=FALSE,
           label_leaves=FALSE,
           label_cell_groups = FALSE,
           label_branch_points=FALSE, 
           show_trajectory_graph=FALSE)

plot_cells(cds,
           genes = c("Lmo4","Plek", "Pf4", "Klf1"),
           label_groups_by_cluster=FALSE,
           label_leaves=FALSE,
           label_cell_groups = FALSE,
           label_branch_points=FALSE, 
           show_trajectory_graph=FALSE)
```

```{r}
plot_cells(cds,
           genes = c("Mecom","Hlf", "Meis1", "Flt3"),
           label_groups_by_cluster=FALSE,
           label_cell_groups = FALSE,
           label_leaves=FALSE,
           label_branch_points=FALSE,
           trajectory_graph_color = "darkorange2",
           trajectory_graph_segment_size = 0.5,
           label_roots = FALSE)

plot_cells(cds,
           genes = c("Adgrl4", "Mcm6",  "Cd34", "Mki67"),
           label_groups_by_cluster=FALSE,
           label_cell_groups = FALSE,
           label_leaves=FALSE,
           label_branch_points=FALSE,
           trajectory_graph_color = "darkorange2",
           trajectory_graph_segment_size = 0.5,
           label_roots = FALSE)

plot_cells(cds,
           genes = c("Satb1", "Il7r", "Cd79a", "Dntt"),
           label_groups_by_cluster=FALSE,
           label_cell_groups = FALSE,
           label_leaves=FALSE,
           label_branch_points=FALSE,
           trajectory_graph_color = "darkorange2",
           trajectory_graph_segment_size = 0.5,
           label_roots = FALSE)

plot_cells(cds,
           genes = c("Irf8", "Elane", "Ctsg", "S100a9"),
           label_groups_by_cluster=FALSE,
           label_leaves=FALSE,
           label_cell_groups = FALSE,
           label_branch_points=FALSE,
           trajectory_graph_color = "darkorange2",
           trajectory_graph_segment_size = 0.5,
           label_roots = FALSE)

plot_cells(cds,
           genes = c("Lmo4","Plek", "Pf4", "Klf1"),
           label_groups_by_cluster=FALSE,
           label_leaves=FALSE,
           label_cell_groups = FALSE,
           label_branch_points=FALSE,
           trajectory_graph_color = "darkorange2",
           trajectory_graph_segment_size = 0.5,
           label_roots = FALSE)

knitr::knit_exit()
```

```{r}
core_cons_list <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/main_analysis/sce_objects/03_sce_analysis/07_core/core_cons_list_hsc")

fraction_curr <- "hsc"
core_cons_df_list <- lapply(as.list(names(core_cons_list)), function(c){
  
  core_cons_list[[c]]$marker_cons_ct$cell_type <- c
  if(fraction_curr == "hsc"){
    core_cons_list[[c]]$marker_cons_ct$assignment <- "receiver"
  }else if(fraction_curr == "str"){
    core_cons_list[[c]]$marker_cons_ct$assignment <- "emitter"
  }
  
  return(core_cons_list[[c]]$marker_cons_ct)
  
})

core_cons_df <- bind_rows(core_cons_df_list)

cc_list <- unique(core_cons_df$gene[which(core_cons_df$core_cons == "TRUE")])
```


```{r}
cds_subset <- cds[rowData(cds)$gene_short_name %in% cc_list,]

graph_test_res <- graph_test(cds_subset)
pr_deg_ids <- row.names(graph_test_res)[graph_test_res$q_value < 0.05]

gene_module_df <- find_gene_modules(cds_subset)

plot_cells(cds_subset,
           genes = c("Eloc"),
           label_groups_by_cluster=FALSE,
           label_leaves=FALSE,
           label_cell_groups = FALSE,
           label_branch_points=FALSE,
           trajectory_graph_color = "darkorange2",
           trajectory_graph_segment_size = 0.5,
           label_roots = FALSE)

plot_cells(cds,
           genes = c("Ramp1","Actr3", "Soat1"),
           label_groups_by_cluster=FALSE,
           label_leaves=FALSE,
           label_cell_groups = FALSE,
           label_branch_points=FALSE,
           trajectory_graph_color = "darkorange2",
           trajectory_graph_segment_size = 0.5,
           label_roots = FALSE)

plot_cells(cds,
           genes = c("Nucks1","Aspm", "Cenpf"),
           label_groups_by_cluster=FALSE,
           label_leaves=FALSE,
           label_cell_groups = FALSE,
           label_branch_points=FALSE,
           trajectory_graph_color = "darkorange2",
           trajectory_graph_segment_size = 0.5,
           label_roots = FALSE)
```

```{r}
cell_group_df <- tibble::tibble(cell=row.names(colData(cds_subset)), 
                                cell_group=colData(cds_subset)$celltypes[colnames(cds_subset)])
agg_mat <- aggregate_gene_expression(cds_subset, gene_module_df, cell_group_df)
row.names(agg_mat) <- stringr::str_c("Module ", row.names(agg_mat))
colnames(agg_mat) <- stringr::str_c("Cluster ", colnames(agg_mat))

pheatmap::pheatmap(agg_mat, cluster_rows=TRUE, cluster_cols=TRUE,
                   scale="column", clustering_method="ward.D2",
                   fontsize=6)
```

```{r, fig.height = 10}
marker_test_res <- top_markers(cds, group_cells_by="cluster", 
                               reference_cells=1000, cores=8)

top_specific_markers <- marker_test_res %>%
                            filter(fraction_expressing >= 0.10) %>%
                            group_by(cell_group) %>%
                            top_n(4, pseudo_R2)

top_specific_marker_ids <- unique(top_specific_markers %>% pull(gene_id))
top_specific_marker_ids <- top_specific_marker_ids[top_specific_marker_ids %in% cc_list]
plot_genes_by_group(cds,
                    top_specific_marker_ids,
                    group_cells_by="cluster",
                    ordering_type="maximal_on_diag",
                    max.size=3)


plot_cells(cds[,colData(cds)$Species_ID == "mcar"],
           genes = c("Ifitm7", "S100a6" ),
           label_groups_by_cluster=FALSE,
           label_leaves=FALSE,
           label_cell_groups = FALSE,
           label_branch_points=FALSE,
           show_trajectory_graph = FALSE,
           label_roots = FALSE)


plot_cells(cds[,colData(cds)$Species_ID == "mspr"],
           genes = c("Oosp1", "Gm3550" ),
           label_groups_by_cluster=FALSE,
           label_leaves=FALSE,
           label_cell_groups = FALSE,
           label_branch_points=FALSE,
           show_trajectory_graph = FALSE,
           label_roots = FALSE)


plot_cells(cds[,colData(cds)$Species_ID == "mcar"],
           genes = c("Mecom", "Mllt3", "Mmrn1", "Hlf", "Procr", "Cited2"),
           label_groups_by_cluster=FALSE,
           label_leaves=FALSE,
           label_cell_groups = FALSE,
           label_branch_points=FALSE,
           show_trajectory_graph = FALSE,
           label_roots = FALSE)


plot_cells(cds[,colData(cds)$Species_ID == "mcar"],
           genes = c("Hlf", "Flt3", "Adgrl4", "Cd34", "Cd63", "Gata2"),
           label_groups_by_cluster=FALSE,
           label_leaves=FALSE,
           label_cell_groups = FALSE,
           label_branch_points=FALSE,
           show_trajectory_graph = FALSE,
           label_roots = FALSE)
```

```{r}
plot_cells(cds[,colData(cds)$Species_ID == "mmus"],
           genes = c("Mecom", "Mllt3", "Mmrn1", "Hlf", "Procr", "Cited2"),
           label_groups_by_cluster=FALSE,
           label_leaves=FALSE,
           label_cell_groups = FALSE,
           label_branch_points=FALSE,
           show_trajectory_graph = FALSE,
           label_roots = FALSE)


plot_cells(cds[,colData(cds)$Species_ID == "mmus"],
           genes = c("Hlf", "Flt3", "Adgrl4", "Cd34", "Cd63", "Gata2"),
           label_groups_by_cluster=FALSE,
           label_leaves=FALSE,
           label_cell_groups = FALSE,
           label_branch_points=FALSE,
           show_trajectory_graph = FALSE,
           label_roots = FALSE)
```

```{r}
plot_cells(cds[,colData(cds)$Species_ID == "mcas"],
           genes = c("Mecom", "Mllt3", "Mmrn1", "Hlf", "Procr", "Cited2"),
           label_groups_by_cluster=FALSE,
           label_leaves=FALSE,
           label_cell_groups = FALSE,
           label_branch_points=FALSE,
           show_trajectory_graph = FALSE,
           label_roots = FALSE)


plot_cells(cds[,colData(cds)$Species_ID == "mcas"],
           genes = c("Hlf", "Flt3", "Adgrl4", "Cd34", "Cd63", "Gata2"),
           label_groups_by_cluster=FALSE,
           label_leaves=FALSE,
           label_cell_groups = FALSE,
           label_branch_points=FALSE,
           show_trajectory_graph = FALSE,
           label_roots = FALSE)
```

```{r}
plot_cells(cds[,colData(cds)$Species_ID == "mspr"],
           genes = c("Mecom", "Mllt3", "Mmrn1", "Hlf", "Procr", "Cited2"),
           label_groups_by_cluster=FALSE,
           label_leaves=FALSE,
           label_cell_groups = FALSE,
           label_branch_points=FALSE,
           show_trajectory_graph = FALSE,
           label_roots = FALSE)


plot_cells(cds[,colData(cds)$Species_ID == "mspr"],
           genes = c("Hlf", "Flt3", "Adgrl4", "Cd34", "Cd63", "Gata2"),
           label_groups_by_cluster=FALSE,
           label_leaves=FALSE,
           label_cell_groups = FALSE,
           label_branch_points=FALSE,
           show_trajectory_graph = FALSE,
           label_roots = FALSE)
```

```{r}
plot_cells_3d(cds, color_cells_by = "partition")
plot_cells(cds, label_principal_points = TRUE)
plot_cells(cds, genes = "Cdkn1c")
plot_cells_3d(cds, color_cells_by = "celltypes", show_trajectory_graph = TRUE,alpha = 0.2)

cds_3d <- order_cells(cds, root_pr_nodes=c("Y_337", "Y_1058", "Y_185"))

plot_cells_3d(cds, color_cells_by = "pseudotime", show_trajectory_graph = FALSE)
plot_cells_3d(cds, genes = "Meis1", show_trajectory_graph = FALSE)
reducedDims(cds)
?plot_cells_3d

pseudo <- pseudotime (cds_3d)
sce$pseudotime[match(names(pseudo), colnames(sce))] <- pseudo

umap_base(sce, color_by = "pseudotime")

```

