---
title: "reclustering human datasets report"
author: "Lea Wölbert"
date: '2024-04-15'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Load objects

```{r seed, message = FALSE}
set.seed(37)
```

```{r load, message = FALSE}
library(tidyverse)
library(scater)
library(pheatmap)
library(Seurat)
library(mclust)
library(cowplot)
```

```{r load_objects}
#base_path <- "/omics/odcf/analysis/OE0538_projects/DO-0008/data/scRNAseq/main_analysis/sce_objects/03_sce_analysis/04_conserved_EMF/04_rcls/"

#seu_list_all <- readRDS(paste0(base_path, "reclustered_ts_hsc_progenitors_list"))

#seu_list_all <- readRDS(paste0(base_path, "reclustered_ts_bone_marrow_list"))

#seu_list_all <- readRDS(paste0(base_path, "reclustered_ts_all_stromal_list"))
#seu_list_all <- readRDS(paste0(base_path, "reclustered_li_all_stromal_list"))

seu_list_all <- readRDS(snakemake@input[["seu_list"]])

nr_celltypes <- length(unique(seu_list_all[[1]][[1]]$cell_type))

```

### Functions

```{r res_info}
# add resolution info to seurat objects for nicer visualisation
add_res_info <- function(seu_list){
  print(names(seu_list))
  for(res in names(seu_list)){
    seu_list[[res]]$resolution <- rep(res, ncol(seu_list[[res]]))
  }
  return(seu_list)
}
```

```{r wide_function}
# heatmap vis
vis_perc_wide_gg <- function(seu, correction_vec = NULL, title_add= NULL){
  
  mat <- table(seu$cell_type, seu$seurat_clusters)
  
  mat1 <- mat/rowSums(mat)*100
  if(!is.null(correction_vec)){
    mat1 <- mat1[,correction_vec]
  }
  
  df_vis <- as.data.frame(mat1)
  df_vis$Var1 <- factor(df_vis$Var1, levels= rev(levels(seu$cell_type)))
  
  plot_wide <- ggplot(df_vis, aes(y = Var1, x = Var2, fill= Freq))+ 
    geom_tile()+
    scale_fill_continuous("% cells/cell type", 
                          limits=c(0, 100), breaks=seq(0,100,by=20),
                          low = "white", high = "blue")+
    theme_classic()+
    theme(axis.text.x = element_text(angle=0),
          axis.ticks = element_blank())+
    xlab("new clusters")+
    ylab("original cell types")+
    ggtitle(paste("resolution", seu$resolution[1], title_add))

  return(plot_wide)
}
```

```{r long_function}
vis_perc_long_gg <- function(seu, correction_vec = NULL, title_add= NULL){
  
  mat <- t(table(seu$cell_type, seu$seurat_clusters))
  
  mat2 <- mat/rowSums(mat)*100
  
  if(!is.null(correction_vec)){
    mat2 <- mat2[correction_vec,]
  }
  
  df_vis <- as.data.frame(mat2)
  df_vis$Var2 <- factor(df_vis$Var2, levels = levels(seu$cell_type))
  df_vis$Var1 <- factor(df_vis$Var1, levels = rev(levels(df_vis$Var1)))
  
  plot_long <- ggplot(df_vis, aes(y = Var1, x = Var2, fill= Freq))+ 
    geom_tile()+
    scale_fill_continuous("% cells/cluster", 
                          limits=c(0, 100), breaks=seq(0,100,by=20),
                          low = "white", high = "blue")+
    theme_classic()+
    theme(axis.ticks = element_blank(),
          axis.text.x = element_text(angle = 60, vjust = 1, hjust = 1))+
    ylab("new clusters")+
    xlab("original cell types")+
    ggtitle(paste("resolution", seu$resolution[1], title_add))

  return(plot_long)
}
```

```{r vis_per_cluster}
# heatmap vis
vis_perc_cluster <- function(seu, correction_vec = NULL, title_add= NULL){
  
  mat <- t(table(seu$cell_type, seu$seurat_clusters))
  
  mat2 <- mat/rowSums(mat)*100
  
  if(!is.null(correction_vec)){
    mat2 <- mat2[correction_vec,]
  }
  
  df_vis <- as.data.frame(mat2)
  df_vis$Var2 <- factor(df_vis$Var2, levels = levels(seu$cell_type))
  df_vis$Var1 <- factor(df_vis$Var1, levels = rev(levels(df_vis$Var1)))
  
  plot_long <- ggplot(df_vis, aes(x = Var2, y = Var1, fill= Freq))+ 
    geom_tile()+
    scale_fill_continuous("% cells/cluster", 
                          limits=c(0, 100), breaks=seq(0,100,by=20),
                          low = "white", high = "blue")+
    theme_classic()+
    theme(axis.ticks = element_blank(),
          axis.text.x = element_text(angle = 60, vjust = 1, hjust = 1))+
    ylab("new clusters")+
    xlab("original cell types")+
    ggtitle(paste("resolution", seu$resolution[1], title_add))

  return(plot_long)
}
```

```{r values}
get_reclustering_mat <- function(seu){
  
  mat <- table(seu$cell_type, seu$seurat_clusters)

  mat1_raw <- mat
  prop_in_ct <- mat1_raw/rowSums(mat1_raw)

  mat2_raw <- t(mat)
  prop_in_clust <- mat2_raw/rowSums(mat2_raw)

  # get the average of both values for each field
  mat_val <- (t(prop_in_ct) + prop_in_clust)/2
  return(mat_val)
}

get_reclustering_values <- function(reso, mat_list, seu_list){
  
  mat <- mat_list[[reso]]
  seu <- seu_list[[reso]]
  
  # extract which nr is higher; nr of clusters or number of cell types
  if(nrow(mat) >= ncol(mat)){
    max_nr <- nrow(mat)
  }else if(nrow(mat) < ncol(mat)){
    max_nr <- ncol(mat)
  }
  
  # get the proportion of fields that are 0 
  # from the max possible nr of fields that can be 0 in perfect re-clustering. 
  # That nr is equivalent to all fields - max_nr
  
  prop_zeros <- length(which(mat == 0))/(ncol(mat)*nrow(mat)-max_nr)

  # get the average of all proportion average, let's just call it "score"
  non_zeros <- mat[which(mat > 0)]
  score <- sum(non_zeros)/length(non_zeros)
  
  # let's also try to reduce the nr of cell types per cluster. 
  # because technically, 1 cluster containing all cell types would be a
  # good re-clustering, too according to prop_zeros and adjusted rand index
  
  nr_ct_per_cluster_all <- vector()
  for(cluster in rownames(mat)){
    nr_ct_per_cluster <- length(which(mat[cluster,] !=0))
    nr_ct_per_cluster_all <- c(nr_ct_per_cluster_all, nr_ct_per_cluster)
  }
  
  # same for clusters
  nr_clusters_per_ct_all <- vector()
  for(ct in colnames(mat)){
    nr_clusters_per_ct <- length(which(mat[,ct] !=0))
    nr_clusters_per_ct_all <- c(nr_clusters_per_ct_all, nr_clusters_per_ct)
  }

  # also calculate the adjusted rand index
  
  adjrand <- adjustedRandIndex(seu$cell_type, seu$seurat_clusters)

  return(
    data.frame(
      "prop_zeros" = prop_zeros,
      "score" = score,
      "adjrand" = adjrand,
      "mean_ct_per_cluster" = mean(nr_ct_per_cluster_all),
      "median_ct_per_cluster" = median(nr_ct_per_cluster_all),
      "mean_cluster_per_ct" = mean(nr_clusters_per_ct_all),
      "median_cluster_per_ct" = median(nr_clusters_per_ct_all),
      "nr_clusters" = nrow(mat),
      "resolution" = reso))
}

vis_clustering_values <- function(results_list, title){
  
  res_df <- bind_rows(results_list)

  vis_df_1 <- res_df
  vis_df_1$sum <- vis_df_1$prop_zeros + vis_df_1$score
  vis_df_1 <- pivot_longer(vis_df_1, cols = c("prop_zeros", "score", "sum"), 
                         names_to = "type", values_to = "value")
  plot1 <- ggplot(vis_df_1, aes(x = resolution, y= value, color = type))+
    geom_point()+
    theme_classic()+
    geom_hline(yintercept = 0.5, color = "black")+
    ylim(c(0, 2))+
    ggtitle(title)
  
  plot2 <- ggplot(vis_df_1, aes(x = resolution, y= value, color = type))+
    geom_point()+
    theme_classic()+
    geom_hline(yintercept = 0.5, color = "black")+
    ggtitle(title)

  plot3 <- ggplot(res_df, aes(x = resolution, y= adjrand))+
    geom_point(color = "green4")+
    theme_classic()+
    geom_hline(yintercept = 0.5, color = "black")+
    ylim(c(0, 1))+
    ggtitle(title)
  
  plot5 <- ggplot(res_df, aes(x = nr_clusters, y= adjrand))+
    geom_point(color = "green4", alpha = 0.6)+
    theme_classic()+
    ylim(c(0, 1))+
    ggtitle(title)+
    xlim(c(0, max(res_df$nr_clusters)))
  
  plot6 <- ggplot(vis_df_1, aes(x = nr_clusters, y= value, color = type))+
    geom_point(alpha = 0.6)+
    theme_classic()+
    ylim(c(0, 2))+
    ggtitle(title)+
    xlim(c(0, max(res_df$nr_clusters)))

  vis_df_2 <- res_df
  vis_df_2 <- pivot_longer(vis_df_2, cols = c("mean_ct_per_cluster",
                                              "median_ct_per_cluster", 
                                              "mean_cluster_per_ct",
                                              "median_cluster_per_ct",
                                              "nr_clusters"), 
                           names_to = "type", values_to = "value")
  vis_df_2$type <- factor(vis_df_2$type,
                          levels = c("nr_clusters",
                                     "mean_cluster_per_ct",
                                     "median_cluster_per_ct",
                                     "mean_ct_per_cluster",
                                     "median_ct_per_cluster"))
                            
  plot4 <- ggplot(vis_df_2, aes(x = resolution, y = value, color = type))+
    geom_point(alpha = 0.7)+
    scale_color_manual(
      "", values = c("mean_ct_per_cluster" = "pink4",
                     "median_ct_per_cluster" = "pink1", 
                     "mean_cluster_per_ct" = "green1",
                     "median_cluster_per_ct" = "green4",
                    "nr_clusters" = "black")
    )+
    geom_hline(yintercept = nr_celltypes, color = "grey60", linetype = "dashed")+
    theme_classic()+
    ylim(c(0, max(nr_celltypes, res_df$nr_clusters)))+
    ggtitle(title)
  
  return(list(plot1, plot2, plot3, plot4, plot5, plot6))
}
```

## Correct EMFs

```{r correct_emfs1}
seu_emf_cor_list <- seu_list_all$seu_emf_cor
seu_emf_cor_list <- add_res_info(seu_emf_cor_list)
```

```{r correct_emfs2, fig.width = 9, fig.height=3}
plot_listw <- lapply(seu_emf_cor_list, vis_perc_wide_gg, 
                    title_add = "correct EMFs")
plot_listw
```

```{r correct_emfs3, fig.height = 35, fig.width=12}
plot_listl <- lapply(seu_emf_cor_list, vis_perc_long_gg, 
                    title_add = "correct EMFs")
plot_grid(plotlist = plot_listl, ncol = 3)
```

```{r correct_emfs4, fig.height = 3, fig.width = 8}
mat_list <- lapply(seu_emf_cor_list, get_reclustering_mat)
res_list <- lapply(as.list(names(mat_list)), get_reclustering_values,
                   mat_list = mat_list, seu_list = seu_emf_cor_list)

plot_listv <- vis_clustering_values(res_list, title = "correct EMFs")
plot_listv
```

## Reverse EMFs

```{r reverse_emfs1}
seu_emf_rev_list <- seu_list_all$seu_emf_rev
seu_emf_rev_list <- add_res_info(seu_emf_rev_list)
```

```{r reverse_emfs2, fig.width = 9, fig.height=3}
plot_listw <- lapply(seu_emf_rev_list, vis_perc_wide_gg, 
                    title_add = "reverse EMFs")
plot_listw
```

```{r reverse_emfs3, fig.height = 35, fig.width=12}
plot_listl <- lapply(seu_emf_rev_list, vis_perc_long_gg, 
                    title_add = "reverse EMFs")
plot_grid(plotlist = plot_listl, ncol = 3)
```

```{r reverse_emfs4, fig.height = 3, fig.width = 8}
mat_list <- lapply(seu_emf_rev_list, get_reclustering_mat)
res_list <- lapply(as.list(names(mat_list)), get_reclustering_values,
                   mat_list = mat_list, seu_list = seu_emf_rev_list)

plot_listv <- vis_clustering_values(res_list, title = "reverse EMFs")
plot_listv
```

## Correct Markers

```{r correct_markers1}
seu_marker_list <- seu_list_all$seu_mark_cor
seu_marker_list <- add_res_info(seu_marker_list)
```

```{r correct_markers2, fig.width = 9, fig.height=3}
plot_listw <- lapply(seu_marker_list, vis_perc_wide_gg, 
                    title_add = "correct Markers")
plot_listw
```

```{r correct_markers3, fig.height = 35, fig.width=12}
plot_listl <- lapply(seu_marker_list, vis_perc_long_gg, 
                    title_add = "correct Marker")
plot_grid(plotlist = plot_listl, ncol = 3)
```

```{r correct_markers4, fig.height = 3, fig.width = 8}
mat_list <- lapply(seu_marker_list, get_reclustering_mat)
res_list <- lapply(as.list(names(mat_list)), get_reclustering_values,
                   mat_list = mat_list, seu_list = seu_marker_list)

plot_listv <- vis_clustering_values(res_list, title = "correct Markers")
plot_listv
```

## Random

```{r random1}
seu_random_list <- seu_list_all$seu_random
seu_random_list <- add_res_info(seu_random_list)
```

```{r random2, fig.width = 9, fig.height=3}
plot_listw <- lapply(seu_random_list, vis_perc_wide_gg, 
                    title_add = "random")
plot_listw
```

```{r random3, fig.height = 35, fig.width=12}
plot_listl <- lapply(seu_random_list, vis_perc_long_gg, 
                    title_add = "random")
plot_grid(plotlist = plot_listl, ncol = 3)
```

```{r random4, fig.height = 3, fig.width = 8}
mat_list <- lapply(seu_random_list, get_reclustering_mat)
res_list <- lapply(as.list(names(mat_list)), get_reclustering_values,
                   mat_list = mat_list, seu_list = seu_random_list)

plot_listv <- vis_clustering_values(res_list, title = "random")
plot_listv
```

```{r}
knitr::knit_exit()
```

### compare all

This has to be done manually

```{r fig.width = 9, fig.height=3}
resolution_chosen <- list()
cluster_vec <- list()

wildcard_curr <- snakemake@wildcards[["reference"]]
# wildcard_curr <- "ts_bone_marrow"
```


```{r}
if(wildcard_curr == "ts_all_stromal"){
  resolution_chosen[["correct_EMFs"]] <- "0.55"
  resolution_chosen[["reverse_EMFs"]] <- "0.45"
  resolution_chosen[["correct_markers"]] <- "0.45"
  resolution_chosen[["random"]] <- "0.25"
  
  cluster_vec[["correct_EMFs"]] <- c(1, 4, 9, 5, 8, 7, 6, 2, 3, 10)
  cluster_vec[["reverse_EMFs"]] <- c(1, 2, 5, 6, 7, 8, 3, 4)
  cluster_vec[["correct_markers"]] <- c(2, 3, 5, 4, 7, 8, 9, 10, 1, 6)
  cluster_vec[["random"]] <- c(1, 3, 5, 4, 2, 6)
  
}else if(wildcard_curr == "ts_hsc_progenitors"){
  resolution_chosen[["correct_EMFs"]] <- "0.3"
  resolution_chosen[["reverse_EMFs"]] <- "0.45"
  resolution_chosen[["correct_markers"]] <- "0.3"
  resolution_chosen[["random"]] <- "0.5"
  
  cluster_vec[["correct_EMFs"]] <- c(2, 4, 5, 8, 3, 1, 6, 7, 9)
  cluster_vec[["reverse_EMFs"]] <- c(1, 4, 5, 8, 2, 3, 7, 6)
  cluster_vec[["correct_markers"]] <- c(2, 5, 4, 3, 1, 6, 7, 8)
  cluster_vec[["random"]] <- c(3, 5, 4, 2, 7, 8, 6, 1)
  
}else if(wildcard_curr == "ts_bone_marrow"){
  resolution_chosen[["correct_EMFs"]] <- "0.45"
  resolution_chosen[["reverse_EMFs"]] <- "0.85"
  resolution_chosen[["correct_markers"]] <- "0.5"
  resolution_chosen[["random"]] <- "0.15"
  
  cluster_vec[["correct_EMFs"]] <- c(3, 4, 6, 8, 2, 5, 7, 8, 1, 9)
  cluster_vec[["reverse_EMFs"]] <- c(6, 8, 1, 9, 3, 5, 10, 2, 4, 13, 11, 12, 7)
  cluster_vec[["correct_markers"]] <- c(4, 3, 6, 8, 9, 2, 5, 7, 1, 10)
  cluster_vec[["random"]] <- c(3, 2, 1, 4)
  
}else if(wildcard_curr == "li_all_stromal"){
  #knitr::knit_exit()
  resolution_chosen[["correct_EMFs"]] <- "0.6"
  resolution_chosen[["reverse_EMFs"]] <- "0.4"
  resolution_chosen[["correct_markers"]] <- "0.9"
  resolution_chosen[["random"]] <- "0.85"
  
  cluster_vec[["correct_EMFs"]] <- c(3, 1, 2, 4, 8, 7, 6, 5)
  cluster_vec[["reverse_EMFs"]] <- c(1, 2, 5, 7, 8, 6, 4, 3)
  cluster_vec[["correct_markers"]] <- c(2, 1, 3, 7, 6, 4, 10, 8, 5, 9)
  cluster_vec[["random"]] <- c(4, 1, 3, 2, 7, 8, 10, 9, 5, 6)
}
```


```{r fig.width = 9, fig.height=3}
plot1 <- vis_perc_wide_gg(seu_emf_cor_list[[resolution_chosen[["correct_EMFs"]]]],
                        title_add = "correct EMFs", 
                        correction_vec = cluster_vec[["correct_EMFs"]])

plot2 <- vis_perc_wide_gg(seu_emf_rev_list[[resolution_chosen[["reverse_EMFs"]]]],
                        title_add = "reverse EMFs", 
                        correction_vec = cluster_vec[["reverse_EMFs"]])

plot3 <- vis_perc_wide_gg(seu_marker_list[[resolution_chosen[["correct_markers"]]]],
                        title_add = "correct Markers", 
                        correction_vec = cluster_vec[["correct_markers"]])

plot4 <- vis_perc_wide_gg(seu_random_list[[resolution_chosen[["random"]]]],
                        title_add = "random", 
                        correction_vec = cluster_vec[["random"]])
plot1
plot2
plot3
plot4
```

```{r fig.height = 6, fig.width = 4}
plot1 <- vis_perc_long_gg(seu_emf_cor_list[[resolution_chosen[["correct_EMFs"]]]],
                        title_add = "correct EMFs", 
                        correction_vec = cluster_vec[["correct_EMFs"]])

plot2 <- vis_perc_long_gg(seu_emf_rev_list[[resolution_chosen[["reverse_EMFs"]]]],
                        title_add = "reverse EMFs", 
                        correction_vec = cluster_vec[["reverse_EMFs"]])

plot3 <- vis_perc_long_gg(seu_marker_list[[resolution_chosen[["correct_markers"]]]],
                        title_add = "correct Markers", 
                        correction_vec = cluster_vec[["correct_markers"]])

plot4 <- vis_perc_long_gg(seu_random_list[[resolution_chosen[["random"]]]],
                        title_add = "random", 
                        correction_vec = cluster_vec[["random"]])
plot1
plot2
plot3
plot4
```

```{r fig.width = 9, fig.height=3}
plot1 <- vis_perc_cluster(seu_emf_cor_list[[resolution_chosen[["correct_EMFs"]]]],
                        title_add = "correct EMFs", 
                        correction_vec = cluster_vec[["correct_EMFs"]])

plot2 <- vis_perc_cluster(seu_emf_rev_list[[resolution_chosen[["reverse_EMFs"]]]],
                        title_add = "reverse EMFs", 
                        correction_vec = cluster_vec[["reverse_EMFs"]])

plot3 <- vis_perc_cluster(seu_marker_list[[resolution_chosen[["correct_markers"]]]],
                        title_add = "correct Markers", 
                        correction_vec = cluster_vec[["correct_markers"]])

plot4 <- vis_perc_cluster(seu_random_list[[resolution_chosen[["random"]]]],
                        title_add = "random", 
                        correction_vec = cluster_vec[["random"]])
plot1
plot2
plot3
plot4
```

```{r fig.height = 6.2, fig.width = 3}
if(wildcard_curr == "ts_hsc_progenitors"){
  vis_perc_cluster(seu_emf_cor_list[[resolution_chosen[["correct_EMFs"]]]],
                   title_add = "correct EMFs", 
                   correction_vec = cluster_vec[["correct_EMFs"]])+
    theme(legend.position = "none")+
    theme(axis.text.x = element_text(angle = 90, size = 12),
        axis.text.y = element_text(size = 12),
        axis.title = element_blank(),
        plot.title = element_blank())
} 
```

```{r fig.height = 5, fig.width = 3}
if(wildcard_curr == "ts_bone_marrow"){
  vis_perc_cluster(seu_emf_cor_list[[resolution_chosen[["correct_EMFs"]]]],
                   title_add = "correct EMFs", 
                   correction_vec = cluster_vec[["correct_EMFs"]])+
    theme(legend.position = "none")+
    theme(axis.text.x = element_text(angle = 90, size = 12),
        axis.text.y = element_text(size = 12),
        axis.title = element_blank(),
        plot.title = element_blank())
} 
```

```{r fig.height = 6, fig.width = 3}
if(wildcard_curr == "ts_all_stromal"){
  vis_perc_cluster(seu_emf_cor_list[[resolution_chosen[["correct_EMFs"]]]],
                   title_add = "correct EMFs", 
                   correction_vec = cluster_vec[["correct_EMFs"]])+
    theme(legend.position = "none")+
    theme(axis.text.x = element_text(angle = 90, size = 12),
        axis.text.y = element_text(size = 12),
        axis.title = element_blank(),
        plot.title = element_blank())
} 
```

```{r fig.height = 6.4, fig.width = 3}
if(wildcard_curr == "li_all_stromal"){
  vis_perc_cluster(seu_emf_cor_list[[resolution_chosen[["correct_EMFs"]]]],
                   title_add = "correct EMFs", 
                   correction_vec = cluster_vec[["correct_EMFs"]])+
    theme(legend.position = "none")+
    theme(axis.text.x = element_text(angle = 90, size = 12),
        axis.text.y = element_text(size = 12),
        axis.title = element_blank(),
        plot.title = element_blank())
} 
```

```{r}
knitr::knit_exit()
```
