---
title: "clustering_species_reports_svm"
author: "Lea Wölbert"
date: '2022-12-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Report for SVM as part of clustering

#### Load libraries, source code 

```{r load,  message = FALSE}
library(DropletUtils, quietly = TRUE) 
library(scater, quietly = TRUE) 
library(scuttle, quietly = TRUE) 
library(scran, quietly = TRUE) 
library(tidyverse, quietly = TRUE) 
```

```{r}
color_tables <- snakemake@params[["color_tables"]]

input <- readRDS(file = snakemake@input)

sce_test <- input[["sce_test"]]
objects_hir <- input[["objects_hierarchical"]]
objects_ser <- input[["objects_seurat"]]
objects_lou <- input[["objects_louvain"]]

species_curr <- sce_test$Species_ID[1]

```

```{r}
source(file = "../source/colors.R")
source(file = "../source/plotting.R")
source(file = "../source/sce_functions.R")
```

```{r}
col_cts_all <- col_cts[names(col_cts) %in% sce_13$Identity_ref_all]
col_cts_fraction <- col_cts[names(col_cts) %in% sce_13$Identity_ref_fraction]
col_batch_exp_day <- col_alp[names(col_alp) %in% sce_13$Batch_exp_day]
col_batch_seq <- col_num[names(col_num) %in% sce_13$Batch_sequencing]
col_ann_age <- col_ann[names(col_ann) %in% sce_13$Age_ID]
col_ann_fraction <- col_ann[names(col_ann) %in% sce_13$Fraction_ID]
col_species <- col_spc[names(col_spc) %in% sce_13$Species_ID]
col_clust_h <- col_num[names(col_num) %in% sce_13$cluster_hierarchical]
col_clust_s <- col_num[names(col_num) %in% sce_13$cluster_seurat]
col_clust_l <- col_num[names(col_num) %in% sce_13$cluster_louvain]

col_cts_cluster_baccin <- col_cts[names(col_cts) %in% sce_13$cluster_ref_baccin]
col_cts_cluster_dahlin <- col_cts[names(col_cts) %in% sce_13$cluster_ref_dahlin]
col_cts_cluster_dolgalev <- col_cts[names(col_cts) %in% sce_13$cluster_ref_dolgalev]
```

# SVM on hierarchical clustering

```{r}
tune_out_hir <- objects_hir[[1]]
pred_hir <- objects_hir[[2]]
```

```{r}
summary(tune_out_hir)
```

```{r}
mat_comp <- as.matrix(table(as.numeric(unfactor(sce_test$cluster_hierarchical)),
                            as.numeric(pred_hir)))

rownames(mat_comp) <- paste0(rownames(mat_comp), "_h")
colnames(mat_comp) <- paste0(colnames(mat_comp), "_p")
print(mat_comp)
```

```{r}

mat_comp <- as.matrix(table(as.numeric(unfactor(sce_test$cluster_hierarchical)),
                            as.numeric(pred_hir)))
mat_comp <- mat_comp[which(rowMeans(mat_comp) > 0), which(colMeans(mat_comp) > 0)]

for(i in 1:nrow(mat_comp)){
  mat_comp[i,] <- mat_comp[i,]/max(mat_comp[i,])
}
rownames(mat_comp) <- factor(as.numeric(rownames(mat_comp)), 
                             levels = as.numeric(rownames(mat_comp)))
colnames(mat_comp) <- factor(as.numeric(colnames(mat_comp)), 
                             levels = as.numeric(colnames(mat_comp)))

rownames(mat_comp) <- paste0(rownames(mat_comp), "_cluster_hierarchical")
colnames(mat_comp) <- paste0(colnames(mat_comp), "_predicted")

pheatmap(mat_comp, cluster_cols = FALSE, cluster_rows = FALSE)

```

# SVM on Seurat clustering

```{r}
tune_out_ser <- objects_ser[[1]]
pred_ser <- objects_ser[[2]]
```

```{r}
summary(tune_out_ser)
```

```{r}
mat_comp <- as.matrix(table(as.numeric(unfactor(sce_test$cluster_seurat)),
                            as.numeric(pred_ser)))

rownames(mat_comp) <- paste0(rownames(mat_comp), "_s")
colnames(mat_comp) <- paste0(colnames(mat_comp), "_p")
print(mat_comp)
```

```{r}

mat_comp <- as.matrix(table(as.numeric(unfactor(sce_test$cluster_seurat)),
                            as.numeric(pred_ser)))
mat_comp <- mat_comp[which(rowMeans(mat_comp) > 0), which(colMeans(mat_comp) > 0)]

for(i in 1:nrow(mat_comp)){
  mat_comp[i,] <- mat_comp[i,]/max(mat_comp[i,])
}
rownames(mat_comp) <- factor(as.numeric(rownames(mat_comp)), 
                             levels = as.numeric(rownames(mat_comp)))
colnames(mat_comp) <- factor(as.numeric(colnames(mat_comp)), 
                             levels = as.numeric(colnames(mat_comp)))

rownames(mat_comp) <- paste0(rownames(mat_comp), "_cluster_seurat")
colnames(mat_comp) <- paste0(colnames(mat_comp), "_predicted")

pheatmap(mat_comp, cluster_cols = FALSE, cluster_rows = FALSE)

```

# SVM on louvain clustering

```{r}
tune_out_lou <- objects_lou[[1]]
pred_lou <- objects_lou[[2]]
```

```{r}
summary(tune_out_lou)
```

```{r}
mat_comp <- as.matrix(table(as.numeric(unfactor(sce_test$cluster_louvain)),
                            as.numeric(pred_lou)))

rownames(mat_comp) <- paste0(rownames(mat_comp), "_l")
colnames(mat_comp) <- paste0(colnames(mat_comp), "_p")
print(mat_comp)
```

```{r}

mat_comp <- as.matrix(table(as.numeric(unfactor(sce_test$cluster_louvain)),
                            as.numeric(pred_lou)))
mat_comp <- mat_comp[which(rowMeans(mat_comp) > 0), which(colMeans(mat_comp) > 0)]

for(i in 1:nrow(mat_comp)){
  mat_comp[i,] <- mat_comp[i,]/max(mat_comp[i,])
}
rownames(mat_comp) <- factor(as.numeric(rownames(mat_comp)), 
                             levels = as.numeric(rownames(mat_comp)))
colnames(mat_comp) <- factor(as.numeric(colnames(mat_comp)), 
                             levels = as.numeric(colnames(mat_comp)))

rownames(mat_comp) <- paste0(rownames(mat_comp), "_cluster_louvain")
colnames(mat_comp) <- paste0(colnames(mat_comp), "_predicted")

pheatmap(mat_comp, cluster_cols = FALSE, cluster_rows = FALSE)

```
