---
title: "clustering_species_reports_k"
author: "Lea Wölbert"
date: '2022-12-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Report for best ks as part of clustering 

#### Load libraries, source code 

```{r load,  message = FALSE}
library(DropletUtils, quietly = TRUE) 
library(scater, quietly = TRUE) 
library(scuttle, quietly = TRUE) 
library(scran, quietly = TRUE) 
library(tidyverse, quietly = TRUE) 
library(dendextend, quietly = TRUE) 
library(factoextra, quietly = TRUE) 
```

```{r}
sce_09 <- readRDS(file = snakemake@input[["sce_09"]])

species_curr <- sce_09$Species_ID[1]
```

```{r}

sce_hsc <- sce_09[,sce_09$Fraction_ID == "hsc"]
sce_str <- sce_09[,sce_09$Fraction_ID == "str"]

# clustering both fractions together
mat <- reducedDim(sce_09, "PCA") # PCA is batch corrected
mat <- scale(mat)

# HSC clustering
mat_hsc <- reducedDim(sce_hsc, "PCA") 
mat_hsc <- scale(mat_hsc)

# Stromal clustering
mat_str <- reducedDim(sce_str, "PCA")
mat_str <- scale(mat_str)

rm(sce_str, sce_hsc, sce_09)
```

```{r}

fviz_nbclust(mat, FUN = hcut, method = "wss", k.max = 28)+
  ggtitle(paste0(species_curr, " BOTH"))

fviz_nbclust(mat, FUN = hcut, method = "silhouette", k.max = 28)+
  ggtitle(paste0(species_curr, " BOTH"))

rm(mat)
```

```{r}

fviz_nbclust(mat_hsc, FUN = hcut, method = "wss", k.max = 16)+
  ggtitle(paste0(species_curr, " HSC"))

fviz_nbclust(mat_hsc, FUN = hcut, method = "silhouette", k.max = 16)+
  ggtitle(paste0(species_curr, " HSC"))

rm(mat_hsc)
```

```{r}

fviz_nbclust(mat_str, FUN = hcut, method = "wss", k.max = 16)+
  ggtitle(paste0(species_curr, " Stromal"))

fviz_nbclust(mat_str, FUN = hcut, method = "silhouette", k.max = 16)+
  ggtitle(paste0(species_curr, " Stromal"))

```
