---
title: "Subclustering results report - Dotplots"
author: "Lea Wölbert"
date: '2023-07-24'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Report on the results of the final annotation.
This report is a bit chaotic and frequently adjusted for exporting plots
for different purposes.

#### Load libraries, source code 

```{r seed, message = FALSE}
set.seed(37)
```

```{r load, message = FALSE}
library(scuttle, quietly = TRUE) 
library(tidyverse, quietly = TRUE) 
library(tibble, quietly = TRUE) 
```

```{r load_objects, message = FALSE}
#load SCE objects
sce <- base::readRDS(file = snakemake@input[["sce_input"]])

nr_hvgs <- snakemake@params[["nr_hvgs"]]
fraction_curr <- snakemake@wildcards[["fraction"]]

# load gene list for dotplots
dtplt_path <- snakemake@input[["gene_list_dtplt"]]
```

```{r load_objects_csv, message = FALSE}
# load and subset
gene_list_dtplt_main <- utils::read.csv(dtplt_path, 
  header = TRUE, 
  sep = ";", 
  check.names=FALSE, 
  stringsAsFactors=FALSE, 
  as.is=TRUE, 
  colClasses = "character")

gene_list_dtplt_main <- gene_list_dtplt_main[
  gene_list_dtplt_main$fraction == fraction_curr,]
gene_list_dtplt_main <- gene_list_dtplt_main[
  grep("Visualisation", gene_list_dtplt_main$use),]
```

```{r colors, message = FALSE}
colors_path <- snakemake@params[["colors_path"]]
source(snakemake@params[["colors"]])

# for factorizing cell types later
if(fraction_curr == "hsc"){
  col_cts <- col_cts_hsc
}else if(fraction_curr == "str"){
  col_cts <- col_cts_str
}

# factorize as required
sce$Species_ID <- factor(sce$Species_ID, levels = names(col_spc))
```

```{r print}
print(col_cts)
```

# Gene expression

## Prepare

```{r aggregate}
agg <- scuttle::aggregateAcrossCells(
  sce, 
  id=colData(sce)[,c("celltypes")], 
  statistics = "mean",
  use.assay.type = "logcounts") # normalized (MultiBatchNorm)
```

```{r vis_df_all}
# generate a dataframe containing only genes that will be visualised
all_genes <- base::unique(gene_list_dtplt_main$gene)

# normalized (MultiBatchNorm)
vis_df_all <- base::as.data.frame(
  t(SummarizedExperiment::assays(agg)$logcounts[
    rownames(SummarizedExperiment::assays(agg)$logcounts) %in% all_genes,]))
vis_df_all
```

```{r vis_df_all_prep}
# further prepare the dataframe for visualisation
vis_df_all <- tibble::rownames_to_column(vis_df_all, "celltypes")

vis_df_all <- tidyr::pivot_longer(
  vis_df_all, 
  cols = c(2:ncol(vis_df_all)), 
  values_to = "expression", 
  names_to = "gene")
```

```{r perc_expressed}
# subset and factor

vis_df_all$celltypes <- factor(
  vis_df_all$celltypes, 
  levels = base::rev(names(col_cts)))

stopifnot(!is.na(vis_df_all$celltypes))

gene_list_dtplt_main$gene[which(duplicated(gene_list_dtplt_main$gene))]

vis_df_main <- vis_df_all[vis_df_all$gene %in% gene_list_dtplt_main$gene,]

vis_df_main$gene <- factor(
  vis_df_main$gene, 
  levels = gene_list_dtplt_main$gene)
```

```{r perc_expressed_func}

get_perc_expressed <- function(vis_df){
  
  vis_df$percent_expressed <- vector(length = nrow(vis_df))
  
  cts <- base::unique(vis_df$celltypes)
  gs <- base::unique(vis_df$gene)
  
  for(ct in cts){
    
    # normalized (MultiBatchNorm)
    lc_temp <- SummarizedExperiment::assays(sce)$logcounts[,sce$celltypes == ct]
    
    for(g in gs){
      
      perc_expr <- length(which(lc_temp[
        rownames(lc_temp) == g,] > 0))/ncol(lc_temp)*100
      
      vis_df$percent_expressed[
        which(vis_df$celltypes == ct & vis_df$gene == g)] <- perc_expr
    }
  }
  return(vis_df)
}

vis_df_main <- get_perc_expressed(vis_df_main)
```

```{r scale, eval = FALSE, include = FALSE}
# scale
get_scale <- function(vis_df){
  
  vis_df$scaled <- vector(length = nrow(vis_df))

  cts <- base::unique(vis_df$celltypes)
  gs <- base::unique(vis_df$gene)
  
  for(ct in cts){
    
    vis_df$scaled[which(vis_df$celltypes == ct)] <- base::scale(
      vis_df$expression[which(vis_df$celltypes == ct)])
  }
  return(vis_df)
}

vis_df <- get_scale(vis_df)
```

```{r rowmax, eval = FALSE, include = FALSE}
# obtain the maximum per row (cell type) and put into an extra dataframe
# for comparison of normalized counts per cell type vs without normalisation
rowmax <- function(dataframe){
  max_vector <- vector()
  
  for(i in 1:nrow(dataframe)){
    max <- base::max(dataframe[i,])
    max_vector <- c(max_vector, max)
  }
  return(max_vector)
}

vis_df_normalized_per_celltype <- vis_df

vis_df_normalized_per_celltype <- vis_df_normalized_per_celltype/
  rowmax(vis_df_normalized_per_celltype)

vis_df_normalized_per_celltype <- tibble::rownames_to_column(
  vis_df_normalized_per_celltype, 
  "celltypes")

vis_df_normalized_per_celltype <- tidyr::pivot_longer(
  vis_df_normalized_per_celltype,
  cols = c(2:ncol(vis_df_normalized_per_celltype)), 
  values_to = "expression",
  names_to = "gene")

```

```{r plot_function}

standard_dotplot <- function(vis_df){
  
  plot_return <- ggplot2::ggplot(vis_df,
                                 aes(x = gene,
                                     y = celltypes,
                                     color = percent_expressed,
                                     size = expression))+
    ggplot2::geom_point()+
    ggplot2::theme_classic()+
    ggplot2::theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
                   axis.text.y = element_text(hjust = 0),
                   axis.title = element_blank())+
    ggplot2::scale_size("logcounts",
                        limits=c(0, max(vis_df$expression)),
                        range = c(0, 5))+
    ggplot2::scale_color_continuous(limits = c(0, 100),
                                    low = "white",
                                    high = "blue")
  
  return(plot_return)
  
}
```


## HSCs

```{r hsc_ggdotplot1, fig.width = 8.5, fig.height = 3.5}
if(fraction_curr == "hsc"){standard_dotplot(vis_df_main)}
```

```{r hsc_ggdotplot1_rev, fig.width = 8.5, fig.height = 3.5}
if(fraction_curr == "hsc"){
  
  ggplot2::ggplot(vis_df_main,
                  ggplot2:: aes(x = gene,
                                y = celltypes,
                                color = expression,
                                size = percent_expressed))+
      ggplot2::geom_point()+
      ggplot2::theme_classic()+
      ggplot2::theme(axis.text.x = element_text(angle = 45, 
                                                hjust = 1,
                                                vjust = 1),
                     axis.text.y = element_text(hjust = 0),
                     axis.title = element_blank(),
                     legend.text = element_text(size = 9),
                     legend.title = element_text(size = 10))+
      ggplot2::scale_size("expression", 
                          limits=c(0, max(vis_df_main$percent_expressed)),
                          range = c(0, 5))+
      ggplot2::scale_color_continuous("logcounts",
                                      limits = c(0, max(vis_df_main$expression)),
                                      low = "white",
                                      high = "blue")
  
}
```

## Stromal cells

```{r str_ggdotplot1, fig.width = 15, fig.height = 4}
# for stromal all/main
if(fraction_curr == "str"){standard_dotplot(vis_df_main)}
```

```{r str_ggdotplot1_rev, fig.width = 15, fig.height = 4}
# for stromal all/main
if(fraction_curr == "str"){
  ggplot2::ggplot(vis_df_main,
                  aes(x = gene,
                      y = celltypes,
                      color = expression,
                      size = percent_expressed))+
      ggplot2::geom_point()+
      ggplot2::theme_classic()+
      ggplot2::theme(axis.text.x = element_text(angle = 45, 
                                                hjust = 1,
                                                vjust = 1),
                     axis.text.y = element_text(hjust = 0),
                     axis.title = element_blank())+
      ggplot2::scale_size("expression", 
                          limits=c(0, max(vis_df_main$percent_expressed)),
                          range = c(0, 5))+
      ggplot2::scale_color_continuous("logcounts",
                                      limits = c(0, max(vis_df_main$expression)),
                                      low = "white",
                                      high = "blue")
}
```

## Specific cell types for visualisation

```{r fractionspecific}
if(fraction_curr == "str"){
  cell_type <- "Adipo/CAR"
  gene_list_dtplt_use <- gene_list_dtplt_main
}else if(fraction_curr == "hsc"){
  cell_type <- "HSC"
  gene_list_dtplt_use <- gene_list_dtplt_main
}
```

```{r agg_again}
sce_temp <- sce[,sce$celltypes == cell_type]
agg <- scuttle::aggregateAcrossCells(sce_temp,
                                     id=colData(sce_temp)[,c("Species_ID")], 
                                     statistics = "mean",
                                     use.assay.type = "logcounts")
```

Separate given cell types by species.
Do this only for the main list

```{r generate_vis_df_spec}

vis_df_spec <- base::as.data.frame(
  t(SummarizedExperiment::assays(agg)$logcounts[
    rownames(SummarizedExperiment::assays(agg)$logcounts) %in% 
      gene_list_dtplt_use$gene,]))

vis_df_spec <- tibble::rownames_to_column(vis_df_spec, "species")
vis_df_spec <- tidyr::pivot_longer(vis_df_spec,
                                   cols = c(2:ncol(vis_df_spec)), 
                                   values_to = "expression", 
                                   names_to = "gene")
vis_df_spec$celltypes <- base::rep(cell_type, nrow(vis_df_spec))

print(gene_list_dtplt_use)
table(duplicated(gene_list_dtplt_use$gene))
```

```{r perc_expressed_spec}
vis_df_spec <- get_perc_expressed(vis_df_spec)

vis_df_spec$species <- factor(vis_df_spec$species, 
                              levels = base::rev(names(col_spc)))
vis_df_spec$gene <- factor(vis_df_spec$gene,
                           levels = gene_list_dtplt_use$gene)

```

```{r hsc_ggdotplot_spec, fig.width = 7.6, fig.height = 1.5}
if(fraction_curr == "hsc"){
  
  ggplot2::ggplot(vis_df_spec,
                  aes(x = gene,
                      y = species,
                      color = percent_expressed,
                      size = expression))+
    ggplot2::geom_point()+
    ggplot2::theme_classic()+
    ggplot2::theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
                   axis.text.y = element_text(hjust = 0),
                   axis.title = element_blank(),
                   legend.position = "none")+
    ggplot2::scale_size("logcounts", 
                        limits=c(0, max(vis_df_spec$expression)),
                        range = c(0, 5))+
    ggplot2::scale_color_continuous(limits = c(0, 100),
                                    low = "white",
                                    high = "blue")+
    ggplot2::ggtitle(cell_type)
  
}
```

```{r str_ggdotplot_spec, fig.width = 5.5, fig.height = 1.5}
if(fraction_curr == "str"){
 
  ggplot2::ggplot(vis_df_spec,
                  aes(x = gene,
                      y = species,
                      color = percent_expressed,
                      size = expression))+
    ggplot2::geom_point()+
    ggplot2::theme_classic()+
    ggplot2::theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
                   axis.text.y = element_text(hjust = 0),
                   axis.title = element_blank(),
                   legend.position = "none")+
    ggplot2::scale_size("logcounts", 
                        limits=c(0, max(vis_df_spec$expression)),
                        range = c(0, 5))+
    ggplot2::scale_color_continuous(limits = c(0, 100),
                                    low = "white",
                                    high = "blue")+
    ggplot2::ggtitle(cell_type)
}
```

```{r session_info}
utils::sessionInfo()
```