---
title: "Subclustering marker genes report"
author: "Lea Wölbert"
date: '2023-03-07'
output: html_document
---

Report on marker genes and their expression in the finally annotated 
cell types.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Load libraries, source code 

```{r seed, message = FALSE}
set.seed(37)
```

```{r load, message = FALSE}
library(scran, quietly = TRUE) 
```

```{r source, message = FALSE}
source(file =  snakemake@params[["plotting"]])
```

```{r load_objects, message = FALSE}
 
# load objects
sce <- base::readRDS(file = snakemake@input[["sce_input"]])
sep <- base::readRDS(file = snakemake@input[["sep"]])

subcluster_curr <- snakemake@wildcards[["subcluster"]]
fraction_curr <- snakemake@wildcards[["fraction"]]

stopifnot(sep == subcluster_curr)

celltype_curr <- sce$celltypes[sce$cluster_after_sub == subcluster_curr]

gene_list <- utils::read.csv(snakemake@input[["gene_list_subcl"]], 
  header = TRUE, 
  sep = ";", 
  check.names=FALSE, 
  stringsAsFactors=FALSE, 
  as.is=TRUE, 
  colClasses = "character")

# load marker genes and results
results_go <- base::readRDS(file = snakemake@input[["go"]])
results_markers <- base::readRDS(file = snakemake@input[["markers"]])

markers <- results_markers[[base::as.numeric(subcluster_curr)]]
go <- results_go[[base::as.numeric(subcluster_curr)]]
```

```{r print_objects}
print(sce)
print(sep)
print(base::unique(sce$cluster_after_sub))
print(subcluster_curr)

print(base::table(sce$cluster_after_sub, sce$celltypes))

sce_subcluster <- sce[,which(sce$cluster_after_sub == sep)]
celltypes <- base::unique(sce_subcluster$celltypes)

print(celltypes)
print(fraction_curr)
print(sce_subcluster)

head(gene_list)

print(fraction_curr == "hsc")
print(fraction_curr == "str")

if(!sep %in% sce$cluster_after_sub){
  knitr::knit_exit()
}
```

```{r colors, meassage = FALSE}
colors_path <- snakemake@params[["colors_path"]]
source(snakemake@params[["colors"]])

col_cts_str
col_cts_hsc

if(fraction_curr == "hsc"){
  col_cts <- col_cts_hsc
}else if(fraction_curr == "str"){
  col_cts <- col_cts_str
}
```

# Identity plots

# Reference cell types 

Cells were annotated with scmap and three reference datasets.

```{r identity_plots, fig.width=8, fig.height=4}

# own functions
plot_1 <- umap_base(sce, color_by = "celltypes")+ 
  ggplot2::ggtitle(base::paste0(fraction_curr))+
  ggplot2::scale_color_manual(values = col_cts)
plot_1l <- umap_legend(sce, color_by = "celltypes")+
   ggplot2::scale_color_manual("Cell types", values = col_cts)
legend_1 <- ggpubr::get_legend(plot_1l)

plot_2 <- umap_base(sce_subcluster, color_by = "celltypes")+ 
  ggplot2::ggtitle(base::paste0(fraction_curr))+
  ggplot2::scale_color_manual(values = col_cts)
plot_2l <- umap_legend(sce_subcluster, color_by = "celltypes")+
  ggplot2::scale_color_manual("Cell types", values = col_cts)
legend_2 <- ggpubr::get_legend(plot_2l)
  
PLOT_1 <- ggpubr::ggarrange(plot_1, legend_1)
PLOT_2 <- ggpubr::ggarrange(plot_2, legend_2)
PLOT_1
PLOT_2
```

# Marker genes

## Found marker genes

```{r markers}
markers[1:50,1:4]
markers[base::order(markers$pct.1, decreasing = TRUE),][1:50,1:4]
```

## GO analysis

```{r go}
go_short <- go$results[go$results$ontology == "biological_process",]
go$results[1:50,c(3, 4)]
go_short[1:50,c(3, 4)]
```

## All Markers

Prepare Plots

```{r marker_plot_function}

gene_exps <- function(gene){
  
  sce_subcluster$Species_ID <- factor(
    sce_subcluster$Species_ID, levels = c("mmus", "mcas", "mspr", "mcar"))

  sce$Species_ID <- factor(
    sce$Species_ID, levels = c("mmus", "mcas", "mspr", "mcar"))
  
  # Gene expression UMAP in cluster X
  plot_1 <- umap_gene(sce_subcluster, gene)

  # Gene expression UMAP in cluster X, separated by species
  plot_2 <- umap_gene(sce_subcluster, gene)+
    ggplot2::facet_grid(cols = vars(sce_subcluster$Species_ID),
                        rows = vars(sce_subcluster$Age_ID))
  
  ggdf <- base::as.data.frame(colData(sce_subcluster))
  # normalised (multibatchnorm)
  logc <- SummarizedExperiment::assays(sce_subcluster)[["logcounts"]]

  ggdf$Species_ID <- factor(
    ggdf$Species_ID, levels = c("mmus", "mcas", "mspr", "mcar"))
  
  plot_3 <- ggplot2::ggplot(ggdf, 
                            aes(x = celltypes,
                                y = logc[rownames(logc) == gene,]))+
    ggbeeswarm::geom_quasirandom(size = 0.2, color = "grey60")+
    ggplot2::theme_classic()+
    ggplot2::geom_boxplot(color = "black", alpha = 0)+
    ggplot2::ylab(paste0(gene, " expression"))+
    ggplot2::facet_grid(cols = vars(sce_subcluster$Species_ID),
                        rows = vars(sce_subcluster$Age_ID))
  
  ggdf_full <- base::as.data.frame(colData(sce))
  # normalised (multibatchnorm)
  logc_full <- SummarizedExperiment::assays(sce)[["logcounts"]]
  
  plot_4 <- umap_gene(sce, gene)
  
  plot_5 <- ggplot2::ggplot(ggdf_full, 
                            aes(x = celltypes,
                                y = logc_full[rownames(logc_full) == gene,], 
                                color = celltypes))+
    ggbeeswarm::geom_quasirandom(size = 0.2)+
    ggplot2::theme_classic()+
    ggplot2::scale_color_manual(values = col_cts)+
    ggplot2::geom_boxplot(color = "black", alpha = 0)+
    ggplot2::ylab(paste0(gene, " expression"))+
    ggplot2::theme(axis.text.x = element_text(angle = 90))

  plot_6 <- umap_gene(sce, gene)+
    ggplot2::facet_grid(cols = vars(sce$Species_ID))
  
  return(list(gene, plot_1, plot_2, plot_3, plot_4, plot_5, plot_6))
}

```

```{r found_markers}

found_markers <- rownames(markers)[1:50]
head(found_markers)

gene_markers <- gene_list$Gene[gene_list$Fraction == fraction_curr]
head(gene_markers)

all_markers <- base::sort(base::unique(c(found_markers, gene_markers)))
all_markers <- as.list(sort(all_markers))
print(all_markers[which(!all_markers %in% rownames(sce))])
all_markers <- all_markers[which(all_markers %in% rownames(sce))]
print(all_markers)
```

## UMAPs

```{r umaps}
plotlist <- lapply(all_markers, gene_exps)
plotlist
```

```{r session_info}
utils::sessionInfo()
```