---
title: "Subclustering results report"
author: "Lea Wölbert"
date: '2023-07-24'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Load libraries, source code 

```{r seed, message = FALSE}
set.seed(37)
```

```{r load, message = FALSE}
#library(SingleCellExperiment, quietly = TRUE) 
#library(scater, quietly = TRUE) 
library(scuttle, quietly = TRUE) 
library(pheatmap, quietly = TRUE) 
#library(viridisLite, quietly = TRUE) 
library(Seurat, quietly = TRUE)
library(SeuratObject, quietly = TRUE)
```

```{r sources, message = FALSE}
source(file = snakemake@params[["plotting"]])
#source("../../source/plotting.R")
```

```{r load_objects, message = FALSE}
#load SCE objects
sce <- readRDS(file = snakemake@input[["sce_input"]])

nr_hvgs <- snakemake@params[["nr_hvgs"]]
fraction_curr <- snakemake@wildcards[["fraction"]]

sce$Species_ID <- factor(sce$Species_ID,
                         levels = c("mmus", "mcas", "mspr", "mcar"))

print(snakemake@input[["gene_list_subclustering"]])
print(snakemake@input[["gene_list_dtplt"]])

gene_list <- read.csv(snakemake@input[["gene_list_subclustering"]], 
  header = TRUE, 
  sep = ";", 
  check.names=FALSE, 
  stringsAsFactors=FALSE, 
  as.is=TRUE, 
  colClasses = "character")
gene_list <- gene_list[gene_list$fraction == fraction_curr,]

gene_list_dtplt <- read.csv(snakemake@input[["gene_list_dtplt"]], 
  header = TRUE, 
  sep = ";", 
  check.names=FALSE, 
  stringsAsFactors=FALSE, 
  as.is=TRUE, 
  colClasses = "character")
gene_list_dtplt <- gene_list_dtplt[gene_list_dtplt$fraction == fraction_curr,]

genes_list_shared <- readRDS(file = snakemake@input[["genes_list_shared"]])
```

```{r colors, message = FALSE}
colors_path <- snakemake@params[["colors_path"]]
source(snakemake@params[["colors"]])

if(fraction_curr == "hsc"){
  col_cat <- col_cat_hsc
  col_cts <- col_cts_hsc
}else if(fraction_curr == "str"){
  col_cat <- col_cat_str
  col_cts <- col_cts_str
}

# mix for nicer plots
sce_mix <- sce[,sample(1:ncol(sce), ncol(sce), replace = F)]
sce_mix$Species_ID <- factor(sce_mix$Species_ID, levels = names(col_spc))
```

# Subclustering 

Since I use a lot of plots from this report, there are many different
more or less good-looking versions of the same plot in this script.

## Overview

```{r overview1}

plot_1 <- umap_base(sce, color_by = "category")+ 
  ggtitle(paste(fraction_curr))+
  scale_color_manual("Category", values = col_cat)
plot_1l <- umap_legend(sce, color_by = "category")+
  scale_color_manual("Category", values = col_cat)
legend_1 <- get_legend(plot_1l)
  
plot_2 <- umap_base(sce, color_by = "celltypes")+ 
  ggtitle(paste(fraction_curr))+
  scale_color_manual("Cell types", values = col_cts)  
plot_2l <- umap_legend(sce, color_by = "celltypes")+
  scale_color_manual("Cell types", values = col_cts)
legend_2 <- get_legend(plot_2l)
  
PLOT_1 <- ggarrange(plot_1, legend_1, widths = c(2, 1))
PLOT_2 <- ggarrange(plot_2, legend_2, widths = c(2, 1))

PLOT_1
PLOT_2
```

```{r overview2}
plot_2 <- umap_base(sce, color_by = "celltypes")+ 
  ggtitle(paste(fraction_curr))+
  scale_color_manual("Cell types", values = col_cts)+
  theme(axis.text = element_blank(),
        axis.title = element_blank(),
        axis.line = element_blank(),
        plot.title = element_blank())
plot_2l <- umap_legend(sce, color_by = "celltypes")+
  scale_color_manual("Cell types", values = col_cts)+
  theme(legend.text= element_text(size = 11),
        legend.title = element_text(size = 14, face = "bold"))
legend_2 <- get_legend(plot_2l)
PLOT_2 <- ggarrange(plot_2, legend_2, widths = c(2, 1))
PLOT_2
```

```{r overview2_size, fig.width = 4, fig.height = 4}
plot_2
```

```{r hsc_antibodies}

if(fraction_curr == "hsc"){
  plot_2 <- umap_base(sce_mix, color_by = "Antibody_combination")+ 
    ggtitle(paste(fraction_curr))+
    scale_color_manual("Antibody combination", 
                       values = c("cKit" = "#ff8124ff",
                                  "CD45/cKit/CD71" = "#a6000cff"))+
    theme(axis.text = element_blank(),
          axis.title = element_blank(),
          axis.line = element_blank(),
          plot.title = element_blank())
  plot_2l <- umap_legend(sce_mix, color_by = "Antibody_combination")+
    scale_color_manual("Antibody combination", 
                       values = c("cKit" = "#ff8124ff",
                                  "CD45/cKit/CD71" = "#a6000cff"))+
    theme(legend.text= element_text(size = 11),
          legend.title = element_text(size = 14, face = "bold"))
  legend_2 <- get_legend(plot_2l)
  PLOT_2 <- ggarrange(plot_2, legend_2, widths = c(2, 1))
  PLOT_2
}
```

```{r str_antibodies}
if(fraction_curr == "str"){
  plot_2 <- umap_base(sce_mix, color_by = "Antibody_combination")+ 
    ggtitle(paste(fraction_curr))+
    scale_color_manual("Antibody combination", 
                       values = c("CD45/CD71" = "#006059ff",
                                  "CD45" = "#6792e4ff"))+
    theme(axis.text = element_blank(),
          axis.title = element_blank(),
          axis.line = element_blank(),
          plot.title = element_blank())
  plot_2l <- umap_legend(sce_mix, color_by = "Antibody_combination")+
    scale_color_manual("Antibody combination", 
                       values = c("CD45/CD71" = "#006059ff",
                                  "CD45" = "#6792e4ff"))+
    theme(legend.text= element_text(size = 11),
          legend.title = element_text(size = 14, face = "bold"))
  legend_2 <- get_legend(plot_2l)
  PLOT_2 <- ggarrange(plot_2, legend_2, widths = c(2, 1))
  PLOT_2
}
```

```{r antibody_plot_size, fig.width = 2, fig.height = 2}
plot_2
```


```{r species_plots}
plot_2 <- umap_base(sce_mix, color_by = "Species_ID")+ 
  ggtitle(paste(fraction_curr))+
  scale_color_manual("species", 
                     values = col_spc)+
  theme(axis.text = element_blank(),
        axis.title = element_blank(),
        axis.line = element_blank(),
        plot.title = element_blank())
plot_2l <- umap_legend(sce_mix, color_by = "Species_ID")+
  scale_color_manual("species", 
                     values = col_spc)+
  theme(legend.text= element_text(size = 11),
        legend.title = element_text(size = 14, face = "bold"))
legend_2 <- get_legend(plot_2l)
PLOT_2 <- ggarrange(plot_2, legend_2, widths = c(2, 1))
PLOT_2
```

```{r species_plots_size, fig.width = 2, fig.height = 2}
plot_2
```

```{r species_separation1}

coord_x <- c(min(reducedDims(sce)$UMAP[,1]), max(reducedDims(sce)$UMAP[,1]))
coord_y <- c(min(reducedDims(sce)$UMAP[,2]), max(reducedDims(sce)$UMAP[,2]))

plot_1 <- umap_base_l(sce[,sce$Species_ID == "mmus"], 
                      color_by = "celltypes")+
  ggtitle("mmus")+
  scale_color_manual("Cell types", values = col_cts)+
  theme(legend.position = "none")+
  xlim(coord_x)+
  ylim(coord_y)
plot_2 <- umap_base_l(sce[,sce$Species_ID == "mcas"], 
                      color_by = "celltypes")+
  ggtitle("mcas")+
  scale_color_manual("Cell types", values = col_cts)+
  theme(legend.position = "none")+
  xlim(coord_x)+
  ylim(coord_y)
plot_3 <- umap_base_l(sce[,sce$Species_ID == "mspr"], 
                      color_by = "celltypes")+
  ggtitle("mspr")+
  scale_color_manual("Cell types", values = col_cts)+
  theme(legend.position = "none")+
  xlim(coord_x)+
  ylim(coord_y)
plot_4 <- umap_base_l(sce[,sce$Species_ID == "mcar"], 
                      color_by = "celltypes")+
  ggtitle("mcar")+
  scale_color_manual("Cell types", values = col_cts)+
  theme(legend.position = "none")+
  xlim(coord_x)+
  ylim(coord_y)

PLOT_1 <- ggarrange(plot_1, legend_1, widths = c(2, 1))
PLOT_2 <- ggarrange(plot_2, legend_1, widths = c(2, 1))
PLOT_3 <- ggarrange(plot_3, legend_1, widths = c(2, 1))
PLOT_4 <- ggarrange(plot_4, legend_1, widths = c(2, 1))

PLOT_1
PLOT_2
PLOT_3
PLOT_4
```

```{r species_separation2}
print(table(sce$Species_ID, sce$celltypes))
```

```{r species_separation3}
print(table(sce$Species_ID, sce$celltypes)/rowSums(table(sce$Species_ID, sce$celltypes))*100)
```

```{r species_separation4, fig.width = 7, fig.height = 5}
plot_a <- umap_base(sce, color_by = "celltypes")+ 
  ggtitle(paste(fraction_curr))+
  scale_color_manual("Cell types", values = col_cts)+
  theme(axis.text = element_blank(),
        axis.title = element_blank(),
        axis.line = element_blank(),
        plot.title = element_blank())+
  facet_wrap( ~ sce$Species_ID, ncol = 2)+
  theme(strip.text = element_text(face = "bold", size = 14),
        strip.background = element_rect(linetype = 0))

plot_a

plot_2l <- umap_legend(sce, color_by = "celltypes")+
  scale_color_manual("Cell types", values = col_cts)+
  theme(legend.text= element_text(size = 11),
        legend.title = element_text(size = 14, face = "bold"))
legend_2 <- get_legend(plot_2l)

PLOT_all <- ggarrange(plot_a, legend_2, widths = c(2.5, 1))
PLOT_all
```

```{r species_separation5, fig.width = 8, fig.height = 5}
PLOT_all <- ggarrange(plot_a, legend_2, widths = c(2.5, 1.5))
PLOT_all
```

## Gene expression

```{r seurat_conv}

seurat <- Seurat::as.Seurat(sce, 
                            counts = "counts",
                            logcounts = "logcounts") # normalized
SeuratObject::Idents(seurat) <- sce$celltypes
seurat@active.ident <- factor(
  seurat@active.ident, levels = rev(levels(SeuratObject::Idents(seurat))))

```

```{r dotplot1, fig.width = 14, fig.height = 10}
if(fraction_curr == "hsc"){
  genes_to_plot <- gene_list_dtplt$gene
  Seurat::DotPlot(seurat, features = genes_to_plot,
                  idents = levels(SeuratObject::Idents(seurat)))+
    Seurat::RotatedAxis()
}
```

```{r dotplot2, fig.width = 14, fig.height = 10}

if(fraction_curr == "hsc"){
  genes_to_plot <- gene_list_dtplt$gene
  Seurat::DotPlot(seurat, features = genes_to_plot, 
                  idents = levels(SeuratObject::Idents(seurat)))+
    Seurat::RotatedAxis()+
    theme(axis.text.y = element_text(size = 16),
          axis.title = element_blank(),
          legend.position = "bottom")
}
```

```{r subset_hsc_plot1, fig.width = 12, fig.height = 4}

if(fraction_curr == "hsc"){
  
  seurat_sub <- seurat
  seurat_sub[['groups']] <- seurat_sub$Species_ID
  seurat_sub[['groups']]$groups <- factor(seurat_sub[['groups']]$groups, 
                                          levels = rev(names(col_spc)))

  genes_to_plot <- gene_list_dtplt$gene
  Seurat::DotPlot(seurat_sub, features = genes_to_plot, 
                  group.by = 'groups', idents = "HSCs")+
    Seurat::RotatedAxis()+
    theme(axis.text.y = element_text(size = 16),
          axis.title = element_blank(),
          legend.position = "bottom")
}
```

```{r subset_hsc_plot2, fig.width = 12, fig.height = 4}

if(fraction_curr == "hsc"){
  
  seurat_sub <- seurat
  seurat_sub[['groups']] <- seurat_sub$Species_ID
  seurat_sub[['groups']]$groups <- factor(seurat_sub[['groups']]$groups, levels = rev(names(col_spc)))

  genes_to_plot <- gene_list_dtplt$gene
  Seurat::DotPlot(seurat_sub, features = genes_to_plot, group.by = 'groups',
                  idents = "Monocyte progs.")+
    Seurat::RotatedAxis()+
    theme(axis.text.y = element_text(size = 16),
          axis.title = element_blank(),
          legend.position = "bottom")
}
```

```{r dotplot3, fig.width = 20, fig.height = 10}
if(fraction_curr == "str"){
  genes_to_plot <- gene_list_dtplt$gene
  Seurat::DotPlot(seurat, features = genes_to_plot, 
                  idents = levels(SeuratObject::Idents(seurat)))+
    Seurat::RotatedAxis()
}
```

```{r dotplot4, fig.width = 20, fig.height = 7}
if(fraction_curr == "str"){
  genes_to_plot <- gene_list_dtplt$gene
  Seurat::DotPlot(seurat, features = genes_to_plot,
                  idents = levels(SeuratObject::Idents(seurat)))+
    Seurat::RotatedAxis()+
    theme(axis.text.y = element_text(size = 16),
          axis.title = element_blank(),
          legend.position = "bottom")
}
```

```{r subset_str_1, fig.width = 20, fig.height = 4}

if(fraction_curr == "str"){
  
  seurat_sub <- seurat
  seurat_sub[['groups']] <- seurat_sub$Species_ID
  seurat_sub[['groups']]$groups <- factor(seurat_sub[['groups']]$groups, 
                                          levels = rev(names(col_spc)))

  genes_to_plot <- gene_list_dtplt$gene
  Seurat::DotPlot(seurat_sub, features = genes_to_plot, 
                  group.by = 'groups', idents = "Osteo")+
    Seurat::RotatedAxis()+
    theme(axis.text.y = element_text(size = 16),
          axis.title = element_blank(),
          legend.position = "bottom")
}
```

```{r subset_str_2, fig.width = 17, fig.height = 4}

if(fraction_curr == "str"){
  
  seurat_sub <- seurat
  seurat_sub[['groups']] <- seurat_sub$Species_ID
  seurat_sub[['groups']]$groups <- factor(seurat_sub[['groups']]$groups, 
                                          levels = rev(names(col_spc)))

  genes_to_plot <- gene_list_dtplt$gene
  Seurat::DotPlot(seurat_sub, features = genes_to_plot,
                  group.by = 'groups', idents = "Adipo/CARs")+
    Seurat::RotatedAxis()+
    theme(axis.text.y = element_text(size = 16),
          axis.title = element_blank(),
          legend.position = "bottom")
}
```

### BL6

```{r bl61, fig.width = 14, fig.height = 10}

seurat <- Seurat::as.Seurat(sce[,sce$Species_ID == "mmus"],
                    counts = "counts", logcounts = "logcounts")

SeuratObject::Idents(seurat) <- sce[,sce$Species_ID == "mmus"]$celltypes
seurat@active.ident <- factor(
  seurat@active.ident, levels = rev(levels(SeuratObject::Idents(seurat))))

if(fraction_curr == "hsc"){
  genes_to_plot <- gene_list_dtplt$gene
  Seurat::DotPlot(seurat, features = genes_to_plot,
                  idents = levels(SeuratObject::Idents(seurat)))+
    Seurat::RotatedAxis()
}
```

```{r bl62, fig.width = 20, fig.height = 10}
if(fraction_curr == "str"){
  genes_to_plot <- gene_list_dtplt$gene
  DotPlot(seurat, features = genes_to_plot, idents = levels(Idents(seurat)))+
    RotatedAxis()
}
```

### CAST

```{r cast1, fig.width = 14, fig.height = 10}

seurat <- Seurat::as.Seurat(sce[,sce$Species_ID == "mcas"],
                            counts = "counts", logcounts = "logcounts")

SeuratObject::Idents(seurat) <- sce[,sce$Species_ID == "mcas"]$celltypes
seurat@active.ident <- factor(
  seurat@active.ident, levels = rev(levels(SeuratObject::Idents(seurat))))

if(fraction_curr == "hsc"){
  genes_to_plot <- gene_list_dtplt$gene
  Seurat::DotPlot(seurat, features = genes_to_plot, 
                  idents = levels(SeuratObject::Idents(seurat)))+
    Seurat::RotatedAxis()
}
```

```{r cast2, fig.width = 20, fig.height = 10}
if(fraction_curr == "str"){
  genes_to_plot <- gene_list_dtplt$gene
  Seurat::DotPlot(seurat, features = genes_to_plot,
                  idents = levels(SeuratObject::Idents(seurat)))+
    Seurat::RotatedAxis()
}
```

### SPRETUS

```{r spret1, fig.width = 14, fig.height = 10}

seurat <- Seurat::as.Seurat(sce[,sce$Species_ID == "mspr"], 
                            counts = "counts", logcounts = "logcounts") 

SeuratObject::Idents(seurat) <- sce[,sce$Species_ID == "mspr"]$celltypes
seurat@active.ident <- factor(
  seurat@active.ident, levels = rev(levels(SeuratObject::Idents(seurat))))

if(fraction_curr == "hsc"){
  genes_to_plot <- gene_list_dtplt$gene
  Seurat::DotPlot(seurat, features = genes_to_plot, 
                  idents = levels(SeuratObject::Idents(seurat)))+
    Seurat::RotatedAxis()
}
```

```{r spet2, fig.width = 20, fig.height = 10}
if(fraction_curr == "str"){
  genes_to_plot <- gene_list_dtplt$gene
  Seurat::DotPlot(seurat, features = genes_to_plot,
                  idents = levels(SeuratObject::Idents(seurat)))+
    Seurat::RotatedAxis()
}
```

### CARO

```{r caro1, fig.width = 14, fig.height = 10}

seurat <- Seurat::as.Seurat(sce[,sce$Species_ID == "mcar"],
                            counts = "counts", logcounts = "logcounts") 

SeuratObject::Idents(seurat) <- sce[,sce$Species_ID == "mcar"]$celltypes
seurat@active.ident <- factor(
  seurat@active.ident, levels = rev(levels(SeuratObject::Idents(seurat))))

if(fraction_curr == "hsc"){
  genes_to_plot <- gene_list_dtplt$gene
  Seurat::DotPlot(seurat, features = genes_to_plot, 
                  idents = levels(SeuratObject::Idents(seurat)))+
    Seurat::RotatedAxis()
}
```

```{r caro2, fig.width = 20, fig.height = 10}
if(fraction_curr == "str"){
  genes_to_plot <- gene_list_dtplt$gene
  Seurat::DotPlot(seurat, features = genes_to_plot, 
                  idents = levels(SeuratObject::Idents(seurat)))+
    Seurat::RotatedAxis()
}
```

### Try the same using ggplot

```{r aggregate}
agg <- scuttle::aggregateAcrossCells(
  sce, id=colData(sce)[,c("celltypes")], 
  statistics = "mean",
  use.assay.type = "logcounts") 

vis_df <- as.data.frame(
  t(assays(agg)$logcounts[
    rownames(assays(agg)$logcounts) %in% gene_list_dtplt$gene,]))

rowmax <- function(dataframe){
  max_vector <- vector()
  
  for(i in 1:nrow(dataframe)){
    max <- max(dataframe[i,])
    max_vector <- c(max_vector, max)
  }
  return(max_vector)
}

vis_df_normalized_per_celltype <- vis_df
vis_df_normalized_per_celltype <- vis_df_normalized_per_celltype/rowmax(vis_df_normalized_per_celltype)
vis_df <- rownames_to_column(vis_df, "celltypes")
vis_df <- pivot_longer(vis_df, cols = c(2:ncol(vis_df)), values_to = "expression", names_to = "gene")

vis_df_normalized_per_celltype <- rownames_to_column(vis_df_normalized_per_celltype, "celltypes")
vis_df_normalized_per_celltype <- pivot_longer(vis_df_normalized_per_celltype,
                                               cols = c(2:ncol(vis_df_normalized_per_celltype)), 
                                               values_to = "expression", names_to = "gene")


vis_df$percent_expressed <- vector(length = nrow(vis_df))
for(ct in unique(vis_df$celltypes)){
  counts_temp <- assays(sce)$logcounts_before_BC[,sce$celltypes == ct]
  for(g in unique(vis_df$gene)){
    perc_expr <- length(which(counts_temp[rownames(counts_temp) == g,] > 0))/ncol(counts_temp)*100
    vis_df$percent_expressed[which(vis_df$celltypes == ct & vis_df$gene == g)] <- perc_expr
  }
}

vis_df$normalized_by_celltype <- vis_df_normalized_per_celltype$expression

vis_df$celltypes <- factor(vis_df$celltypes, levels = rev(names(col_cts)))
vis_df$gene <- factor(vis_df$gene, levels = gene_list_dtplt$gene)

```

```{r hsc_ggdotplot1, fig.width = 7, fig.height = 3.5}
# for HSCS
ggplot(vis_df, aes(x = gene, y = celltypes, color = percent_expressed,
                   size = expression))+
  geom_point()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
        legend.position = "none", axis.text.y = element_text(hjust = 0),
        axis.title = element_blank())+
  scale_size("logcounts", limits=c(0, 9), range = c(0, 4))+
  scale_color_continuous(limits = c(0, 100),low = "white", high = "blue")
```

```{r hsc_ggdotplot2, fig.width = 7, fig.height = 4}
# for HSCs 
ggplot(vis_df, aes(x = gene, y = celltypes, color = expression,
                   size = percent_expressed))+
  geom_point()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
        legend.position = "bottom")+
  scale_color_continuous("logcounts", limits=c(0, 9), 
                         low = ("white"),high = "blue")+
  scale_size("logcounts", limits=c(0, 100), range = c(0,4))

ggplot(vis_df, aes(x = gene, y = celltypes, color = normalized_by_celltype,
                   size = percent_expressed))+
  geom_point()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
        legend.position = "bottom")+
  scale_color_continuous("logcounts normalized by cell type", 
                         limits=c(0, 1), low = ("white"),high = "blue")+
  scale_size("logcounts", limits=c(0, 100), range = c(0, 4))
```

```{r str_ggdotplot1, fig.width = 14, fig.height = 4}
# for stromal all
ggplot(vis_df, aes(x = gene, y = celltypes, color = percent_expressed,
                   size = expression))+
  geom_point()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
        legend.position = "bottom")+
  scale_size("logcounts", limits = c(0, 100), range = c(0,4))+
  scale_color_continuous(limits = c(0, 9),  low = "white",high = "blue")

ggplot(vis_df, aes(x = gene, y = celltypes, color = expression,
                   size = percent_expressed))+
  geom_point()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
        legend.position = "bottom")+
  scale_color_continuous("logcounts", limits=c(0, 9), low = ("grey95"), high = "blue2")+
  scale_size("logcounts", limits = c(0, 100), range = c(0,4))

ggplot(vis_df, aes(x = gene, y = celltypes, color = normalized_by_celltype,
                   size = percent_expressed))+
  geom_point()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
        legend.position = "bottom")+
  scale_color_continuous("logcounts normalized by celltype", limits=c(0, 1), low = ("grey95"), high = "blue2")+
  scale_size("logcounts", limits = c(0, 100), range = c(0,4))
```

```{r str_ggdotplot2, fig.width = 14, fig.height = 4}
# for stromal all
ggplot(vis_df, aes(x = gene, y = celltypes, color = normalized_by_celltype,
                   size = percent_expressed))+
  geom_point()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
        legend.position = "bottom")+
  scale_color_continuous("logcounts", limits=c(0, 1), low = ("grey95"), high = "blue2")+
  scale_size("logcounts", limits = c(0, 100), range = c(0,4))

ggplot(vis_df, aes(x = gene, y = celltypes, fill = expression))+
  geom_tile()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
        legend.position = "bottom")+
  scale_fill_continuous("logcounts", limits=c(0, 9), 
                        low = ("grey95"), high = "blue2")
```

```{r str_ggdotplot3, fig.width = 7, fig.height = 3.5}
# for stromal short
if(fraction_curr == "str"){
  vis_df_short <- vis_df[which(!vis_df$gene %in% c("Ibsp", "Acan", "Adipoq", "Sp7", "Mgp", "Vim", "Thy1", "Nes", "Dcn", "Emcn", "S100a6",
                                             "Cspg4", "Aqp7", "Cd300lg", "Efnb2", "Ly6a", "C1qtnf9", "Slc9a3r2", "Sparcl1", "Flt4", "Col1a1",
                                             "Slc6a6", "Sema3g", "Mecom", "Lrg1", "Abcc9", "Ephb4", "Selp", "Sele", "Fbln2",
                                             "Nr2f2", "Acta2", "Mylk", "Vtn", "Adamts5", "Icam1", "Aplnr", "Tm4sf1", "Tinagl1", "Aqp1")),]
  vis_df_short$gene <- factor(vis_df_short$gene, levels = levels(vis_df$gene)[which(levels(vis_df$gene) %in% vis_df_short$gene)])

  ggplot(vis_df_short, aes(x = gene, y = celltypes, color = percent_expressed,
                     size = expression))+
    geom_point()+
    theme_classic()+
    theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
          legend.position = "bottom",
          axis.text.y = element_text(hjust = 0),
          axis.title = element_blank())+
    scale_color_continuous(limits=c(0, 100),  low = ("white"), high = "blue")+
  scale_size("logcounts", limits = c(0, 9), range = c(0,4))
}
```

```{r agg_again}
if(fraction_curr == "str"){
  cell_type <- "Adipo/CARs"
}else if(fraction_curr == "hsc"){
  cell_type <- "HSCs"
}

sce_temp <- sce[,sce$celltypes == cell_type]
agg <- scuttle::aggregateAcrossCells(sce_temp, id=colData(sce_temp)[,c("Species_ID")], 
                            statistics = "mean",
                            use.assay.type = "logcounts")

vis_df <- as.data.frame(
  t(assays(agg)$logcounts[
    rownames(assays(agg)$logcounts) %in% gene_list_dtplt$gene,]))

vis_df <- rownames_to_column(vis_df, "species")
vis_df <- pivot_longer(vis_df, cols = c(2:ncol(vis_df)), values_to = "expression", names_to = "gene")

vis_df$percent_expressed <- vector(length = nrow(vis_df))
for(s in unique(vis_df$species)){
  counts_temp <- assays(sce_temp)$logcounts[,sce_temp$Species_ID == s]
  for(g in unique(vis_df$gene)){
    perc_expr <- length(which(counts_temp[rownames(counts_temp) == g,] > 0))/ncol(counts_temp)*100
    vis_df$percent_expressed[which(vis_df$species == s & vis_df$gene == g)] <- perc_expr
  }
}

vis_df$species <- factor(vis_df$species, levels = rev(names(col_spc)))
vis_df$gene <- factor(vis_df$gene, levels = gene_list_dtplt$gene)
```

```{r hsc_ggdotplot3, fig.width = 5.5, fig.height = 1.5}
# for HSCs
ggplot(vis_df, aes(x = gene, y = species, color = percent_expressed,
                   size = expression))+
  geom_point()+
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_blank(),
        axis.title.x = element_blank(), plot.title = element_text(size = 11))+
  scale_color_continuous(limits=c(0, 100),  low = ("white"), high = "blue")+
  scale_size("logcounts", limits=c(0, 9), range = c(0,4))+
  ggtitle(cell_type)
```

```{r hsc_ggdotplot4, fig.width = 12, fig.height = 1.5}
ggplot(vis_df, aes(x = gene, y = species, color = percent_expressed,
                   size = expression))+
  geom_point()+
  theme_classic()+
  theme(axis.text.x = element_blank(),
        legend.position = "none", plot.title = element_text(size = 11))+
  scale_color_continuous(limits=c(0, 100),  low = ("white"), high = "blue")+
  scale_size("logcounts", limits=c(0, 9), range = c(0,4))+
    ggtitle(cell_type)
```

```{r str_ggdotplot4, fig.width = 5.5, fig.height = 1.5}
if(fraction_curr == "str"){
  vis_df_short <- vis_df[which(!vis_df$gene %in% c("Ibsp", "Acan", "Adipoq", "Sp7", "Mgp", "Vim", "Thy1", "Nes", "Dcn", "Emcn", "S100a6",
                                             "Cspg4", "Aqp7", "Cd300lg", "Efnb2", "Ly6a", "C1qtnf9", "Slc9a3r2", "Sparcl1", "Flt4", "Col1a1",
                                             "Slc6a6", "Sema3g", "Mecom", "Lrg1", "Abcc9", "Ephb4", "Selp", "Sele", "Fbln2",
                                             "Nr2f2", "Acta2", "Mylk", "Vtn", "Adamts5", "Icam1", "Aplnr", "Tm4sf1", "Tinagl1", "Aqp1")),]
  vis_df_short$gene <- factor(vis_df_short$gene, levels = levels(vis_df$gene)[which(levels(vis_df$gene) %in% vis_df_short$gene)])

  ggplot(vis_df_short, aes(x = gene, y = species, color = percent_expressed,
                     size = expression))+
    geom_point()+
    theme_classic()+
    theme(legend.position = "none", plot.title = element_text(size = 11),
          axis.text.x = element_blank(),
          axis.title.x = element_blank())+
  scale_color_continuous(limits=c(0, 100),  low = ("white"), high = "blue")+
  scale_size("logcounts", limits=c(0, 9), range = c(0,4))+
    ggtitle(cell_type)
}
```

## Comparison to References

```{r comaprison_str}

if(fraction_curr == "str"){
  sce_temp1 <- sce
  sce_temp1$baccin_celltype_scmapclust <- factor(
    sce_temp1$baccin_celltype_scmapclust, levels = c("Adipo-CAR",
                                                     "Osteo-CAR",
                                                     "Ng2+ MSCs",
                                                     "Osteoblasts",
                                                     "Arteriolar fibro.",
                                                     "Fibro/Chondro p.",
                                                     "Chondrocytes",
                                                     "Endosteal fibro.",
                                                     "Arteriolar ECs",
                                                     "Sinusoidal ECs",
                                                     "Smooth muscle",
                                                     "unassigned"))
  
   sce_temp1$dolgalev_celltype_scmapclust <- factor(
    sce_temp1$dolgalev_celltype_scmapclust, levels = c("MSPC-Adipo",
                                                       "MSPC-Osteo",
                                                       "Osteoblasts",
                                                       "Osteo",
                                                       "Fibroblasts",
                                                       "Chondrocytes",
                                                       "EC-Arteriar",
                                                       "EC-Arteriolar",
                                                       "EC-Sinusoidal",
                                                       "Pericytes",
                                                       "Smooth-muscle",
                                                       "unassigned"))

  mat1 <- table(sce_temp1$celltypes, sce_temp1$baccin_celltype_scmapclust)
  mat1 <- mat1/rowSums(mat1)*100

  mat2 <- table(sce$celltypes, sce$dahlin_celltype_scmapclust)
  mat2 <- mat2/rowSums(mat2)*100
 
  mat3 <- table(sce_temp1$celltypes, sce_temp1$dolgalev_celltype_scmapclust)
  mat3 <- mat3/rowSums(mat3)*100

  pheatmap(mat1,
           cluster_rows = FALSE,
           cluster_cols = FALSE)
  
  pheatmap(mat2)
  
  pheatmap(mat3,
           cluster_rows = FALSE,
           cluster_cols = FALSE)
  
  mat4 <- table(sce_temp1$baccin_celltype_scmapclust, sce_temp1$celltypes)
  mat4 <- mat4/rowSums(mat4)*100

  mat5 <- table(sce$dahlin_celltype_scmapclust, sce_temp1$celltypes)
  mat5 <- mat5/rowSums(mat5)*100
 
  mat6 <- table(sce_temp1$dolgalev_celltype_scmapclust, sce_temp1$celltypes)
  mat6 <- mat6/rowSums(mat6)*100

  pheatmap(mat4,
           cluster_rows = FALSE,
           cluster_cols = FALSE)
  
  pheatmap(mat5)
  
  pheatmap(mat6,
           cluster_rows = FALSE,
           cluster_cols = FALSE)
}  
```

```{r comparison_hsc}

if(fraction_curr == "hsc"){
  sce_temp1 <- sce
  sce_temp1$baccin_celltype_scmapclust <- factor(
    sce_temp1$baccin_celltype_scmapclust, levels = c("LMPPs",
                                                     "Mk prog.",
                                                     "Gran/Mono prog.",
                                                     "Mono prog.",
                                                     "Neutro prog.",
                                                     "large pre-B.",
                                                     "Eo/Baso prog.",
                                                     "Ery/Mk prog.",
                                                     "Erythroblasts",
                                                     "unassigned"))
  
   sce_temp1$dahlin_celltype_scmapclust <- factor(
    sce_temp1$dahlin_celltype_scmapclust, levels = c("HSC LT",
                                                     "HSC ST",
                                                     "MPP1",
                                                     "MPP2",
                                                     "LMPP",
                                                     "GMP",
                                                     "Monocyte Progenitor",
                                                     "proNeu",
                                                     "proB",
                                                     "CLP",
                                                     "Basophil",
                                                     "Mast",
                                                     "MEP",
                                                     "Mkp",
                                                     "Erythroblast",
                                                     "unassigned"))

  mat1 <- table(sce_temp1$celltypes, sce_temp1$baccin_celltype_scmapclust)
  mat1 <- mat1/rowSums(mat1)*100

  mat2 <- table(sce_temp1$celltypes, sce_temp1$dahlin_celltype_scmapclust)
  mat2 <- mat2/rowSums(mat2)*100
 
  pheatmap(mat1,
           cluster_rows = FALSE,
           cluster_cols = FALSE)
  
  pheatmap(mat2,
           cluster_rows = FALSE,
           cluster_cols = FALSE)
  
  mat4 <- table(sce_temp1$baccin_celltype_scmapclust, sce_temp1$celltypes)
  mat4 <- mat4/rowSums(mat4)*100

  mat5 <- table(sce_temp1$dahlin_celltype_scmapclust, sce_temp1$celltypes)
  mat5 <- mat5/rowSums(mat5)*100
 
  pheatmap(mat4,
           cluster_rows = FALSE,
           cluster_cols = FALSE)
  
  pheatmap(mat5,
           cluster_rows = FALSE,
           cluster_cols = FALSE)
}  

```

```{r session_info}
sessionInfo()
```