---
title: "Subclustering report"
author: "Lea Wölbert"
date: '2023-07-24'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Load libraries, source code 

```{r load,  message = FALSE}
library(SingleCellExperiment, quietly = TRUE) 
library(scater, quietly = TRUE) 
library(scran, quietly = TRUE) 
library(pheatmap, quietly = TRUE) 
library(tidyverse, quietly = TRUE) 
library(viridisLite, quietly = TRUE) 
library(Seurat)

set.seed(37)
```

```{r message = FALSE}
# load sources
source(file = "../../source/plotting.R")
source(file = "../../source/sce_functions.R")
```


```{r message = FALSE}
#load SCE objects
sce <- readRDS(file = snakemake@input[["sce_input"]])

fraction_curr <- snakemake@wildcards[["fraction"]]

sce$Species_ID <- factor(sce$Species_ID,
                         levels = c("mmus", "mcas", "mspr", "mcar"))
```

```{r}
gene_list <- read.csv(snakemake@input[["gene_list_subclustering"]], 
  header = TRUE, 
  sep = ";", 
  check.names=FALSE, 
  stringsAsFactors=FALSE, 
  as.is=TRUE, 
  colClasses = "character")

gene_list <- gene_list[gene_list$fraction == fraction_curr,]
```

```{r}
color_table <- read.csv(snakemake@params[["color_table"]], 
  header = TRUE, 
  sep = ";", 
  check.names=FALSE, 
  stringsAsFactors=FALSE, 
  as.is=TRUE, 
  colClasses = "character")

col_curr <- color_table[color_table$fraction == fraction_curr,]

col_cts <- col_curr$color[col_curr$level %in% sce$celltypes]
col_cat <- col_curr$color[col_curr$level %in% sce$category]

names(col_cts) <- col_curr$level[col_curr$level %in% sce$celltypes]
names(col_cat) <- col_curr$level[col_curr$level %in% sce$category]

```

# Subclustering Overview

```{r}

plot_1 <- umap_base(sce, color_by = "category")+ 
  ggtitle(fraction_curr)+
  scale_color_manual("Category", values = col_cat)
plot_1l <- umap_legend(sce, color_by = "category")+
  scale_color_manual("Category", values = col_cat)
legend_1 <- get_legend(plot_1l)
  
plot_2 <- umap_base(sce, color_by = "celltypes")+ 
  ggtitle(paste(fraction_curr))+
  scale_color_manual("Cell types", values = col_cts)  
plot_2l <- umap_legend(sce, color_by = "celltypes")+
  scale_color_manual("Cell types", values = col_cts)
legend_2 <- get_legend(plot_2l)
  
PLOT_1 <- ggarrange(plot_1, legend_1, widths = c(2, 1))
PLOT_2 <- ggarrange(plot_2, legend_2, widths = c(2, 1))

PLOT_1
PLOT_2
```

```{r}

coord_x <- c(min(reducedDims(sce)$UMAP[,1]), max(reducedDims(sce)$UMAP[,1]))
coord_y <- c(min(reducedDims(sce)$UMAP[,2]), max(reducedDims(sce)$UMAP[,2]))

plot_1 <- umap_base_l(sce[,sce$Species_ID == "mmus"], 
                      color_by = "celltypes")+
  ggtitle("mmus")+
  scale_color_manual("Cell types", values = col_cts)+
  theme(legend.position = "none")+
  xlim(coord_x)+
  ylim(coord_y)
plot_2 <- umap_base_l(sce[,sce$Species_ID == "mcas"], 
                      color_by = "celltypes")+
  ggtitle("mcas")+
  scale_color_manual("Cell types", values = col_cts)+
  theme(legend.position = "none")+
  xlim(coord_x)+
  ylim(coord_y)
plot_3 <- umap_base_l(sce[,sce$Species_ID == "mspr"], 
                      color_by = "celltypes")+
  ggtitle("mspr")+
  scale_color_manual("Cell types", values = col_cts)+
  theme(legend.position = "none")+
  xlim(coord_x)+
  ylim(coord_y)
plot_4 <- umap_base_l(sce[,sce$Species_ID == "mcar"], 
                      color_by = "celltypes")+
  ggtitle("mcar")+
  scale_color_manual("Cell types", values = col_cts)+
  theme(legend.position = "none")+
  xlim(coord_x)+
  ylim(coord_y)

PLOT_1 <- ggarrange(plot_1, legend_1, widths = c(2, 1))
PLOT_2 <- ggarrange(plot_2, legend_1, widths = c(2, 1))
PLOT_3 <- ggarrange(plot_3, legend_1, widths = c(2, 1))
PLOT_4 <- ggarrange(plot_4, legend_1, widths = c(2, 1))

PLOT_1
PLOT_2
PLOT_3
PLOT_4
```

```{r}
print(table(sce$Species_ID, sce$celltypes))
```

```{r}
print(table(sce$Species_ID, sce$celltypes)/rowSums(table(sce$Species_ID, sce$celltypes))*100)
```

## Gene expression

```{r}

seurat <- as.Seurat(sce, counts = "counts", logcounts = "logcounts") # logcounts (assay) only used if dims (reduction) = NULL
Idents(seurat) <- sce$celltypes
seurat@active.ident <- factor(seurat@active.ident, levels = rev(levels(Idents(seurat))))

```

```{r fig.width = 20, fig.height = 10}

genes_to_plot_hsc <- c(
  "Mecom",
  "Procr",
  "Slamf1",
  "Hlf",
  "Meis1",
  "Adgrl4",
  "Cd34",
  "Dctpp1",
  "Mcm6",
  "Lig1",
  "Hells",
  "Mpo",
  "Elane",
  "Irf8",
  "Ccr2",
  "S100a8",
  "S100a9",
  "Flt3",
  "Satb1",
  "Dntt",
  "Hdc",
  "Cpa3",
  "Gata2",
  "Pbx1",
  "Itga2b",
  "Pf4",
  "Vwf",
  "Gata1",
  "Car1",
  "Car2",
  "Blvrb",
  "Klf1",
  "Epor",
  "Hba-a1",
  "Mki67",
  "Lockd",
  "Cenpa"
)

genes_to_plot_mes <- c(
 "Cxcl12",
 "Kitl",
 "Lepr",
 "Adipoq",
 "Ibsp",
 "Spp1",
 "Alpl",
 "Bglap",
 "Sp7",
 "Car3",
 "Comp",
 "Fmod",
 "Chad",
 "Sox9",
 "Acan",
 "Mgp",
 "Dcn",
 "Fn1",
 "Pdgfra",
 "Vim",
 "Cd34",
 "Thy1",
 "Nes",
 "Cspg4"
)

genes_to_plot_ecs <- c(
 # pan endo
 "Cdh5",
 "Emcn",
 "Pecam1",
 
 # niche markers
 "Cxcl12",
 "Kitl",

 # capillary
 "Car4", # capillary venous, # capillary lung, can be lung capillary, rat lung capillary, aerocyte capillary, lung capillaries
 "Aqp7", # capillary (human adipose tissue)
 "Rgcc", # capillary,  # capillary HUMAN schupp
 "Aqp1", # arteriar BM, microvascular, brain capillary level
 "Cd300lg", #  small arterioles, venules, and capillaries of most tissue, capillary
 "Timp4", # arterial BM,  inhibitor of capillary endothelial cell migration, artery injury, heart
 "Aplnr",  # capillary lung, angiogenesis, activationl

  # arterial capillary
 "Efnb2", # arterial BM # arterial HUMAN schupp, arteries and microvessels,  arterial microvessels, vessel fate, angiogenesis artery to capillary
 "C1qtnf9", # arteriar BM, capillary endothelial, arterial hypertension, arteriole-capillary cluster
 "Tspan13", # arteriar BM, dysfunctional endothelium, capillaries, sinusoid in heart
 "Slc9a3r2",# arteriolar BM, # AEC baccin, arterioles and arteries, sports related, capillary, microvasculature, capillary and artery, C A and V
 "Slc6a6", # arterial BM, # AEC baccin, capillary
 
 # arterial 
 "Fbln2",# arterial BM, # AEC baccin, arterial stiffness, arteries, related to arterial hypertension
 "Ly6a", # arterial BM, # AEC baccin, heart, EC progenitor subset
 "Sparcl1", # arterial BM, # AEC baccin, quiescence, venous
 "Cd34", # artery
 "Tm4sf1",# arterial BM, SEC baccin, AEC baccin, possibl stem, human lung arteries progenitor
 "Sema3g", # arterial BM, # arterial HUMAN schupp, arteries during development, not specific EC

 # large artery
 "Sox17", # large artery, # AEC baccin # arterial HUMAN schupp
 "Mecom", # artery, arterial, non-capillary, arterial fate
 "Hey1", # artery # arterial BM, # arterial HUMAN schupp, arterial cell fate, great vessels, artery formatio
 "Gja4", # large artery, # arterial BM, # arteriar BM, # arterial HUMAN schupp, arterial shear, arterial gene expression in arteries, aorta, small and large vessels
 
 # capillary/sinusoidal
 "Cldn5", # SEC baccin, # AEC baccin
 "Plvap", # SEC baccin, # capillary lung, # venous HUMAN schupp, lung capillary
 "Lrg1", # sinusoidal BM, SEC baccin

 # sinusoidal BM
 "Tfpi", # sinusoidal BM, sinusoidal BM, SEC baccin
 "Stab2", # sinusoidal BM, # sinusoidal BM
 "Adamts5", # sinusoidal BM
 "Flt4", # sinusoidal BM, # sinusoidal BM
 "Abcc9",# sinusoidal BM
 "Ackr1", # sinusoidal BM, # venous HUMAN schupp
 
 # general venous
 "Ephb4", #VENOUS
 "Selp",# sinusoidal BM, # venous HUMAN schupp
 "Icam1",# sinusoidal BM
 "Sele",# sinusoidal BM
 "Nr2f2",  # venous HUMAN schupp
 "Vcam1" # sinusoidal BM, # venous HUMAN schupp

 #"Cotl1", # transition vessel 
 #"Sox4" # transition vessel 
 
  #"Vwf", # venous HUMAN schupp, vessel marker for coagulation both arteriolar and venous

 #"Tgfb2", # capillary arteriolar
 #"Tfrc" # capillary venous
 #"Cytl1" # large artery
 # "Notch4",
 #"Mfsd2a" # capillary
# "Ly6a", # arterial BM
# "Fabp4",# sinusoidal BM, sinusoidal BM, SEC baccin, AEC baccin
 #"Ubd", # sinusoidal BM, # sinusoidal BM
 #"Ctsl",# sinusoidal BM
 #"Il6st",# sinusoidal BM
 #"Sepp1"# sinusoidal BM, SEC baccin

 #"Gkn3",# arterial BM
 #"Ly6c1", # arteriolar BM, # AEC baccin
 #"Egfl7"# arteriolar BM

 #"Fabp5",# arterial BM
 #"Eng" #SEC baccin, # AEC baccin
 #"Kdr" # SEC baccin
 #"Apln", # capillary lung, angiogenesis
 #"Fibin", # capillary lung
 #"Cd93"# capillary lung
 #"Ednrb", # capillary lung
 #"Cd200", # arterial BM,  arterioles, most veins and venules, as well as continuous and fenestrated capillaries, sinusoids in BM, weakly expressed on blood capillaries, AEC baccin

 # "Ass1", # endothelial health, shear stress

 #"Vegfc", # arteriar BM, AEC baccin
 #"Ramp3",# arterial BM
 #"Gnas", # arterial BM
# "Cav1", # arterial BM, # arteriar BM, # AEC baccin
# "Rbp7",# arterial BM

 #"Podxl", # arterial BM
# "Bcam", # AEC baccin 
 #"Fbln5", # artery, large artery, # arterial HUMAN schupp, quiescence
# "Glul", # capillary arteriolar, # AEC baccin

)

genes_to_plot_smc <- c(
  "Acta2", # smooth
  "Tagln", # smooth
  "Mylk", # smooth
  "Tinagl1", # peri
  "Rgs5", # peri
  "Rgs4", # peri
  "Vtn", # peri
  "Steap4" # peri
)
```

```{r fig.width = 14, fig.height = 10}
if(fraction_curr == "hsc"){
  genes_to_plot <- genes_to_plot_hsc
  DotPlot(seurat, features = genes_to_plot, idents = levels(Idents(seurat)))+
    RotatedAxis()
}
```

```{r fig.width = 20, fig.height = 10}
if(fraction_curr == "str"){
  genes_to_plot <- unique(c(genes_to_plot_mes, genes_to_plot_ecs, genes_to_plot_smc))
  DotPlot(seurat, features = genes_to_plot, idents = levels(Idents(seurat)))+
    RotatedAxis()
}
```

## Comparison to References

```{r}

if(fraction_curr == "str"){
  sce_temp1 <- sce
  sce_temp1$baccin_celltype_scmapclust <- factor(
    sce_temp1$baccin_celltype_scmapclust, levels = c("Adipo-CAR",
                                                     "Osteo-CAR",
                                                     "Ng2+ MSCs",
                                                     "Osteoblasts",
                                                     "Arteriolar fibro.",
                                                     "Fibro/Chondro p.",
                                                     "Chondrocytes",
                                                     "Endosteal fibro.",
                                                     "Arteriolar ECs",
                                                     "Sinusoidal ECs",
                                                     "Smooth muscle",
                                                     "unassigned"))
  
   sce_temp1$dolgalev_celltype_scmapclust <- factor(
    sce_temp1$dolgalev_celltype_scmapclust, levels = c("MSPC-Adipo",
                                                       "MSPC-Osteo",
                                                       "Osteoblasts",
                                                       "Osteo",
                                                       "Fibroblasts",
                                                       "Chondrocytes",
                                                       "EC-Arteriar",
                                                       "EC-Arteriolar",
                                                       "EC-Sinusoidal",
                                                       "Pericytes",
                                                       "Smooth-muscle",
                                                       "unassigned"))

  mat1 <- table(sce_temp1$celltypes, sce_temp1$baccin_celltype_scmapclust)
  mat1 <- mat1/rowSums(mat1)*100

  mat2 <- table(sce$celltypes, sce$dahlin_celltype_scmapclust)
  mat2 <- mat2/rowSums(mat2)*100
 
  mat3 <- table(sce_temp1$celltypes, sce_temp1$dolgalev_celltype_scmapclust)
  mat3 <- mat3/rowSums(mat3)*100

  pheatmap(mat1,
           cluster_rows = FALSE,
           cluster_cols = FALSE)
  
  pheatmap(mat2)
  
  pheatmap(mat3,
           cluster_rows = FALSE,
           cluster_cols = FALSE)
  
  mat4 <- table(sce_temp1$baccin_celltype_scmapclust, sce_temp1$celltypes)
  mat4 <- mat4/rowSums(mat4)*100

  mat5 <- table(sce$dahlin_celltype_scmapclust, sce_temp1$celltypes)
  mat5 <- mat5/rowSums(mat5)*100
 
  mat6 <- table(sce_temp1$dolgalev_celltype_scmapclust, sce_temp1$celltypes)
  mat6 <- mat6/rowSums(mat6)*100

  pheatmap(mat4,
           cluster_rows = FALSE,
           cluster_cols = FALSE)
  
  pheatmap(mat5)
  
  pheatmap(mat6,
           cluster_rows = FALSE,
           cluster_cols = FALSE)
}  
```

```{r}

if(fraction_curr == "hsc"){
  sce_temp1 <- sce
  sce_temp1$baccin_celltype_scmapclust <- factor(
    sce_temp1$baccin_celltype_scmapclust, levels = c("LMPPs",
                                                     "Mk prog.",
                                                     "Gran/Mono prog.",
                                                     "Mono prog.",
                                                     "Neutro prog.",
                                                     "large pre-B.",
                                                     "Eo/Baso prog.",
                                                     "Ery/Mk prog.",
                                                     "Erythroblasts",
                                                     "unassigned"))
  
   sce_temp1$dahlin_celltype_scmapclust <- factor(
    sce_temp1$dahlin_celltype_scmapclust, levels = c("HSC LT",
                                                     "HSC ST",
                                                     "MPP1",
                                                     "MPP2",
                                                     "LMPP",
                                                     "GMP",
                                                     "Monocyte Progenitor",
                                                     "proNeu",
                                                     "proB",
                                                     "CLP",
                                                     "Basophil",
                                                     "Mast",
                                                     "MEP",
                                                     "Mkp",
                                                     "Erythroblast",
                                                     "unassigned"))

  mat1 <- table(sce_temp1$celltypes, sce_temp1$baccin_celltype_scmapclust)
  mat1 <- mat1/rowSums(mat1)*100

  mat2 <- table(sce_temp1$celltypes, sce_temp1$dahlin_celltype_scmapclust)
  mat2 <- mat2/rowSums(mat2)*100
 
  pheatmap(mat1,
           cluster_rows = FALSE,
           cluster_cols = FALSE)
  
  pheatmap(mat2,
           cluster_rows = FALSE,
           cluster_cols = FALSE)
  
  mat4 <- table(sce_temp1$baccin_celltype_scmapclust, sce_temp1$celltypes)
  mat4 <- mat4/rowSums(mat4)*100

  mat5 <- table(sce_temp1$dahlin_celltype_scmapclust, sce_temp1$celltypes)
  mat5 <- mat5/rowSums(mat5)*100
 
  pheatmap(mat4,
           cluster_rows = FALSE,
           cluster_cols = FALSE)
  
  pheatmap(mat5,
           cluster_rows = FALSE,
           cluster_cols = FALSE)
}  

```

# Subclustering QC

```{r}
make_plot_list <- function(gene, title){
  
  ggdf <- as.data.frame(colData(sce_temp))
  logc <- assays(sce_temp)[["logcounts"]]
  
  plot1 <- umap_gene(sce_temp, gene)

  plot1 <- umap_gene(sce_temp, gene)+
    facet_grid(cols = vars(sce_temp$Species_ID))

  ggdf$Species_ID <- factor(ggdf$Species_ID,
                            levels = c("mmus", "mcas", "mspr", "mcar"))
  
  plot1 <- ggplot(ggdf, aes(x = celltypes,
                             y = logc[rownames(logc) == gene,]))+
    geom_violin(fill = "grey60")+
    theme_classic()+
    geom_boxplot(color = "black", alpha = 0)+
    ylab(paste0(gene, " expression"))+
    facet_grid(cols = vars(sce_temp$Species_ID))+
    theme(axis.text.x = element_text(angle = 90))+
    ggtitle(paste(title), gene)
  
  return(list(gene, plot1))
}
```

```{r}

for(i in unique(gene_list$cluster)){

  print(i)
  gene_list_temp <- gene_list[gene_list$cluster == i,]
  print(gene_list_temp)
  genes <- unique(gene_list_temp$gene)
  genes <- genes[which(genes %in% rownames(sce))]

  if(i == "2_4"){
    cluster <- c(2, 4)
  }else if(i == 7){
    cluster <- NULL
  }else{
    cluster <- i
  }
  print(cluster)
  
  sce_temp <-  sce[,sce$cluster_louvain == cluster]
  
  coord_x <- c(min(reducedDims(sce_temp)$UMAP[,1]), 
               max(reducedDims(sce_temp)$UMAP[,1]))
  coord_y <- c(min(reducedDims(sce_temp)$UMAP[,2]), 
               max(reducedDims(sce_temp)$UMAP[,2]))

  if(!is.null(cluster)){
    plot_1 <- umap_base_l(sce_temp[,sce_temp$Species_ID == "mmus"], 
                          color_by = "annotation_subcluster")+
      ggtitle("mmus")+
      xlim(coord_x)+
      ylim(coord_y)
  
    plot_2 <- umap_base_l(sce_temp[,sce_temp$Species_ID == "mcas"], 
                          color_by = "annotation_subcluster")+
      ggtitle("mcas")+
      xlim(coord_x)+
      ylim(coord_y)
  
    plot_3 <- umap_base_l(sce_temp[,sce_temp$Species_ID == "mspr"], 
                          color_by = "annotation_subcluster")+
      ggtitle("mspr")+
      xlim(coord_x)+
      ylim(coord_y)
    
    plot_4 <- umap_base_l(sce_temp[,sce_temp$Species_ID == "mcar"], 
                          color_by = "annotation_subcluster")+
      ggtitle("mcar")+
      xlim(coord_x)+
      ylim(coord_y)

    print(head(sce_temp$annotation_subcluster))
    print(head(sce_temp$Species_ID))
    plot_5 <- umap_base_l(sce_temp, color_by = "annotation_subcluster")+
      facet_grid(cols = vars(sce_temp$annotation_subcluster),
                 rows = vars(sce_temp$Species_ID))
  
    title <- paste(fraction_curr, sce_temp$annotation_cluster[1])
    
    plot_list <- lapply(genes, make_plot_list, title)
    print(list(plot_1, plot_2, plot_3, plot_4, plot_5))
    print(plot_list)
  }
}
```

```{r}
sessionInfo()
```