---
title: "batch_correction_summary"
author: "Lea Wölbert"
date: '2022-12-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Summary report after Batch correction to see how well the top HVG genes
overlap between fractions.

#### Load libraries, source code 

```{r load,  message = FALSE}
library(SingleCellExperiment, quietly = TRUE) 
library(DropletUtils, quietly = TRUE) 
library(tidyverse, quietly = TRUE) 
library(ComplexUpset, quietly = TRUE)
set.seed(37)
```

```{r load_snakemake, message = FALSE}

sce_02_pathlist <- snakemake@input[["sce_02"]]
fractions <- snakemake@params[["fractions"]]

sce_list_02 <- list()
names(sce_02_pathlist) <- unlist(sce_02_pathlist)
print(sce_02_pathlist)

for(f in fractions){
  sce_list_02[[f]] <- readRDS(file = sce_02_pathlist[[which(grepl(f, names(sce_02_pathlist)))]])
}

```

```{r}

df_overlap <- data.frame(
 row.names = unique(c(rownames(sce_list_02$hsc),
                      rownames(sce_list_02$str)))
)

df_overlap$hsc <- vector(length = nrow(df_overlap))
df_overlap$str <- vector(length = nrow(df_overlap))

df_overlap$hsc[rownames(df_overlap) %in% rownames(sce_list_02$hsc)] <- TRUE
df_overlap$str[rownames(df_overlap) %in% rownames(sce_list_02$str)] <- TRUE

plot <- ComplexUpset::upset(df_overlap, 
              intersect = colnames(df_overlap),
              sort_intersections_by = c("cardinality", "ratio"),
              min_size = 5,
              name = NULL
)

plot
```

```{r}
sessionInfo()
```
