---
title: "Clustering report"
author: "Lea Wölbert"
date: '2022-12-19'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Report for clustering as part of manual annotation at fraction level.

#### Load libraries, source code 

```{r seed,  message = FALSE}
set.seed(37)
```

```{r load,  message = FALSE}
library(bluster, quietly = TRUE) 
```

```{r source, message = FALSE}
source(file =  snakemake@params[["functions"]])
source(file =  snakemake@params[["plotting"]])
```

```{r load_objects}
#sce_inp <- base::readRDS(file = snakemake@input[["sce_input"]])
sce_l <- base::readRDS(file = snakemake@input[["sce_l"]])
fraction_curr <- snakemake@wildcards[["fraction"]]
```

```{r colors, meassage = FALSE}
colors_ref_path <- snakemake@params[["colors_ref_path"]]
colors_path <- snakemake@params[["colors_path"]]
source(snakemake@params[["colors"]])

#sce_inp <- factor_reference_cts(sce_inp)
sce_l <- factor_reference_cts(sce_l)

if(fraction_curr == "hsc"){
  col_cts_ref["unassigned"] <- "honeydew2"
  col_num <- c(col_num, "DOWNSAMPLED" = "grey90")
}else if(fraction_curr == "str"){
  col_cts_ref["unassigned"] <- "mistyrose3"
}

# randomize counts for nicer plots
#sce_inp[,base::sample(c(1:ncol(sce_inp)), size = ncol(sce_inp))]
sce_l[,base::sample(c(1:ncol(sce_l)), size = ncol(sce_l))]


col_cts_baccin <- col_cts_ref[base::match(
  levels(sce_l$baccin_celltype_scmapclust), 
  names(col_cts_ref))]
col_cts_dahlin <- col_cts_ref[base::match(
  levels(sce_l$dahlin_celltype_scmapclust), 
  names(col_cts_ref))]
col_cts_dolgalev <- col_cts_ref[base::match(
  levels(sce_l$dolgalev_celltype_scmapclust),
  names(col_cts_ref))]

col_batch_exp_day <- col_alp[names(col_alp) %in% sce_l$Batch_exp_day]
col_age <- col_age[names(col_age) %in% sce_l$Age_ID]
col_frc <- col_frc[names(col_frc) %in% sce_l$Fraction_ID]
col_spc <- col_spc[names(col_spc) %in% sce_l$Species_ID]

col_clust_l <- col_num[names(col_num) %in% sce_l$cluster_louvain]
```

Annotations for reference.

```{r plots_function}

title_full <- base::paste0(fraction_curr, sce_l$k_louvain[1])

identity_plots <- function(sce){
  
  plot_1 <- umap_base(sce, color_by = "baccin_celltype_scmapclust")+ 
    ggplot2::ggtitle(title_full)+
    ggplot2::scale_color_manual(values = col_cts_baccin)
  plot_1l <- umap_legend(sce, color_by = "baccin_celltype_scmapclust")+
    ggplot2::scale_color_manual("baccin_celltype_scmapclust",
                                values = col_cts_baccin)
  legend_1 <- ggpubr::get_legend(plot_1l)

  plot_2 <- umap_base(sce, color_by = "dahlin_celltype_scmapclust")+
    ggplot2::ggtitle(title_full)+
    ggplot2::scale_color_manual(values = col_cts_dahlin)
  plot_2l <- umap_legend(sce, color_by = "dahlin_celltype_scmapclust")+
    ggplot2::scale_color_manual("dahlin_celltype_scmapclust",
                                values = col_cts_dahlin)
  legend_2 <- ggpubr::get_legend(plot_2l)
  
  # plot_3 <- umap_base(sce, color_by = "dolgalev_celltype_scmapclust")+
  #   ggplot2::ggtitle(title_full)+
  #   ggplot2::scale_color_manual(values = col_cts_dolgalev)
  # plot_3l <- umap_legend(sce, color_by = "dolgalev_celltype_scmapclust")+
  #   ggplot2::scale_color_manual("dolgalev_celltype_scmapclust",
  #                               values = col_cts_dolgalev)
  # legend_3 <- ggpubr::get_legend(plot_3l)
  
  PLOT_1 <- ggpubr::ggarrange(plot_1, legend_1)
  PLOT_2 <- ggpubr::ggarrange(plot_2, legend_2)
  #PLOT_3 <- ggpubr::ggarrange(plot_3, legend_3)

  #return(list(PLOT_1, PLOT_2, PLOT_3))
  return(list(PLOT_1, PLOT_2))
}
identity_plots <- identity_plots(sce_l)
```

```{r plots, fig.width=8, fig.height=4}
identity_plots
```

# Louvain

```{r print_tables}
print(base::table(sce_l$cluster_louvain))
print(base::table(sce_l$cluster_louvain, sce_l$Species_ID))
print(base::table(sce_l$cluster_louvain, sce_l$Age_ID))
```

## Clusters

```{r plot_clusters, fig.width=8, fig.height=4}

plot_title <- base::paste0(fraction_curr, sce_l$k_louvain[1])

plot_1 <- umap_base(sce_l, color_by = "cluster_louvain")+ 
  ggplot2::ggtitle(plot_title)+
  ggplot2::scale_color_manual(values = col_clust_l)
plot_1l <- umap_legend(sce_l, color_by = "cluster_louvain")+
  ggplot2::scale_color_manual("cluster (louvain)", values = col_clust_l)
legend_1 <- ggpubr::get_legend(plot_1l)

plot_2 <- pca_base2(sce_l, color_by = "cluster_louvain")+ 
  ggplot2::ggtitle(plot_title)+
  ggplot2::scale_color_manual(values = col_clust_l)
plot_2l <- pca_legend(sce_l, color_by = "cluster_louvain")+
  ggplot2::scale_color_manual("cluster (louvain)", values = col_clust_l)
legend_2 <- ggpubr::get_legend(plot_2l)

plot_3 <- pca_base3(sce_l, color_by = "cluster_louvain")+ 
  ggplot2::ggtitle(plot_title)+
  ggplot2::scale_color_manual(values = col_clust_l)
plot_3l <- pca_legend(sce_l, color_by = "cluster_louvain")+
  ggplot2::scale_color_manual("cluster (louvain)", values = col_clust_l)
legend_3 <- ggpubr::get_legend(plot_3l)

PLOT_1 <- ggpubr::ggarrange(plot_1, legend_1)
PLOT_2 <- ggpubr::ggarrange(plot_2, legend_2)
PLOT_3 <- ggpubr::ggarrange(plot_3, legend_3)
  
PLOT_1
PLOT_2
PLOT_3
knitr::knit_exit()

```

## QC

```{r legends, fig.width=8, fig.height=4}
ggdf <- base::as.data.frame(colData(sce_l))

# legends
plot_baccin_leg <- ggplot2::ggplot(ggdf,
                                   aes(x = cluster_louvain,
                                       fill=baccin_celltype_scmapclust))+
  ggplot2::geom_bar(position = "stack") +
  ggplot2::scale_fill_manual("baccin_celltype_scmapclust",
                             values = col_cts_baccin)

legend_baccin <- ggpubr::get_legend(plot_baccin_leg)

plot_dahlin_leg <- ggplot2::ggplot(ggdf,
                                   aes(x = cluster_louvain,
                                       fill=dahlin_celltype_scmapclust))+
  ggplot2::geom_bar(position = "stack") +
  ggplot2::scale_fill_manual("dahlin_celltype_scmapclust",
                             values = col_cts_dahlin)

legend_dahlin <- ggpubr::get_legend(plot_dahlin_leg)

plot_dolgalev_leg <- ggplot2::ggplot(ggdf,
                                     aes(x = cluster_louvain,
                                         fill=dolgalev_celltype_scmapclust))+
  ggplot2::geom_bar(position = "stack") +
  ggplot2::scale_fill_manual("dolgalev_celltype_scmapclust",
                             values = col_cts_dolgalev)
legend_dolgalev <- ggpubr::get_legend(plot_dolgalev_leg)
# use legends for later
```

```{r qc_plots, fig.width=8, fig.height=4}
# plots
plot1a <- ggplot2::ggplot(ggdf,
                          aes(x = cluster_louvain,
                              fill=Batch_exp_day,
                              color = Batch_exp_day))+
  ggplot2::geom_bar(position = "stack")+
  ggplot2::theme_classic()+
  ggplot2::scale_fill_manual("Experimental day", values = col_batch_exp_day)+
  ggplot2::scale_color_manual("Experimental day", values = col_batch_exp_day)+
  ggplot2::theme(axis.text.x = element_text(angle = 90))+
  ggplot2::ggtitle(plot_title)

plot1b <- ggplot2::ggplot(ggdf,
                          aes(x = cluster_louvain,
                              fill=Batch_exp_day,
                              color = Batch_exp_day))+
  ggplot2::geom_bar(position = "fill") +
  ggplot2::theme_classic()+
  ggplot2::scale_fill_manual("Experimental day",
                             values = col_batch_exp_day)+
  ggplot2::scale_color_manual("Experimental day",
                              values = col_batch_exp_day)+
  ggplot2::theme(axis.text.x = element_text(angle = 90))+
  ggplot2::ggtitle(plot_title)

plot2a <- ggplot2::ggplot(ggdf,
                          aes(x = Batch_exp_day,
                              fill=cluster_louvain,
                              color = cluster_louvain))+
  ggplot2::geom_bar(position = "stack")+
  ggplot2::theme_classic()+
  ggplot2::scale_fill_manual("Cluster (louvain)", values = col_clust_l)+
  ggplot2::scale_color_manual("Cluster (louvain)", values = col_clust_l)+
  ggplot2::theme(axis.text.x = element_text(angle = 90))+
  ggplot2::ggtitle(plot_title)+
  ggplot2::facet_grid(cols = vars(ggdf$Fraction))

plot2b <- ggplot2::ggplot(ggdf,
                          aes(x = Batch_exp_day,
                              fill=cluster_louvain,
                              color = cluster_louvain))+
  ggplot2::geom_bar(position = "fill")+
  ggplot2::theme_classic()+
  ggplot2::scale_fill_manual("Cluster (louvain)",  values = col_clust_l)+
  ggplot2::scale_color_manual("Cluster (louvain)", values = col_clust_l)+
  ggplot2::theme(axis.text.x = element_text(angle = 90))+
  ggplot2::ggtitle(plot_title)+
  ggplot2::facet_grid(cols = vars(ggdf$Fraction))

plot3a <- ggplot2::ggplot(ggdf,
                          aes(x = cluster_louvain,
                              fill=Age_ID,
                              color = Age_ID))+
  ggplot2::geom_bar(position = "stack")+
  ggplot2::theme_classic()+
  ggplot2::scale_fill_manual("Age", values = col_age)+
  ggplot2::scale_color_manual("Age", values = col_age)+
  ggplot2::theme(axis.text.x = element_text(angle = 90))+
  ggplot2::ggtitle(plot_title)

plot3b <- ggplot2::ggplot(ggdf,
                          aes(x = cluster_louvain,
                              fill=Age_ID,
                              color = Age_ID))+
  ggplot2::geom_bar(position = "fill")+
  ggplot2::theme_classic()+
  ggplot2::scale_fill_manual("Age", values = col_age)+
  ggplot2::scale_color_manual("Age", values = col_age)+
  ggplot2::theme(axis.text.x = element_text(angle = 90))+
  ggplot2::ggtitle(plot_title)

plot4a <- ggplot2::ggplot(ggdf,
                          aes(x = Age_ID,
                              fill=cluster_louvain,
                              color = cluster_louvain))+
  ggplot2::geom_bar(position = "stack")+
  ggplot2::theme_classic()+
  ggplot2::scale_fill_manual("Cluster (louvain)", values = col_clust_l)+
  ggplot2::scale_color_manual("Cluster (louvain)", values = col_clust_l)+
  ggplot2::theme(axis.text.x = element_text(angle = 90))+
  ggplot2::ggtitle(plot_title)

plot4b <- ggplot2::ggplot(ggdf,
                          aes(x = Age_ID,
                              fill=cluster_louvain,
                              color = cluster_louvain))+
  ggplot2::geom_bar(position = "fill")+
  ggplot2::theme_classic()+
  ggplot2::scale_fill_manual("Cluster (louvain)", values = col_clust_l)+
  ggplot2::scale_color_manual("Cluster (louvain)", values = col_clust_l)+
  ggplot2::theme(axis.text.y = element_blank(),
                 axis.text.x = element_text(angle = 90))+
  ggplot2::ggtitle(plot_title)

plot1a
plot1b
plot2a
plot2b
plot3a
plot3b
plot4a
plot4b
```

```{r qc_plots_spec, fig.width=8, fig.height=4}
# Species
# this was disabled
plot5a <- ggplot2::ggplot(ggdf,
                          aes(x = cluster_louvain,
                              fill=Species_ID,
                              color = Species_ID))+
  ggplot2::geom_bar(position = "stack")+
  ggplot2::theme_classic()+
  ggplot2::scale_fill_manual("Age", values = col_spc)+
  ggplot2::scale_color_manual("Age", values = col_spc)+
  ggplot2::theme(axis.text.x = element_text(angle = 90),
                 axis.title.y = element_blank())+
  ggplot2::ggtitle(plot_title)

plot5a
```


```{r qc_plots_spec2, fig.width=8, fig.height=4}
plot5b <- ggplot2::ggplot(ggdf,
                          aes(x = cluster_louvain,
                              fill=Species_ID,
                              color = Species_ID))+
  ggplot2::geom_bar(position = "fill") +
  ggplot2::theme_classic()+
  ggplot2::scale_fill_manual( "Age", values = col_spc)+
  ggplot2::scale_color_manual( "Age", values = col_spc)+
  ggplot2::theme(axis.text.x = element_text(angle = 90),
                 axis.title.y = element_blank())+
  ggplot2::ggtitle(plot_title)

plot5b
```

```{r qc_plots_spec3, fig.width=8, fig.height=4}
plot6a <- ggplot2::ggplot(ggdf,
                          aes(x = Species_ID,
                              fill=cluster_louvain,
                              color = cluster_louvain))+
  ggplot2::geom_bar(position = "stack")+
  ggplot2::theme_classic()+
  ggplot2::scale_fill_manual("Cluster (louvain)", values = col_clust_l)+
  ggplot2::scale_color_manual("Cluster (louvain)", values = col_clust_l)+
  ggplot2::theme(axis.text.x = element_text(angle = 90),
                axis.title.y = element_blank())+
  ggplot2::ggtitle(plot_title)

plot6a
```

```{r qc_plots_spec4, fig.width=8, fig.height=4}
plot6b <- ggplot2::ggplot(ggdf,
                          aes(x = Species_ID,
                              fill=cluster_louvain,
                              color = cluster_louvain))+
  ggplot2::geom_bar(position = "fill") +
  ggplot2::theme_classic()+
  ggplot2::scale_fill_manual("Cluster (louvain)", values = col_clust_l)+
  ggplot2::scale_color_manual("Cluster (louvain)", values = col_clust_l)+
  ggplot2::theme(axis.text.y = element_blank(),
                 axis.text.x = element_text(angle = 90),
                 axis.title.y = element_blank())+
  ggplot2::ggtitle(plot_title)

plot6b
```


```{r qc_plots_no_legend, fig.width=8, fig.height=4}
# Cell types
plot7a <- ggplot2::ggplot(ggdf,
                          aes(x = cluster_louvain,
                              fill=baccin_celltype_scmapclust,
                              color = baccin_celltype_scmapclust))+
  ggplot2::geom_bar(position = "stack") +
  ggplot2::theme_classic()+
  ggplot2::scale_fill_manual(values = col_cts_baccin)+
  ggplot2::scale_color_manual(values = col_cts_baccin)+
  ggplot2::theme(legend.position = "none",
                 axis.text.x = element_text(angle = 90),
                 axis.title.y = element_blank())+
  ggplot2::ggtitle(plot_title)

plot7b <- ggplot2::ggplot(ggdf,
                          aes(x = cluster_louvain,
                              fill=baccin_celltype_scmapclust,
                              color = baccin_celltype_scmapclust))+
  ggplot2::geom_bar(position = "fill") +
  ggplot2::theme_classic()+
  ggplot2::scale_fill_manual(values = col_cts_baccin)+
  ggplot2::scale_color_manual(values = col_cts_baccin)+
  ggplot2::theme(legend.position = "none",
                 axis.text.x = element_text(angle = 90),
                 axis.title.y = element_blank())+
  ggplot2::ggtitle(plot_title)
```

```{r qc_plots_no_legend2, fig.width=8, fig.height=4}
plot8a <- ggplot2::ggplot(ggdf,
                          aes(x = cluster_louvain,
                              fill=dahlin_celltype_scmapclust,
                              color = dahlin_celltype_scmapclust))+
  ggplot2::geom_bar(position = "stack") +
  ggplot2::theme_classic()+
  ggplot2::scale_fill_manual(values = col_cts_dahlin)+
  ggplot2::scale_color_manual(values = col_cts_dahlin)+
  ggplot2::theme(legend.position = "none",
                 axis.text.x = element_text(angle = 90),
                 axis.title.y = element_blank())+
  ggplot2::ggtitle(plot_title)

plot8b <- ggplot2::ggplot(ggdf,
                          aes(x = cluster_louvain,
                              fill=dahlin_celltype_scmapclust,
                              color = dahlin_celltype_scmapclust))+
  ggplot2::geom_bar(position = "fill") +
  ggplot2::theme_classic()+
  ggplot2::scale_fill_manual(values = col_cts_dahlin)+
  ggplot2::scale_color_manual(values = col_cts_dahlin)+
  ggplot2::theme(legend.position = "none",
                 axis.text.x = element_text(angle = 90),
                 axis.title.y = element_blank())+
  ggplot2::ggtitle(plot_title)

plot9a <- ggplot2::ggplot(ggdf,
                          aes(x = cluster_louvain,
                              fill=dolgalev_celltype_scmapclust,
                              color = dolgalev_celltype_scmapclust))+
  ggplot2::geom_bar(position = "stack") +
  ggplot2::theme_classic()+
  ggplot2::scale_fill_manual(values = col_cts_dolgalev)+
  ggplot2::scale_color_manual(values = col_cts_dolgalev)+
  ggplot2::theme(legend.position = "none",
                 axis.text.x = element_text(angle = 90),
                 axis.title.y = element_blank())+
  ggplot2::ggtitle(plot_title)

plot9b <- ggplot2::ggplot(ggdf,
                          aes(x = cluster_louvain,
                              fill=dolgalev_celltype_scmapclust,
                              color = dolgalev_celltype_scmapclust))+
  ggplot2::geom_bar(position = "fill") +
  ggplot2::theme_classic()+
  ggplot2::scale_fill_manual(values = col_cts_dolgalev)+
  ggplot2::scale_color_manual(values = col_cts_dolgalev)+
  ggplot2::theme(legend.position = "none",
                 axis.text.x = element_text(angle = 90),
                 axis.title.y = element_blank())+
  ggplot2::ggtitle(plot_title)
```

```{r plots2, fig.width=8, fig.height = 11}

PLOT7a <- ggpubr::ggarrange(plot7a, legend_baccin, ncol = 1)
PLOT7b <- ggpubr::ggarrange(plot7b, legend_baccin, ncol = 1)
PLOT8a <- ggpubr::ggarrange(plot8a, legend_dahlin, ncol = 1)
PLOT8b <- ggpubr::ggarrange(plot8b, legend_dahlin, ncol = 1)
PLOT9a <- ggpubr::ggarrange(plot9a, legend_dolgalev, ncol = 1)
PLOT9b <- ggpubr::ggarrange(plot9b, legend_dolgalev, ncol = 1)

PLOT7a
PLOT7b
PLOT8a
PLOT8b
PLOT9a
PLOT9b
```

```{r plotx, fig.width=12, fig.height=4}

plot_x <- umap_base(sce_l, color_by = "cluster_louvain")+
  ggplot2::scale_color_manual(values = col_clust_l)+
  ggplot2::ggtitle(title_full)+
  ggplot2::facet_grid(cols = vars(sce_l$Species_ID))
plot_xl <- umap_legend(sce_l, color_by = "cluster_louvain")+
  ggplot2::scale_color_manual("cluster_louvain", values = col_clust_l)
legend_x <- ggpubr::get_legend(plot_xl)

PLOT_X <- ggpubr::ggarrange(plot_x, legend_x, widths = c(3,1))
PLOT_X
```

## Silhouette and Purity

```{r silhouette}

# Silhouette
sil.approx <- bluster::approxSilhouette(reducedDim(sce_l, "PCA"), 
                                        clusters = sce_l$cluster_louvain)
sil.data <- base::as.data.frame(sil.approx)
sil.data$closest <- factor(ifelse(sil.data$width > 0, 
                                  sce_l$cluster_louvain, 
                                  sil.data$other))
sil.data$cluster <- sce_l$cluster_louvain

ggplot2::ggplot(sil.data,
                aes(x=cluster, y=width, colour=closest))+
  ggbeeswarm::geom_quasirandom(size = 0.1)+
  ggplot2::theme_classic()+
  ggplot2::ggtitle(title_full)+
  ggplot2::scale_color_manual("cluster (louvain)", values = col_clust_l)+
  ggplot2::theme(legend.position = "none")+
  ggplot2::xlab("cluster (louvain)")+
  ggplot2::ylim(-1, 1)+
  ggplot2::ylab("Silhouette width")

ggplot2::ggplot(sil.data, 
                aes(x=cluster, y=width, colour=closest))+
  ggbeeswarm::geom_quasirandom(size = 0.1)+
  ggplot2::theme_classic()+
  ggplot2::ggtitle(title_full)+
  ggplot2::facet_grid(cols = vars(sce_l$Species_ID))+
  ggplot2::scale_color_manual("cluster (louvain)", values = col_clust_l)+
  ggplot2::theme(legend.position = "none")+
  ggplot2::xlab("cluster (louvain)")+
  ggplot2::ylim(-1, 1)+
  ggplot2::ylab("Silhouette width")

# Purity
pure_sce <- bluster::neighborPurity(reducedDim(sce_l, "PCA"),
                                    sce_l$cluster_louvain)
pure_data <- base::as.data.frame(pure_sce)
pure_data$maximum <- factor(pure_data$maximum)
pure_data$cluster <- sce_l$cluster_louvain

ggplot2::ggplot(pure_data, 
                aes(x=cluster, y=purity, colour=maximum))+
  ggbeeswarm::geom_quasirandom(size = 0.1)+
  ggplot2::theme_classic()+
  ggplot2::ggtitle(title_full)+
  ggplot2::scale_color_manual("cluster (louvain)", values = col_clust_l)+
  ggplot2::theme(legend.position = "none")+
  ggplot2::xlab("cluster (louvain)")+
  ggplot2::ylim(0, 1)+
  ggplot2::ylab("Cluster purity")

ggplot2::ggplot(pure_data, 
                aes(x=cluster, y=purity, colour=maximum))+
  ggbeeswarm::geom_quasirandom(size = 0.1)+
  ggplot2::theme_classic()+
  ggplot2::ggtitle(title_full)+
  ggplot2::facet_grid(cols = vars(sce_l$Species_ID))+
  ggplot2::scale_color_manual("cluster (louvain)", values = col_clust_l)+
  ggplot2::theme(legend.position = "none")+
  ggplot2::xlab("cluster (louvain)")+
  ggplot2::ylim(0, 1)+
  ggplot2::ylab("Cluster purity")

ggplot2::ggplot(pure_data, 
                aes(x=cluster, y=purity, color=cluster))+
  ggplot2::geom_boxplot(outlier.size = 0.1)+
  ggplot2::theme_classic()+
  ggplot2::ggtitle(title_full)+
  ggplot2::scale_color_manual("cluster (louvain)", values = col_clust_l)+
  ggplot2::theme(legend.position = "none")+
  ggplot2::xlab("cluster (louvain)")+
  ggplot2::ylim(0, 1)+
  ggplot2::ylab("Cluster purity")

ggplot2::ggplot(pure_data, 
                aes(x=cluster, y=purity, color=cluster))+
  ggplot2::geom_boxplot(outlier.size = 0.1)+
  ggplot2::theme_classic()+
  ggplot2::ggtitle(title_full)+
  ggplot2::scale_color_manual("cluster (louvain)", values = col_clust_l)+
  ggplot2::facet_grid(cols = vars(sce_l$Species_ID))+
  ggplot2::theme(legend.position = "none")+
  ggplot2::xlab("cluster (louvain)")+
  ggplot2::ylim(0, 1)+
  ggplot2::ylab("Cluster purity")
```

```{r session_info}
utils::sessionInfo()
```