---
title: "Species Bulk quality report"
author: "Lea Wölbert"
date: '2023-11-07'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Report on the quality of the cell type pseudo-bulks (annotated)

#### Load objects

```{r seed,  message = FALSE}
set.seed(37)
```

```{r load,  message = FALSE}
library(pcaExplorer)
library(pheatmap)
library(RColorBrewer)
library(SingleCellExperiment)
```

```{r source, message = FALSE}
source(file =  snakemake@params[["plotting"]])
```

```{r load_objects}
sce <- base::readRDS(snakemake@input[["sce_input"]])
celltype <- snakemake@wildcards[["celltype"]]

# these are cell types that are so small that usually they don't work
cts_exclude <- snakemake@params[["cts_exclude"]]
print(cts_exclude)

# alter celltypes to fit the wildcards for subsetting
sce$celltypes_alt <- sce$celltypes
sce$celltypes_alt <- base::gsub(" ", "_", sce$celltypes_alt)
sce$celltypes_alt <- base::gsub("/", "_", sce$celltypes_alt)
sce$celltypes_alt <- base::gsub("[.]", "", sce$celltypes_alt)

sce_ct <- sce[,which(sce$celltypes_alt == celltype)]
ct_curr <- sce_ct$celltypes[1]

rlog_list = base::readRDS(snakemake@input[["rlog"]])
rld <- rlog_list[[ct_curr]]

print(rld)
print(ct_curr)

if(ct_curr %in% cts_exclude){
  print("excluded cell type")
  knitr::knit_exit()
}
```

```{r colors, meassage = FALSE}
colors_path <- snakemake@params[["colors_path"]]
source(snakemake@params[["colors"]])
```

# QC

```{r qc}
plot1 <- pcaExplorer::distro_expr(rld, plot_type = "boxplot")+
  ggplot2::theme_classic()+
  ggplot2::theme(axis.text.x = element_text(angle = 90))+
  ggplot2::theme(legend.position = "none")

plot1
```

```{r pca1}
rld_pca <- stats::prcomp(t(SummarizedExperiment::assay(rld)))
rld_cor <- pcaExplorer::correlatePCs(rld_pca, colData(rld))
pcaExplorer::plotPCcorrs(rld_cor)
```

```{r ggdf}

ggdf <- base::as.data.frame(rld_pca$x)

ggdf$Antibody_combination <- colData(rld)$Antibody_combination
ggdf$age <- colData(rld)$age
ggdf$species <- colData(rld)$species
ggdf$batch <- colData(rld)$batch
ggdf$Batch_sequencing <- colData(rld)$Batch_sequencing
ggdf$sample <- colData(rld)$sample
ggdf$ncells <- colData(rld)$ncells

head(ggdf)
```

# PCAs

```{r pca_plots}

title_full <- base::paste(ct_curr)

plot1 <- ggplot2::ggplot(ggdf, aes(x = PC1, y = PC2, color = species))+
  ggplot2::geom_point()+
  ggplot2::theme_classic()+
  ggplot2::theme(axis.text = element_blank(),
                 axis.ticks = element_blank())+
  ggplot2::scale_color_manual("Species", values = col_spc)
plot1

plot2 <- ggplot2::ggplot(ggdf, aes(x = PC1, y = PC2, color = age))+
  ggplot2::geom_point()+
  ggplot2::theme_classic()+
  ggplot2::theme(axis.text = element_blank(),
                 axis.ticks = element_blank())+
  ggplot2::scale_color_manual("Age", values = col_age)
plot2

plot3 <- ggplot2::ggplot(ggdf, aes(x = PC1, y = PC2, color = batch))+
  ggplot2::geom_point()+
  ggplot2::theme_classic()+
  ggplot2::theme(axis.text = element_blank(),
                 axis.ticks = element_blank())
plot3

plot4 <- ggplot2::ggplot(ggdf, 
                         aes(x = PC1, y = PC2, color = Antibody_combination))+
  ggplot2::geom_point()+
  ggplot2::theme_classic()+
  ggplot2::theme(axis.text = element_blank(),
                 axis.ticks = element_blank())
plot4

plot5 <- ggplot2::ggplot(ggdf, aes(x = PC1, y = PC2, color = ncells))+
  ggplot2::geom_point()+
  ggplot2::theme_classic()+
  ggplot2::theme(axis.text = element_blank(),
                 axis.ticks = element_blank())
plot5
```

```{r pca2}
rld_pca <- stats::prcomp(t(SummarizedExperiment::assay(rld)))
plot3 <- pcaExplorer::pcascree(rld_pca, type="pev")
print(plot3)
```

```{r pca3}
pcaExplorer::hi_loadings(rld_pca, topN = 20, whichpc = 1)
```

```{r pca4}
pcaExplorer::hi_loadings(rld_pca, topN = 20, whichpc = 2)
```

```{r make_dist_plot}
sampleDists <- stats::dist(t(SummarizedExperiment::assay(rld)))
sampleDistMatrix <- base::as.matrix(sampleDists)
rownames(sampleDistMatrix) <- rld$species
colnames(sampleDistMatrix) <- NULL

colors <- grDevices::colorRampPalette(
  base::rev(RColorBrewer::brewer.pal(9, "Blues")))(255)

pheatmap::pheatmap(
  sampleDistMatrix,
  clustering_distance_rows=sampleDists,
  clustering_distance_cols=sampleDists,
  col=colors)
```

```{r sessioninfo}
utils::sessionInfo()
```