---
title: "Species nDGE report"
author: "Lea Wölbert"
date: '2023-11-07'
output: html_document
---

Report on nDGE results at cell type level (annotated).

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Load objects

```{r seed, message = FALSE}
set.seed(37)
```

```{r load, message = FALSE}
library(EnhancedVolcano)
library(SingleCellExperiment)
```

```{r source, message = FALSE}
source(file = snakemake@params[["plotting"]])
```

```{r manual, include = FALSE, eval = FALSE}

shared_gene_list <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/scRNAseq/main_analysis/sce_objects/03_sce_analysis/02_DESeq2_crossspecies/06_nres/PC_0.05_FC_1.5/shared_genes_str_celltypes")

sce <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/scRNAseq/main_analysis/sce_objects/02_sce_anno/10_anns/sce_str-10")

celltype_res_list <- readRDS("/omics/odcf/analysis/OE0538_projects/DO-0008/data/scRNAseq/main_analysis/sce_objects/03_sce_analysis/02_DESeq2_crossspecies/06_nres/PC_0.05_FC_1.5/res_str_celltype")
names(celltype_res_list)
shared_gene_list$HSCs
```


```{r load_objects}

fc_cutoff <- snakemake@params[["fc_cutoff"]]
padj_cutoff <- snakemake@params[["padj_cutoff"]]

sce <- base::readRDS(snakemake@input[["sce_input"]])
celltype <- snakemake@wildcards[["celltype"]]

# alter celltypes to fit the wildcards for subsetting
sce$celltypes_alt <- sce$celltypes
sce$celltypes_alt <- gsub(" ", "_", sce$celltypes_alt)
sce$celltypes_alt <- gsub("/", "_", sce$celltypes_alt)
sce$celltypes_alt <- gsub("[.]", "", sce$celltypes_alt)

cts_exclude <- snakemake@params[["cts_exclude"]]

sce_ct <- sce[,which(sce$celltypes_alt == celltype)]
ct_curr <- unfactor(sce_ct$celltypes[1])
print(ct_curr)

if(ct_curr %in% cts_exclude){
  print("excluded cell type")
  knitr::knit_exit()
}
```

```{r load_subset}
celltype_res_list <- base::readRDS(snakemake@input[["celltype_res"]])
shared_gene_list <- base::readRDS(snakemake@input[["celltype_shared_genes_list"]])

names(celltype_res_list)
names(shared_gene_list)

ct_curr %in% names(celltype_res_list)
ct_curr %in% names(shared_gene_list)

# subset objects to required cluster and fractions
celltype_res_ct <- celltype_res_list[[ct_curr]]
shared_genes_ct <- shared_gene_list[[ct_curr]]

```

# Show Pval distributions

```{r pval_function}
see_pvals <- function(celltype_res, comparison){
  plot1 <- EnhancedVolcano::EnhancedVolcano(celltype_res, 
                                            lab = "",
                                            x = 'log2FoldChange',
                                            y = 'pvalue', 
                                            col = c("grey70",
                                                    "grey70", 
                                                    "dodgerblue3",
                                                    "grey70"),
                                            subtitle = "",
                                            colAlpha = 0.9, 
                                            pointSize = 0.5,
                                            pCutoff = padj_cutoff,
                                            FCcutoff = fc_cutoff)+
    ggplot2::theme_classic()+
    ggplot2::ggtitle(base::paste(comparison))+
    ggplot2::theme(legend.position="none", 
                   plot.subtitle = element_blank())

  print(plot1)
}
```

## MMUS MCAS

```{r mmus_mcas}
print(celltype_res_ct[["mmus-mcas"]])
res_df_comb_mmus_mcas <- celltype_res_ct[["mmus-mcas"]]
see_pvals(celltype_res = res_df_comb_mmus_mcas, comparison = "mmus-mcas")
```

## MMUS MSPR

```{r mmus_mspr}
res_df_comb_mmus_mspr <- celltype_res_ct[["mmus-mspr"]]
see_pvals(celltype_res = res_df_comb_mmus_mspr, comparison = "mmus-mspr")
```

## MMUS MCAR

```{r mmus_mcar}
res_df_comb_mmus_mcar <- celltype_res_ct[["mmus-mcar"]]
see_pvals(celltype_res = res_df_comb_mmus_mcar, comparison = "mmus-mcar")
```

## MCAS MSPR

```{r mcas_mspr}
res_df_comb_mcas_mspr <- celltype_res_ct[["mcas-mspr"]]
see_pvals(celltype_res = res_df_comb_mcas_mspr, comparison = "mcas-mspr")
```

## MCAS MCAR

```{r mcas_mcar}
res_df_comb_mcas_mcar <- celltype_res_ct[["mcas-mcar"]]
see_pvals(celltype_res = res_df_comb_mcas_mcar, comparison = "mcas-mcar")
```

## MSPR MCAR

```{r mspr_mcar}
res_df_comb_mspr_mcar <- celltype_res_ct[["mspr-mcar"]]
see_pvals(celltype_res = res_df_comb_mspr_mcar, comparison = "mspr-mcar")
```

# Print lists

```{r print_shared_genes}
print(ct_curr)
print(base::sort(shared_genes_ct))
```

```{r sessioninfo}
utils::sessionInfo()
```